### ISSUE TITLE
Aqueduct on road

### ISSUE THREAD

**Issue by nwtour** [bvschaik/julius#10]
In Jullius one aqueduct on road restricted, but in original game its normal usage. Bug or feature?
![1](https://user-images.githubusercontent.com/3074285/33954932-ef4f7140-e04a-11e7-8d87-83bdde7db548.jpg)
![2](https://user-images.githubusercontent.com/3074285/33954946-fc992148-e04a-11e7-8ce0-853fe2d8cc60.jpg)

**Comment by bvschaik** [comment]
Definitely a bug, I'll look into it.
