### ISSUE TITLE
Visual feedback for the land clearing tool

### ISSUE THREAD

**Issue by devnoname120** [bvschaik/julius#103]
When clearing some land using the tool, there is no visual feedback. Only when left click is pressed and mouse is dragged does the user know what will be destroyed.

**Comment by bvschaik** [comment]
Good one. Maybe highlight the building/tile in red when you hover over it?

**Comment by crudelios** [comment]
This is a visual change from C3, but I agree it would be an useful one!

> Maybe highlight the building/tile in red when you hover over it?

Seems like a good idea :)
