### ISSUE TITLE
Support russian language

### ISSUE THREAD

**Issue by Temik007** [bvschaik/julius#104]
On screen wrong symbols, i think it is problem with codepage

I install Caesar III, copy files in install folder, rename c3.rus to c3.eng and c3_mm.rus to c3_mm.eng
Screenshot:
![img_20190216_145550](https://user-images.githubusercontent.com/47690657/52899571-89819000-31fc-11e9-95d4-fe80de7ff727.jpg)

**Comment by bvschaik** [comment]
The C3 installation, is that an originally English version? All letters are basically images stored in the .sg2/.555 files that are shipped with the game, and an English installation will only contain letters in Latin1 encoding. No Russian/Cyrillic characters are present.

If it's a Russion version of the game however, I'd like to investigate.

**Comment by Temik007** [comment]
Yes, it is standalone russian version game. The translation was made by "1C", it's official version on Russia

**Comment by nwtour** [comment]
Yes. In russia official publisher 1C overwrite latin symbols mapping in c3.eng, c3_mm.eng and rename to c3.rus, c3_mm.rus

Russian version without files c3.eng, c3_mm.eng (only c3.rus, c3_mm.rus)
And with overwrited wavs files (Russian speeches now work fine)

![](http://ingame-portal.3dn.ru/_ld/13/34671379.jpg)

**Comment by dalerank** [comment]
Seems need also change font, because native font support latin symbols only

**Comment by crudelios** [comment]
Yes the .sg2 and .555 are different, and probably the string to font image assignments are different as well, that's why the text looks bogus.

I think the best way to do this is to compare what is being displayed with what the characters should be, and create an internal conversion table for each language that needs it.

The French version will probably have problems with accented letters as well.

**Comment by bvschaik** [comment]
French uses Latin1, and all accented characters are present in the .sg2/.555. Most West-European languages should be OK with the English graphics.

**Comment by crudelios** [comment]
Humm strange, I remember Pharaoh didn't work with the same executable... Maybe C3 is different!

**Comment by nwtour** [comment]
FYI. First screen = correct russian symbols in main menu, second = incorrect
![2019-02-17 01-31-33](https://user-images.githubusercontent.com/3074285/52911393-5e5a7780-32b4-11e9-8733-d78de4e9493a.png)
![2019-02-17 01-32-44](https://user-images.githubusercontent.com/3074285/52911400-6dd9c080-32b4-11e9-987e-537d9130aed0.png)

c3.rus and c3_mm.rus used WINDOWS-CP1251 encoding
[https://en.wikipedia.org/wiki/Windows-1251](https://en.wikipedia.org/wiki/Windows-1251)

**Comment by bvschaik** [comment]
Could someone send me the Russian c3.exe so I can have a look? (I already have the c3_fonts.sg2/.555 and *.rus files)

**Comment by bvschaik** [comment]
I'm working on this now. I found out that the Russian version was not patched to 1.0.1.0. Julius will upgrade your C3 to 1.0.1.0, but some new texts were added that need to be translated.

Could someone provide translations for the strings `formatted like this`?

In the File menu: `Delete game`
In the Options menu: `Difficulty`

Extra warnings:
- `Must be placed on edge of map`
- `Must place on open water`
- `Cannot place here`
- `No earthquakes are scheduled`
- `Some plots are too far from a road`
- `Parts of your city are boxed in`
- `People living there will soon perish`
- `Data limit reached - see readme`

Title for the "delete file" dialog: `Delete a file`

Religion advisor: `You have turned the effects of the gods OFF. Although they may be angry or pleased, they will not show it.`

Market lady information screen that shows what good she is fetching/returning: `Collecting:` and `Returning with:`

Difficulty settings dialog:
- `Difficulty settings`
- `Very easy`
- `Easy`
- `Normal`
- `Hard`
- `Very hard`
- `Gods effects OFF`
- `Gods effects ON`
- `Right click to exit`

**Comment by nwtour** [comment]
> I'm working on this now. I found out that the Russian version was not patched to 1.0.1.0. Julius will upgrade your C3 to 1.0.1.0, but some new texts were added that need to be translated.
> 
> Could someone provide translations for the strings `formatted like this`?
> 
> In the File menu: `Delete game`

`Удалить игру`

> In the Options menu: `Difficulty`

`Сложность`
 
> Extra warnings:
> 
>     * `Must be placed on edge of map`

`Должно быть размещено на краю карты`

> 
>     * `Must place on open water`

`Должно быть размещено на воде`

> 
>     * `Cannot place here`

`Не может быть размещено тут`

> 
>     * `No earthquakes are scheduled`

`Землетрясения не предвидится`

> 
>     * `Some plots are too far from a road`

`Некоторые участки слишком далеко от дороги`

> 
>     * `Parts of your city are boxed in`

`Часть Вашего города стеснена`

> 
>     * `People living there will soon perish`

`Люди живущие там скоро погибнут`

> 
>     * `Data limit reached - see readme`

`Превышен лимит данных - см. справку`

> 
> 
> Title for the "delete file" dialog: `Delete a file`

`Удалить файл`

> 
> Religion advisor: `You have turned the effects of the gods OFF. Although they may be angry or pleased, they will not show it.`

`Вы отключили эффекты богов. Они могут быть злыми или довольными, Вы не узнаете этого.`

> 
> Market lady information screen that shows what good she is fetching/returning: `Collecting:` and `Returning with:`

`Сбор:` and `Возвращается с:`

> 
> Difficulty settings dialog:
> 
>     * `Difficulty settings`

`Настройки сложности`

> 
>     * `Very easy`

`Очень простой`

> 
>     * `Easy`

`Простой`

> 
>     * `Normal`

`Нормальный`

> 
>     * `Hard`

`Сложный`

> 
>     * `Very hard`

`Очень сложный`

> 
>     * `Gods effects OFF`

`Эффекты богов ОТКЛ`

> 
>     * `Gods effects ON`

`Эффекты богов ВКЛ`

> 
>     * `Right click to exit`

`ПКМ  для выхода`

**Comment by bvschaik** [comment]
Thanks!

Could you try the following:
1. Download the Russian patch files from: https://bintray.com/bvschaik/caesar3-patches/russian
2. Download the most recent unstable of Julius for your platform from: https://github.com/bvschaik/julius
3. Extract all files to your Caesar 3 folder, and run Julius

You should now be able to run the game in Russian, with all bugfixes and enhancements from the patch. Note that I did not implement the grammatical corrections from `russian.csv`: it was too much work to figure out for me (and too much impact on the existing codebase).
Let me know if you encounter any issues.

**Comment by nwtour** [comment]
Look awesome. Great job!
Smoke test passed

> Let me know if you encounter any issues

Little bug:
In russian version mission1.pak named as MISSION1.pak, but unix system case-sensitive and 
its looks like:
ERROR: unable to load external image  01b.bmp  8968
INFO: Loading saved game  mission1.pak
![screen](https://user-images.githubusercontent.com/3074285/55359939-bacbcc00-54db-11e9-871f-f504146dde82.png)
(black screen and empty money/population)

>You should now be able to run the game in Russian, with all bugfixes and enhancements from the patch

FYI:
Yes patch work. But if run Jullius on default russian version, new menu look like:
![screen](https://user-images.githubusercontent.com/3074285/55360396-eac79f00-54dc-11e9-9ae6-cf563fd9fbc2.png)
("Difficult level" translated as "Help" and onclick opened empty popup)

It may be difficult for Jullius beginners to find a patch.

**Comment by bvschaik** [comment]
> Little bug:
> In russian version mission1.pak named as MISSION1.pak, but unix system case-sensitive and
> its looks like:

Ooh, good one. I've been developing on Linux mostly, and I thought I had fixed everything related to case-sensitivity. Fixed now.

> Yes patch work. But if run Jullius on default russian version, new menu look like:
> ("Difficult level" translated as "Help" and onclick opened empty popup)
> 
> It may be difficult for Jullius beginners to find a patch.

Would it help if I add a pop-up telling them to download the patch when Julius detects the language files are not compatible?

**Comment by nwtour** [comment]
> Ooh, good one. I've been developing on Linux mostly, and I thought I had fixed everything related to case-sensitivity. Fixed now.

Yes. Its work

> Would it help if I add a pop-up telling them to download the patch when Julius detects that the language files are not compatible?

Ideal solution: include https://github.com/mendsley/bsdiff and auto apply binary patches "from the box". Binary patch - not contain thrirdparty intellectual property and can be in standard distribution.
But pop-up or console warning (non blocking) too good idea.

**Comment by nwtour** [comment]
~2h in-game and found only one little bug:
Game offer save file in russian language. Its bad idea - file saved with unrecognized encoding (double encoded?)
![screen](https://user-images.githubusercontent.com/3074285/55409438-b7335600-556a-11e9-8cb0-21a9a417bfe8.png)
![screen](https://user-images.githubusercontent.com/3074285/55409454-bf8b9100-556a-11e9-9ed7-efc22cacfde5.png)

My little patch to fetch latin name of mission as default savefile https://github.com/nwtour/julius/commit/8d9b37ea6c5b6fe14461fd27021ee8dc164d392a

**Comment by bvschaik** [comment]
The encoding for user-entered strings is messed up at the moment: all strings are encoded in-game using the detected encoding from the .eng/.rus files (Windows-1250/1251/1252). Since Linux and MacOS generally use UTF-8 for filenames, this results in gibberish filenames in Linux, and MacOS flatly refuses to save to filenames that are not valid UTF-8. Windows is another interesting story: it interprets filenames using the system encoding and then converts to UTF-16 internally. This results in filename "Ììé Ðèì.sav" for the default Russian filename on my English Windows... I guess that when Windows is in Russian, it will work OK.

By the way, when you type in the "save game" dialog, do Cyrillic characters appear properly or are they also messed up?

Anyway, I'll create a new issue for this; it's not limited to the Russian version.

**Comment by bvschaik** [comment]
Closing this because the game can now be played in Russian. If you encounter any other problems, please open separate issues.
