### ISSUE TITLE
C3.<lang> File Converter

### ISSUE THREAD

**Issue by jfkonecn** [bvschaik/julius#112]
Based what I've seen with how the C3.<lang> file works, it seems like it would take forever to properly add new strings without things breaking. 

Do you think it would be worth it for me to write a script/program to convert the C3.<lang> to a different format so that adding new strings could be done more easily?

I was thinking about converting it to JSON or XML so that non-programmers could more easily help with any errors in the translations.

**Comment by bvschaik** [comment]
You mean something like EngConverter in my [citybuilding-tools](https://github.com/bvschaik/citybuilding-tools) repository?

**Comment by jfkonecn** [comment]
Yeah just like that!
