### ISSUE TITLE
Automatically upload Travis-CI artifacts

### ISSUE THREAD

**Issue by devnoname120** [bvschaik/julius#115]
AppVeyor provides the built artifacts which is very handy in order to test the latest version without a working environment. It would be useful if we did the same for Travis-CI.

[Bintray](https://bintray.com/) could be used as a host, it has a free open-source plan with 1TB/month downloads and 10GB storage which should be plenty enough for our use case.

Also, Travis-CI [has built-in support for Bintray](https://docs.travis-ci.com/user/deployment/bintray/).

- [X] Windows https://github.com/bvschaik/julius/commit/85b0b8ec6563b439725bfe4ad3184847e5bbb579 (and AppVeyor)
~~- [ ] Linux (too hard)~~
- [X] Mac https://github.com/bvschaik/julius/commit/bb742edd47861b6568558552bb5cd6ef3baefeb0
- [X] PS Vita https://github.com/bvschaik/julius/pull/125
- [X] Nintendo Switch https://github.com/bvschaik/julius/pull/132

**Comment by bvschaik** [comment]
For macOS and the Vita port, this makes sense.
The Linux builds are not quite cross-platform, are they?

**Comment by devnoname120** [comment]
If we make the Travis job statically link all the libraries they should be cross-platform on Linux. 👍

**Comment by devnoname120** [comment]
I've tried to provide static Linux builds using musl as a static-friendly libc. Unfortunately SDL2 seems to rely on some symbols that are provided by glibc, not by musl.

If someone wants to give another try to self-contained Linux builds, I suggest going the [AppImage](https://github.com/AppImage/AppImageKit) route.

**Comment by devnoname120** [comment]
AppImage building could be inspired from this: https://github.com/OpenRCT2/OpenRCT2/pull/7957/files
