### ISSUE TITLE
Self soldiers lost after click "Go to fort"

### ISSUE THREAD

**Issue by nwtour** [bvschaik/julius#12]
![1](https://user-images.githubusercontent.com/3074285/34072831-66db4274-e29f-11e7-9756-c7a7232ea1f2.png)
![2](https://user-images.githubusercontent.com/3074285/34072834-735bb0a6-e29f-11e7-9adb-07b86e6c6ec3.png)

Step to reproduce: City with population greater 10000 and more 3 forts. Click on several legions "Go to Fort" and as result RANDOM numbers of soldiers DIED.

My realisation to fix this bug (if needed): https://github.com/nwtour/julius/pull/5

**Comment by bvschaik** [comment]
Could you supply a saved game? I don't have the time to build a 10000-population city.

If you've hit the routing limit, that's what happens in the original game as well. And I want to keep Julius as close to the original as possible.

**Comment by nwtour** [comment]
[sav.zip](https://github.com/bvschaik/julius/files/1565023/sav.zip)
Load safe and send second legion on screen to Fort. Its not 100% reproduce, but 5-10 tries and soldiers died.
I run original game and unable reproduce.... MAX_ROUTES != kill units

**Comment by bvschaik** [comment]
The original game also kills the soldiers...
Steps to reproduce:
1. Let your savefile run for 1 tick (low speed)
2. Send both legions home while paused
3. Observe that both legions lose 1 soldier after a short while

**Comment by nwtour** [comment]
>The original game also kills the soldiers...
Ok. Its true. Thanks
