### ISSUE TITLE
UX improvements for map and mini-map movement

### ISSUE THREAD

**Issue by shirakaba** [bvschaik/julius#127]
Based on a bit of recent gameplay on macOS, I felt that it would be great if we could:

1. move the map diagonally by holding down two arrow keys simultaneously (currently you can only move horizontally *or* vertically).
2. support click-and-drag when moving the minimap viewport position (currently you can only click-and-release to change the viewport position in steps).

**Comment by crudelios** [comment]
Humm the lack of diagonal scrolling may be more a bug than a missing feature, because the map scrolling function does support it and it works if you tap two arrow keys at the same time, just not if you keep them pressed.

Click-and-drag seems a nice idea that is used in modern games!

**Comment by crudelios** [comment]
I'm working on this, but I'll probably only submit a PR once #107 is merged.

**Comment by scresante** [comment]
Being able to middle-click (or right click with a modifier) to recenter the map at the position of the click would be a very welcome UX enhancement.
