### ISSUE TITLE
Encoding issues with user-entered strings

### ISSUE THREAD

**Issue by bvschaik** [bvschaik/julius#137]
Using text in the save game/load game dialogs with characters that are not in ASCII results in incorrect filenames. Due to different operating systems having different encodings for filenames, saved games may either have invalid characters in the filename (Linux), wrong characters if the "code page" of the game differs from the system (Windows), or the game simply refuses to create invalid filenames (MacOS).

You also cannot type any characters other than plain ASCII symbols in the dialogs.

**To Reproduce**
Easiest to reproduce:
1. Load the Russian version in any of the three operating systems
2. Go to New career
3. Save the game with the default filename

**Expected behavior**
Game is saved with the right filename

**Comment by crudelios** [comment]
Based on the info on this bug and on #104, perhaps we should indeed internally convert strings to UTF-8? That would make things easier with filenames.

**Comment by bvschaik** [comment]
Actually, I was thinking of doing it the other way around, since we cannot display all of UTF-8 with the internal font graphics. The only places where using `uint8_t` for strings is a problem is when loading scenarios, and loading and saving `.sav` files. Changing all other places is going to be a major pain. Plus, filenames are encoded differently per platform, so that's also the place where you want to do conversion.

**Comment by nwtour** [comment]
>Encoding issues with user-entered strings

Now in Jullius disabled non-english text input with comment: 'only accept non-multibyte chars' in platform/keyboard_input.c

It makes sense to solve this issue only if you enable input otherwise it is easier to simply replace 'Default savefile template' by any English text (full disable non-english filenames)

**Comment by bvschaik** [comment]
> It makes sense to solve this issue only if you enable input otherwise it is easier to simply replace 'Default savefile template' by any English text (full disable non-english filenames)

That's indeed my intention. I started working on this yesterday evening, and I'm learning a lot about encodings and filesystems...

**Comment by bvschaik** [comment]
@nwtour Entering Russian text should work properly now. One question for you: when I enable a Russian keyboard on my operating system, the standard hotkeys (P = pause, W = water overlay, etc) do not work because those keys now produce Cyrillic letters. How do you normally do that when playing games? Use a Latin keyboard?
And if I want to support Russian keyboards, what would be good Cyrillic alternatives for the following hotkeys?

- P: pause/unpause game
- F: show fire overlay
- D: show damage overlay
- C: show crime overlay
- T: show problem overlay
- W: show water overlay
- L: cycle through legions

**Comment by nwtour** [comment]
> @nwtour Entering Russian text should work properly now. One question for you: when I enable a Russian keyboard on my operating system, the standard hotkeys (P = pause, W = water overlay, etc) do not work because those keys now produce Cyrillic letters. How do you normally do that when playing games? Use a Latin keyboard?

All keyboards bear both letters (English and Russian). In the literature denotes the English equivalent, but all soft hotkeys work with both keyboard layots (Ctrl+Я in Firefox work as Ctrl+Z, but in literature denotes as Ctrl+Z) like http://wiki.libsdl.org/SDL_Scancode

> And if I want to support Russian keyboards, what would be good Cyrillic alternatives for the following hotkeys?

No needed special hotkeys for Russian language. Standart hotkeys hardcoded in help (see screenshot).
Pause (button "P" in English layot and "З" in Russian layot) its SDL_SCANCODE_P
SDL_GetKeyFromScancode(SDL_SCANCODE_P) its "P" in English, and "З" in Russian layot.
![screen](https://user-images.githubusercontent.com/3074285/55759577-58864480-5a62-11e9-8ccc-a4cfebd6c27a.png)

**Comment by nwtour** [comment]
I try master branch. Russian input and Cyrillic filenames work perfect on my PC (Linux with utf8 filesystem)!
Russian hotkeys work if Julius started in UK and layot changed to RU.
If game started in RU layot - hotkeys not work even if you change to UK.

**Comment by bvschaik** [comment]
@nwtour That's interesting about the hotkeys, and that doesn't mirror my experience: at least on macOS the hotkeys immediately stop working when I switch to RU. Which operating system do you use?

**Comment by bvschaik** [comment]
@nwtour Could you check the most recent build (for commit 0f53623761a74fe497f2cd802412685fceb399ce)? I've made some changes which should make Julius look at scancodes for non-Latin keyboard layouts.
