### ISSUE TITLE
Overlay tooltip leaves ghosting on the sidebar

### ISSUE THREAD

**Issue by bvschaik** [bvschaik/julius#140]
The sidebar does not get redrawn when a tooltip is forced to draw over it, leaving ghosts of the tooltip.

**To Reproduce**
1. Set your screen to 640x480
2. Use an overlay and make sure we have a relatively long tooltip text. The water overlay will work for reservoir & fountain-covered areas
3. Move the mouse and map around such that the tooltip is forced to the right side of the mouse, and also overlaps with the sidebar
4. Wiggle the mouse around
5. Admire the beautiful ghosting

**Expected behavior**
Either the tooltip should never overlap with the sidebar (I think this is the easiest to implement) or the sidebar should be redrawn / cached after a tooltip is put over it.

**Screenshots**
![ghosting](https://user-images.githubusercontent.com/104874/56090719-1c117900-5ea6-11e9-973c-fd098a7c8b92.png)

**Comment by crudelios** [comment]
This one's on me, must be due to the implementation of partial window invalidation.

**Comment by crudelios** [comment]
Hey I've been sick for the past few days and now that I'm up and running I was about to submit a PR to fix this by changing the tooltip position, but I guess it's useless now :P
