### ISSUE TITLE
Moving the view with keys doesn't work when hovering over some elements

### ISSUE THREAD

**Issue by devnoname120** [bvschaik/julius#147]
**Describe the bug**

Keyboard directional keys normally allow to move the view.
Hovering over some elements (e.g. house build button) don't prevent the directional keys from working. Hovering over some elements (e.g. advisors button) prevent the directional keys from working.

**To Reproduce**

1. Open a city.
2. Hover over the advisors button.
3. Try to move using the directional keys.
4. Nothing happens.

**Expected behavior**

It's possible to move.

**Screenshots**

![image](https://user-images.githubusercontent.com/2824100/56437323-2e911580-62df-11e9-9b2f-f7fd4fc71c08.png)

**Additional context**

Tested on e753cc6ce3d658b0a5a1f7d1dc0964c6e1ccf53e.
I've tried on Windows 10, as well as on the Vita.

This is not an original bug, I cannot reproduce this incorrect behavior when running the original Caesar 3 executable.

**Comment by bvschaik** [comment]
Good catch!
