### ISSUE TITLE
Incorrect import, not possible to stockpile

### ISSUE THREAD

**Issue by atolstoy** [bvschaik/julius#150]
Hello.
This is possibly a bug in the game mechanics, and it goes like this:
In some scenarious Caesar demands goods that you cannot produce your self and need to import. If this occurs for source materials like clay or iron, your trade routes supply it only if there are proper workshops in the city. The turnout also depends on how much goods (eg. pottery or weapons) your city can produce. In other words, it feels like the import is demand-based and does not respect the supply figures on the empire map. 
This is wrong, because the player is therefore unable to fulfill Caesar's demands. Let me show the example city with Caesar demanding clay:
https://www.dropbox.com/s/hsbhawt45e2vb8v/Damascus%20Remastered-2.sav?dl=0
Whatever I do, I just can't collect the required amount - traders simply refuse to deliver it to my warehouses.
If you know how to fix it or just give a clue for it - please do so.
Kind regards.

**Comment by bvschaik** [comment]
The maximum amount of a raw material that will be imported is determined by the number of active workshops that can process that resource, using the following simple formula:
`max amount = 2 + 2 * number of workshops` ([source](https://github.com/bvschaik/julius/blob/8be9f1e0179864bcc7d8eee0f224168b13bf6b8c/src/empire/empire.c#L244))

For clay, that's the number of pottery workshops. To import 32 clay, you would need to place 15 pottery workshops and staff them.

This behaviour is also present in the original game, so I'm closing this issue.
