### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by cyberdyne-sys** [bvschaik/julius#158]
This isn't really a bug report, but an enhancement idea. Ages ago, i played the original game on a P1, with mouse and keyboard, but now, i'm trying to run it on a laptop PC. Don't get me wrong, everything seems to be fine so far; there's only one small disturbing thing, what i noticed. On a laptop (w/o external mouse), it'd be especially useful a shortcut key, for emulating right mouse button clicks. I'm aware, nothing like this is part of the original game, but still, this little addition would be highly appreciated.

**Comment by cyberdyne-sys** [comment]
Any thoughts, or comments on this?

**Comment by bvschaik** [comment]
Sounds like something that can be added. How does pressing Ctrl + clicking sound for right-click?
