### ISSUE TITLE
German text is Out of Bounds. 

### ISSUE THREAD

**Issue by Glurak18** [bvschaik/julius#162]
**Describe the bug**

With the German version the Text is most of the time Out of Bounds. 

**To Reproduce**

Just start the Game with German Files.

[Caesar3 German ENG.zip](https://github.com/bvschaik/julius/files/3463750/Caesar3.German.ENG.zip)

**Comment by Glurak18** [comment]
I did a picture:

![image](https://user-images.githubusercontent.com/36120118/62415895-9a4e8280-b631-11e9-94af-fc2f19183245.png)

**Comment by bvschaik** [comment]
I've started work on this, but I'm wondering how those two screens look like in the original Caesar 3. Could you perhaps attach screenshots from C3? (or attach the German .exe)

**Comment by Glurak18** [comment]
[c3.zip](https://github.com/bvschaik/julius/files/3503840/c3.zip)
Here the german exe.

**Comment by bvschaik** [comment]
Both issues in the screenshots have been fixed. If you encounter any other major out-of-bounds issues, please open a new issue.
