### ISSUE TITLE
Install from the original CD, no patches, plays at easiest difficulty

### ISSUE THREAD

**Issue by loreb** [bvschaik/julius#167]
**Describe the bug**

As in the subject

**To Reproduce**

1. Install the original game, without patching it up to the latest version
2. load eg Mediolanum (5th level) and notice how much money you have, or the size of enemy armies...

**Expected behavior**

The game plays at the expected difficulty

**Saved games**
I don't think this is needed

**Screenshots**

No screenshots

**Additional context**

The problem, if I understand correctly, is that the settings ("c3.inf") from an unpatched game are shorter, and buffer_read_i32() defaults to returning zero, which for eg the difficulty setting is not the default value.

The plan is to upgrade my Caesar III install on windows and copy it over, but the julius should imho either warn ("hey, the patch fixes lots of bugs!") or at least avoid overwriting the default settings with spurious zeros.

A tentative patch follows; take the two "If"s as if they were comments of course! :)

```
diff --git a/src/core/buffer.c b/src/core/buffer.c
index 5576cd10..ef3c115d 100644
--- a/src/core/buffer.c
+++ b/src/core/buffer.c
@@ -154,6 +154,15 @@ int32_t buffer_read_i32(buffer *buf)
     }
 }
 
+int buffer_try_read_i32(buffer *buffer, int32_t *value)
+{
+    if (check_size(buf, 4)) {
+        *value = buffer_read_i32(buffer);
+        return 1;
+    }
+    return 0;
+}
+
 int buffer_read_raw(buffer *buf, void *value, int max_size)
 {
     int size = buf->size - buf->index;
diff --git a/src/core/buffer.h b/src/core/buffer.h
index 4c2ca747..e6c8c01f 100644
--- a/src/core/buffer.h
+++ b/src/core/buffer.h
@@ -132,6 +132,14 @@ int16_t buffer_read_i16(buffer *buffer);
  */
 int32_t buffer_read_i32(buffer *buffer);
 
+/**
+ * Tries to read a signed 32-bit integer (all or nothing)
+ * @param buffer Buffer
+ * @param value value to read into
+ * @return Nonzero if whole integer could be read, zero otherwise
+ */
+int buffer_try_read_i32(buffer *buffer, int32_t *value);
+
 /**
  * Reads raw data
  * @param buffer Buffer
diff --git a/src/game/settings.c b/src/game/settings.c
index 3bcaebb9..9655d4f2 100644
--- a/src/game/settings.c
+++ b/src/game/settings.c
@@ -76,6 +76,7 @@ static void load_settings(buffer *buf)
     buffer_skip(buf, 6);
     data.game_speed = buffer_read_i32(buf);
     data.scroll_speed = buffer_read_i32(buf);
+    // XXX why skip name?
     buffer_skip(buf, 32); //uint8_t player_name[32];
     buffer_skip(buf, 16);
     data.last_advisor = buffer_read_i32(buf);
@@ -100,9 +101,19 @@ static void load_settings(buffer *buf)
     for (int i = 0; i < MAX_PERSONAL_SAVINGS; i++) {
         data.personal_savings[i] = buffer_read_i32(buf);
     }
-    data.victory_video = buffer_read_i32(buf);
-    data.difficulty = buffer_read_i32(buf);
-    data.gods_enabled = buffer_read_i32(buf);
+    // overflow 99% means bad config, so warn
+    if (buf.overflow) being told about this would have been useful;
+    // After this (or after the next line?) begin options
+    // added with the update but not present in the original CD,
+    // so it makes sense to TRY reading them or we get eg
+    // data.difficulty set to zero :D
+    buffer_try_read_i32(buf, &data.victory_video);
+    buffer_try_read_i32(buf, &data.difficulty);
+    buffer_try_read_i32(buf, &data.gods_enabled);
+    // MAYBE because I don't know if the update only adds these options
+    // (in which case we can stick to default values) or also fixes any
+    // bugs in the game data (in which case we'd better warn)
+    if (buf.overflow) maybe warn about overflow somehow;
 }
 
 void settings_load(void)

```

**Comment by bvschaik** [comment]
Sorry for not getting back to you sooner - I was on holiday.
You're right. Julius should use default values (hard difficulty level and gods enabled) when it cannot read any further. I'll implement this.

As for warning when you don't have the patch: it's a bit hard to detect and not really foolproof. The majority of improvements of the patch are in c3.exe, which are of course all implemented in Julius. The other changes are related to the language files (.eng) to add texts for e.g. the difficulty setting, and the empire files (.emp). I _could_ check whether the text for the "difficulty" options menu entry is missing from the language file and warn based on that?

**Comment by loreb** [comment]
Great, thank you.
Starting a new career the game works fine, at least until Carthago, so I'll just wait for a certain package manager to pick this patch :D
Btw, following the link from bug 168 you **do** state that step 2 is installing the patch, so if I missed it, sorry... I'm also opening another issue to request a working Italian patch, as explained in https://bintray.com/bvschaik/caesar3-patches.
