### ISSUE TITLE
Please provide Italian patch

### ISSUE THREAD

**Issue by loreb** [bvschaik/julius#169]
https://bintray.com/bvschaik/caesar3-patches does say to open a ticket here, so here it is.
/usr/bin/file says "c3up11It.EXE: MS-DOS executable, NE for MS Windows 3.x (EXE)",
which Windows 10 is no longer able to run, and reading Italian forums it seems that people
play the unpatched version because they are unable/unwilling to set up a vm, install caesar 3 there and copy the files back.

Installing the 64-bit compatible version from sierrahelp.com works with julius, but c3.exe complains that the CD is missing even if it's there...

I'm assuming you have a script or something to do most of the work; if you need me to do anything, just ask.

**Comment by bvschaik** [comment]
I have an old WinXP VM ready for these cases :-)
Could you send me the following files from your 1.0 Italian installation so I can run the patcher?

- c3.exe
- c3.eng
- c3_mm.eng
- c3.emp

**Comment by loreb** [comment]
Here they are
[c3.zip](https://github.com/bvschaik/julius/files/3718301/c3.zip)

If you feel like announcing the patch, like for the Russian version, the forum is at https://caesar3.forumattivo.com/

**Comment by bvschaik** [comment]
Thanks, I will have a look at them tomorrow when I'm back home and at my computer.

**Comment by bvschaik** [comment]
I ran the installer on your files and it worked on my VM.
Could you try [these updated files](https://bintray.com/bvschaik/caesar3-patches/italian)? It also shouldn't complain about the missing CD anymore.

**Comment by bvschaik** [comment]
Yes, the File -> Delete dialog was added in the patch and therefore using the 1.0 language file would result in those kind of bugs.

Thanks for testing, I will close this issue.
