### ISSUE TITLE
Missing switch default cases

### ISSUE THREAD

**Issue by devnoname120** [bvschaik/julius#17]
There are many instances (~175) where a switch on an `int` doesn't have a `case default`. Here is an example: https://github.com/bvschaik/julius/blob/6979976658bab1bdc3db7e9b056b62b20bcb289e/src/Building.c#L386

This often leads to uninitialized variables being used. Instead, the error should be logged, and a default value should be assigned.

**Comment by bvschaik** [comment]
Which tool do you use to find those instances?

**Comment by devnoname120** [comment]
[CLion](https://www.jetbrains.com/clion/), it's [free for opensource projects](https://www.jetbrains.com/buy/opensource/?product=ALL).

**Comment by bvschaik** [comment]
Checked all switch statements, I found no more uninitialized variables.

**Comment by devnoname120** [comment]
I think it's worth logging it when a `default` case is hit as it's not supposed to happen.
