### ISSUE TITLE
Support Traditonal Chinese

### ISSUE THREAD

**Issue by 411752230** [bvschaik/julius#186]
Hi there, I found this patch for C3 is pretty enjoyable. Great thanks for the dev's dedication!!!
However, I found julius doesn't support Chinese version, which is a pity. Would it be possible for this patch to support Chinese? I can share the official language pack for you then.
https://drive.google.com/file/d/1R2mN5OO6tCmk4wZUjackYDIcC8WLfOpT/view?usp=sharing

By the way, the language pack is only Traditional Chinese, rather than Simplified Chinese which is absent for a long time. I dont suppose julius could give a font support to get the game into Simplified Chinese version?

**Comment by bvschaik** [comment]
Hi! Julius indeed does not support the Chinese version since I didn't have the files from the Chinese version. I'm going to have a look at this: I'm wondering how the Chinese version devs solved the font issues.

Could you perhaps send the full installation, instead of the selection you put on Google drive? You can leave out the "smk" and "wavs" folders.

Supporting Simplified Chinese: it depends on how the Traditional Chinese version is implemented. I'd like to have as little impact on the current code as possible, and since the fonts are currently embedded in the game's graphics it might not be possible to support Simplified Chinese.

**Comment by 411752230** [comment]
Thanks for your concern！:D 
Here is the full installation pack of C3 traditional Chinese:
https://drive.google.com/file/d/1az1_B-SV-UilOILr26YL2x8VE57yXBGq/view?usp=sharing

During the installation, please tick "convert into Chinese". Feel free to take advantage of it, this should be all I can do at least.

**Comment by bvschaik** [comment]
Thanks! I just got the Chinese version running. I don't understand any of it but this gives me something to work with.

**Comment by 411752230** [comment]
Great to hear! If you got any question concerning the Chinese text of C3, feel free to ask me. I shall try my best to answer.

**Comment by bvschaik** [comment]
You can grab an experimental Windows build from here: https://bintray.com/bvschaik/julius-branches/windows/chinese-1.1.0.177-2526283a#files
Some things don't work properly, but the basics are there - please try it out.

Questions:
- File names: does the game only allow Latin characters or can you also enter Chinese ones?
- Was there a Chinese version of the assignment editor?

**Comment by 411752230** [comment]
Amazing, great work! I shall represent all the Chinese players of c3 to say THANKS for you!
The patch looks wonderful to me, except the missing text when press "ESC". It's OK baecause the original version has a messy code in this part.

Grateful to answer:
1. It is true that the Chinese version doesn't support Chinese characters inputting just the same as the English version. Any inputting Chinese character or translated by EngConverter will baecome a "?". 
2.Unfortunately, there was no Chinese version of the AE. Some of the Chinese veteran players have used the Eng version for long. Is there possibility to get the AE into Chinese? If do so, I am a volunteer here to be the translator getting all things right.

Moreover, I am wondering have you successfully translated the new text in the main menu of c3? The newly added bar "Caesar III assignment editor" seems to have been translated into "凱撒大帝III assignment editor".

**Comment by lingjiameng** [comment]
Commit here to backup. 
[traditional-chinese-chars.txt](https://github.com/bvschaik/julius/files/3927481/traditional-chinese-chars.txt)
[simplified-chinese-chars.txt](https://github.com/bvschaik/julius/files/3927557/simplified-chinese-chars.txt)

**Comment by 411752230** [comment]
backup
![chinese-chars](https://user-images.githubusercontent.com/14128007/70248665-3215d600-17b6-11ea-84e1-7cd0412d38b8.png)

**Comment by bvschaik** [comment]
New version:
https://bintray.com/bvschaik/julius-branches/windows/chinese-1.1.0.182-cf2ca744#files

Fixed:
- Thinner, more readable font
- Window title is now in Chinese
- Exit game dialog now has text (please check if it's correct)
- The medium-sized font is drawn 2px lower, making it align better with the interface elements

Things still to do:
- Links in the help section are always 2 characters red and clickable, the rest is white
- Create new `rome.555` file for Simplified Chinese
- Unrelated to Julius: update ENGConverter to support Chinese, so we can perhaps start to translate the editor texts

Please try it out and report any bugs/improvements.

**Comment by 411752230** [comment]
Good job! The window title and the exit game dialog work correctly and perfectly. 

Sorry me again for the screenshots yesterday, I'm afraid that the thinner font makes the texts a bit of too thin though it looks better than the original one especially in the Help section.
Is there a medium between the original and the thinner one. Like semi-bold?

The game would crash when opening the help section. I don't suppose it was temporarily disabled under development?

**Comment by lingjiameng** [comment]
Exit game dialog is correct.
[bug] consultant page and world map can't open

**Comment by cyberdyne-sys** [comment]
> Any inputting Chinese character or translated by EngConverter will baecome a "?".

My addition isn't actually about chinese characters, but at this point, i'd like to let you know about, that the same happens, with letters "ő" and "ű", when creating translation, with ENGConverter.

**Comment by 411752230** [comment]
> > Any inputting Chinese character or translated by EngConverter will baecome a "?".
> 
> My addition isn't actually about chinese characters, but at this point, i'd like to let you know about, that the same happens, with letters "ő" and "ű", when creating translation, with ENGConverter.

as a result of the font cannot identify the translation or text inputting.

**Comment by bvschaik** [comment]
> My addition isn't actually about chinese characters, but at this point, i'd like to let you know about, that the same happens, with letters "ő" and "ű", when creating translation, with ENGConverter.

That's because those two letters are not supported by Windows codepage 1252, and therefore also not in Julius when using any Western European language.

**Comment by bvschaik** [comment]
@411752230 and @lingjiameng Final Windows build with semi-bold font for Traditional Chinese is [here](https://bintray.com/bvschaik/julius-branches/windows/chinese-1.1.0.186-d14234bc#files): could you give it a go with the original Traditional Chinese `rome.555` and report any issues here? I'd like to finish this issue and then continue the discussion on the Simplified Chinese version in #192.

**Comment by lingjiameng** [comment]
Sure! I think it works well.

**Comment by 411752230** [comment]
Traditional Chinese now with semi-bold works wonderfully. I think TS could be done at here

Just found a small problem in-game.  Start a new game with a bigger map, deleting all objects at one go by clear land, you will see some rocks as well as some other objects become red before you click the clear land button again with all the red objects turning to normal.

**Comment by crudelios** [comment]
> Just found a small problem in-game. Start a new game with a bigger map, deleting all objects at one go by clear land, you will see some rocks as well as some other objects become red before you click the clear land button again with all the red objects turning to normal.

Offtopic, but fixed by #196.
