### ISSUE TITLE
When starting a new career, the entered governor name is not saved 

### ISSUE THREAD

**Issue by bvschaik** [bvschaik/julius#194]
@bvschaik Another bug with the latest julius you provided both in Eng and Chinese version. Start a new game and give yourself a new name. set some housing and waiting for the fire broken. You will see no matter what name you have set the governer's name is always "the new governer"

_Originally posted by @411752230 in https://github.com/bvschaik/julius/issues/192#issuecomment-563078808_

**Comment by 411752230** [comment]
Maybe another small one? Have you noticed that enabling overlays mode of view will disable the added red cursor of "clear land" as same as the original.

**Comment by crudelios** [comment]
> Maybe another small one? Have you noticed that enabling overlays mode of view will disable the added red cursor of "clear land" as same as the original.

That is a "feature", not a bug (read: I haven't implemented the red cursor to the overlay mode yet).

Also, offtopic.

**Comment by 411752230** [comment]
> > Maybe another small one? Have you noticed that enabling overlays mode of view will disable the added red cursor of "clear land" as same as the original.
> 
> That is a "feature", not a bug (read: I haven't implemented the red cursor to the overlay mode yet).
> 
> Also, offtopic.

Good one. Cheers.

**Comment by 411752230** [comment]
Just found the concerning changelog of c3 1.1 as reference.
The governor's name will no longer be reset to 'The New Governor' or take the name from a previous game when changing games or maps. This will work from any new saved games (not old ones.)
