### ISSUE TITLE
Improve full screen resolution support

### ISSUE THREAD

**Issue by crudelios** [bvschaik/julius#201]
Now that Julius has support for scaling, it is possible to easily set a full screen resolution independently of monitor resolution.

So I suggest changing the `Display options` menu so that it allows showing all resolutions that the monitor supports, using scaling to display the desired resolution on fullscreen. Instead of the three buttons, up/down arrows could be used.

The only issue is, I don't know how compatible that is with the original C3 settings file.

**Comment by bvschaik** [comment]
I think there are a couple of fields left in the settings file which are not used by C3, so that should not be a problem.

I see other issues:

- Where do we get the resolutions from?
- How do we display them in the list, in all the different languages we currently support?
- We use `SDL_WINDOW_FULLSCREEN_DESKTOP` for fullscreen: we can never go beyond the current desktop resolution using scaling
- What do we do about aspect ratio? Stretching 800x600 to full-HD or letterboxing?

I think a better option might be to have a setting for display scale in the display options instead.

**Comment by crudelios** [comment]
For the first three issues:
We could use `SDL_GetDisplayMode` to get the available resolutions and list them individually, using the up/down arrow buttons to list each one. We could display it as a basic `800x600`, `1024x768`, etc...

> What do we do about aspect ratio?

Good question. No idea. Add a display setting?

> I think a better option might be to have a setting for display scale in the display options instead.

That is a good idea, but we would also need some translation for a text like `Scale settings`.

**Comment by bvschaik** [comment]
> That is a good idea, but we would also need some translation for a text like `Scale settings`.

Exactly. And this is also the reason why I'm hesitant about changing features that require language changes, since I have no intention of maintaining 10+ language translation files as well...

**Comment by dcnieho** [comment]
While its possible, i wonder what the use case would be. Its not like
Julius is heavy to run (for my machines anyway), so i have no interest to
easy switch to a lower resolution. If wanted it could be a command-line
option, matched against the list of SDL resolutions. Keeps it simple, and
sufficient for what is likely an edge use case?

**Comment by crudelios** [comment]
It's necessary for Android because there is no way to invoke the command line and the autodetection doesn't always work.

**Comment by bvschaik** [comment]
Why would it be necessary for Android? Can't you just do `getResources().getDisplayMetrics().density` and scale accordingly?

**Comment by crudelios** [comment]
Is that java code? I'll try it out.

**Comment by bvschaik** [comment]
Yes, put that in the activity. It will give you a floating point number which can be used directly as display-scale.

**Comment by crudelios** [comment]
I'll try it out, thanks. Meanwhile I'll close this.
