### ISSUE TITLE
I cannot get the MP3s to work

### ISSUE THREAD

**Issue by KillahNeo** [bvschaik/julius#204]
It simply does not work, i've created a folder named mp3 and correctly named all the files, no change whatsoever in-game, also i'd like to ask why does Julius skip the game intro .smk videos? 

Can i change that?

![image](https://user-images.githubusercontent.com/47231209/71639703-176e3a00-2c5a-11ea-9f01-88cbd3b4acf7.png)

**Comment by crudelios** [comment]
Did you copy `libmpeg123-0.dll`? 

If you didn't, go to the [`SDL_mixer` website](https://www.libsdl.org/projects/SDL_mixer/) and download the runtimes for Windows (if you downloaded Julius from here, you'll need the 32 bit version). Then copy the file `libmpeg123-0.dll` to the same folder where Julius is.

**Comment by 411752230** [comment]
Same here. The skipped intro video of julius because of its lower resolution?

An additional question. The high quality MP3? May I know what's the exact difference between the original .wav from Steam or GOG edition and the HQ MP3. Their sizes? 
If the HQ MP3 once published publicly could more or less improve the gameplay, why dont we upload them online and give out a download link on the README.md of julius since julius does support this feature.

**Comment by crudelios** [comment]
> The skipped intro video of julius because of its lower resolution?

The intro videos are not included in the source code, so I'm guessing it was a deliberate choice by @bvschaik to skip the videos for faster loading.

> The high quality MP3?

The original wavs have a constant hiss that the MP3s don't.

> why dont we upload them online and give out a download link on the README.md of julius

Because the MP3s are copyrighted, so to prevent any legal problems we decided not to distribute them.

**Comment by 411752230** [comment]
Ok, is there a way to get the HQ mp3 except dowloading from the archive? I dont suppose is there someone could share them since the Chinese C3 community got no idea of it at all. Thanks in advance!

**Comment by KillahNeo** [comment]
I can get you the original MP3s, i have all of them in their originall format, it was downloaded by my father in 1999..
Add me on Steam, https://steamcommunity.com/id/killahneo/

**Comment by KillahNeo** [comment]
> 
> 
> Did you copy `libmpeg123-0.dll`?
> 
> If you didn't, go to the [`SDL_mixer` website](https://www.libsdl.org/projects/SDL_mixer/) and download the runtimes for Windows (if you downloaded Julius from here, you'll need the 32 bit version). Then copy the file `libmpeg123-0.dll` to the same folder where Julius is.

I have done that with no luck, but i still want the videos to play at the intro.

**Comment by crudelios** [comment]
Which version of Julius did you download? MP3 support is a new feature and is not available in the `Latest stable`, only on `Unstable` (which, coincidentially, is now more stable than `Stable`).

**Comment by KillahNeo** [comment]
> 
> 
> Which version of Julius did you download? MP3 support is a new feature and is not available in the `Latest stable`, only on `Unstable` (which, coincidentially, is now more stable than `Stable`).

I have the stable version, well if that was specified i would had known earlier, lol, but anyways, i have new plans for Caesar III, i would like to remaster the game entirely, is that possible? I know it is possible to replace some files with other impressions games like from Pharaoh, as i've seen a old post on the internet.
Thanks for the hard work you guys have made until here though

**Comment by KillahNeo** [comment]
Just an example here

Original:
![test](https://user-images.githubusercontent.com/47231209/71645445-7f06a280-2cb7-11ea-9759-640e5e6d0a43.jpg)

Remaster:
![test-remaster](https://user-images.githubusercontent.com/47231209/71645446-8332c000-2cb7-11ea-946d-7032308d74c0.jpg)

**Comment by crudelios** [comment]
> I have the stable version, well if that was specified i would had known earlier

Yeah the stable version is a few months old already. Perhaps a new one should be released when android support is merged.

> i would like to remaster the game entirely, is that possible?

Right now it isn't, allowing high-res textures requires changing the entire graphics engine. We talked last year about doing it, but we didn't have the time to even start.

The remaster looks nice and sharp! Sid you use an AI to upscale the background?

Also, is MP3 working now so this issue can be closed?

**Comment by KillahNeo** [comment]
Yes close down.
