### ISSUE TITLE
Voice of Caesar

### ISSUE THREAD

**Issue by m-mohr** [bvschaik/julius#209]
**Describe the bug**
I'm playing the German version of Caesar with the 1.1.0 release of Julius. Everything seems to work fine, but the voice of Caesar (when I'm in dept or can't deliver requested goods) is really loud and "croaky". I always have to lover the volume with head phones or my ears get blown away. It works well when I start the original game.

**To Reproduce**
Not sure... Install German game and play horribly so that Caesar has to complain...

**Expected behavior**
Voice should be as "smooth" as in the original game.

**Saved games**
[Let this save game run for some minutes and it will happen...](https://github.com/bvschaik/julius/files/4024052/Hier.weiter.zip)

**Screenshots**
N/A

**Additional context**
Windows 10

PS: Thank you for all the work. It's great!

**Comment by bvschaik** [comment]
Hi, thanks for reporting. This sounds like issue #161, which was fixed after 1.1.0 was released.

Could you perhaps try this version with video improvements and see if video works correctly here? https://bintray.com/bvschaik/julius-branches/windows/video-improvements-1.1.0.212-3f3b8492#files

**Comment by m-mohr** [comment]
Great, works like a charm. Thank you!
