### ISSUE TITLE
Music playing on map editor

### ISSUE THREAD

**Issue by KillahNeo** [bvschaik/julius#210]
It should play only on the main menu but instead if plays when you are inside the map editor

**Comment by crudelios** [comment]
I think the map editor should always play the `ROME1` music.

As @KillahNeo said, right now it keeps playing the main menu music. However, it you disable and re-enable the music in the audio options, it starts playing `ROME1`. Furthermore, if you then return to the main menu, whatever music is playing does not stop.

**Comment by KillahNeo** [comment]
I have the original SETUP.mp3 if anyone needs it tho

**Comment by bvschaik** [comment]
I would like that, yes. Can you perhaps send it through Gitter?

I'm just looking into this:
- The original editor plays ROME1
- The original game keeps playing the last city's music when going back to the main menu

My proposal for Julius:
- Play ROME1 in the editor
- Start playing SETUP again when going back to the main menu

**Comment by KillahNeo** [comment]
By the way, if we could rip this off C3 it would make a very good new icon.
I can send you the file via Steam @bvschaik give me your steamid
![1505305693-3118401307 - Copia](https://user-images.githubusercontent.com/47231209/71843559-ef8c3580-30a2-11ea-9447-272a483b7814.jpg)

**Comment by bvschaik** [comment]
My Steam ID is pecuniam.

**Comment by KillahNeo** [comment]
> 
> 
> My Steam username is pecuniam, but that's not my steam ID? I have a limited account since I never bought anything, only tested stuff for game companies.
> This is my profile URL if that helps: https://steamcommunity.com/profiles/76561197999105548/

How can i work testing stuff for game companies?

**Comment by bvschaik** [comment]
> How can i work testing stuff for game companies?

I don't know how that goes nowadays. I was a frequent beta tester for Tilted Mill, the company founded by old Impressions Games employees, and they started using Steam for distributing beta games ages ago. Tilted Mill is no longer producing games though.

Anyway, can you add me as friend on steam through there or is that not possible?

**Comment by KillahNeo** [comment]
I have sent you a friend invite

**Comment by KillahNeo** [comment]
![icone](https://user-images.githubusercontent.com/47231209/71846660-ddfa5c00-30a9-11ea-8ca5-4ba5924ea541.png)

**Comment by bvschaik** [comment]
Music has been fixed now according to my proposal.
