### ISSUE TITLE
Two bugs found in the AE

### ISSUE THREAD

**Issue by 411752230** [bvschaik/julius#211]
1. Go to the AE and click native centers or others alike. Not only the native center is selected but also it has been placed on the map (Double click?)

2. Once selected Native center or others alike, right click to cancel the select and left click on the map, the the buildnig is still selected and built without featured cursor.

![QQ截图20200107135102](https://user-images.githubusercontent.com/14128007/71871941-d7c1b980-3155-11ea-87d9-247150c26465.jpg)

**Comment by bvschaik** [comment]
Thanks for reporting! The second one also worked for other tools (trees, rocks, etc).
