### ISSUE TITLE
Make intro video optional

### ISSUE THREAD

**Issue by KillahNeo** [bvschaik/julius#213]
Self-explanatory, make a command line or somenthing to toggle on or off the loading of the intro videos according to the user's taste

**Comment by bvschaik** [comment]
Intro movie can now be viewed by clicking the button in the lower right of the main menu.

**Comment by KillahNeo** [comment]
> 
> 
> Intro movie can now be viewed by clicking the button in the lower right of the main menu.

Add a Cutscenes button in the main menu

**Comment by 411752230** [comment]
@bvschaik Get back from the intro video to main menu, the music plays rome1 rather than setup
