### ISSUE TITLE
Caesar 3 1.0.1.0 Spanish missing.

### ISSUE THREAD

**Issue by zLurn** [bvschaik/julius#216]
"If you don't see your language here, please open a ticket at https://github.com/bvschaik/julius/issues"

Okie dokie.

**Comment by bvschaik** [comment]
Hi, I assume you have the 1.0 Spanish version? If so, could you upload the following files from your 1.0 Spanish installation so I can run the patcher?

- c3.exe
- c3.eng
- c3_mm.eng
- c3.emp

**Comment by bvschaik** [comment]
I managed to get the files, the patched files can be downloaded here: https://bintray.com/bvschaik/caesar3-patches/spanish/1.0.1.0
