### ISSUE TITLE
Caesar III Portuguese Brazillian Language missing

### ISSUE THREAD

**Issue by KillahNeo** [bvschaik/julius#217]
Title says it all

**Comment by crudelios** [comment]
I sent the portuguese translation to @bvschaik so this is solved.

**Comment by KillahNeo** [comment]
Portuguese from Portugal but i'm not sure if it's the same as the Portuguese Brazillian version

**Comment by bvschaik** [comment]
I don't think there was a European Portuguese version of the game, Sierra only officially published Italian, French, German, and Spanish versions in addition to English. The language files that @crudelios sent are Brazilian. I'm awaiting a few translations and then I can upload the files.

**Comment by bvschaik** [comment]
Files have been uploaded, please test them: https://bintray.com/bvschaik/caesar3-patches/portuguese-br

**Comment by KillahNeo** [comment]
Yes, but there are translations missing

**Comment by bvschaik** [comment]
Which ones specifically?

**Comment by crudelios** [comment]
@KillahNeo The editor doesn't have a portuguese translation, if that's what's missing.

**Comment by KillahNeo** [comment]
The editor needs to be translated

**Comment by bvschaik** [comment]
Since I'm not fluent in Portuguese (either variant), please translate these files for me: 
[editor_language_files.zip](https://github.com/bvschaik/julius/files/4050311/editor_language_files.zip)

**Comment by KillahNeo** [comment]
Working on c3_map_mm.xml
@crudelios you could work on the other one

**Comment by bvschaik** [comment]
Crudelios is not Brazilian. And I understand that the two languages are quite different, so don't expect any help there.

**Comment by KillahNeo** [comment]
> 
> 
> Crudelios is not Brazilian. And I understand that the two languages are quite different, so don't expect any help there.

They are not that different at all

**Comment by bvschaik** [comment]
I'm going to close this issue since there's nothing I can do about this at the moment. Once you finish the translation, post a comment here and I'll reopen the issue so we can get the translated editor files available for download.

**Comment by felipecrs** [comment]
What's weird is that the readme (leiame) says it's version 1.1, while the English version is actually 1.0.1.0. I wonder if they have the same enhancements/fixes.

**Comment by bvschaik** [comment]
Yes, they do, there was only 1 patch for Caesar 3. The "1.0.1.0" and "1.1" patch versions are the same and the version numbers are used interchangeably in the documentation. Back in the days there was no convention for version numbers, I suppose...

**Comment by felipecrs** [comment]
Hahaha, that's right.
