### ISSUE TITLE
Upload artifacts built from all branches and pull requests

### ISSUE THREAD

**Issue by devnoname120** [bvschaik/julius#219]
For example using https://transfer.sh, each file can be up to 10 GB and will be stored for 14 days. This is not a lot but this can make testing on exotic platforms (PS Vita, Switch, etc.) easier as you can just ask someone who has a PS Vita to test for you without setting up the corresponding environment.

Note that [pull requests always skip the deploy step](https://docs.travis-ci.com/user/deployment#pull-requests) so it will need to be put in `after_success` or another step.

**Comment by bvschaik** [comment]
A while ago you mentioned Azure Pipelines which includes downloadable artifacts. Maybe that would be an idea to use instead of the current Travis/AppVeyor/Bintray combination?
Branch builds are currently uploaded to https://bintray.com/bvschaik/julius-branches

**Comment by devnoname120** [comment]
True, I think that uploading them to transfer.sh is less effort than porting the whole CI system to Azure Pipelines though.

**Comment by devnoname120** [comment]
Quick update about Azure Pipelines it seems to have (since when?) very strict retention policies regarding builds and artifacts. I would not recommend Azure Pipelines in the current state. The limits can only be barely increased.

![image](https://user-images.githubusercontent.com/2824100/72483324-def56100-3800-11ea-8f39-cf5f192d8b5c.png)

**Comment by bvschaik** [comment]
The limits are ok for PRs and branches. For master we can still upload to Bintray.
Are Github Actions any better?

**Comment by bvschaik** [comment]
Just clicked through to the website: transfer.sh seems a one-man project not meant for storing CI artifacts. Azure pipelines may be OK but is a lot of work, same thing for Github actions. If someone's willing to make the effort, please do and open a PR. For now I will close this issue.

**Comment by devnoname120** [comment]
Imho it's ok for temporary storage. I'm willing to make the effort to implement transfer.sh in our pipeline. If this is ok for you, please reopen the issue and assign it to me.

**Comment by bvschaik** [comment]
I cannot with a clear conscience use a file _transfer_ site for _storage_. Besides, we cannot guess how long this service will continue if the page starts with "Don’t Panic! transfer.sh will live on!"
