### ISSUE TITLE
Caesar III Original Icon's Remaster

### ISSUE THREAD

**Issue by KillahNeo** [bvschaik/julius#226]
Just in-case anyone wants it or wants to implement this monumental arch in-game in the future someway somehow imma leave it here.
Format is already in .png

![c3 icon](https://user-images.githubusercontent.com/47231209/72225605-14cae900-3566-11ea-89b9-08365c1e89aa.png)

![c3icon2](https://user-images.githubusercontent.com/47231209/72225607-172d4300-3566-11ea-89fb-3d748353b8c7.png)

**Comment by bvschaik** [comment]
These are not remastered, they're in-game graphics directly from the demo's .sg2 file. The building (triumphal arch) is already available in-game.
As for the icon: we keep the coin for Julius.

**Comment by KillahNeo** [comment]
Actually yes, but i've uploaded the wrong images, here are the remasters.
Besides i think these could be optional for other players so there's no need to close the issue as you've done

![c3 icon-remaster](https://user-images.githubusercontent.com/47231209/72226361-1220c180-356f-11ea-9aff-998d7e09dbda.png)
![c3icon2-remaster](https://user-images.githubusercontent.com/47231209/72226362-1220c180-356f-11ea-9e32-003f505688f3.png)
