### ISSUE TITLE
Does the Vita version support MP3 playback?

### ISSUE THREAD

**Issue by AlC4pwn** [bvschaik/julius#228]
Just curious if the Vita version also supports MP3 playback? Also on the website there are only 5 MP3 files, not the 8 listed on https://github.com/bvschaik/julius/blob/master/doc/mp3_support.md

**Comment by crudelios** [comment]
It should support MP3 playback, but it really depends on the SDL implementation.

The extra 3 files are in case someone wants to improve the existing ones by using some sort of AI.

**Comment by AlC4pwn** [comment]
I found all the MP3's as listed, they're located here http://sierrachest.com/index.php?a=games&id=91&title=caesar-3&fld=music

**Comment by bvschaik** [comment]
I added a link to the original high-quality MP3 files in the MP3 support documentation.
The ones on SierraChest are the .wavs converted to .mp3, which are not better in quality compared to the original MP3s.

**Comment by AlC4pwn** [comment]
> 
> 
> I added a link to the original high-quality MP3 files in the MP3 support documentation.
> The ones on SierraChest are the .wavs converted to .mp3, which are not better in quality compared to the original MP3s.

Oh that's too bad, I hadn't tried those ones yet as I already had the original ones downloaded.
