### ISSUE TITLE
GameSpeed Info

### ISSUE THREAD

**Issue by ArtySh0ck** [bvschaik/julius#229]
Please, add some info-string (label on top panel for example...) about **current gamespeed**. Sometimes its difficult to remember which  current game speed is while Pause when it controlled by hotkeys ( "[" and "]" ), as example, and when its unpaused sometimes its unexpectedly too fast. Another reason: it would be just comfortable thing, for real.

**Comment by 411752230** [comment]
Agree. Message bar like this would be perfect.
![QQ截图20200115142734](https://user-images.githubusercontent.com/14128007/72410370-3f55b580-37a3-11ea-85da-c4c8c44f3dc2.jpg)

**Comment by crudelios** [comment]
I think this is actually a good idea, and could be placed at the top menu with up/down arrows at large enough resolutions.

**Comment by crudelios** [comment]
I have added the game speed with to buttons to the top menu, here's how it looks:

![](https://user-images.githubusercontent.com/6518876/72721646-709ffe00-3b74-11ea-9304-3d52e6dc129d.JPG)

@jfkonecn has mentioned that the arrow buttons don't look so good in the top menu.

The buttons can be ditched, and an alternative would be for the game to display `Game speed: X%` (perhaps with the darker background like for the pop and Dn) and, upon left clicking on the text, the `Speed settings` window would open.

Any suggestions? [Here's a link to the windows build of my current implementation with the arrow buttons](https://ci.appveyor.com/api/buildjobs/wov4x98gvaag4ksv/artifacts/build%2Fjulius.exe).

**Comment by bvschaik** [comment]
I agree that the arrow buttons look out of place. Just "Game speed X%" would be good, and I think we should keep the regular background: the dark background comes only in a fixed size, and even the English text will overflow.

**Comment by bvschaik** [comment]
Further discussion should continue in #281 .
