### ISSUE TITLE
Resharper Code Analysis

### ISSUE THREAD

**Issue by polaretto** [bvschaik/julius#23]
Hi, I have the [Resharper ](https://www.jetbrains.com/resharper-cpp/) tool which alerts me of "some" warnings may be interesting to check. Here are the results:
[Code Issues in 'julius'.txt](https://github.com/bvschaik/julius/files/1717760/Code.Issues.in.julius.txt)

**Comment by bvschaik** [comment]
Only a few, huh? Thanks! I might ask you to re-generate that export for me a couple of times, if you don't mind 😉 

I'll take a look at them sometime this week. I skimmed through them, and I'm wondering: why does it report things like `Cannot resolve symbol 'building'` (for example in `src/building/barracks.c` when the compiler _can_ find it?

**Comment by polaretto** [comment]
That's quite interesting. The suggested fix says to add _#include building.h_ ... Maybe the compiler can infer the type from somewhere else? I'm not sure... Btw of course these warnings are just good hints for possible bugs but many of them may even not be worth fixing as for most code analysis reports...

**Comment by polaretto** [comment]
I think most of the reported issues are related to the fact that the project is seen as C++ while most of the codebase in C (and follows C conventions). Therefore fixing them or not depends on whether the direction to follow is to move to a C++ architecture or to stay in a C-based one.

**Comment by bvschaik** [comment]
Most of the reported issues are indeed related to C++ and can be ignored. I have categorized the errors and will work on the most important ones, like uninitialized variables.
