### ISSUE TITLE
One button to command "return to fort for all existing legions"

### ISSUE THREAD

**Issue by ArtySh0ck** [bvschaik/julius#230]
Please, add some button (on screen of Military Advisor, for example) to command for ALL existing legions to return to their forts, please. It would make UI much comfortable to play. Thank you!

**Comment by bvschaik** [comment]
The Military advisor already contains buttons to send each legion home (which I personally rarely use). This new button would basically save just 5 clicks, while I'm totally at a loss where I would place the 'send all home' button.

**Comment by crudelios** [comment]
> while I'm totally at a loss where I would place the 'send all home' button.

Agreed. I looked and couldn't find a good spot to place the button.

**Comment by ArtySh0ck** [comment]
![button](https://user-images.githubusercontent.com/46932541/72476860-e6177180-37f6-11ea-9419-2b43f6ebd54d.png)

For example.

**Comment by ArtySh0ck** [comment]
OR! Do swap "Empire service" and "Return to fort" columns. And that global returning button could be placed under "Return to fort" column.

**Comment by bvschaik** [comment]
Below the list will run into the text in some translations. Above it does not look nice. I still think this functionality is not necessary for the few times per mission that you might want to use it.

**Comment by ArtySh0ck** [comment]
![New Project](https://user-images.githubusercontent.com/46932541/72601366-f37b4b80-391d-11ea-83dc-56da74ef1d46.jpg)

Maybe a tooltip while hover on? With SHIFT (or Alt...) that button will send command to return to all existing legions.

**Comment by bvschaik** [comment]
The problem with adding tooltips: we can only work with the strings defined in the original text files, because I don't want to bundle or maintain 9 translations with Julius, so that's no option.
I still think this too much of an effort to save at most 5 mouse clicks every couple of game years.
