### ISSUE TITLE
What about AutoSave?

### ISSUE THREAD

**Issue by ArtySh0ck** [bvschaik/julius#232]
Don't pretty sure if it can broke Caesar 3 game mechanics, but it would be a very useful to have an **Autosave** option with own in-game settings. Thanks!

**Comment by bvschaik** [comment]
Caesar 3 already has support for monthly autosaves under the hood, but it was never implemented in the UI.

I just implemented it as toggle in the Options menu. Translated strings for the on/off states are already in the .eng files.

**Comment by 411752230** [comment]
> Caesar 3 already has support for monthly autosaves under the hood, but it was never implemented in the UI.
> 
> I just implemented it as toggle in the Options menu. Translated strings for the on/off states are already in the .eng files.

Wow, thats really a feature of leagcy.

**Comment by crudelios** [comment]
> Does the .eng also has texts concerning the autosaves info bar?

Do you really want to have a bar appearing every sigle in-game month? Because that's a lot of bars.

**Comment by bvschaik** [comment]
> Does the .eng also has texts concerning the autosaves info bar? Just like #229 @ArtySh0ck Posted.

No, it doesn't.

**Comment by 411752230** [comment]
@crudelios Indeed. It's not suitable to get a monthly message bar for that. As @bvschaik said that no mapping text, it cant be the same as Zeus + Poseidon: notification semiannually.
![QQ截图20200116122117](https://user-images.githubusercontent.com/14128007/72493243-3de7c400-385b-11ea-8914-7d85a140affe.jpg)

**Comment by bvschaik** [comment]
Autosave has been implemented. File will be saved as `autosave.sav` - Caesar 3 uses `last.sav` but I found that name a bit weird.
