### ISSUE TITLE
Folders ending with ".sav" get listed as files and can be opened

### ISSUE THREAD

**Issue by crudelios** [bvschaik/julius#234]
If you save a folder as `<any name>.sav`, then that folder will be listed as a valid city in the Load/Save/Delete dialog.

If you then try to open the file, this will happen:

![empty_city](https://user-images.githubusercontent.com/6518876/72457637-f7dd2280-37be-11ea-80de-95b6bb49ef46.JPG)

As you can see, the game loads an empty city with no terrain and everything set to `0`. The `emperor wrath` message appears because your empire rating is also `0`.

In C3, while the folder appears as a city in the Load/Save/Delete dialog, if you try to open it it will refuse saying that the file does not exist.

Suggestions to fix the bug:
* Do not show folders ending with `.sav` as cities in the Load/Save/Delete dialog. This can easily be done by adding a check for  `entry->d_type == DT_REG` in the function `dir_find_files_with_extension` of file `src/core/dir.c`, which should only check for files anyway.
* This, however, does not prevent the user from manually typing the folder name, thus loading an empty file. To fix that, we should check the return value of the `game_file_load_saved_game` (and friends) in function `button_ok_cancel` of file `src/window/file_dialog.c`, triggering a `File does not exist` message if the function returns `0`.

**Comment by crudelios** [comment]
Upon further testing, loading an empty file that ends with `.sav` also causes the game to load an empty city.

However, contrary to a folder, the original Caesar 3 also opens the empty city just like Julius.

I think that, too, should be fixed, perhaps by somehow checking if the city file is valid.

**Comment by bvschaik** [comment]
>     * This can easily be done by adding a check for  `entry->d_type == DT_REG` in the function `dir_find_files_with_extension` of file `src/core/dir.c`, which should only check for files anyway.

I'd rather flip the check around and block directories and known non-files. Symlinks should be supported, and the [documentation](https://www.gnu.org/software/libc/manual/html_node/Directory-Entries.html) says:
> DT_UNKNOWN: The type is unknown. Only some filesystems have full support to return the type of the file, others might always return this value.

But anyway, I will implement this. The one for loading an empty file is a different matter though.

**Comment by crudelios** [comment]
> I'd rather flip the check around and block directories and known non-files.

Yeah, that makes more sense.

I can do it if you want, since I posted the bug and know how to fix it. Saves you some work.

**Comment by bvschaik** [comment]
If you'd like to, go ahead 👍

**Comment by crudelios** [comment]
I'll do this later today then 😉
