### ISSUE TITLE
Create a secondary Julius build

### ISSUE THREAD

**Issue by KillahNeo** [bvschaik/julius#237]
With game bugs fixed, non-compatible to old savegames.

**Comment by 411752230** [comment]
Um. If things go in that way, i'd like to suggest an unofficial C3 patch 1.2,

while Julius may stay consistent with its description.

**Comment by crudelios** [comment]
This has been discussed before, and is ultimately up for @bvschaik to decide what to do, since it's her project to begin with.

So I don't really this this issue is needed :wink:

**Comment by bvschaik** [comment]
The goal of Julius is stated in the readme, and that will not change. For any other enhancements I foresee a fork of the code.
