### ISSUE TITLE
Add "accept none" button to warehouses

### ISSUE THREAD

**Issue by KillahNeo** [bvschaik/julius#239]
A "Accept nothing" button for warehouses.

**Comment by ArtySh0ck** [comment]
OMG YES!

![123](https://user-images.githubusercontent.com/46932541/72601731-a3e94f80-391e-11ea-952b-2efd3ca2545f.png)

A good place for that button is above existing "Become the trade center" button.
And this button must have two states:
1. for all types to "Accept nothing".
2. for all types to "Accept".

**Comment by bvschaik** [comment]
It's a good idea, but I'm struggling with this one. The dialog must have room for 15 resources, and it must also fit on 640x480 resolution, which means we run out of room.
Also, since we cannot use any text other than what is already in the game, the button will either say "Not accepting" or "Refuse goods" (instead of "Accept none" / "Accept nothing"). Which would be preferable?

**Comment by crudelios** [comment]
I think `Refuse goods` is clearer. Is there a replacement for `Accept all`? Also, clicking the button should also refuse goods not yet available, i.e. imported goods, as right now when you start a new trade route thr new goods get accepted everywhere.

**Comment by bvschaik** [comment]
These are the strings we have in that "group" in the text file. As far as I can see these are not used anywhere in Caesar 3.

    <group id="15">
        <string id="0">Accept goods</string>
        <string id="1">Refuse goods</string>
        <string id="2">Go get goods</string>
    </group>

**Comment by crudelios** [comment]
I think you can set every resource, even unused ones, to "not accept"

**Comment by bvschaik** [comment]
Actually, yes, that was also my conclusion after thinking about it during lunch.

**Comment by bvschaik** [comment]
Zeus has just an X button on the bottom right. We can do the same:

![zeus-accept-none](https://user-images.githubusercontent.com/104874/72679597-fd818380-3ab0-11ea-820d-2c8e8582a8e4.jpg)

**Comment by 411752230** [comment]
> Zeus has just an X button on the bottom right. We can do the same:
That's amazing!

**Comment by crudelios** [comment]
Perhaps... should the game default every new granary/warehouse to `Accept none`?

**Comment by KillahNeo** [comment]
@bvschaik So you can actually make UI changes.. interesting

**Comment by bvschaik** [comment]
> Perhaps... should the game default every new granary/warehouse to `Accept none`?

No. The warehouse should accept everything, in case the player either does not know about the special orders or simply does not care about them (unlikely for experienced players but still).

> @bvschaik So you can actually make UI changes.. interesting

Yes we can, BUT: no new strings, no new graphics, no drastic changes from what's available in C3.

**Comment by bvschaik** [comment]
![warehouse-accept-none](https://user-images.githubusercontent.com/104874/72741638-554ee600-3ba8-11ea-8252-ef891faf857a.png)

So, I just implemented the 'x' for both granaries and warehouses. Mouse tooltip shows "Refuse goods". Any resources which become available after opening a trade route will also be set to "Not accepting" when you use this button.
