### ISSUE TITLE
Unable to control productions after clearing it

### ISSUE THREAD

**Issue by ArtySh0ck** [bvschaik/julius#241]
I have some timber yards and furniture factories.

Now i turned OFF this productions. Later i delete all of them. 

Advisor says me next: 

![step1](https://user-images.githubusercontent.com/46932541/72625522-98634c00-3951-11ea-8b02-c12674d53421.png)

![step2](https://user-images.githubusercontent.com/46932541/72625629-cba5db00-3951-11ea-8204-648a8efb9093.png)

Dont even know, maybe should be?

**Comment by bvschaik** [comment]
This bug is also present in C3, and I see no way to fix this without messing up the normal case where you did not have industries to start with.
