### ISSUE TITLE
That weird C3 nature

### ISSUE THREAD

**Issue by ArtySh0ck** [bvschaik/julius#243]
![Безымянный](https://user-images.githubusercontent.com/46932541/72666665-47b92500-3a1d-11ea-84d1-f5581e0c784b.png)

Arrow 1 -> this product already rotted while Arrow 2 -> just about to start to grow.

Could we direct it in right nature way? Example:

We have 5 tiles (fields) of soil on each farm. When it get enought workers and starts to farming all of 5 tiles must have a small young plants. Then, after 5 ticks of time all 5 fields get growing up synchronously. And so on, till it get a final stage of their vegetation. With a correct count of time ticks, of course to bring the same time of farming like in C3 original farming. Only me get a discomfort feelings when see that plants grows not synchronously?

**Comment by crudelios** [comment]
While not accurate, the way it works right now allows you to see the production progress in a more graular way.

So I don't think it should be changed.

**Comment by ArtySh0ck** [comment]
![step1](https://user-images.githubusercontent.com/46932541/72667098-de3b1580-3a20-11ea-8b27-63f23431c6fd.png)
![step2](https://user-images.githubusercontent.com/46932541/72667099-de3b1580-3a20-11ea-8215-71f709ec30a9.png)
![step3](https://user-images.githubusercontent.com/46932541/72667100-de3b1580-3a20-11ea-94b7-58753b973523.png)

This is right way plants to grow.

**Comment by crudelios** [comment]
That way you can get 0% - 33% - 66% progress, whereas right now you can get five times as much granularity...

**Comment by 411752230** [comment]
A very delicate feature.

**Comment by crudelios** [comment]
We could grow one part of one tile in succession, that would be the both realistic and granular.

**Comment by ArtySh0ck** [comment]
![sts](https://user-images.githubusercontent.com/46932541/72668000-adf87480-3a2a-11ea-996f-3bcfdfe41ade.png)


Like that? Would be cool enough

**Comment by crudelios** [comment]
Exactly. It's just a matter of checking if that preserves savegame compatibility.

**Comment by KillahNeo** [comment]
The game could have all its bugs fixed and be improved a hundred times more, we could have the ultimate caesar III experience, why keep this stupid idea of preserving savegame compability..
I don't understand why's that even important if Julius grows bigger by day and will be probably responsible for a new Caesar III community itself..

**Comment by bvschaik** [comment]
While I agree that it's not quite how nature works, the current implementation does give a very good at-a-glance indication how far production is. And if we're talking about mimicking nature: harvesting wheat 19 times per year is also not natural...

> It's just a matter of checking if that preserves savegame compatibility.

It does not. Therefore I'm closing this.
