### ISSUE TITLE
"Autosave - Lost in the Crowd"

### ISSUE THREAD

**Issue by ArtySh0ck** [bvschaik/julius#245]
![Безымянный](https://user-images.githubusercontent.com/46932541/72671720-11000080-3a57-11ea-90ce-e1a2d0cc7911.png)

Guys, someone can help me to find my Autosave? Cause after 5-6 times doing that i feel my eyes say goodbye to me.

PLEASE rename autosave file to "!Autosave". 
"!" for sorting on top of saves list. 
Big "A" to have a chance to find it among other saves.

A lots of thanks.

**Comment by ArtySh0ck** [comment]
I just checked, C3 havent any symbols except "-"

But it looks fine to do:
![image](https://user-images.githubusercontent.com/46932541/72678169-07ed4e80-3aac-11ea-8d0d-595f4b2bce64.png)

For a more "cute" it makes sense to put another "-" on end of it.

**Comment by bvschaik** [comment]
Caesar 3 names it "last.sav", that's even worse. Zeus also uses "autosave" (autosave history and autosave replay), and I don't like filenames with funny characters at the start - that might also give problems on different operating systems.
Just type "autosave" if you want to load it?
