### ISSUE TITLE
Ineffective autosave

### ISSUE THREAD

**Issue by ArtySh0ck** [bvschaik/julius#246]
![image](https://user-images.githubusercontent.com/46932541/72671784-32152100-3a58-11ea-86b7-042b206b871c.png)

I think the reason to have an autosaving backups is to have a chance to come back in time. But month? - it's very useless with problems we often meet in C3. Probably it would be more useful if:
1. There is a few autosave files, like autosave1 (earlier), autosave2, autosave3. I guess i've seen this in some game...
2. There is an Option Window appears when we click on "Autosave options", and there something like a three radio buttons -> Autosave each month (maybe someone needs that...), Autosave each halfyear (every Jan, and every Jul) and Autosave each year.

Obliviously that **second variant** is most elegant, but i understand, doing these things its not so easy. But i hope sometime it will work like that for more comfortable gaming. Thank you!

**Comment by ArtySh0ck** [comment]
OR!
3. Let that "Monthly autosave ON" string be a switcher between a few options:
- Monthly autosave ON
- Halfyear autosave ON
- Year autosave ON
- Autosave OFF

**Comment by KillahNeo** [comment]
I agree with @ArtySh0ck

**Comment by bvschaik** [comment]
The reason to have autosave is that you still have a save when you accidentally close the window, the game crashes on you (should be very rare) or your power goes down. You should still take care of any important progress saves yourself.

Your second and third suggestions cannot be implemented because we're limited by the text that the game already contains.

**Comment by ArtySh0ck** [comment]
Its impossible to add new string vars? im not a programmer, but i thought it can be possible. Well... sad =(

**Comment by bvschaik** [comment]
> Its impossible to add new string vars?

Indeed. There are 9 language versions of the game, Julius supports all of them, and adding strings  requires: a) translating them to all 9 languages, and b) somehow distributing the new strings together with the julius.exe file. There is no way to do that now.

**Comment by ArtySh0ck** [comment]
This problem borns impossibility with many many UI improvements to make. I guess i was too overexcited, now i love Julius completely.

**Comment by ArtySh0ck** [comment]
OMG, its a VERY ineffective. Was a trouble with money, dept actualy, and i need to back at least a few moment back. So, that drunk Caesar sent a threat, i go load autosave and... i'm here, when he send me a threat. It happens and it autosaves in the same time.
Crashes - isnt not a reason for autosaves at ALL. When it crashes - we try to find a reason why, try to fix, try to reinstall or delete something, we dont go load autosaves to take the same crash at the same moment again and again, lol. If it crashes - it will crash, autosaves cant handle. And it never crushes by my c3 or Julius, even unstable, btw. AUTOSAVES is for gaming schemes, for playing, for tryings, for play safely within game. So... this way autosaves as Julius does now didnt help me, gotta replay )

**Comment by crudelios** [comment]
Ideas for dealing with saves that expands on this (I can eventually implement it, but I'm limited in time and have other ideas to implement as well):

* Monthly autosave has 10 saves for city, and saves in the format `autosave-<city name>-<number>.sav.` The `<number>` rotates from `0` to `9`. To make implementation easier, upon opening a new city the autosave counter gets reset to `0`
* Hotkey for quicksave (`F1` maybe? I don't know if that one is available). File is saved as `quicksave-<city name>.sav` (no `<number>` here)
* Always quicksave city on exit. Your `F1` quicksave will be overwritten.
* `Continue` button to main menu, which opens the last saved game (usually the quicksave from the last exit)

**Comment by ArtySh0ck** [comment]
Maybe F5 for quicksave and F9 for quickload? These keys is most popular in games quicksaving\loading.

And, Yearly autosaving is must... =) thanks!

**Comment by crudelios** [comment]
The only available function keys for quicksaving/quickloading are `F10` and `F11` 😞

**Comment by bvschaik** [comment]
I've been thinking about this:
- The load/save game dialog can handle only a limited number of files (200 to be exact). Yearly autosaves / 10 saves per city will quickly consume all available entries
- Yet another button on the main menu for "continue" will make it too cluttered

>  It happens and it autosaves in the same time.

Autosave is at the turn of the month. A lot of other things also happen at the turn of the month.

> Crashes - isnt not a reason for autosaves at ALL.

I meant computer crashes because of power loss. That still happens.

> AUTOSAVES is for gaming schemes, for playing, for tryings, for play safely within game.

That's exactly what _manual_ saves are for.

My opinion is still that the user is responsible for saving his/her own progress, especially when trying things out or doing risky things.
