### ISSUE TITLE
Granary's off road

### ISSUE THREAD

**Issue by ArtySh0ck** [bvschaik/julius#247]
![ambar-road](https://user-images.githubusercontent.com/46932541/72675493-b5049e80-3a8d-11ea-9dd2-7e9e4f715bdd.png)

Actualy, idea belongs by GamerZakh =) but i found it realy cool, all of us knows how ugly looks next roads to granary.
More detailed about an issue linked with timecode here https://youtu.be/OXONBt5U-U0?t=2355

But, i think, by picture on top it would be even more perfectly looks than just a road-direction fix, road must ENTER closely to granary's enter/exit points.

**Comment by crudelios** [comment]
I'll see if this one can be done without affecting savegames.

**Comment by ArtySh0ck** [comment]
WOW! When we can try it within unstable?

**Comment by crudelios** [comment]
As soon as #254 is merged.

**Comment by ArtySh0ck** [comment]
Mama told me - "learn github, noob" xD

**Comment by crudelios** [comment]
When this issue is closed, that means the new code has been merged (meaning, integrated into the latest Julius unstable build).
