### ISSUE TITLE
MapEditor's bug

### ISSUE THREAD

**Issue by ArtySh0ck** [bvschaik/julius#248]
1. Main settings window (starting conditions, win criteria...)
2. "Buildings allowed" menu.
3. When do a right-click to back to main window it closes "Buildings allowed" menu and main window too! When do same with other menus - it's doing ok.

I know it's not a Julius bug, but i cant find MapEditor repo to ticket there. And i think Bianca is author of MapEditor too. Thanks.

**Comment by bvschaik** [comment]
Nice one, fixed :)
