### ISSUE TITLE
Pillar hasnt a capital when must

### ISSUE THREAD

**Issue by ArtySh0ck** [bvschaik/julius#253]
![Безымянный](https://user-images.githubusercontent.com/46932541/72728462-14e66c80-3b96-11ea-9c77-366c674e557c.png)

Sometimes, when rating reached required score its pillar hasnt a capital. Even if score hold till next year (Jan).

**Comment by bvschaik** [comment]
Like I explained in a comment on the youtube video, the capital is only shown if:
- the rating requirement has been reached, AND:
- the rating is 30 or higher

The reason for that last requirement is that the capital image is too big. If we put it on the "12" rating in your example, you will only see the capital and nothing of the column.
