### ISSUE TITLE
Immediately delete buildings?

### ISSUE THREAD

**Issue by crudelios** [bvschaik/julius#255]
The current implementation in Julius follows the original C3: if you delete a building, it gets highlighted in red and only disappears after a little while. How long it takes to disappear depends on the game speed and the internal day of the in-game month you're in.

This was probably done to save processing time, since back then computers had much more limited processing power.

However, this is very cumbersome, especially on slow speeds or when the game is paused. At 10% speed you have to wait for a while for the building to be removed, and it will never be removed while the game is paused.

It's very easy to implement the immediate removal of a building. In fact, it only seems to require a single line of code to be added.

So, why not do it? Is it too much of a gameplay change? Are there any side effects I'm not seeing?

**Comment by bvschaik** [comment]
Buildings continue to function during the few ticks that it takes to delete, which will cause some differences in behavior. And I actually like the fact that you have to wait a little for "the engineers to demolish the building and clean up the area".

**Comment by crudelios** [comment]
> Buildings continue to function during the few ticks that it takes to delete, which will cause some differences in behavior.

True, those are subtle but they do exist.

> And I actually like the fact that you have to wait a little for "the engineers to demolish the building and clean up the area".

I hate when they take more than 10 seconds to do that though. Well, I guess it's a matter of preference but I had to ask. I'll close this now.
