### ISSUE TITLE
Set all goods standard to "not accepting" when placing a new Warehouse

### ISSUE THREAD

**Issue by hansvermeersch** [bvschaik/julius#256]
When placing a new ware house all goods are set to "accepting" the first thing you typically do is to change all goods to "not accepting" except for one.

there for the proposal to set all goods standard to "not accepting" when placing a new Warehouse.

**Comment by bvschaik** [comment]
We already discussed that [here](https://github.com/bvschaik/julius/issues/239#issuecomment-576048118).
