### ISSUE TITLE
Warehouse/Granary: Set new goods added by new trading routes standard to "not accepting"

### ISSUE THREAD

**Issue by hansvermeersch** [bvschaik/julius#257]
When new trade routes are opened, the new good are added to the existing warehouses and granaries. These goods are standard set to "accepting". It would make more sense to have it standard set to "not accepting"

**Comment by bvschaik** [comment]
When you use the new "accept none" button on the warehouse/granary, this will indeed work like you describe.

**Comment by hansvermeersch** [comment]
great thanks
