### ISSUE TITLE
Failing build reservuar sometimes leads to small visual glitch (also present in original game)

### ISSUE THREAD

**Issue by galkinvv** [bvschaik/julius#26]
There is a small visual glitch sometimes appearing during build two connected reservours  with mouse press-drag-release

Steps to reproduce:
* Load save from [reservuars-test.zip](https://github.com/bvschaik/julius/files/1733315/reservuars-test.zip)
* Try to build reservuar with dragging from the left to right in specific place.
It fails to build with "must build on clear land" (ok) but the background becomes glitched (see two 3x3 blocks) ![c3-reserv](https://user-images.githubusercontent.com/1609972/36336790-243e2d04-139c-11e8-874e-cd7a80be21e0.png)

The original game has this bug too (at least in wine-steam), so I'm not sure if fixing this will be in the spirit of this project.

Btw, the current state of project looks really great! Even very picker player that loves the original - finds its great! Big thanks!

**Comment by bvschaik** [comment]
It appears this happens when the game cannot find a way to place aqueducts between the two reservoirs. This is an UI issue so I see no harm in fixing this :)
