### ISSUE TITLE
Add current ratings to the top menu bar

### ISSUE THREAD

**Issue by jfkonecn** [bvschaik/julius#261]
Building off of @ArtySh0ck 's idea....
![image](https://user-images.githubusercontent.com/24961694/72854234-c44c3d80-3c81-11ea-825d-bccd9cf4a797.png)

I notice myself constantly checking the ratings menu. I was thinking it would be nice to have it up top.
We could have difference colors for when you've completed/have yet to complete certain ratings.
We could have a tooltip which displays what the ratings menu tells you to do to improve the rating.
Left click could take you to the ratings screen.

**Comment by 411752230** [comment]
I dont know why but I really dislike additional messages messed up to UI, especially with the top bar. If this is to be implemented, what's the sense of rating counselor? Just more info in detail?

And how about under the lower resolutions? Even if caesar iv doesnt implement this.

**Comment by KillahNeo** [comment]
Chance of this being implemented 1%

**Comment by jfkonecn** [comment]
As a user you have a lot of repetitive clicks to get to information you really care about. This information is almost as important as how much money you have, which is why I think it belongs on the main UI. The original development team knew that users should have quick access to rating so they made it available with the senate building. If it ends up looking ugly then the PR can be rejected and this feature can be left for an enhanced version.

**Comment by 411752230** [comment]
Repetitve clicks is true when you check it whether you have reached the goal. But not all the time you need to have a look on that easily. If this will be implemented anyhow, maybe Senate is a good choice.

**Comment by crudelios** [comment]
I think the original idea is too verbose.

The top menu should only display something small like: `Objectives 0/5` (the five objectives being culture, peace, prosperity, favor and population).
Hovering the mouse would show each objective:

```
Culture 0/50
Prosperity 0/50
Peace 0/50
Favour 0/50
( Target population is 5000 )
```
Right-clicking would open the ratings menu where you could check how to increase the culture target.

**Comment by bvschaik** [comment]
Ratings have been added to the sidebar (enable the extra info in Options), so I'm going to close this issue.
