### ISSUE TITLE
Language Selector

### ISSUE THREAD

**Issue by KillahNeo** [bvschaik/julius#264]
Maybe an language selector in-game

**Comment by 411752230** [comment]
In fact, i am thinking about a C3config.exe for some extra settings which is optional to everyone and of course Language select belongs to one of it.  Like this for RA 95. 
![QQ截图20200122173003](https://user-images.githubusercontent.com/14128007/72882080-f1115b00-3d3c-11ea-99fe-c81b5936a659.jpg)

This will make many things flexible rather than adding to the game directly. Anyway, just an idea.

**Comment by devnoname120** [comment]
I suggest to fork https://github.com/LRFLEW/OpenRCT2Launcher if you want to do a launcher. The use case is very very similar to julius's.

**Comment by crudelios** [comment]
An in-game language selector is not possible because, ironically, the string `Language` doesn´t exist in `c3.eng`.

An external configuration manager is an option though.

**Comment by bvschaik** [comment]
> An in-game language selector is not possible because, ironically, the string `Language` doesn´t exist in `c3.eng`.

On top of that, (almost) all languages use `c3.eng` and `c3_mm.eng` for the strings, and you can only have one of those. Plus, you cannot see from the file which language is in there. For detecting other encodings than Western Europe, I had to resort to a [quite dirty detection algorithm](https://github.com/bvschaik/julius/blob/3a816815c5e12e786f97504a28452e5272f12157/src/core/encoding.c#L579).

The external manager would certainly be an option, but building it in Julius is not.

**Comment by KillahNeo** [comment]
Hmmm, maybe a first-run language selector for Julius Windows / Mac ?

**Comment by devnoname120** [comment]
> On top of that, (almost) all languages use `c3.eng` and `c3_mm.eng` for the strings, and you can only have one of those.

Couldn't we agree on a naming convention? For example `c3_fr.eng`, `c3_en.eng`?

**Comment by KillahNeo** [comment]
> Couldn't we agree on a naming convention? For example `c3_fr.eng`, `c3_en.eng`? The vanilla game would still work with the default language file but then julius would be available in other languages if they are installed.

this

**Comment by bvschaik** [comment]
> Couldn't we agree on a naming convention? For example `c3_fr.eng`, `c3_en.eng`? The vanilla game would still work with the default language file but then julius would be available in other languages if they are installed.

That will not work for languages which require other files to change as well. Russian has C3_Fonts.sg2 / C3_Fonts.555 as extra graphics and c3.rus/c3_mm.rus for the language files, Chinese has Rome.555 for the characters, Polish has a completely different set of graphics (C3.sg2/555, C3_North.sg2/555, C3_South.sg2/555).

I think this should be implemented as an external program.
