### ISSUE TITLE
My Julius can't playback mp3s

### ISSUE THREAD

**Issue by ArtySh0ck** [bvschaik/julius#265]
![1](https://user-images.githubusercontent.com/46932541/72894076-34f76680-3d23-11ea-8335-42a055344b12.png)
![2](https://user-images.githubusercontent.com/46932541/72894077-358ffd00-3d23-11ea-92aa-04723240d4a5.png)

I've done all steps to instructions. I removed original rome1.wav rome2.wav etc... from wavs dir, and run julius (music is ON via game settings) - nothing is playing back.
Things i tried:
Put .mp3 files to wavs directory - no result
Make dir named "mp3" and put .mp3 files there - no result.

Julius ver 1.2.0.34

**Comment by crudelios** [comment]
I'll take care of this bug. Right now I don't know whyit doesn't work, but expect an update to this issue. I may ask you to test custom builds, if you don't mind.

The mp3 should go to a folder called `mp3`, so leave them there for testing.

**Comment by ArtySh0ck** [comment]
For now these .mp3s are in 3 places: mp3 dir, main dir, wavs dir. So i wont delete them, ok.

**Comment by crudelios** [comment]
As long as you keep them in the `mp3` folder, there's no problem.

Here's a build with better logging of mp3 errors: https://ci.appveyor.com/api/buildjobs/8jf15rsyuq3tnt12/artifacts/build%2Fjulius.exe

Can you run this build and then copy `julius-log.txt` please?

**Comment by ArtySh0ck** [comment]
> INFO: Error opening music file 'mp3/ROME1.mp3'. Reason: Failed loading libmpg123-0.dll: б—°Вѕ
> INFO: Error opening music file '(null)'. Reason: Couldn't open '(null)'
> INFO: Error opening music file 'mp3/ROME1.mp3'. Reason: Failed loading libmpg123-0.dll: б—°Вѕ
> INFO: Error opening music file '(null)'. Reason: Couldn't open '(null)'

[julius-log.txt](https://github.com/bvschaik/julius/files/4103264/julius-log.txt)

**Comment by crudelios** [comment]
If you downloaded the 64-bit version of libmpg, try downloading the 32-bit or vice-versa

**Comment by ArtySh0ck** [comment]
![123](https://user-images.githubusercontent.com/46932541/72990206-6db53f80-3df8-11ea-9214-5d66e9eca503.png)

**Comment by ArtySh0ck** [comment]
OMG with 32bit version of libmpg123-0.dll - WORKS! I can hear the music within game.

**Comment by crudelios** [comment]
Nice! Please close this issue now 😉

**Comment by ArtySh0ck** [comment]
But it isnt nice. I have a 64 bit system, HOW can i guess i need x86 32bit DLL???

**Comment by crudelios** [comment]
This specific issue is fixed. The outdated instructions are being talked about on issue #270, and the eventual inclusion of the dll with the build is also being discussed on issue #271. So to avoid clutter, it's best to close this one.
