### ISSUE TITLE
All original MP3s

### ISSUE THREAD

**Issue by TheRealAyCe** [bvschaik/julius#266]
This only lists the 5 standard tracks: https://bintray.com/bvschaik/caesar3-music/mp3#files
You mention here that there also also combat and menu tracks possible: https://github.com/bvschaik/julius/blob/master/doc/mp3_support.md

Could you provide them as well? Or do they not exist, and you just gave the possibility to replace them with your own mp3s?

**Comment by crudelios** [comment]
> Or do they not exist, and you just gave the possibility to replace them with your own mp3s?

Exactly 😉 I'm waiting for an AI that magically restores the original quality, or at least for someone skilled enough to do it.

**Comment by TheRealAyCe** [comment]
@crudelios  Not that unlikely, considering what already exists for images. :P https://deep-image.ai/

**Comment by crudelios** [comment]
Indeed! But unfortunately nothing appeared until now... And I've been looking,

Anyway, please close this issue!
