### ISSUE TITLE
Make building temples quicker

### ISSUE THREAD

**Issue by m-mohr** [bvschaik/julius#267]
Just an idea: I'm always annoyed when building temples. Most of the time I want to build all 5, but then I need to click a lot, first the temple button, then small temple or big temple and then place the actual building. Could that be improved somehow? Maybe by opening the sub-menus by default or so? Not sure what's possible with the menus...

**Comment by ArtySh0ck** [comment]
Maybe when click a temple button we got a full list of all temples. Like:
- Ceres (small)
- Neptune (small)
- etc..
- Ceres (large)
- etc
- (last one of) Oracle

?

**Comment by crudelios** [comment]
I think your alternative - 11 sub-options - is less ui-friendly than clicking twice.

Besides, on low resolutions 11 sub-options probably won't fit :/

Automatically opening sub menus on hover might work, but needs quite a bit of reworking of the internals of menus.

Frankly, I don"t think such a small change is worthy of so much work.

**Comment by m-mohr** [comment]
Is there a text string for "All"? One could add that and then build the temples after each other with just 5 clicks... so basically:

Click "Temples", "Small", "All", click on map for the first time => Ceres placed, click on map for the second time => Neptune placed, ....

**Comment by crudelios** [comment]
Regarding the idea of menu hover, it wouldn't actually only be useful for temples, but for farms, raw materials and workshops as well. So it wouldn't be as useless as I first thought.

There is a string for the work `All`. While unconventional, I think your idea would be practical. Better yet: it would keep cycling. Even better: it would build a temple to whatever god had less total temples rating, based on a weighted score of small and large temples.

Would this change the game strategy too much, though?

**Comment by m-mohr** [comment]
Yes, I also thought about it keep cycling. I'd love that.
If we don't want that behavior, maybe allow some shortcuts to switch between things in lists? For example +/- to get to next/prev temple (or farm type or so).

Whether it should change based on the rating, I'm not sure. I guess that could be a bit too smart. ;-)

**Comment by crudelios** [comment]
Yeah, just cycling would be enough, otherwise the strategy regarding the gods would almost be gone.

**Comment by crudelios** [comment]
It's doable:

![cycle_temples](https://user-images.githubusercontent.com/6518876/73094591-ce1bae00-3ed8-11ea-9b1e-f2d6ef128e60.gif)

I'm just not sure if it's a good idea...

**Comment by gusowski1** [comment]
What if you stoped building Neptun and then start again?
Will it start with Ceres or with Mercur?

**Comment by crudelios** [comment]
> What if you stoped building Neptun and then start again?
Will it start with Ceres or with Mercur?

It will go back to Ceres

**Comment by m-mohr** [comment]
> It's doable:
> 
> ![cycle_temples](https://user-images.githubusercontent.com/6518876/73094591-ce1bae00-3ed8-11ea-9b1e-f2d6ef128e60.gif)
> 
> I'm just not sure if it's a good idea...

I love it! 😍 Is there a pull request already? Great work!

**Comment by crudelios** [comment]
No PR yet, but here's a link to the branch:

https://github.com/crudelios/julius/tree/allow-cycling-temples-on-build?files=1

**Comment by ArtySh0ck** [comment]
Another way. When choose a building to build - game will not close building list. So we dont need to open that list again and again each time by clicking on icon of building type. This could be useful not only for temples, actualy.

**Comment by m-mohr** [comment]
Could we merge this into Julius, @crudelios ? Maybe optional via menu?

**Comment by bvschaik** [comment]
I'm fine with having this a UI improvement that can be enabled in the settings.
