### ISSUE TITLE
Scroll speed differences

### ISSUE THREAD

**Issue by m-mohr** [bvschaik/julius#268]
Scrolling to the left and right seems to be double the speed than scrolling up and down. I'm not sure what I like more, but shouldn't it scroll in the same speed in all directions?

**Comment by crudelios** [comment]
I don't really feel this, but there is a way for you to test: if you start in a corner and place your mouse an opposite screen corner, you should reach the other corner of the map at the same time both horizontally and vertically. Example (using arrow keys to scroll):

![map_diagonal_scroll](https://user-images.githubusercontent.com/6518876/72973381-15187f00-3dc5-11ea-941b-1fe4a19e0dbf.gif)

**Comment by m-mohr** [comment]
Have you tried with a mouse? I'm pretty sure it's that way I described for me and I think I also remember GamerZakh mentioning this behaviour.

**Comment by crudelios** [comment]
Yes I did. It feels the same speed to me. I even counted the time it takes to scroll the map top to bottom, and then left to right, and it took more or less 4 seconds for both axis (that's another way to test).

Also, due to the isometric perspective, the tiles are 30 pixels width vs 15 pixels height, so your feeling of the speed being different may stem from that.

I'm also using Windows 10.

**Comment by m-mohr** [comment]
> 
> 
> Yes I did. It feels the same speed to me. I even counted the time it takes to scroll the map top to bottom, and then left to right, and it took more or less 4 seconds for both axis (that's another way to test).

I tried that, too. left->right took 5.5 sek, down->up 6.5 sek. It is indeed not as different as it looks like.

> Also, due to the isometric perspective, the tiles are 30 pixels width vs 15 pixels height, so your feeling of the speed being different may stem from that.

And I guess that is the reason for it. Still, it feels weird. Not sure this is something that should be fixed or not, just wanted to say that this feels weird for me (and maybe others) when playing. Also fine if this is closed.

**Comment by crudelios** [comment]
You have a point to your issue. I just tested on C3 and the left->right scroll speed is twice as slow. Meaning it takes half the time scrolling the map from the top to the bottom than it does from the left to the right.

From what I remember, that used to be how things worked on Julius, but meanwhile either me or @bvschaik changed that. Perhaps we should change that again.

**Comment by bvschaik** [comment]
I've heard a couple of people noticing this issue, so I'd like to change it so that the scroll acts the same as Caesar 3. I think the original behaviour got lost during the touch support implementation. I'll have a look.

**Comment by crudelios** [comment]
> I think the original behaviour got lost during the touch support implementation. 

You're probably right :stuck_out_tongue:

**Comment by bvschaik** [comment]
It wasn't the touch support after all: it's been like this forever, I think.
Scrolling is now exactly the same as in C3. However, it wasn't horizontal scroll being twice as fast, it was vertical scroll being twice as slow. As a consequence the vertical scroll is now more jumpy.

**Comment by crudelios** [comment]
Well I have pixel-based camera on my plans, so eventually that'll be fixed!

**Comment by bvschaik** [comment]
> Well I have pixel-based camera on my plans, so eventually that'll be fixed!

When you do, please keep a very close eye on performance. The city drawing routines expect to be able to blit full or half-tiles in one go. I had to optimize those to get decent performance for larger screens.

**Comment by crudelios** [comment]
Sure, I'll probably have to try a couple of different approaches, but I really hope it's feasible.
