### ISSUE TITLE
Issue compiling with Flatpak

### ISSUE THREAD

**Issue by jurf** [bvschaik/julius#27]
Hey, I’m trying to create a [Flatpak](https://flatpak.org/) for Julius, but I’m basically stuck at this:

```
-- Found SDL2: /usr/lib/libSDL2.so;-lpthread  
-- Found SDL2_mixer: /usr/lib/libSDL2_mixer.so (found version "2.0.1") 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
SDL2MAIN_LIBRARY
    linked by target "julius" in directory /run/build/julius
```

What could be up with that?

Fedora 27, x86_64

**Comment by dalerank** [comment]
seems cmake cache used with old data?

**Comment by jurf** [comment]
Can’t be, Flatpak starts with a fresh directory everytime.

**Comment by jurf** [comment]
So it’s an issue in the freedesktop runtime in the end, but if I remove the requirement for SDL2main I can compile normally on Linux.

**Comment by bvschaik** [comment]
I'm not sure it's a problem with freedesktop. I added SDL2main a couple of weeks ago for Visual C++, but I just tested and it doesn't seem to be needed.

**Comment by jurf** [comment]
Well, the library, even though it’s only a compatibility library, should be present in the runtime so it was a problem on both sides I guess.

**Comment by DontUseGithub** [comment]
If the flatpak issue got resolved, can we now submit the game for inclusion into [Athenaeum](https://gitlab.com/librebob/athenaeum)?

**Comment by jurf** [comment]
I have not looked into this since then. I wanted to at least archive my progress, so I looked at the old Flatpak manifest I made, but it’s just a bare skeleton. Unfortunately, I do not have time or motivation to work on this anymore.

**Comment by bvschaik** [comment]
In the meantime, Julius is on [Flathub](https://flathub.org/apps/details/com.github.bvschaik.julius) ([manifest](https://github.com/flathub/com.github.bvschaik.julius)) thanks to Barthalion.

**Comment by jurf** [comment]
Oh cool! I misunderstood what you meant under ‘Flatpak issue’. :P
