### ISSUE TITLE
Better Julius installation options

### ISSUE THREAD

**Issue by ArtySh0ck** [bvschaik/julius#271]
I found that mp3, dll inserting kind a tricky, hard.

Why we cant have a two variants of Julius?
1. First one like this one we have (julius.exe, couple of dll)
2. Second one "First One" + /mp3/ dir with all 5 mp3's + that mpg123-0 dll (cant remember right name). "Full Package" for example. And this one even doesnt need an installation wizard. BUT, with installation wizard it would be more elegant... and checkboxes, which ones a player does want to be installed or doesnt want.

**Comment by crudelios** [comment]
At first I thought that adding the `libmpg123-0.dll` was unneeded, as not many people had the mp3 files anyway.
Now that the mp3 are widely available and many people want to use them, I think we should just include the dll and remove the instructions to add it for Windows.

An installer for such a simple thing seems like a bit of overkill to me. I also don't like the idea of directly distributing music files with the game, as they were expressly released for personal use only, not for bundled distribution with a game.

**Comment by ArtySh0ck** [comment]
Believe me... most of simple users trust installators much more than some suspicious archives...

**Comment by crudelios** [comment]
While that may be true, I still think an installer is unnecessary.

I'm all for ease of use and that's why I approve including the `libmpg123-0.dll` with the builds, but creating an installer just to drop four files in a single directory is, in my opinion, a bit too much.

**Comment by bvschaik** [comment]
I just added libmpg123 to the Windows build and updated the mp3 support doc.
