### ISSUE TITLE
Hotkeys to select buildings to construct

### ISSUE THREAD

**Issue by pinouchon** [bvschaik/julius#274]
Have you considered adding hotkeys (customisable or not) to select buildings? At the very least for constructing roads, housing, deleting buildings and cancelling the last action. Something similar to the hotkey system you would find in warcraft/starcraft games.

I feel when I play the game that I constantly click those. I think it's very unfortunate that these are not available in the original game.

**Comment by KillahNeo** [comment]
Excellent idea

**Comment by bvschaik** [comment]
Do you have a suggestion for the key mapping? The following letters are already taken:

- `P` pause
- `F` fire overlay
- `D` damage overlay
- `C` crime overlay
- `T` problems overlay
- `W` water overlay
- `L` go to legion

**Comment by crudelios** [comment]
How about using the numpad? It more or less matches the button configuraton... for submenus, use `1` for the first item, `2` for the second... etc

**Comment by bvschaik** [comment]
Who still has a numpad on their laptops these days?

**Comment by crudelios** [comment]
They do? I have zero knowledge about current hotkeys. It's a pity because I alwsys thought it would be a good combination...

**Comment by bvschaik** [comment]
Hmm... just tested: apparently they don't (while they do in C3).
But my first point still stands: how many people play using a full keyboard these days?

**Comment by crudelios** [comment]
> But my first point still stands: how many people play using a full keyboard these days?

I still have full keyboards, but yeah it's not so common.

Another alternative that maps the button positions to the sidebar layout:

`6`, `7`, `8` -> first row of buttons;
`Y`, `U`, `I` ->second row of buttons;
`H`, `J`, `K` ->third row of buttons;
`N`, `M`, `<whatever is to the right of M>` ->fourth row of buttons

Undo, city messages and goto problem would be missing, but those are not commonly used.

For submenus, we could select the position by the corresponding number: `1` for the upmost option, `2` for the second, etc...

**Comment by bvschaik** [comment]
The whole top row is used for shortcuts to the advisors, I forgot to mention those. Also, I don't like a keypad-like mapping on the main keyboard because it's a hell to implement because of different keyboard layouts.

**Comment by crudelios** [comment]
Granted, it's not the best idea.

The overlay keyboards make things hard.

Some ideas though:

* `H` for housing
* `R` for roads
* `Delete` for clear land
* `R` for religion
* `E` for education
*  `A` for administration
* `S` for security
* `I` for industrial
* `U` for undo
* `M` for messages
* `Space` for cycling through trouble spots

Missing: water, health, entertainment, engineering.

When a submenu is open, the keyboard numbers could select the corresponding option instead of opening the advisor window.

**Comment by m-mohr** [comment]
If there are conflicts, what about generally using CTRL/ALT/SHIFT + letter?

**Comment by crudelios** [comment]
> If there are conflicts, what about generally using CTRL/ALT/SHIFT + letter?

Even though it wouldn't be consistent (a single letter hotkey for each building menu would be best), it's possible to use:

* `SHIFT + E` for entertainment
* `CTRL + E` for engineering
* `SHIFT + W ` for water
* `SHIFT + R` for religion
* `SHIFT + H` for health

**Comment by crudelios** [comment]
Here are some more useful ones:

* `CTRL + S` Open Save dialog (in city and editor)
* `CTRL + O` Open Load dialog(in city and menus)
* `CTRL + N` Open main menu (in city)

**Comment by pinouchon** [comment]
Would it be hard to implement something configurable ? (hopefully that takes care of different layouts).
Here is my suggestion: You have a global switch that toggles between "normal hotkeys" and "custom hotkeys"
When selecting "custom hotkeys", you see a list of all possible configurable actions (select road, select shovel, select housing, cancel last action, toggle fire overlay, go to advisor...) that you can click, then press a key, and that key is assigned to this action.
The custom hotkeys could have the "normal hotkeys" preselected so you don't have to rebind everything yourself.

Eg: if you select road, press F, then the fire overlay doesn't have a shortcut, but you can reassign it below.

When I am playing the same, I use a custom autohotkey script to remap some keys. The ones I use the most frequently are (they are under easily accesible keys):
speed up, speed down, go to advisor to see unemployment, go to trading advisor for exports, go to emperor for requests. But I'm pretty sure that I would use the "build road", "select shovel", "cancel last action" even more if some hotkey existed for them.
Also high in the list of stuff I'm sure I would use is: "select prefecture", "select engineer post", "select doctor".

**Comment by bvschaik** [comment]
I'll look into making the hotkeys configurable.
Yesterday I briefly looked at the hotkey handling code for #379, and I discovered that it's just not working properly for other keyboard layouts than the standard US and very similar Western European layouts, so I think the only way to fix that is to let the user configure the hotkeys to their liking.

**Comment by crudelios** [comment]
> I think the only way to fix that is to let the user configure the hotkeys to their liking.

Like! Since I was thinking about implementing a gamepad configuration, this will go hand in hand :wink:

Oh and I think we'll eventually need to separate the `Options` window by tabs, as it's getting crowded now...

**Comment by bvschaik** [comment]
> Oh and I think we'll eventually need to separate the `Options` window by tabs, as it's getting crowded now...

Yes, at least the hotkeys should be a separate tab (or even window, perhaps).

**Comment by crudelios** [comment]
I guess we can consider this issue fixed at last?

**Comment by attrition** [comment]
There should be a hotkey for Undo, I think

**Comment by bvschaik** [comment]
Undo is not quite bug-free, to put it mildly, so I wouldn't want people to accidentally trigger it with a hotkey.

Regarding the hotkeys for buildings: I suppose what we have now is enough at the moment. If we need hotkeys for more buildings, a new issue can be created.
