### ISSUE TITLE
Endless respawned wolves

### ISSUE THREAD

**Issue by 411752230** [bvschaik/julius#277]
Six assignment: Lugdunum (also happen in assignment five: Mediolanum)

Just see the wolf respawned on the hill in this save (genererated by julius)
![QQ截图20200126013055](https://user-images.githubusercontent.com/14128007/73124894-947f9b80-3fdb-11ea-8f0f-471a5d7ffcce.jpg)

Test with this save
[test.zip](https://github.com/bvschaik/julius/files/4112320/test.zip)

but with this one in which the wolves has been cleared once for all.
[test2.zip](https://github.com/bvschaik/julius/files/4112329/test2.zip)

**Comment by crudelios** [comment]
Does this always happen or only after reloading a city?

**Comment by 411752230** [comment]
Always, not concering about reloading

**Comment by bvschaik** [comment]
Wolves do not respawn if you kill them all. In your first save, however, there is still one wolf left in the walled area on the right of the map:
![wolf](https://user-images.githubusercontent.com/104874/73140811-48853300-407d-11ea-9898-ef8e77a93ff1.jpg)

Caesar 3 does the same when loading your save. Kill that one wolf and they will stop respawning.
