### ISSUE TITLE
Link to Emperor's requests on window "Emperial dispatch ready”

### ISSUE THREAD

**Issue by ArtySh0ck** [bvschaik/julius#278]
Have another nice idea from GamerZakh's discord community:

![image](https://user-images.githubusercontent.com/46932541/73125052-2c18c600-3fab-11ea-9464-5604fa15d55e.png)

And im agreed with

**Comment by crudelios** [comment]
Indeed, it makes no sense that both the "emperor requests goods" and "the emperor's gratitude" have a button to the empire advisor, but the one that would be really useful, "imperial dispatch ready", has simply a "help" button. This is going to my todo list, unless someone else steps in. Should be an easy change.

**Comment by bvschaik** [comment]
Yes. This is indeed one of the things I wrote down for my "to do" list when I watched GamerZakh's playthrough.
