### ISSUE TITLE
Can’t build farm

### ISSUE THREAD

**Issue by jurf** [bvschaik/julius#28]
So I’m playing Brundisium and I want to contruct a farm, but the menu to select one never opens, all I get is this:

![snimka obrazovky z 2018-03-01 10-46-16](https://user-images.githubusercontent.com/7472425/36837908-e958ca9a-1d3d-11e8-97ff-95713a911dee.png)

But I can normally construct temples.

**Comment by bvschaik** [comment]
Interesting. The raw materials submenu is also broken. I'll take a look.

**Comment by jurf** [comment]
Thanks!

**Comment by jurf** [comment]
Yeah, it works now, but I can’t build a pottery in Brundisium, shouldn’t that be possible?

**Comment by bvschaik** [comment]
Making pottery will be enabled later, once you've met a few objectives :)

**Comment by jurf** [comment]
Hm, it wasn’t, but I managed to pass somehow), after some time), but now in Capua I’m getting the same bug as in the OP, but with Raw Materials :-/

**Comment by bvschaik** [comment]
Oops, looks like I broke the workshops while fixing the farms/raw materials. Should be OK now, sorry about that :flushed:
