### ISSUE TITLE
External Program: C3config.exe making things optional and flexible

### ISSUE THREAD

**Issue by 411752230** [bvschaik/julius#284]
With the community of julius grown, everyone who gave his/her suggestions should be thanked. 

However, as regards some issues concerning UI enhancement and Language selector, opinions differ or infeasibility to the game directly.

So here comes the suggestion: Rather than "A or B" and "OK or not OK", it would be a great if a C3config.exe or c3launcher.exe added to julius, which would be fairly optional and flexible to contain features with contradictions and settings in addition. For example:
![](https://user-images.githubusercontent.com/14128007/72882080-f1115b00-3d3c-11ea-99fe-c81b5936a659.jpg)

Last but not least, all the implementors of julius should be appreciated first because they are the true practicer without any payment. Great thanks to them. Thank you all!

**Comment by Legionary2** [comment]
Nice 
What does enable small infantry , counter strike expansion mean ? 
A fork will probably be implemented eventually. I would love market order control / warehouse control - gatehouses and sprite limit removal for large populations. 

Others probably want a better census etc ...

**Comment by 411752230** [comment]
> Nice
> What does enable small infantry , counter strike expansion mean ?
> A fork will probably be implemented eventually. I would love market order control / warehouse control - gatehouses and sprite limit removal for large populations.
> 
> Others probably want a better census etc ...

Oh, actually that's an example of Red Alert 95 not for Julius.

**Comment by Legionary2** [comment]
Lol gotcha

**Comment by dalerank** [comment]
simple ui framework for SDL2 without textures https://github.com/dalerank/nanogui-sdl

![screenshot1](https://user-images.githubusercontent.com/918081/73241253-8e8fe300-41b2-11ea-8c03-cce7b95a65fb.png)

**Comment by ArtySh0ck** [comment]
It could be a c3launcher.exe with "start game" button

**Comment by 411752230** [comment]
> It could be a c3launcher.exe with "start game" button

Nice naming, I'd like to change the title

**Comment by crudelios** [comment]
The sdl framework makes things nicely cross-compatible.

Another possibility would be to use c3's own gui (always using english language) with a button for "extra settings" inside the game.

**Comment by bvschaik** [comment]
> Another possibility would be to use c3's own gui (always using english language) with a button for "extra settings" inside the game.

I like this one.

**Comment by 411752230** [comment]
> I like this one.

@crudelios @bvschaik Wonderful. Only a suggester am I. As you bros are the practicers, just feel free to change the title of this issue or open another one.

> As for thanking people: it's not common to have a "credits" screen in open source software listing all the folks that helped. People who contributed code are on [this page](https://github.com/bvschaik/julius/graphs/contributors). In addition, not everyone wants to have their name in software.

So be it. Truthfully I have never thought about a credits like that. Just verbal.

**Comment by 411752230** [comment]
Also, auto-update would be an idea.

**Comment by bvschaik** [comment]
> Also, auto-update would be an idea.

In what sense? Auto-updating the executable when new versions become available? That's very hard, because we support 6+ platforms with each their own update mechanism (if any).

**Comment by crudelios** [comment]
> In what sense? Auto-updating the executable when new versions become available? That's very hard, because we support 6+ platforms with each their own update mechanism (if any).

Agreed.

However, I think we could display the current Julius version at the bottom left corner of the main menu (in a small  white font so it isn't too noticeable).

Another idea would be to implement a small, embeeded HTTP client (like [CHttpClient](http://chttpclient.sourceforge.net/)) that would check on GitHub whether there was a new release version, and display, next to the current version on the main menu, a string like `new version 1.3.0 available`.

**Comment by 411752230** [comment]
> However, I think we could display the current Julius version at the bottom left corner of the main menu (in a small white font so it isn't too noticeable).
> 
> Another idea would be to implement a small, embeeded HTTP client (like [CHttpClient](http://chttpclient.sourceforge.net/)) that would check on GitHub whether there was a new release version, and display, next to the current version on the main menu, a string like `new version 1.3.0 available`.

If others coundnt implement that, maybe the android apk is needed in the future.

**Comment by bvschaik** [comment]
> Another idea would be to implement a small, embeeded HTTP client (like [CHttpClient](http://chttpclient.sourceforge.net/)) that would check on GitHub whether there was a new release version, and display, next to the current version on the main menu, a string like `new version 1.3.0 available`.

You'd need HTTPS as well since Github doesn't host on HTTP anymore. And for that we need to link to OpenSSL or equivalent... I'd rather not do that.

Displaying the current Julius version somewhere would be good though.

**Comment by crudelios** [comment]
> You'd need HTTPS as well since Github doesn't host on HTTP anymore. And for that we need to link to OpenSSL or equivalent... I'd rather not do that.

Makes sense. Too much overkill for such a small feature (even a HTTP client is a big thing, but more manageable).

> Displaying the current Julius version somewhere would be good though.

I'll do it later today then.

**Comment by bvschaik** [comment]
First mockup of the configuration screen. I found an unused background:
![config-screen](https://user-images.githubusercontent.com/104874/73455111-b8dacf80-436f-11ea-8a7c-fa22aa3cd850.jpg)
Shoot!

**Comment by Legionary2** [comment]
> First mockup of the configuration screen - English only. I found an unused background:
> 
> Shoot!

I think its lovely , good work.

**Comment by crudelios** [comment]
I have nothing to shoot, it looks good and new so I am rather acritical right now.

But I have suggestions to add:

* More gameplay changes that don't mess with the savegames: for example, fix the gods bugs
* UI changes: make #281 an option
* Language: it will probably require a restart, and either a drop-down widget is implemented, or we use the up/down arrows to cycle them. Also, it can only be implemented after a way to store the languages is defined

If eventually all the new settings don't fit, perhaps we could add tabs?

Also, did you think about the format in which to save the config file? Or are you going to use the free slots in `c3.inf`?

**Comment by bvschaik** [comment]
> UI changes: make #281 an option

Yes, that was my idea as well.

> Language: it will probably require a restart, and either a drop-down widget is implemented, or we use the up/down arrows to cycle them. Also, it can only be implemented after a way to store the languages is defined

We can do a language switch without restart: we do that when going to the editor as well. And there already is a select box used in the editor that we can reuse.
This configuration screen will always be in English though.

> If eventually all the new settings don't fit, perhaps we could add tabs?

Yes.

> Also, did you think about the format in which to save the config file? Or are you going to use the free slots in `c3.inf`?

I'd like to store them in a separate `julius.ini` file as plaintext key/value pairs.

**Comment by 411752230** [comment]
> This configuration screen will always be in English though.

Would it be possible for its translation? extra text open for everyone to translate

**Comment by bvschaik** [comment]
Because the game simply does not know which language is currently loaded and thus should be used. And for Chinese we have the added complexity that the settings cannot use any other characters than the 2188 hat are defined in the graphics file.
One additional problem with a language selector is that other files may also need to change. For Polish it's the c3.sg2 and 555 files, for Russian and Chinese we need to load extra graphics.

**Comment by crudelios** [comment]
Another suggestion for the extra config: allow immediate deletion of buildings

**Comment by bvschaik** [comment]
I'd like to use it for bug fixes only.

**Comment by ArtySh0ck** [comment]
> I found an unused background:

in c3 this background is unused, but c3demo ))

btw that screenshot is amazing start of something useful

**Comment by ArtySh0ck** [comment]
wait, where i can find that menu?

**Comment by crudelios** [comment]
> wait, where i can find that menu?

It's not finished yet so the code isn't available.

**Comment by KillahNeo** [comment]
> ![config-screen](https://user-images.githubusercontent.com/104874/73455111-b8dacf80-436f-11ea-8a7c-fa22aa3cd850.jpg)
That's a background from Caesar III Demo

**Comment by bvschaik** [comment]
Menu is available for testing [here](https://bintray.com/bvschaik/julius-branches/windows/config-1.2.0.66-14ab2b29#files). You can access it from the main menu using the Options button. Note that I have moved playing the intro videos to a config option as well.

**Comment by 411752230** [comment]
> Menu is available for testing [here](https://bintray.com/bvschaik/julius-branches/windows/config-1.2.0.66-14ab2b29#files). You can access it from the main menu using the Options button. Note that I have moved playing the intro videos to a config option as well.

Amazing. Looks wonderful. Maybe some sound effects like button clicking would be nice for the extra setting?

100 years ghost? What's that? lol

Why dont add an option about intro video of AE?

The background picture looks very comfortable with much higher resolution. If the main menu wallpaper could be such big and clear, that'd be excellent.

**Comment by bvschaik** [comment]
> 100 years ghost? What's that? lol

See [the documentation](https://github.com/bvschaik/julius/wiki/Configuration) that I have just written 😃

**Comment by Legionary2** [comment]
> > 100 years ghost? What's that? lol
> 
> See [the documentation](https://github.com/bvschaik/julius/wiki/Configuration) that I have just written 😃

YAY - damn ghosts couldn’t stand them

**Comment by bvschaik** [comment]
The new options are in the latest master.
I will close this issue - if anyone has more suggestions, please open a separate issue for them.
