### ISSUE TITLE
Wandering pointer

### ISSUE THREAD

**Issue by ArtySh0ck** [bvschaik/julius#286]
Julius ver.: "julius-1.2.0.50-99323657-windows.zip"

![Безымянный](https://user-images.githubusercontent.com/46932541/73300198-49eb6280-4219-11ea-95ea-fc616f3ddcef.png)

That arrow (pointer) was on its normal place a few minutes ago. But then, i cant remember, maybe i rotate a cam, or something, but i was looking for a place to build something, and when i see that blue pointer (exit of map) THERE - i was shocked, never see that before.

[1-arty-bugWanderingPointer-12050-28jan.zip](https://github.com/bvschaik/julius/files/4124320/1-arty-bugWanderingPointer-12050-28jan.zip)

savegame attached in .zip

its Londinium map (campaign)

**Comment by ArtySh0ck** [comment]
I can bring another savefile, but it was saved much more earlier. If it helps

**Comment by bvschaik** [comment]
It's a known bug which is also present in C3. If the entry/exit flag is in range of a reservoir or fountain, it will jump out of the way when you rotate the map. It will go to the nearest tile that is *not* in range of a fountain/reservoir.

Another interesting thing about entry/exit points is that you can use them to mine iron and marble.
