### ISSUE TITLE
Sound bug with Caesar 3 by 1C (russian version)

### ISSUE THREAD

**Issue by ArtySh0ck** [bvschaik/julius#288]
Things i did:
1. Installed Caesar 3 from licensed cd by 1C (russian verison)
2. Patched with:
![image](https://user-images.githubusercontent.com/46932541/73448570-d3aa4580-4369-11ea-9d0c-43d3578b3f1c.png)

3. And Julius added.

For default, this 1C version have only russian textes, but sounds are still english. But even that doesnt matter, cause NO SOUND playing at all! No music, no city sounds, no game effects (i tried). But, when i just install, and run c3 (before patching and adding Julius) - sound was, and music was. 

I know here is another ticket with this problem, but that guy dissappeared )) so i open another to watch. Thanks.

**Comment by ArtySh0ck** [comment]
OHH IM STUPID, i know the reason!!! i guess....

When i start c3.exe it makes sound playble CAUSE my c3 cd in my cd-rom, and this c3.exe takes wavs from cd directory! I will try to copy "wavs" folder...

**Comment by crudelios** [comment]
You got it! You probably went for a "minimum" install (it was common back in the day to only install the data files and keep the audio and video on the CD to save disk space) and the sounds stayed on the CD-rom. If you copy them to the C3 folder, you should be able to hear them.

Also, it may be that the russian version doesn't have russian audio, though I find that unlikely.

**Comment by ArtySh0ck** [comment]
About russian audio that was my mistake. Yes, it is russian texted and russian voiced too.

Ok, i copy wavs and smk. But there is NO 555 dir. But my english installation have 555 dir. What is it?

**Comment by bvschaik** [comment]
The 555 dir contains pixel data for the background images you see on the mission briefing / mission victory dialogs. I think those are also on the CD when doing a minimum install. Or perhaps the Russion version has placed those in the main dir. You can search for `01b.555` and see where they are located.

**Comment by ArtySh0ck** [comment]
yep. these is in main c3 folder, they have .555 ext but have different names )))

and in 1c version i have not 01b.555 01w.555 and so on files, i have only the same 555 files to c3 eng version in main folder =(

**Comment by crudelios** [comment]
> yep. these is in main c3 folder, they have .555 ext but have different names )))
> 
> and in 1c version i have not 01b.555 01w.555 and so on files, i have only the same 555 files to c3 eng version in main folder =(
> 
> by the search i found that:
> 84 *.555 files in c3 (eng, gog) in whole c3 directory (include "555" dir too)
> 41 *.555 files in c3 (rus, 1c) in c3 directory (there is no "555" dir)

This needs further testing. If you start julius from a clean maximum install of the russian version and start a mission, does it work?

**Comment by ArtySh0ck** [comment]
I havent an option as "minimum" or "maximum" installation via install =( it asks me only path to where i want it to be installed.

**Comment by ArtySh0ck** [comment]
http://arty.ho.ua/test.gif

**Comment by crudelios** [comment]
Thank you for the gif. Does the original Caesar 3 show the background graphics on the mission assignment?

**Comment by ArtySh0ck** [comment]
I think it doesnt. What should me to do? I have to 555 directory on my c3 by c1 cd-rom...
![image](https://user-images.githubusercontent.com/46932541/73458023-47098280-437d-11ea-95f5-de389306bbee.png)

**Comment by ArtySh0ck** [comment]
and i've checked that Data1.cab. there is no 555 folder too.

**Comment by crudelios** [comment]
> should i just copy 555 folder from my c3 english dir?

That would probably work, but won't solve the issue for someone who wants to use a clean russian version.

Can you send me (via gitter, not here please) a link with the zipped  `555` files you have in the clean russian version? Note: the file will be somewhat large, from 50 to 150 megs depending on what you have.

**Comment by ArtySh0ck** [comment]
> The 555 dir contains pixel data for the background images you see on the mission briefing / mission victory dialogs.

If its just a images, maybe files in 555 dir (eng.version) hasnt any english words, what makes them universal for any language of c3? So, as i checked, i have no mission's background images within russian version, on cd too, it makes sense to just copy 555 folder from my c3 english directory to my c3 russion directory?

**Comment by bvschaik** [comment]
> If its just an images, maybe files in 555 dir (eng.version) hasnt any english words, what makes them universal for any language of c3?

Yes. Those are just background images without any text on them.

> So, as i checked, i have no mission's background images within russian version, on cd too, maybe it makes sense to just copy 555 folder from my c3 english directory to my c3 russion directory?

Yes. It seems the 1C version forgot to include the 555 folder.

**Comment by crudelios** [comment]
Nice, problem solved then.

**Comment by ArtySh0ck** [comment]
> I know we would technically be distributing game files, but perhaps on the russian patch provided by bintray we should include the `555` folder?

Agree!

Should i close this topic?

**Comment by bvschaik** [comment]
> Last moment, i have a question. What does these language patches do? Am i right when i think it makes a game version up to date as GOG version?

Yes. People with the old 1.0 CD version cannot run the installer for the 1.1 patch anymore since it does not work on Windows 10, so I provide these zip files for the officially supported languages (German, French, Italian, Spanish). For Polish and Russian: they never got the patch in the first place, so the patches for those languages will enable them to upgrade to 1.1 with Julius.

As for including the .555 files: I don't think we should do that.

**Comment by perk11** [comment]
So for anyone hitting this issue: You need to copy "wavs" and "smk" folders from CD into Caesar 3 directory and that makes the sounds work.
