### ISSUE TITLE
Yet another argument for always having column capitals when objective is achieved

### ISSUE THREAD

**Issue by crudelios** [bvschaik/julius#291]
Every couple of months someone asks for the top of the columns in the ratings advisor to show when the ratings are achieved on low objectives.

The answer is invariably the same: the top is too big to fit when the objectives are low.
I have agreed with that answer so far, but now I'm changing my opinion.

From an UI perspective, there are two options:

1. The column + capital height is proportional to the `rating / 100`. This is the current implementation, and causes the mentioned problem.
2. The column height is proportional to the `rating / 100`, and the capital is added to the top. This is what I suggest.

It may be said that, in such a case, two ratings at the same value, but in which one is fulfilled and the other is not, will be a different height.

But from an user information perspective, in which the actual rating is clearly visible, I do think it makes more sense to add the capital to its top, even with the disadvantage I mentioned. The user gets the information he actually wants: whether the objective is complete or not.

Another option: add this to the expanded options from #281.

**Comment by bvschaik** [comment]
I think the C3 behavior is fine. The capital is also an indication of how advanced your city is. If you're playing an open play map, or the map doesn't have a target for a rating, the capital will be displayed when you have a rating of at least 30. As for user information: the rating with target is also displayed below the column.

As for making this a configurable option: I don't want to present a gazillion options to the user.

**Comment by crudelios** [comment]
It's not totally fine, as it confuses the player. But I admit there is no "clean" alternative, so I'm closing this.
