### ISSUE TITLE
Endless attacks of the enemy army

### ISSUE THREAD

**Issue by MarkusCicero** [bvschaik/julius#293]
Any chance of realizing an endless loop of the "enemy army attack" event in the editor?
At one time, creating maps for Caesar 3 really lacked this feature, which was made in subsequent games of this series.

**Comment by bvschaik** [comment]
Unfortunately, not without breaking compatibility with Caesar 3. And since the project's aim is to keep savegames and scenarios compatible with C3 (both ways!), this will not be implemented.
