### ISSUE TITLE
Zebras are considered hostile

### ISSUE THREAD

**Issue by perk11** [bvschaik/julius#294]
Balistas and the city's armies are attacking the Zebras that are spawned normally on the map as if they were wolves.
[Here is the save file where this happens right after loading it](https://github.com/bvschaik/julius/files/4145348/9-peace-fixed.zip).

**Comment by bvschaik** [comment]
Hi, thanks for reporting.
However, in Caesar 3, the zebra (and sheep on central maps) will also be attacked by the city's defenses. Therefore, this is not a bug but intended behavior.

**Comment by perk11** [comment]
Oh, looks like it was changed in 1.1 patch, I never got a chance to play it before. Good to know, sorry about the bug report.

**Comment by bvschaik** [comment]
No worries. I never played with 1.0 so I also did not know it was changed. Enjoy the game!
