### ISSUE TITLE
Londinium Population Bug

### ISSUE THREAD

**Issue by KillahNeo** [bvschaik/julius#298]
I remember playing the Londinium map and building a huge city (12k pop or something like that) and then all new buildings that I placed wouldn't appear anymore. 

I think that has something to do with integer limitation but I am not quite sure how it works.

**Comment by bvschaik** [comment]
The game has a hardcoded building limit of 2000 buildings (and 1000 figures). This is the same in C3, and changing it will break savegame compatibility.

**Comment by KillahNeo** [comment]
Why not just make a second julius branch which fixes these old ass bugs?

**Comment by bvschaik** [comment]
Because that's not the goal of the project.
Anyone is free to fork the project and make these changes. In fact, Keriew's fork is already implementing roadblocks. Perhaps you can convince him to add other things: https://github.com/Keriew/julius

**Comment by sdwvit** [comment]
Hey @bvschaik could you please point which constants should be changed to bump the limit?

**Comment by bvschaik** [comment]
At least `MAX_BUILDINGS`, `MAX_FIGURES`, and `MAX_ROUTES`, but possibly more. Also take saving and loading files into account and test thoroughly.

**Comment by sdwvit** [comment]
Thanks for your hard work! I tested yesterday and everything works almost flawlessly! 🙆‍♂️🙏
