### ISSUE TITLE
Something wrong with game's mechanics

### ISSUE THREAD

**Issue by atolstoy** [bvschaik/julius#30]
Hello!
I've been playing Julius with the updated Caesar III 1.0.1 bundle (the one where you can adjust difficulty level). There were certain oddities that I encountered, such as messages about low bridges that prevent boats from navigation - although I didn't have low bridges at all.
But what really made me write this issue is the situation with my small Tarraco city, where I got stuck with a somewhat stupid behaviour of enemy warriors. Please have a look:
https://yadi.sk/d/4_lVp0un3VdD7s
Some local uprisers approached my city but they failed to find the right path to the distant part of the map. They stand next to the long ship bridge and don't proceed further. Therefore, they don't do any harm to my city. As long as it is a 'war mode', no new settlers arrive to my city, but still my population grows and I even have some unemployed workers.
The question is how I can get enemies go away?

**Comment by bvschaik** [comment]
Hi, thanks for reporting!
I checked your enemies in the original C3 game: they behave exactly the same, walking back and forth before the bridge, so I'm going to close this issue.
As for getting rid of them: build a barracks on your city island and a javelin fort on the mainland. Wait until it's full and then attack the enemies with it. Your population will grow in January when the yearly births/deaths are calculated and you have room in the houses for the babies.

Regarding the low bridges issue: if you could supply me with a saved game for that as well, I'll have a look.
