### ISSUE TITLE
Screenshot Maps

### ISSUE THREAD

**Issue by KillahNeo** [bvschaik/julius#300]
Perhaps add a button or hotkey that screenshots the entire map of the game, somenthing simillar to this:

![0s9w1vX](https://user-images.githubusercontent.com/47231209/73914967-1489e900-4899-11ea-8393-f76d702cd010.jpg)

So that people don't have to resort to shit like this:
https://imgur.com/a/AHGRS

**Comment by crudelios** [comment]
I like this.

I'll see what I can do.

**Comment by bvschaik** [comment]
I actually have a very old branch locally somewhere for this. The main challenge is not overflowing RAM when screenshotting an enormous map.

**Comment by crudelios** [comment]
Makes  sense. An enourmous map will tke upwards of 200MB to fit the entire thing. If we used a png library to reduce the image disk size, the  RAM usage would increase even further.

It can still be done if we check for errors and throw a log warning if the user has run out of memory.

**Comment by bvschaik** [comment]
Since we already have code for creating BMP screenshots (F12), I wanted to reuse that. BMP is lossless, easy to write, can be done in increments (render a couple of tiles in height, write, render a couple of tiles, write, ...). That way we can minimize memory usage.

**Comment by crudelios** [comment]
> BMP is lossless, easy to write, can be done in increments (render a couple of tiles in height, write, render a couple of tiles, write, ...). That way we can minimize memory usage.

I guess that's true. And we avoid another dependency in a png encoder. But the file size will be colossal.

**Comment by bvschaik** [comment]
> But the file size will be colossal.

I can live with that.

**Comment by crudelios** [comment]
All right. If you can't find your old branch I can try throwing something later today.

**Comment by Legionary2** [comment]
I really like this idea
