### ISSUE TITLE
Triumphal Arch Rarity and it's connection to Roadblocks

### ISSUE THREAD

**Issue by KillahNeo** [bvschaik/julius#302]
I have seen in many pictures a triumphal arch, and i've always wondered if can they be built and if so how? 

![image](https://user-images.githubusercontent.com/47231209/73915813-e1e0f000-489a-11ea-88e5-66d20dea9cbd.png)

Now i've figured it how, and it amazes me.

You need to send troops to Caesar, when requested, to a distant battle and win! Sending any group of legions not divisible by 3 (1, 2,4,5) will result in a win.

You will then be awarded a TA. Build it near you luxury housing because it has lots of good land value. 

But don't build it in the middle of a road, or all traffic will cease. Even though it is an arch, is acts like a real road block!

Triumphal arches are one of the few directional buildings in Caesar3. That is, their orientation actually makes a difference. All walkers have no problem passing through the openings in the archway, but they can not pass through the other two sides of the arch.

But anyways, maybe that could be available without the need to send troops to Caesar, or the math done to obtain access the triumphal arch should be changed? or even better, the code for the arch could be changed into adding roadblocks for Caesar III?

**Comment by bvschaik** [comment]
> Sending any group of legions not divisible by 3 (1, 2,4,5) will result in a win.

That's not true. You need to send enough troops such that your troops are stronger than the enemy so they will win the battle. How strong the enemy is, is different for each distant battle.

The arch does not act as a roadblock. And of course people can't walk through a wall of marble...

As for making them available for general use: no. You have to earn them.
