### ISSUE TITLE
Editor Adjustments and 1 Bug

### ISSUE THREAD

**Issue by Legionary2** [bvschaik/julius#305]
Hi again, 
In the current unstable build (not sure about stable), if you place native infrastructure and then place roads, the native infrastructure will be cleared/disappear in the map editor. 

Next, I noticed denarii can now be requested by the emperor in the map editor which is awesome. However, the limitations of the request are only up to 999. I understand why that's there because of course when dealing with resources no request would be in that number range, but it would be nice in the case of dealing with money to request within the 100-10000-99999 range.

Additionally, through campaign digging, the final military mission of Lindum had an invasion of 160, yet the editor ends at 120 - I know for hardware issues of the time I suppose. Can that limit be expanded for a large invasion option in custom scenarios? Since it is the editor, the player doesn't have to go beyond 120, just for those who would like it of course. 

Finally, is there anyway to utilize the available win criteria to force the player to maybe stay in the scenario for a desired amount of years even though they have reached the required ratings for promotion? Say the player may be able to achieve victory in year 27 but I wish for them to still deal with heavy invasions / requests in years 30 and 35 etc... is there a way to make winning time be conditional as in reach this desired amount of time + achieve ratings? 

Cheers and thanks for all the hard work!

**Comment by bvschaik** [comment]
Regarding the native structures: good one! I just checked and it's also present in 1.2.0. I'll have a look tomorrow.

Denarii requests: also a good one. The field for the amount is limited to 32767 though, so I think I'll put the max on 30000.

Invasion size: not just invasions, there's also a limited number of slots available for enemy formations and there's of course the figure limit of 1000. I'll have a look as well.

Win criteria: you could try the "survival time" option, though I seem to remember that it did not work properly in Caesar 3. Perhaps we can fix that.

**Comment by Legionary2** [comment]
Glad I could help !!! I enjoy custom scenarios so I fiddle around with it quite a bit. As for denarii, yeah 30000 is fine for sure. If the number of invasion units can be increased it would just be a nice touch for some military minded assignments or that once and a while heavy flair up invasion. 

Also, I JUST noticied that in the editor, if you select win criteria to yes and not even select a date, it somehow greets you with a promotion to clerk and then ports you to campaign … very weird and I'm sure not intended lolol.

**Comment by Legionary2** [comment]
Ok its actually two bugs. If you select YES for survival time and input any desired date - nothing happens. When you close out the editor and then try to load the mission in the editor - FIRED! Message appears and ports you to the citizen tutorial of the campaign. 

If you select YES for win time and input any desired date or not and just right click out of it - it will prompt you to clerk promotion and port you to the brundisium tutorial level. 

Hope this helps :)

**Comment by crudelios** [comment]
> Ok its actually two bugs.....

Wow, it really gets you fired or allows you to win, all from within the editor! Funny one!

Note that for this to happen, you have to disable every rating (culture, prosperity, peace and favor) and disable open play as well.

**Comment by bvschaik** [comment]
At least you can test the newly added lose game audio with this :rofl:

**Comment by crudelios** [comment]
> At least you can test the newly added lose game audio with this :rofl:

Yes. Caesar was very disappointed with my scenario editing skills.

**Comment by Legionary2** [comment]
Lulz, I went to the galley for a bad map ...

**Comment by bvschaik** [comment]
> Should `game_tick_run()` even be called when the editor is active?

Yes, because otherwise the invasion/entry/exit/fishing flags do not show up.

Current unstable makes the following changes:

- Increase request amount to 30000 for denarii
- Increase max invasion size to 200
- Fix fired/victory screen being shown in the editor

I'm still looking into the natives.

**Comment by bvschaik** [comment]
And the natives have been fixed as well. Could you have a look?

**Comment by Legionary2** [comment]
You got it Bianca I’ll look right now ! Also, I was talking to credelios over at discord. Your new denarii amount got me thinking (He likes it too), for enemy army types - could the Romans become an enemy army (caesars blue) for custom maps maybe having a civil war ? Figured it’s not too intensive since the enemy graphics are already there. Let me know :)

**Comment by Legionary2** [comment]
> And the natives have been fixed as well. Could you have a look?

Denarii goes to 30000, and draws the proper amount from the treasury 
Natives no longer disappear after roads are drawn
No issue with fire/victory campaign port
Invasion test of like 180 (while I can count individual units) from the eye test and knowing this game - it was certainly a larger fuller stream of units so I'm sure its no issue

**Comment by bvschaik** [comment]
Regarding the Romans becoming an enemy army: unfortunately not without breaking compatibility.

Thanks for verifying!
