### ISSUE TITLE
Julius doesn't work no more on French Version

### ISSUE THREAD

**Issue by fryjo** [bvschaik/julius#307]
Julius 1.1.0 worked well on French vers but now 1.2.0 doesn't work , i can't have access to the option menu or build roadblock.

Good Job for the enhanced version of Caesar 3 (◍•ᴗ•◍)❤

**Comment by crudelios** [comment]
What do you mean by "it doesn't work"? It doesn't open at all?

Options menu was created after version 1.2.0 and are only available on `Unstable` builds.

Roadblock isn't available in this version of Julius, but on @Keriew's build which is available at:

https://github.com/Keriew/julius

**Comment by fryjo** [comment]
Ok my bad gonna test the unstable release and check it later

**Comment by bvschaik** [comment]
I'm going to assume that installing the unstable and/or Keriew's fork has solved the issue. If not, please comment here with more information and I'll reopen the issue.
