### ISSUE TITLE
Official packages

### ISSUE THREAD

**Issue by pkubaj** [bvschaik/julius#31]
You may want to put some info about systems that package julius. FreeBSD and OpenBSD now do.

**Comment by Quix0r** [comment]
Also please consider adding a `README.md` and explain there the usual things such as getting it running, it looks like the data is missing?

**Comment by bvschaik** [comment]
@pkubaj Julius is 1.0.0 now. What do I need to do to get the release pushed to *BSD?

**Comment by bvschaik** [comment]
Thanks, I will mail him.
<sup>(By the way, I removed his mail address from your comment)</sup>

**Comment by Quix0r** [comment]
Thank you for adding a `README.md` file. 👍

**Comment by bvschaik** [comment]
@pkubaj Could you update the FreeBSD package to  [1.1.0](https://github.com/bvschaik/julius/releases/tag/v1.1.0)?

**Comment by pkubaj** [comment]
All FreeBSD maintainers get notifications about new versions of their maintained software and I already got one about julius.

Here's a Phabricator review for new version of julius:
https://reviews.freebsd.org/D20424

**Comment by bvschaik** [comment]
Ah, good to know. Thanks!
