### ISSUE TITLE
Fix notification for Oracle needing road access when it actually doesn't need it

### ISSUE THREAD

**Issue by vorsprung1** [bvschaik/julius#312]
You can place an Oracle 1 tile away from the road and it will function fine, it just needs prefecture  and engineer access. But the notification is false when placing it like that.

**Comment by bvschaik** [comment]
The notification is partly true in the sense that it needs engineer/prefect coverage, which cannot be provided without a road. Without the warning, people will think that the oracle will work fine when placed in the middle of nowhere.

**Comment by vorsprung1** [comment]
I'm only talking about when it's just **one tile away** from the road. Like when you place a housing tile one tile away from the road, it's valid, it doesn't clear out like if it were in the middle of nowhere.
