### ISSUE TITLE
Fix theaters working fine even without actors from a colony

### ISSUE THREAD

**Issue by vorsprung1** [bvschaik/julius#313]
In the theater screen it says no plays, but it works as if it had plays. I'm not sure about the amphitheater.

**Comment by bvschaik** [comment]
Thanks for the suggestion. Amphitheaters do not provide the full entertainment value without performers provided by gladiator schools or actor colonies.
"Fixing" this feature will break savegame compatibility (that is: loading a Caesar 3 savegame in Julius will destabilize your city), so this will not be changed.
