### ISSUE TITLE
How about not allowing to wall in wolfes (rendering them completely harmless) by treating them like enemy troups and not allowing building next to them?

### ISSUE THREAD

**Issue by vorsprung1** [bvschaik/julius#315]
Just an idea. Not, you just wall them in at the beginning and it's like they were never there, defeating the purpose of even having them in the game.

**Comment by bvschaik** [comment]
Thanks for the suggestion. However, this is a gameplay change for Caesar 3, and Julius does not incorporate gameplay changes, so I'm going to close this.

**Comment by crudelios** [comment]
Note that this can be discussed in [Keriew's fork](https://github.cnom/Keriew/julius), because gameplay changes are being applied there.
