### ISSUE TITLE
Crashes when opening mission1.pak on PowerPC64 (Big Endian)

### ISSUE THREAD

**Issue by lenoil98** [bvschaik/julius#32]
Successfully compiles with no errors.  Game starts okay, but when you start a new career, after entering the new governor's name the game crashes.  See below:

Initializing SDL.
SDL initialized.
Current resolution: 1920 x 1200
Fullscreen? 0
Texture created (1024 x 768)
 OK: model loaded
SOUND: OK
SOUND: trying music file: wavs/SETUP.WAV
SOUND: playing music file: wavs/SETUP.WAV
INFO: Window 1 shown
INFO: Window 1 hidden
INFO: Window 1 shown
SOUND: playing channel 3
SOUND: playing wavs/01B.WAV on channel 0
Loading saved game: mission1.pak
ERR:COMP1 Corrupt.
ERR:COMP Error uncompressing.
ERR:COMP1 Corrupt.
ERR:COMP Error uncompressing.
ERR:COMP1 Corrupt.
ERR:COMP Error uncompressing.
ERR:COMP1 Corrupt.
ERR:COMP Error uncompressing.
ERR:COMP1 Corrupt.
ERR:COMP Error uncompressing.
ERR:COMP1 Corrupt.
ERR:COMP Error uncompressing.
ERR:COMP1 Corrupt.
ERR:COMP Error uncompressing.
ERR:COMP1 Corrupt.
ERR:COMP Error uncompressing.
ERR:COMP1 Corrupt.
ERR:COMP Error uncompressing.
ERR:COMP1 Corrupt.
ERR:COMP Error uncompressing.
ERR:COMP1 Corrupt.
ERR:COMP Error uncompressing.
ERR:COMP1 Corrupt.
ERR:COMP Error uncompressing.
ERR:COMP1 Corrupt.
ERR:COMP Error uncompressing.
ERR:COMP1 Corrupt.
ERR:COMP Error uncompressing.
ERR:COMP1 Corrupt.
ERR:COMP Error uncompressing.
ERR:COMP1 Corrupt.
ERR:COMP Error uncompressing.
ERR:COMP1 Corrupt.
ERR:COMP Error uncompressing.
ERR:COMP1 Corrupt.
ERR:COMP Error uncompressing.
ERR:COMP1 Corrupt.
ERR:COMP Error uncompressing.
ERR:COMP1 Corrupt.
ERR:COMP Error uncompressing.
Error: signal 11:

**Comment by bvschaik** [comment]
I think I identified and fixed the cause of the crash, but I don't have a big-endian computer to test it on (except a very old PowerPC Mac, but that can't run cmake or sdl2).

Could you try with the latest master and let me know the results?

**Comment by bvschaik** [comment]
Great!
Could you perhaps also run the test suite (using `ctest`) and report the results? I'm fairly confident that endian-ness is no problem now, but the test suite is a good way to make sure 😃

**Comment by lenoil98** [comment]
Looks like there's work to be done!  Below are the test results:
./runtests.sh
[ 60%] Built target julius
[ 61%] Built target compare
[100%] Built target autopilot
Running tests...
Test project /usr/ports/tmp/julius/build
      Start  1: sav_tower
 1/14 Test  #1: sav_tower ........................***Failed    0.91 sec
      Start  2: sav_request1
 2/14 Test  #2: sav_request1 .....................***Failed    2.94 sec
      Start  3: sav_request2
 3/14 Test  #3: sav_request2 .....................   Passed    7.81 sec
      Start  4: sav_caesar1
 4/14 Test  #4: sav_caesar1 ......................   Passed    2.46 sec
      Start  5: sav_caesar2
 5/14 Test  #5: sav_caesar2 ......................***Failed    2.82 sec
      Start  6: sav_caesar3
 6/14 Test  #6: sav_caesar3 ......................***Failed    3.04 sec
      Start  7: sav_caesar4
 7/14 Test  #7: sav_caesar4 ......................***Failed    3.17 sec
      Start  8: sav_invasion1
 8/14 Test  #8: sav_invasion1 ....................***Failed    4.56 sec
      Start  9: sav_invasion2
 9/14 Test  #9: sav_invasion2 ....................***Failed    6.79 sec
      Start 10: sav_invasion3
10/14 Test #10: sav_invasion3 ....................***Failed    8.52 sec
      Start 11: sav_invasion4
11/14 Test #11: sav_invasion4 ....................***Failed   10.12 sec
      Start 12: sav_invasion5
12/14 Test #12: sav_invasion5 ....................***Failed   11.79 sec
      Start 13: sav_routing_full
13/14 Test #13: sav_routing_full .................   Passed    3.99 sec
      Start 14: sav_curses
14/14 Test #14: sav_curses .......................***Failed    3.68 sec

21% tests passed, 11 tests failed out of 14

Total Test time (real) =  72.66 sec

The following tests FAILED:
	  1 - sav_tower (Failed)
	  2 - sav_request1 (Failed)
	  5 - sav_caesar2 (Failed)
	  6 - sav_caesar3 (Failed)
	  7 - sav_caesar4 (Failed)
	  8 - sav_invasion1 (Failed)
	  9 - sav_invasion2 (Failed)
	 10 - sav_invasion3 (Failed)
	 11 - sav_invasion4 (Failed)
	 12 - sav_invasion5 (Failed)
	 14 - sav_curses (Failed)
Errors while running CTest

**Comment by bvschaik** [comment]
Oh bugger. At least a few tests pass so it's not all bad..
I'll have to set up a qemu to debug this. Which OS and compiler do you use?

**Comment by lenoil98** [comment]
Sorry for the delay.  Results are mixed. Here are the new test results:

Running tests...
Test project /usr/ports/tmp/julius/build
      Start  1: sav_tower
 1/14 Test  #1: sav_tower ........................   Passed    0.83 sec
      Start  2: sav_request1
 2/14 Test  #2: sav_request1 .....................   Passed    2.93 sec
      Start  3: sav_request2
 3/14 Test  #3: sav_request2 .....................   Passed    7.76 sec
      Start  4: sav_caesar1
 4/14 Test  #4: sav_caesar1 ......................***Failed    2.46 sec
      Start  5: sav_caesar2
 5/14 Test  #5: sav_caesar2 ......................***Failed    2.80 sec
      Start  6: sav_caesar3
 6/14 Test  #6: sav_caesar3 ......................***Failed    3.03 sec
      Start  7: sav_caesar4
 7/14 Test  #7: sav_caesar4 ......................***Failed    3.19 sec
      Start  8: sav_invasion1
 8/14 Test  #8: sav_invasion1 ....................   Passed    4.54 sec
      Start  9: sav_invasion2
 9/14 Test  #9: sav_invasion2 ....................   Passed    6.79 sec
      Start 10: sav_invasion3
10/14 Test #10: sav_invasion3 ....................   Passed    8.52 sec
      Start 11: sav_invasion4
11/14 Test #11: sav_invasion4 ....................***Failed   10.19 sec
      Start 12: sav_invasion5
12/14 Test #12: sav_invasion5 ....................***Failed   12.08 sec
      Start 13: sav_routing_full
13/14 Test #13: sav_routing_full .................   Passed    4.10 sec
      Start 14: sav_curses
14/14 Test #14: sav_curses .......................   Passed    3.79 sec

57% tests passed, 6 tests failed out of 14

Total Test time (real) =  73.10 sec

The following tests FAILED:
	  4 - sav_caesar1 (Failed)
	  5 - sav_caesar2 (Failed)
	  6 - sav_caesar3 (Failed)
	  7 - sav_caesar4 (Failed)
	 11 - sav_invasion4 (Failed)
	 12 - sav_invasion5 (Failed)
Errors while running

**Comment by lenoil98** [comment]
Sorry for the delay.  Results are mixed. Here are the new test results:

Running tests...
Test project /usr/ports/tmp/julius/build
      Start  1: sav_tower
 1/14 Test  #1: sav_tower ........................   Passed    0.83 sec
      Start  2: sav_request1
 2/14 Test  #2: sav_request1 .....................   Passed    2.93 sec
      Start  3: sav_request2
 3/14 Test  #3: sav_request2 .....................   Passed    7.76 sec
      Start  4: sav_caesar1
 4/14 Test  #4: sav_caesar1 ......................***Failed    2.46 sec
      Start  5: sav_caesar2
 5/14 Test  #5: sav_caesar2 ......................***Failed    2.80 sec
      Start  6: sav_caesar3
 6/14 Test  #6: sav_caesar3 ......................***Failed    3.03 sec
      Start  7: sav_caesar4
 7/14 Test  #7: sav_caesar4 ......................***Failed    3.19 sec
      Start  8: sav_invasion1
 8/14 Test  #8: sav_invasion1 ....................   Passed    4.54 sec
      Start  9: sav_invasion2
 9/14 Test  #9: sav_invasion2 ....................   Passed    6.79 sec
      Start 10: sav_invasion3
10/14 Test #10: sav_invasion3 ....................   Passed    8.52 sec
      Start 11: sav_invasion4
11/14 Test #11: sav_invasion4 ....................***Failed   10.19 sec
      Start 12: sav_invasion5
12/14 Test #12: sav_invasion5 ....................***Failed   12.08 sec
      Start 13: sav_routing_full
13/14 Test #13: sav_routing_full .................   Passed    4.10 sec
      Start 14: sav_curses
14/14 Test #14: sav_curses .......................   Passed    3.79 sec

57% tests passed, 6 tests failed out of 14

Total Test time (real) =  73.10 sec

The following tests FAILED:
	  4 - sav_caesar1 (Failed)
	  5 - sav_caesar2 (Failed)
	  6 - sav_caesar3 (Failed)
	  7 - sav_caesar4 (Failed)
	 11 - sav_invasion4 (Failed)
	 12 - sav_invasion5 (Failed)
Errors while running

**Comment by bvschaik** [comment]
Funny. Test 4 passed before but fails now.

Could you let me know your OS and compiler? I want to debug this.

**Comment by bvschaik** [comment]
I have a 32-bit PowerPC virtual machine with Debian running now, and I get the same results. Will investigate.
