### ISSUE TITLE
Maybe more visibility when controlling legions?

### ISSUE THREAD

**Issue by ArtySh0ck** [bvschaik/julius#320]
![image](https://user-images.githubusercontent.com/46932541/74337791-a74eea00-4da9-11ea-8258-a9e44492d211.png)

Example:
Currently i need to choose one legion, we say its Rabbits, to move or something. BUT, u know, clicking there the game somehow gives us random (i know it isnt random, it depends on "legion layer", and time when current legion came to point, earlier or later) legion.

Idea: maybe game should somehow give us a highlight of choosen legion when it clicked once? We click on that mess of legions and TROOPS are, maybe, come greener? And then we decide, to do something with it, or just right-click it to drop and try another to pick. 
Better, but impossible (i think): to highlight troops in legion when it hovered by cursor.

Thanks.

**Comment by crudelios** [comment]
This is absolutely required for touch support, but I have no idea on what to implement.

**Comment by BeleGMRV** [comment]
How about using the side panel to allow you to select your legions from there, as an alternative to clicking on them directly on the screen.  There can never be more than six so it should take up too much space there.  That way you would never click on the wrong one, and you could even order them around without having to see them on screen (e.g. when sending your legions one by one to a far away area of the map).

A military section on the panel could be untoggled by default (the side panel being used by default for other info, e.g. game speed, scores, etc), and toggled only when you click on a legion, then untoggled again when clicking anywhere else to show whatever other information is ).  I can think of an issue with this approach, which is that the panel may be untoggled when you still want to use it (i.e. when you're sending them somewhere far away, you would still need to switch back and forth from the minimap, losing part of the benefit).  A workaround would be to show the military section of the panel by default for as long as you are being invaded (there must be a flag somewhere that keeps the battle music playing, you could pin it to that).

To save space and make it look nicer, you could use the legion banners as buttons, as they already convey all the necessary information about the legion, i.e. whether they are legionnaires, cavalry or javelinmen, and the icon telling them apart (fish, snake, eagle, etc).  You could perhaps add next to the banner the name of the legion, in case that's more helpful to some players, and how many soldiers are left.  All those text strings are used in the Military Advisor tab, so should be easily referred to and readily translated to all languages.  It would be really cool to also be able to show some icons or colour coded spots for health, academy training and morale, but it may end up looking a bit too cluttered?  Just throwing ideas around.

Many thanks.

**Comment by crudelios** [comment]
Based on @BeleGMRV's comment, and as said on the discord channel, expanding the military view by replacing the build buttons with a military panel could work well.

**Comment by crudelios** [comment]
This is what I have so far:

![city 2020-03-10 09 34 29](https://user-images.githubusercontent.com/6518876/76299359-dd9d5d80-62b2-11ea-86c2-15766b81341d.png)

Any suggestions to improve the interface are welcome!

**Comment by bvschaik** [comment]
Instead of the text-based "Go to legion" and "Return to fort" buttons you can use the image buttons that are also used in the Military advisor.

Maybe add Next/Prev arrow buttons to quickly select another legion? (like the `L` hotkey)

I'm not sure about the "line formation" button, it's not clear to me what it does when I click on it. And does the text fit for all languages?

**Comment by crudelios** [comment]
> Instead of the text-based "Go to legion" and "Return to fort" buttons you can use the image buttons that are also used in the Military advisor.

Yeah, the text can go to a tooltip.

> Maybe add Next/Prev arrow buttons to quickly select another legion? (like the `L` hotkey)

Like! 👍 

> I'm not sure about the "line formation" button, it's not clear to me what it does when I click on it. And does the text fit for all languages?

It doesn't, bah!

If I replace the other two buttons with images I may be able to display the current formation button. It'll probably look crammed though,

**Comment by crudelios** [comment]
> Better, but impossible (i think): to highlight troops in legion when it hovered by cursor.

Possible and currently being implemented on my military sidebar project.

**Comment by devnoname120** [comment]
@crudelios This can be closed now, right?

**Comment by crudelios** [comment]
It will as soon as #516 is merged.
