### ISSUE TITLE
That russian 1C Caesar 3 again...

### ISSUE THREAD

**Issue by ArtySh0ck** [bvschaik/julius#321]
Guys, hope u enjoy, russian fans of C3 really exited to have Julius and it going on with updates! I have a lot a questions, issues from some of them. And one of these issues, actualy, hurts me as well, so :

C3 (rus, 1C ver.) font-style. It's so disgusting styled, eyes are bleeding after 30 minutes of playing. I think, its something wrong with text-shadow effect, its so sloppy-pixeled, and font as it is too. You dont need to be native speaker of russian to see that difference:
![image](https://user-images.githubusercontent.com/46932541/74339654-2d206480-4dad-11ea-9b31-2cd89ee0f2af.png)
![image](https://user-images.githubusercontent.com/46932541/74339674-3a3d5380-4dad-11ea-89be-8da26dd8704b.png)
Ohhh its impossible to explain, but you see how elegant and accurate english version textes in comparison. PROBLEM is most of Caesar's textes are small, especially if it ran as 1920x1080 (as i play) and everytime player have to strain eyes to understand a deal by text.

As a member of GZ discord channel i have read there, in C3 letters is a images. That's right? So, i want to offer my assistance. If Bianca or Crudelios can explain and lil help me with that process here, in this topic (or our gitter), i can try to "restyle" that font for C3.

Thanks!

**Comment by bvschaik** [comment]
I was already wondering how you guys could read the Russian font...

Yes, all letters are images. I unpacked the Russian ones for you: [russian-fonts.zip](https://github.com/bvschaik/julius/files/4193609/russian-fonts.zip)

Note that there are 1580 images in total... 10 sets of 158 images per font size/color. The 158 images include the Latin letters and punctuation: we can reuse those from the English version. Then you'd "only" need to restyle the 64 Cyrillic characters times 10 fonts. Note that the images should stay the same size, but I think a lot can be done to make them clearer.

**Comment by ArtySh0ck** [comment]
Ok, thanks! I will try to do something with this.

**Comment by ArtySh0ck** [comment]
> Note that the images should stay the same size, but I think a lot can be done to make them clearer.

I need their size must not be bigger or less? original <= new, original >= new, or original == new?

**Comment by ArtySh0ck** [comment]
Now, i guess, i found main reason they look so hardly to look at. Cause shadows. When i zoom it i can see the same quality of letter structure, but shadow in russian version is too "pixeled".

**Comment by bvschaik** [comment]
> I need their size must not be bigger or less? original <= new, original >= new, or original == new?

At least for height: original == new. Width does not really matter.

**Comment by ArtySh0ck** [comment]
Another question, how can i test my results within game?

**Comment by bvschaik** [comment]
At the moment: not 😞  I still need to write a utility program to pack the images back into a .sg2 and .555 file...

**Comment by ArtySh0ck** [comment]
Guys, its such a horrible, i hate it now! Already playd with color, depths, shadows, but still ugly OR worst - some symbols came "broken". If some symbol hadnt came a broken its very same as original. I thought about, to paint a new symbols at all but i have no so much experience and time for this =(

Maybe we can still save as it is now? Somebody know how to use "ImBatch" ? Maybe some advice? Cause this software can do same operation too many images in a group (its really comfortably) and it have much instruments to edit them, but i cant find what exacly i need more of others... 

Thanks for any advices, maybe someone have exp. in design.

**Comment by bvschaik** [comment]
No advice, but a head's up that I'll probably have a look at it this evening.

And what do you mean by "broken"?

**Comment by bvschaik** [comment]
I've looked into it. It's tedious work, but I've now changed 32 letters for the "black" font, lower case only. I used Times New Roman as base font, since that looks more or less like the letters currently in use.

Old font:
![font-old](https://user-images.githubusercontent.com/104874/76365218-0b23ee80-6327-11ea-8e1a-abe5e395b54b.png)

New font:
![font-new](https://user-images.githubusercontent.com/104874/76365230-137c2980-6327-11ea-9c2d-d78d85da528f.png)

How does this look?

And which of the fonts need adjustment, all 10 of them? Is for example the white text used in the help pages readable enough?

**Comment by ArtySh0ck** [comment]
> And what do you mean by "broken"?

i mean, when i do add some new filter that can help with one symbol and it came looks better, some another symbol came like its cropped, cutted off by corners or sides. for example, when i try to edit letter "ф", that results me to no annoying shadow (its good), but upper and lower stick came dissappeared almost till the end.

**Comment by ArtySh0ck** [comment]
Your result is wonder, are u wizard, Bianca? =) its looking so good as never before, believe me! How did u do that??? How u convert .png files from image to font format?

**Comment by bvschaik** [comment]
> How did u do that??? How u convert .png files from image to font format?

Last weekend I wrote a small basic command-line program to change 1 image in the .sg2/.555 files, so I'm using that to replace the letters one by one.

How I did it:

1. Create an HTML page with all the letters. Determine font, text, shadow and background color, make sure it's the right font size.
2. Take a screenshot of that page
3. Remove the background color using the Gimp
4. Cut out the letters one by one at the correct size in the Gimp and save as new image
5. Use my command-line tool to replace the letters one by one

I'm going to automate this process so I can replace all 158 letters in one font color/size in one go.

**Comment by bvschaik** [comment]
@ArtySh0ck Could you give [these font files](https://github.com/bvschaik/julius/files/4321090/C3_fonts.zip) a go and let me know how this looks? Just extract the files to your C3 folder, overwriting the old ones (make a backup first).
I've replaced all normal-sized letters, I'm still working on the big title font.

**Comment by bvschaik** [comment]
And here are the [font files](https://github.com/bvschaik/julius/files/4325770/C3_fonts.zip) with the large title fonts also replaced. Could you test them out?

**Comment by bvschaik** [comment]
I've added the new font files to the [Russian patch](https://bintray.com/bvschaik/caesar3-patches/russian).

**Comment by ArtySh0ck** [comment]
Ok, i will check it soon as i can, thank you! <3
