### ISSUE TITLE
German translation for "Getting food" in granary is wrong

### ISSUE THREAD

**Issue by m-mohr** [bvschaik/julius#322]
In granaries there are three states for food:
* Accept
* Don't accept
* Getting food

"Getting food" has a wrong translation in German. There it says basically "Don't distribute food" (in German "Nahrungsmittel halten"), which is the opposite of getting food and very confusing. Can this be fixed? Unfortunately, it is already wrong in the original C3. Correct would be "Nahrungsmittel fordern". If there's no term in the language files, one could probably use the "Getting goods" (German: "Waren fordern") from the warehouses.

If "Nahrungsmittel" as term for food is too long there are some shorter synonyms: Nahrung (preferred), Lebensmittel, Essen (worst).

**Comment by m-mohr** [comment]
I'm collecting some more "overflows" and shortened versions:
* "Nahrungsmittel halten" (wrong translation anyway) => "Nahrung fordern"
* "Unser Karren ist hier und wartet auf neue Anweisungen" => "Unser Karren wartet hier auf neue Anweidungen."
* "ACHTUNG: Dieses Lagerhaus ist bald voll. Es kann nur noch einige bevorstehende Vorräte aufnehmen und neue Arten von Waren werden überhaupt nicht mehr angenommen." => "ACHTUNG: Dieses Lagerhaus ist bald voll. Es nimmt nur noch wenige Vorräte auf. Neue Arten von Waren werden nicht mehr angenommen."

**Comment by m-mohr** [comment]
Could we move the text a bit to the right? Like 5px or so?

![grafik](https://user-images.githubusercontent.com/8262166/74382280-6678c480-4ded-11ea-8850-177b7a7fd9f0.png)

**Comment by m-mohr** [comment]
And here it would be 10px or so...

![grafik](https://user-images.githubusercontent.com/8262166/74382354-91631880-4ded-11ea-9887-ba369306fc55.png)

**Comment by m-mohr** [comment]
I've got a updated c3.eng with less overflowing text and will continue to improve it. I'm happy to share what I've changed.

**Comment by bvschaik** [comment]
FYI: you can use [Eng converter](https://github.com/bvschaik/citybuilding-tools/releases/tag/engconverter-v0.4) to convert the `.eng` files to `.xml` and vice versa.

**Comment by m-mohr** [comment]
@bvschaik Yes, I used it and worked well.

**Comment by bvschaik** [comment]
I've gone through all building info screens and I updated a few text offsets so they do not overlap with the help button. That solves the issue in the two screenshots in the comments above.
If you find any more, please post them.
