### ISSUE TITLE
Scrolling in windowed mode

### ISSUE THREAD

**Issue by m-mohr** [bvschaik/julius#323]
I think this got worse with the touch support improvements as the scrolling area got reduced. In windowed mode it's now pretty hard to scroll as the area is so tiny and you easily leave the window by accident. I think the area for scrolling should be back to normal (i.e. larger)  when in windowed mode.

**Comment by crudelios** [comment]
Humm I did not change the scrolling area using the mouse, it just wasn't too large to begin with.

But it could be increased on window mode indeed.

**Comment by m-mohr** [comment]
Sorry for blaming you. I thought it could have been related.

**Comment by crudelios** [comment]
No problem, it could very well have been related. Scrolling has always been iffy on windowed mode anyway...

**Comment by bvschaik** [comment]
As far as I remember the scroll area has been 5px. The risk with enlarging it is that it will be difficult to click the top menu items without scrolling the map.

Caesar3 solves this by using a Windows API to detect when the mouse hits the screen edge (not the window edge). We cannot use that because it doesn't work on other platforms, and I have no idea how that would work in a multi-monitor setup anyway.

If you have suggestions on how to improve the scrolling, please post them.

**Comment by m-mohr** [comment]
Maybe the mouse is not the best input device. What about the arrows on the keyboard in addition?

**Comment by bvschaik** [comment]
Only making it scroll below the menu will make matters even worse, since you have to cross the scroll area to reach the top menu...

Arrow keys already work to scroll, and you can also click the minimap to jump to an area quickly.

**Comment by crudelios** [comment]
Not the best thing, but we can increase the scroll to 10px to the left, right and bottom sides and keep 5px (or maybe increase less, to i.e. 7px) to the top side.

**Comment by crudelios** [comment]
I was just noticing today that something does indeed feel different regarding scrolling on windowed mode, even though it shouldn't be.

**Comment by bvschaik** [comment]
Using smooth scrolling or the C3 one? I've been using the C3 one and I don't feel a difference.

**Comment by crudelios** [comment]
Using smooth scrolling with high DPI.

**Comment by m-mohr** [comment]
Maybe for window mode click-drag in addition would be the more useful than trying to hover a 5px area somewhere, but in the end I'm not even sure whether many people use windowed mode. I just used it once when I was translating and testing for #322.

**Comment by crudelios** [comment]
I just use windowed mode for testing. The arrow keys also work. I'm not really sure about the click-drag using mouse.

Upon further checking, the scrolling area hasn't changed, it's as clumsy as before.

So I think this issue should be closed without changing anything.

**Comment by bvschaik** [comment]
Click-drag: I'm also not sure about that.

> So I think this issue should be closed without changing anything.

I agree.
