### ISSUE TITLE
Editor Flag Placement 

### ISSUE THREAD

**Issue by Legionary2** [bvschaik/julius#324]
In my latest editor map, I placed entry and exit points as well as 4 invasion points. Saved it and then loaded it some time later. Invasion flags and entry / exit points disappear but are still recognized in the editor as 4 points set and immigrants come and go on the actual map. Just a visual bug I suppose !

**Comment by bvschaik** [comment]
But a bug nonetheless! I could reproduce it:

1. Create map with entry/exit and invasion points and save it
2. Exit the editor, load a random city in the game
3. Go back to the editor and load the map you just saved: flags are gone

I'll have a look.

**Comment by Legionary2** [comment]
Cool, I know not a huge thing I just thought I was seeing things at first because it didn’t always happen - but it was the pause !

**Comment by bvschaik** [comment]
I fixed this by unpausing the game when loading a map in the editor: flags should always display now. Thanks for finding this!
