### ISSUE TITLE
cant control map vita

### ISSUE THREAD

**Issue by chriscanturia** [bvschaik/julius#329]
once in game, my right analog stick doesnt work. The map does move sometimes and when it does, it fully goes to one side.

**Comment by crudelios** [comment]
Being fixed by #328.

**Comment by bvschaik** [comment]
Could you try [this build](https://bintray.com/bvschaik/julius-branches/vita/fix-vita-keys-1.3.0.12-b38eaa5#files) and check if it fixes the problem?

**Comment by chriscanturia** [comment]
this build fixed the issue
