### ISSUE TITLE
Cannot list more than 207 saved games

### ISSUE THREAD

**Issue by CommonLoon102** [bvschaik/julius#333]
When I click "Load saved game" only the first 207 saved games are visible in the list. This is a bug in the original version too.

**Comment by crudelios** [comment]
You're right it is a bug, the limit should be `200` :wink:

Seriously though, this is not a bug, it's a "feature". I guess it *could* be fixed, but then you'd lose access to those files on the original C3.

**Comment by bvschaik** [comment]
The limit has been lifted in 4ff7bc157193bd1cbdb2b37a2161e14596927a37
