### ISSUE TITLE
Setting up in VS2019 (Windows) problem.

### ISSUE THREAD

**Issue by Uberwire** [bvschaik/julius#334]
For some reason, VS cannot find the two SDL libraries. I'm following the build instructions from here: https://github.com/bvschaik/julius/blob/master/doc/building_windows.md#a-using-microsoft-visual-studio-64-bit-build

I am currently stuck at 10. Setting up CMake command arguments.
I've set mine as such: `-DCMAKE_PREFIX_PATH=D:\\Visual Studio\\Libs\\SDL2-2.0.10;D:\\Visual Studio\\Libs\\SDL2_mixer-2.0.4`, but I'm still getting the error:

> Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR)		C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake	137

**Comment by bvschaik** [comment]
The space in the path may be a problem. Does it work when you use `D:\\Visual\ Studio\\Libs` (note the `\` before the space) instead of `D:\\Visual Studio\\Libs`?

**Comment by Uberwire** [comment]
> The space in the path may be a problem. Does it work when you use `D:\\Visual\ Studio\\Libs` (note the `\` before the space) instead of `D:\\Visual Studio\\Libs`?

It froze and I got that notification that VS is busy. I suspected something was wrong as I've waited for a couple of minutes for it to snap out of it, which it didn't, so I've restarted it with the settings saved (escaped whitespace), but the error is still there!

**Comment by bvschaik** [comment]
Could you try moving the libraries to a path without a space in them?

**Comment by crudelios** [comment]
You can also try `DCMAKE_PREFIX_PATH="D:\\Visual Studio\\Libs\\SDL2-2.0.10;D:\\Visual Studio\\Libs\\SDL2_mixer-2.0.4"`

**Comment by Uberwire** [comment]
> You can also try `-DCMAKE_PREFIX_PATH="D:\\Visual Studio\\Libs\\SDL2-2.0.10;D:\\Visual Studio\\Libs\\SDL2_mixer-2.0.4"`

This worked, except I removed the escape characters. (Extra backslash). Thanks!
