### ISSUE TITLE
Replay Map Confirmation Window

### ISSUE THREAD

**Issue by TheBeardedOne** [bvschaik/julius#338]
Hello! 

I have always been annoyed when I am clumsy, and hit "replay map" by accident, without saving!

So I decided it would be a great and minor addition to this project to introduce a replay mission confirmation window!

I have already made the changes, and would love to push them!

Here is a screenshot of it in action!

![image](https://user-images.githubusercontent.com/5952785/74873671-a54ad500-532d-11ea-8ce2-b49737521797.png)
![Julius_confirmation](https://user-images.githubusercontent.com/5952785/74873790-d88d6400-532d-11ea-9082-b960cb782ccc.gif)

**Comment by bvschaik** [comment]
Hi, thanks for the suggestion! I've also hit replay a couple of times by accident...

As for the screenshot: it looks a bit weird with twice "Replay map" in one dialog. Also, for yes/no dialogs we have the popup dialog that shows just `v` and `x` buttons (like the quit dialog). I've just done a quick implementation using the popup: see the latest dev version. How does that look?

**Comment by TheBeardedOne** [comment]
While I agree that the "Replay Map" word is repetitive, I think that my change (I submitted a pull request) changes as little of the original code as possible and maintains the file-per-window approach that the original developers used.

I can change the words if you want.

**Comment by TheBeardedOne** [comment]
I could also bring over the checkmark / x into the replay_confirm.c file so that it is more in line with original implementation, if you want.

**Comment by CommonLoon102** [comment]
> 
> 
> Hi, thanks for the suggestion! I've also hit replay a couple of times by accident...
> 
> As for the screenshot: it looks a bit weird with twice "Replay map" in one dialog. Also, for yes/no dialogs we have the popup dialog that shows just `v` and `x` buttons (like the quit dialog). I've just done a quick implementation using the popup: see the latest dev version. How does that look?

I think it looks nice, but it should have some text between the `Replay Map` title text and the `v` and `x` buttons. Similarly what the `Exit game` confirmation dialog has. Just a short text like `Start over this mission?` or something like that should be there. Or is it not possible to add new text, is it? Maybe there is something similar there already.

**Comment by crudelios** [comment]
> Maybe the text Proceed? could be used there. It is shown on the Load map dialog with the list of saves.

Agreed. It looks weird without any text.

**Comment by bvschaik** [comment]
The problem is that there is no text available in the language files so this is the best we can do...

**Comment by crudelios** [comment]
`Proceed?` could be a candidate, although it would require a small rewrite of the `popup_dialog`

**Comment by TheBeardedOne** [comment]
I like the idea of the word Proceed. I'll add it to my changes.

**Comment by TheBeardedOne** [comment]
Would anyone happen to know the text group `Proceed ` is in?

**Comment by bvschaik** [comment]
Good one! I just updated the code.

**Comment by bvschaik** [comment]
How does this look?

![dialog](https://user-images.githubusercontent.com/104874/74955024-502dc280-5404-11ea-9fc1-1461ca5ffa6c.jpg)

**Comment by TheBeardedOne** [comment]
Very good.
