### ISSUE TITLE
The Application Was Unable to Start Correctly 0xc000007b Error

### ISSUE THREAD

**Issue by Uberwire** [bvschaik/julius#341]
After successfully setting up the project in VS, I've built the project with current settings and got `Build All Successful`. After moving julius.exe to my game directory and launching it, I've got the error. (I've got SDL and SDLMixer DLLs in there as well.

**Comment by crudelios** [comment]
You are mixing thr x86 version of the game with the x64 of sdl dlls, or vice-versa.

**Comment by Uberwire** [comment]
Oh right. Thanks!
