### ISSUE TITLE
Show future reservoir (and fountain) supply area

### ISSUE THREAD

**Issue by CommonLoon102** [bvschaik/julius#343]
In the original it is annoying to count the tiles when building a new reservoir. I have to save the game, imagine where should I put the reservoir, and if my calculation was wrong, I have to load the game and place it again and see if it provides water to that area where I meant it to be. So, it would be very helpful if the game would show it in advance, if the green reservoir image has water filled in it (or even if it doesn't, because you can connect an aqueduct later), the future pipes should be shown as green too. Or just show the covered area somehow else (if not pipes).

Something similar should be done to fountains too. Show the area with some color which will have water if you place the fountain (only if the fountain has water in it).

**Comment by bvschaik** [comment]
I like this. Last weekend I placed a reservoir 2 tiles off just for this reason.

**Comment by CommonLoon102** [comment]
Are you going to implement it? I guess for you it would take minutes.
I would only invest time if you don't want to actually implement it. I'm not yet familiar with the codebase.

**Comment by crudelios** [comment]
It's certainly doable (red color mask due to testing, can be changed):

![city 2020-02-21 02 26 07](https://user-images.githubusercontent.com/6518876/74998879-db817500-5451-11ea-9858-96e446e8e003.png)

**Comment by CommonLoon102** [comment]
At a minimum this would be enough. If we would want to have the most sophisticated solution this is what I would go for: draw the pipes too as green (like the reservoir) instead of just a color mask. And if the reservoir has water in it, the pipes should show water in them too. The pipes should be only drawn to those tiles where it makes sense (not under hills or water). So just re-use the already available logic what draws the pipes normally. Only difference is that it should have a green tint (if the reservoir is green too while placing). In case if the reservoir is currently at an invalid place (red tinted), don't draw the pipes at all.

**Comment by crudelios** [comment]
Due to the way the game works, it's not possible to use the same logic when constructing. I'm thinking about a simple blue mask regardless of whether the reservoir has water access or not. It's simpler and provides the needed information.

**Comment by CommonLoon102** [comment]
`it's not possible`
I thought C is Turing complete.

**Comment by crudelios** [comment]
> I thought C is Turing complete.

I thought context could be understood. It's not possible without fundamentally changing the internal workings of the game, therefore eroding whatever advantages code reuse could have.

**Comment by crudelios** [comment]
What do you think about this?

![city 2020-02-28 15 59 48](https://user-images.githubusercontent.com/6518876/75564474-23049400-5a44-11ea-8da2-85a66375921f.png)

**Comment by CommonLoon102** [comment]
Better than nothing. Basically it is the same as 8 days before, but you have changed the color, right?
Does it show the blue area even if the reservoir is not filled?
Does it work for fountains too? Previously I wrote it shouldn't show the blue area if the fountain doesn't have water access but I think maybe it still would be useful to show it even in that case.
