### ISSUE TITLE
Gods overlay tooltip: indicate covered gods

### ISSUE THREAD

**Issue by crudelios** [bvschaik/julius#348]
From discord:

> > Got a suggestion on YouTube, not a gameplay change, but on the religion overlay, is it possible for it to show which gods the houses have/don't have?

> Humm maybe on the tooltip for the overlay? Otherwise the overlay will look like a rainbow

I think it's a nice little idea :wink:

**Comment by KillahNeo** [comment]
There's a discord group?

**Comment by crudelios** [comment]
GamerZakh has a discord group and he added a channel for julius, so there are discussions there as well.

**Comment by crudelios** [comment]
To do this we need to change the tooltip implementation, which frankly is useful for other projects such as #320.

**Comment by laurentiupopa79** [comment]
That would also need to mention - while clicking on a priest - which is his patron god. Kind of difficult to achieve.

**Comment by bvschaik** [comment]
How does this look?

![tooltip-gods](https://user-images.githubusercontent.com/104874/80253869-63feda80-867a-11ea-9dda-42585d3ea10f.png)

**Comment by laurentiupopa79** [comment]
That looks great! Just two dots ":" after "different gods".

**Comment by bvschaik** [comment]
":" added as well.
