### ISSUE TITLE
no ingame music, missing entries in options menu, no roadblocks

### ISSUE THREAD

**Issue by jobe83** [bvschaik/julius#349]
When running Julius I have no ingame music - rest of the sound works fine. 
Also I seem to be missing entries in the options menu (see screenshot attached) and ingame I don´t have roadblocks as an option. 

I had it with the Julius version from some time ago and still have it with the 1.3 release and 1.3 in development version.

Ingame I have a German version, at least everything is in German. I don´t even know whether that is a differnet version or not. Í bought the game from GOG.
![caesar3_reduced options](https://user-images.githubusercontent.com/61391832/75119443-3948d380-5683-11ea-809d-9f1433746201.jpg)

Thanks for any help - and fantastic job and excetion with Julius!! Thank you!

**Comment by CommonLoon102** [comment]
Maybe you played this version?
https://github.com/Keriew/julius

It has roadblocks.

**Comment by jobe83** [comment]
Thanks a lot! That gave me the options I was looking for. Still no ingame music, just sonds, but I can always have the soundtrack running separately :P

**Comment by bvschaik** [comment]
Do you perhaps have music turned off in the sound settings? To check: load any savegame, and from the top menu select Options -> Sound settings.

**Comment by ArtySh0ck** [comment]
hmm... maybe its a reason to add some explainable text to version string? like "Julius Original/Base version 1.3.0.24". And ask Keriew to do some "Julius KeriewModed version 1.3.5.8....". To people can find it clearer...

**Comment by crudelios** [comment]
@jobe83 If the music still isn't working, can you please run the game, load a city, run the game for a minute then post `julius-log.txt` here as an attachment? Thanks.

**Comment by Maximuss83** [comment]
@CommonLoon102 @bvschaik 
I do not get the options of roadblocks in the game. I have the GOG version and Julius 1.3.1. installed. The options menu is the same as jobe83 showed, and these options work fine. I just don't get roadblocks....

**Comment by crudelios** [comment]
@Maximuss83 get it from here:

https://github.com/Keriew/julius

**Comment by Maximuss83** [comment]
That doesn't work either.

**Comment by jobe83** [comment]
Okay, now I cannot save the game... Whatever I do, whenever I confirm the save it seems to work fine but then the file isn´t there.

**Comment by jobe83** [comment]
And I just realized it also doesn´t remember the options I set. Everything is reseted when I restart the game,

**Comment by crudelios** [comment]
@Maximuss83 Which link are you exactly following? I just tried getting it from the link I gave you and both the roadblocks and the extra options are working.

**Comment by bvschaik** [comment]
@Maximuss83 If you have trouble running the "roadblocks" version, please open an issue at https://github.com/Keriew/julius/issues instead, since it's a different project.

@jobe83 Please post more information about your music issue.

**Comment by bvschaik** [comment]
@jobe83 I'm assuming music has been turned off in the settings. If that's not the case, please post more information and I'll reopen the issue.

**Comment by jobe83** [comment]
It hasn´t been turned off. Was the first thing I checked. I have normal music in the menu screen. Only once I start a game it is gone, though all other sounds are still there.

**Comment by crudelios** [comment]
@jobe83 Please leave the julius log here.

**Comment by jobe83** [comment]
INFO: Julius version 1.2.0.204-8ce71635-dirty

INFO: Initializing SDL

INFO: SDL initialized

INFO: Loading game from working directory

INFO: Config key  gameplay_fix_immigration  1

INFO: Config key  gameplay_fix_100y_ghosts  1

INFO: Config key  ui_sidebar_info  1

INFO: Config key  ui_show_intro_video

INFO: Config key  ui_smooth_scrolling  1

INFO: Config key  ui_walker_waypoints  1

INFO: Config key  ui_visual_feedback_on_delete  1

INFO: Config key  gameplay_change_grandfestival  1

INFO: Config key  gameplay_change_jealous_gods  1

INFO: Config key  gameplay_change_global_labour  1

INFO: Config key  gameplay_change_school_walkers  1

INFO: Config key  gameplay_change_retire_at_60  1

INFO: Config key  gameplay_enable_extra_forts  1

INFO: Config key  gameplay_wolves_block  1

INFO: Detected language:  German

INFO: Detected encoding:  1252

INFO: Creating screen 1920 x 1080, fullscreen? 1

INFO: Texture created (1920 x 1080)

INFO: model loaded

INFO: Loading audio files

INFO: Window resized to 1920 x 1080

INFO: Texture created (1920 x 1080)

INFO: Window 1 shown

INFO: Loading saved game  CURRENT GAME1.sav

INFO: Saving game  CURRENT GAME1.sav

INFO: Window resized to 1920 x 1080

INFO: Texture created (1920 x 1080)

INFO: Window resized to 1920 x 1080

INFO: Texture created (1920 x 1080)

INFO: Window resized to 1920 x 1080

INFO: Texture created (1920 x 1080)

INFO: Window resized to 1920 x 1080

INFO: Texture created (1920 x 1080)

INFO: Saving game  CURRENT GAME1.sav

INFO: Saving game  CURRENT GAME1.sav

INFO: Loading saved game  mission1.pak

INFO: Saving game  CArthago.sav

INFO: Exiting game

**Comment by crudelios** [comment]
@jobe83 You are not using base Julius, but an old version of Keriew's fork.

Please try downloading the latest build of Julius and see if music works. Note that savegames from Keriew's fork and incompatible with Julius and will crash the game if you try opening them.

Anyway, if music does work, then the issue lies with Keriew's fork and not with base Julius.

If music still does not work, please post `julius-log.txt` from the most recent base Julius again.

**Comment by jobe83** [comment]
I tried both - more then once the base Julius. Sound is there when launching normal C3 and it is gone with the mod.

**Comment by crudelios** [comment]
@jobe83 We recently fixed a problem that was causing the log file to not register an error loading music.

Can you run the most recent build of Julius, open a city and post the log again?

**Comment by bvschaik** [comment]
Also, could you tell us:

- Do you have the MP3s installed for playback?
- Which DLL files are present in the folder where you installed Julius? In particular, does it include `libmpg123-0.dll`?

**Comment by jobe83** [comment]
The libmpg123-0.dll is there. 

I have a folder full of .wavs, not sure which MP3 "installation" you mean. Is that a separate thing from the normal installation?

**Comment by bvschaik** [comment]
The MP3 option is indeed a separate thing. If you had set it up you'd know.

Just to summarize:
- Caesar 3 plays music while on the main menu
- Caesar 3 plays music while in the city
- Julius plays music while on the main menu
- Julius does NOT play music while in the city

Question: could you try [this build](https://bintray.com/bvschaik/julius-branches/windows/music-logging-1.3.1.13-2fff906b#files) and post the `julius-log.txt` again? We added some extra logging to debug this.

**Comment by Shiyarudein** [comment]
Hello, 
I have the same problem with my game. The original game run with sound and the game with an higher resolution also run with no problem. 

I tried with several Julius versions and i have no sound at all. The game works with new options.

I try with your version and i play several minutes.

Here the julius-log.txt:

INFO: Julius version 1.3.1.13-2fff906b

INFO: Initializing SDL

INFO: SDL initialized

INFO: Loading game from working directory

INFO: Config key  gameplay_fix_immigration  1

INFO: Config key  gameplay_fix_100y_ghosts  1

INFO: Config key  gameplay_fix_editor_events  1

INFO: Config key  ui_sidebar_info  1

INFO: Config key  ui_show_intro_video  1

INFO: Config key  ui_smooth_scrolling  1

INFO: Config key  ui_visual_feedback_on_delete  1

INFO: Config key  ui_allow_cycling_temples  1

INFO: Config key  ui_show_water_structure_range  1

INFO: Detected language:  French

INFO: Detected encoding:  1252

INFO: Creating screen 1536 x 864, fullscreen? 1

INFO: Texture created (1536 x 864)

INFO: model loaded

ERROR: SOUND: not initialized

INFO: Window resized to 1536 x 864

INFO: Texture created (1536 x 864)

INFO: System resize to 1536 x 864

INFO: Window 1 shown

INFO: Loading scenario  Caesarea.map

INFO: Loading scenario  Caesarea.map

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Saving game  Mon empire.sav

INFO: Loading saved game  Mon empire.sav

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Exiting game

**Comment by bvschaik** [comment]
@Shiyarudein That seems to be another problem, since you have no sounds at all, please continue the discussion in #363.

**Comment by jobe83** [comment]
> The MP3 option is indeed a separate thing. If you had set it up you'd know.
> 
> Just to summarize:
> 
> * Caesar 3 plays music while on the main menu
> * Caesar 3 plays music while in the city
> * Julius plays music while on the main menu
> * Julius does NOT play music while in the city
> 
> Question: could you try [this build](https://bintray.com/bvschaik/julius-branches/windows/music-logging-1.3.1.13-2fff906b#files), let a city run for a minute and post the `julius-log.txt` again? We added some extra logging to debug this.

I did with same result - no ingame sound!

INFO: Julius version 1.3.1.13-2fff906b

INFO: Initializing SDL

INFO: SDL initialized

INFO: Loading game from working directory

ERROR: 'c3.eng' or 'c3_mm.eng' files not found or too large.

INFO: Loading game from base path C:\Caesar3 music test\

ERROR: 'c3.eng' or 'c3_mm.eng' files not found or too large.

INFO: Loading game from user pref C:\Program Files (x86)\Caesar III

INFO: Config key  gameplay_fix_immigration  1

INFO: Config key  gameplay_fix_100y_ghosts  1

INFO: Config key  ui_sidebar_info  1

INFO: Config key  ui_show_intro_video

INFO: Config key  ui_smooth_scrolling  1

INFO: Config key  ui_visual_feedback_on_delete  1

INFO: Config key  ui_allow_cycling_temples  1

INFO: Detected language:  German

INFO: Detected encoding:  1252

INFO: Creating screen 1920 x 1080, fullscreen? 1

INFO: Texture created (1920 x 1080)

INFO: model loaded

INFO: Loading audio files

INFO: Playing music file 'wavs/setup.wav' at volume 80

INFO: Window resized to 1920 x 1080

INFO: Texture created (1920 x 1080)

INFO: Window 1 shown

INFO: Loading saved game  mission1.pak

INFO: Playing music file 'wavs/ROME1.WAV' at volume 80

INFO: Exiting game

**Comment by bvschaik** [comment]
@jobe83 This is really weird. The logging indicates that the file is there and music started playing correctly 🤔 
Could you perhaps upload `C:\Program Files (x86)\Caesar III\wavs\ROME1.WAV`, so we can check if there's something wrong with that file?

**Comment by jobe83** [comment]
> @jobe83 This is really weird. The logging indicates that the file is there and music started playing correctly 🤔
> Could you perhaps upload `C:\Program Files (x86)\Caesar III\wavs\ROME1.WAV`, so we can check if there's something wrong with that file?

I attached all rome.wavs including rome1.

**Comment by bvschaik** [comment]
Where did you upload the files? I don't see them.
You have to drag the files to this comment box and then leave the links it auto-generates.

**Comment by jobe83** [comment]
I thought I attached a .zip, but github thinks it is a different format for some reason.

https://drive.google.com/open?id=1ZYMgoHwE-BUk0_DVgYYtDrupmElpOUk2

All my rome.wavs are very small, only 4kb. Is that normal?

**Comment by bvschaik** [comment]
> All my rome.wavs are very small, only 4kb. Is that normal?

No, that's not normal. They should be between 11 and 19 MB. That explains why Julius loads them correctly, but you don't hear anything because they only contain less than a second of silence..
The question is: where does Caesar 3 load the wavs from? Are you sure music works using the same C3 installation? Do you need to insert a CD to play?

**Comment by jobe83** [comment]
Mh, it actually asks me now to put in a CD when trying to launch C3 instead of Julius - and I bought it of GOG... meaning I cannot launch c3 now anymore..

**Comment by crudelios** [comment]
@jobe83 That's a mess, I don't understand what's happening there!

Anyway, I would suggest you backup your saved cities (every file with the extension `sav`, optionally also every one with the extension `map`), uninstall C3, reinstall the GOG version and try Julius again.

**Comment by jobe83** [comment]
Okay, will do so (in the evening) and come back to you :)

**Comment by crudelios** [comment]
@jobe83 I guess reinstalling the game fixed your problem?

**Comment by jobe83** [comment]
It did, actually! Thanks a lot for the help and especially the project!

**Comment by crudelios** [comment]
Glad it worked! Have fun playing the game and keep checking for news ;)

**Comment by jobe83** [comment]
Will definitely do - hoping for some exciting stuff :D
