### ISSUE TITLE
Another idea for ExtraInfoPanel: God's Indicator

### ISSUE THREAD

**Issue by ArtySh0ck** [bvschaik/julius#352]
![image](https://user-images.githubusercontent.com/46932541/75264297-e6445d00-57f7-11ea-979f-bb13c57a0fea.png)

Just for explain i did that ugly pic. So:
1. Ceres - Mood is good (golden color of letter)
2. Neptune - Mood is wonderful (golden color of letter, with loving heart)
3. Mercury and Venus - Mood is average (just white color of letter)
4. Mars - Mood is angry (red color of letter, with thunderbolt) 

All of these indicators are just idea, it should be more clear, but we can start to discuss this additional option to extra info panel.

PS: Making it horizontal we can save much space there.
PS2: For cuteness we can ask for help our friend GamerZakh, who is good designer, to help with these drawings.

**Comment by CommonLoon102** [comment]
Since there are two gods starting with the same letter maybe this is not the best. If you click their temples, each god has an icon, maybe those should be used instead. Showing the mood could be done differently, like just printing the text below the icons, that would be the simplest, it it might be too small if we want it to fit.

**Comment by crudelios** [comment]
Regarding new icons: by design, Julius only uses existing assets, so adding new images is no option.

Adding the existing gods' icon may be confusing.

How about just alerting for angry gods?

**Comment by theradeonxt** [comment]
There is the warning message for Gods unhappy which should give the player some time to fix until they get cursed.
If we think about gameplay, normally at the beginning a player may often check gods status, then in mid-game to late game most likely they have oracles and it's rare to need to go and check each one.

**Comment by bvschaik** [comment]
I agree with @theradeonxt here: there's already a message for unhappy gods, and beyond the start of the mission there's not really a need to constantly watch the gods.

When implementing the extra sidebar info, I went through the advisors to see which information would be nice to have constantly in view. Beyond the things we have now, I couldn't come up with more information to add. I've been actually playing the game the past few weeks, and I really like the employment indicator, the ratings are handy to check progress, and I barely used the advisors, apart from setting trade status of resources and dispatching Caesar's requests.
