### ISSUE TITLE
Game not scaling properly on 4k monitor

### ISSUE THREAD

**Issue by RiccardoGiro** [bvschaik/julius#357]
The game runs smoothly on a 4k (3840x2400) Dell laptop. However, there is a scaling problem when playing at this resolution: everything, from the cursor size to the in-game rendered graphics (tiles, buttons, etc.), is incredibly tiny. I don't know why, but even though in my general Windows screen settings the GUI scaling is set to 250%, the game resets everything to the default value of 100%, making it almost unplayable on a 13" screen.

**Comment by crudelios** [comment]
Hi, try running the game with the following command line options:

`--display-scale 2 --cursor-scale 2`

**Comment by RiccardoGiro** [comment]
Thank you for the response. Could you show me the full procedure? Sorry, but I am not an expert on command line prompts

**Comment by crudelios** [comment]
Sure.

The simplest way is for you to create a shortcut to Julius that defines the command line options for you. That way all you have to do in the future is to double-click the shortcut.

To create the shortcut, do the following:

* Right-click the Julius executable
* Select `Create shortcut`
* (Optional): Move the created shortcut to any folder you desire and rename it
* Right-click the shortcut
* Select `Properties`
* In the new window, make sure the `Shortcut` tab is selected. If not, click it.
* In `Target`, add the following code to the end:

        --display-scale 2 --cursor-scale 2

    Make sure to add a space between whatever text was set in `Target` and the added text, otherwise you'll get an error.

* Click `OK`
* Double click the shortcut. The game should now scale to be twice as large.

**Comment by RiccardoGiro** [comment]
Thank you so much. The scaling problem is solved.

**Comment by crudelios** [comment]
Note that there is now a setting on the `Options` menu on the first screen that allows you to set both the screen scaling and mouse scaling, so there's no need to fiddle with command shortcuts anymore.
