### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by gbservantuz** [bvschaik/julius#36]
INFO: Initializing SDL
INFO: SDL initialized
INFO: Loading game from working directory
ERROR: 'c3.eng' or 'c3_mm.eng' files not found or too large.
INFO: Creating screen, fullscreen? 1
INFO: Texture created (1920 x 1080)
ERROR: unable to load main graphics

OS: Ubuntu 18.04

**Comment by bvschaik** [comment]
Yes, julius requires the files from the original C3 game to run. I've just added a notice for that. I'm in the process of writing READMEs for every platform: the game itself is release-ready.
