### ISSUE TITLE
Julius plays no sound at all

### ISSUE THREAD

**Issue by bvschaik** [bvschaik/julius#363]
Hello, 
I have the same problem with my game. The original game run with sound and the game with an higher resolution also run with no problem. 

I tried with several Julius versions and i have no sound at all. The game works with new options.

I try with your version and i play several minutes.

Here the julius-log.txt:

INFO: Julius version 1.3.1.13-2fff906b

INFO: Initializing SDL

INFO: SDL initialized

INFO: Loading game from working directory

INFO: Config key  gameplay_fix_immigration  1

INFO: Config key  gameplay_fix_100y_ghosts  1

INFO: Config key  gameplay_fix_editor_events  1

INFO: Config key  ui_sidebar_info  1

INFO: Config key  ui_show_intro_video  1

INFO: Config key  ui_smooth_scrolling  1

INFO: Config key  ui_visual_feedback_on_delete  1

INFO: Config key  ui_allow_cycling_temples  1

INFO: Config key  ui_show_water_structure_range  1

INFO: Detected language:  French

INFO: Detected encoding:  1252

INFO: Creating screen 1536 x 864, fullscreen? 1

INFO: Texture created (1536 x 864)

INFO: model loaded

ERROR: SOUND: not initialized

INFO: Window resized to 1536 x 864

INFO: Texture created (1536 x 864)

INFO: System resize to 1536 x 864

INFO: Window 1 shown

INFO: Loading scenario  Caesarea.map

INFO: Loading scenario  Caesarea.map

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Determined music track is the same as before, not updating:  1

INFO: Saving game  Mon empire.sav

INFO: Loading saved game  Mon empire.sav

INFO: Determined music track is the same as before, not updating:  1
(...)

INFO: Exiting game

_Originally posted by @Shiyarudein in https://github.com/bvschaik/julius/issues/349#issuecomment-594686218_

**Comment by bvschaik** [comment]
@Shiyarudein From the log: `ERROR: SOUND: not initialized` does not sound very good... I've added more logging at that point. Could you try [this build](https://bintray.com/bvschaik/julius-branches/windows/music-logging-1.3.1.15-79274f96#files) and post the log again? In your case, there's no need to load a city, just starting the game and immediately exiting is enough.

**Comment by Shiyarudein** [comment]
Ok Thanks. 

I have this:
INFO: Julius version 1.3.1.15-79274f96

INFO: Initializing SDL

INFO: SDL initialized

INFO: Loading game from working directory

INFO: Detected language:  French

INFO: Detected encoding:  1252

INFO: Creating screen 1536 x 864, fullscreen? 1

INFO: Texture created (1536 x 864)

INFO: model loaded

ERROR: SOUND: not initialized, reason:  WASAPI can't initialize audio client: 

INFO: SOUND: number of audio devices:  1

INFO: SOUND: audio device:  Haut-parleurs / écouteurs (Realtek Audio)

INFO: Window resized to 1536 x 864

INFO: Texture created (1536 x 864)

INFO: System resize to 1536 x 864

INFO: Window 1 shown

INFO: Exiting game

**Comment by crudelios** [comment]
@Shiyarudein What's your version of Windows?

**Comment by crudelios** [comment]
@bvschaik: Using [`SDL_OpenAudioDevice`](https://wiki.libsdl.org/SDL_OpenAudioDevice), [`SDL_GetAudioDeviceName`](https://wiki.libsdl.org/SDL_GetAudioDeviceName) and [`SDL_GetNumAudioDevices`](https://wiki.libsdl.org/SDL_GetNumAudioDevices) to loop through all available audio devices when the default returns an error may fix this.

**Comment by Shiyarudein** [comment]
@crudelios it is Windows 10

**Comment by bvschaik** [comment]
Changing device does not work here since there's only one. The driver seems to be the problem here.

@Shiyarudein I've added some code to try all drivers one by one when it fails to set up sounds. Could you perhaps try [this new build](https://bintray.com/bvschaik/julius-branches/windows/music-logging-1.3.1.16-497489e4#files) and post the julius-log.txt file again? Even if you do get sound I'd like to see the log. Thanks!

**Comment by Shiyarudein** [comment]
yes it works! I have sound! thanks you! 

INFO: Julius version 1.3.1.16-497489e4

INFO: Initializing SDL

INFO: SDL initialized

INFO: Loading game from working directory

INFO: Config key  gameplay_fix_immigration  1

INFO: Config key  gameplay_fix_100y_ghosts  1

INFO: Config key  gameplay_fix_editor_events  1

INFO: Config key  ui_sidebar_info  1

INFO: Config key  ui_show_intro_video  1

INFO: Config key  ui_smooth_scrolling  1

INFO: Config key  ui_visual_feedback_on_delete  1

INFO: Config key  ui_allow_cycling_temples  1

INFO: Config key  ui_show_water_structure_range  1

INFO: Detected language:  French

INFO: Detected encoding:  1252

INFO: Creating screen 1536 x 864, fullscreen? 1

INFO: Texture created (1536 x 864)

INFO: model loaded

ERROR: Sound failed to initialize using default driver: WASAPI can't initialize audio client: 

INFO: Not using audio driver wasapi, reason: WASAPI can't initialize audio client: 

INFO: Using audio driver: directsound

INFO: Loading audio files

INFO: Playing music file 'wavs/setup.wav' at volume 80

INFO: Window resized to 1536 x 864

INFO: Texture created (1536 x 864)

INFO: System resize to 1536 x 864

INFO: Window 1 shown

INFO: Playing music file 'wavs/ROME1.WAV' at volume 80

INFO: Playing music file 'wavs/ROME1.WAV' at volume 80

INFO: Playing music file 'wavs/ROME1.WAV' at volume 80

INFO: Playing music file 'wavs/setup.wav' at volume 80

INFO: Exiting game

**Comment by bvschaik** [comment]
Great, thanks for responding so quickly! Enjoy your game with sounds 😄

**Comment by Jugarq4** [comment]
"new build" link is broken, can you send working link please?

**Comment by bvschaik** [comment]
That was a debug build specifically for this issue. Please see my other comment.
