### ISSUE TITLE
Apply patch on Linux

### ISSUE THREAD

**Issue by didacusAbella** [bvschaik/julius#367]
How to apply caesar's patch on linux? Thanks

**Comment by bvschaik** [comment]
What exactly do you mean? Do you get the popup message like below when you try to start the game?

![no-patch](https://user-images.githubusercontent.com/104874/76168862-952b5600-6173-11ea-8598-7d47e2df1023.png)

If so, get the patch for your language [here](https://bintray.com/bvschaik/caesar3-patches), and just unzip the file's contents to your Caesar 3 directory.

If you mean something else, please post with more information.

**Comment by didacusAbella** [comment]
I have tried to unzip and replace the files in the caesar 3 directory but the popup message continues to appear.

**Comment by bvschaik** [comment]
Which language are you trying to patch?

**Comment by didacusAbella** [comment]
1. Julius 1.3.1
2. Language: Italian

**Comment by bvschaik** [comment]
Hmm, weird. I just downloaded the Italian patch files, and no message appeared 🤔 

Things to try:
- Could you run Julius from the command line / terminal? When it starts up, it will print debug logging. Could you copy/paste the logging here?
- To which directory did you extract the patch files? If you save a city in the game, does that saved game appear in the same directory?

**Comment by didacusAbella** [comment]
This is the Directory where I extracted the patch files. There is the save file too with name __Partitone__
![directory](https://user-images.githubusercontent.com/11076147/76171469-30c8c080-618c-11ea-88bf-fae928493c81.png)

And this is the logging history after loading the save file

![debug](https://user-images.githubusercontent.com/11076147/76171479-52c24300-618c-11ea-8722-9e48b1caabb1.png)

**Comment by bvschaik** [comment]
Ah, thanks for the screenshot! I see the problem: since files on Linux are case-sensitive, you now have two copies of the patched files.

To solve this: please remove the following files:
- C3.ENG
- c3.eng
- C32.EMP
- c32.emp
- C3_mm.eng
- c3_mm.eng

Then, extract the files from the patch again.

**Comment by didacusAbella** [comment]
Perfect! The message not appear anymore. Thank you so much for your help. I'll close the issue

**Comment by bvschaik** [comment]
Thanks for letting us know. Great to hear, enjoy the game!
