### ISSUE TITLE
Some hotkeys do not work on international keyboards

### ISSUE THREAD

**Issue by crudelios** [bvschaik/julius#37]
First of all, great job for an excellent work! This project is amazing in scope, and the fact that you completed it is just incredible!

Now, on with the bug,

Some hotkeys do not work on international keyboards.

For example, on my keyboard, which is portuguese (pt_PT), the '[' and ']' chars are used by pressing "Alt Gr" (or right alt) + 8 for '[', and 9 for ']'.

This has no effect in julius, while it works fine  on the original Caesar 3.

I am guessing the issue is in `hotkey.c`, and I propose the following fix.

In lines 151 to 166 (function `hotkey_character`), change:

```
if (data.alt_down) {
        switch (c) {
            case 'X': case 'x':
                hotkey_esc();
                break;
            case 'K': case 'k':
                cheat_init_or_invasion();
            case 'C': case 'c':
                cheat_money();
                break;
            case 'V': case 'v':
                cheat_victory();
                break;
        }
        return;
    }
```

To:

```
if (data.alt_down) {
        switch (c) {
            case 'X': case 'x':
                hotkey_esc();
                return;
            case 'K': case 'k':
                cheat_init_or_invasion();
            case 'C': case 'c':
                cheat_money();
                return;
            case 'V': case 'v':
                cheat_victory();
                return;
        }
    }
```

I am not entirely sure this would work as I unfortunately don't have the time to compile the code myself, but I can test it for you if you want. All I need is a windows build.

**Comment by bvschaik** [comment]
I'll only be able to look at it next month. One alternative: you can fork,
fix and create a pull request. This will start an automated AppVeyor build,
from which you can download the windows exe on the artifact page.

**Comment by crudelios** [comment]
I managed to compile the game and unfortunately my proposed fix does not work. I will investigate how SDL handles keystrokes and try to come up with a proper fix.

**Comment by crudelios** [comment]
I've been checking how SDL handles keyboard events and unfortunately it's not trivial to fix the issue, due to the way keyboard modifiers (ctrl, alt, etc) work.

My suggestion would be to add the hotkeys to `Page Up` and `Page Down`, as well as `[` and `]`. Both those keys exist in all keyboards, as far as I can tell, and are currently unused in Caesar 3.

**Comment by bvschaik** [comment]
Ok, thanks for looking into it. I'm going to have a look when I get back.
