### ISSUE TITLE
Move in the city by keeping right mouse button pressed

### ISSUE THREAD

**Issue by devnoname120** [bvschaik/julius#375]
It's common for strategy games to allow you to move through the map just by holding the right mouse button pressed and moving (usually the cursor disappears while doing this).

**Comment by NeoXaero** [comment]
would be an excellent addition

**Comment by fetchinist** [comment]
I want it too! I hope it's possible with the right button or the middle button!

**Comment by devnoname120** [comment]
I've made the changes. If you want to test this feature you can use the development version: https://ci.appveyor.com/api/buildjobs/p839hc782v63wykb/artifacts/julius-1.3.1.89-2114de68-windows.zip

**Comment by fetchinist** [comment]
Thank you! That's what I wanted! And I wish I could choose the scroll direction! (I prefer to do the opposite)

And when I scroll to the end of the screen and then back to the opposite direction, it doesn't scroll immediately, but it stays on the edge for a while, and the screen scrolls. I hope it moves right away!

**Comment by crudelios** [comment]
It's working fine for me as well 😃 

I agree with @fetchinist, I think it would be more intuitive if moving the mouse down would scroll up and vice-versa. Perhaps adding (yet another) option for that wouldn't be a bad idea...

 > And when I scroll to the end of the screen and then back to the opposite direction, it doesn't scroll immediately, but it stays on the edge for a while, and the screen scrolls. I hope it moves right away!

I don't really understand what you mean. Do you mean if you use the old scrolling method or if you scroll to the edge of the map? For me both of these seem to be working fine....

**Comment by fetchinist** [comment]
Sorry about my bad english. I think the meaning was not correct because I was using a translator.

Suppose you're scrolling in the left direction of the screen. As you move your mouse, at some point the screen will reach the left end of the map.

If you hold the mouse button and continue to move the mouse to the left even after the screen reaches the left end, and then move it back to the right, the screen will not scroll for a while and then move to the right.

It feels like the mouse cursor is out on the left side of the screen and back inside the screen.

**Comment by devnoname120** [comment]
I respectfully disagree about the scroll direction. I've just checked and OpenRCT2 uses the same scroll mechanism, and in my experience most strategy games do this as well.

It might be a little more intuitive to 'grab' the screen, but here the cursor disappears and anyway the 'grab' screen paradigm would fail when you reach the border of the window with your cursor.

> If you hold the mouse button and continue to move the mouse to the left even after the screen reaches the left end, and then move it back to the right, the screen will not scroll for a while and then move to the right.

This makes total sense! Going to take a look into this.

**Comment by crudelios** [comment]
> I respectfully disagree about the scroll direction. I've just checked and OpenRCT2 uses the same scroll mechanism, and in my experience most strategy games do this as well.

Fair enough. It already works well, anyway.

**Comment by devnoname120** [comment]
@fetchinist I've fixed the issue. Could you try again with the ZIP from here? https://ci.appveyor.com/project/bvschaik/julius/builds/31966583/job/woe1quehuirw83ul/artifacts

**Comment by fetchinist** [comment]
Good! It works perfectly! Thank you very much.

**Comment by jdmillard** [comment]
(I understand that this issue is closed)

Idea: config option for inverting the direction, where default is the one that matches other games. This will allow those to "grab" the map if they prefer it that way.
