### ISSUE TITLE
Speed keys do not repeat

### ISSUE THREAD

**Issue by ralphcook** [bvschaik/julius#379]
In the original Caesar III, if I press and hold the "[" key, the game speed slows down while the "[" character repeats. In Julius, it seems that the repeat does not occur, I have to press the key repeatedly to get the same effect.

This is not a big deal, just a slight difference in the gameplay.

**Comment by ralphcook** [comment]
Also interesting: on my machine, pageUp and pageDown keys do not repeat either. I'm on Windows 10 Pro, HP Elitebook; they do not repeat by being held down on either the laptop keyboard or an external Logitech keyboard.

**Comment by bvschaik** [comment]
Speed keys now repeat due to the dynamic hotkeys implementation.
