### ISSUE TITLE
When merged houses get vacant, they do so at the wrong location

### ISSUE THREAD

**Issue by crudelios** [bvschaik/julius#38]
When a merged house devolves, it creates vacant lots at the wrong location.

Here is what happens:

![juliusbug1](https://user-images.githubusercontent.com/6518876/50653247-c5300580-0f80-11e9-94c0-6d781d501fff.jpg)

Becomes:

![juliusbug2](https://user-images.githubusercontent.com/6518876/50653251-c9f4b980-0f80-11e9-9a33-2892159ad656.jpg)

As you can see, one of the vacant lots remains where it should be and the remaining three vacant lots get offset by one tile (and the road is destroyed/replaced by vacant lots).

I am attaching a save game that shows the bug. Just let the city run for a little while in julius and you'll see.

Also, I tested this very same file in the original C3 executable and this bug does not happen at all.

[juliushousebug.zip](https://github.com/bvschaik/julius/files/2724784/juliushousebug.zip)

My reasoning for this bug is due to an oversight in function `create_vacant_lot` in file `building\house.c`. In line 72, you have the following code:

`map_building_tiles_add(b->id, b->x + 1, b->y, 1, image_id, TERRAIN_BUILDING);`

But shouldn't that `b->x + 1` just be `b->x`?

As I said in the other issue, unfortunately I have no time to properly compile the game and test it so I can confirm this is the root cause of the bug.

**Comment by bvschaik** [comment]
Good find! I'll fix next month when I have access to my computer again.

**Comment by crudelios** [comment]
I managed to compile the game and the cause of the bug is indeed the `+ 1`. Removing that fixes the problem.

I can fork and create a pull request with the fixed code if you want.
