### ISSUE TITLE
Option to map 'Esc' key to deselect

### ISSUE THREAD

**Issue by gauravsamudra** [bvschaik/julius#382]
Would it be possible to add an option to map 'Esc' key to deselect (currently right click) instead of exit from game confirmation dialog?

**Comment by NeoXaero** [comment]
would be an excellent addition

**Comment by crudelios** [comment]
I agree.

@bvschaik If you agree with this, I'll implement it as a generic function that replaces the huge amout of `if (m->right.went_up || (m->is_touch && m->left.double_click))` that is all over the code due to 
#360 and also adds the `ESC` hotkey.
