### ISSUE TITLE
Travis: macOS-related problem trying to bump SDL to 2.0.12

### ISSUE THREAD

**Issue by crudelios** [bvschaik/julius#386]
I'm trying to update SDL to 2.0.12 in travis. Everything is working except for mac OS, which throws the following error during `make install`:

```
CMake Error at /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/BundleUtilities.cmake:452 (message):
  otool -l failed: 1
  
  /Applications/Xcode-9.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump:
  '@rpath/hidapi.framework/Versions/A/hidapi': No such file or directory
```

It seems SDL 2.0.12 now requires hidapi, at least for mac. However, since I don't use macOS, I don't really know how to fix this.

So, does anyone have any suggestions?

**Comment by bvschaik** [comment]
I've tried it out and encountered the same error. Adding this bit at line 628 of CMakeLists.txt fixes it:
```
    # if SDL2 library is a framework, we need to indicate to CMake
    # the path to its dependencies. SDL2_LIBRARY contains two parts.
    # Example: /Library/Frameworks/SDL2.framework;-framework Cocoa
    # So strip out everything after the ';'
    string(REGEX REPLACE ";.*$" "" SDL2_LIB_DIR "${SDL2_LIBRARY}")
    if(EXISTS "${SDL2_LIB_DIR}/Versions/A/Frameworks")
        set(DIRS "${DIRS};${SDL2_LIB_DIR}/Versions/A/Frameworks")
    endif()
```

I did notice that the cursor's transparent bits are no longer transparent in SDL2.0.12. Is that also the case on other platforms?

**Comment by crudelios** [comment]
> I did notice that the cursor's transparent bits are no longer transparent in SDL2.0.12. Is that also the case on other platforms?

Confirmed in Windows.

**Comment by crudelios** [comment]
I have come up with a fix to the transparency issue by manually converting the image data from string to valid colors instead of using a palette.

It's compatible with previous SDL versions and as a bonus, the conversion should be faster.
