### ISSUE TITLE
Error: 'c3.eng' or 'c3_mm.eng' not found or large || Game pre-init failed

### ISSUE THREAD

**Issue by garganshul108** [bvschaik/julius#387]
Describe the bug, the steps to reproduce, and if possible attach a saved game that show the wrong behavior.

Following the instructions given for [Linux System](https://github.com/bvschaik/julius/blob/master/doc/building_linux.md)
I found this in my terminal after running 
```shell
 ./julius
```

![JuliusError1](https://user-images.githubusercontent.com/45210080/77289554-3bdd2e00-6d00-11ea-935a-f6c0eec8560f.png)

**Comment by garganshul108** [comment]
[treefile.txt](https://github.com/bvschaik/julius/files/4367640/treefile.txt)
This is the tree of the Julius clone directory
Which file/folder do I need to point to?

**Comment by crudelios** [comment]
You need to point to your Caesar 3 installation folder as the game requires the base Caesar 3 assets to run.

**Comment by garganshul108** [comment]
I am actually not able to understand which is my Caesar 3 installation folder. Ia it the folder where I cloned the repository?

**Comment by crudelios** [comment]
No. You need to install the game Caesar 3 in order to be able to use Julius. If you don't have Caesar 3, you can buy it from [Gog.com](https://www.gog.com/game/caesar_3), for example.

**Comment by garganshul108** [comment]
Okay, Thanks.
I have uploaded the game source [here](https://github.com/garganshul108/caesar-III)

**Comment by crudelios** [comment]
@garganshul108 What are you doing???? You can't upload the game like that, it's illegal! Remove it from your github and take out the link, please!

**Comment by bvschaik** [comment]
@garganshul108 Do you want to get us into legal trouble? You've just gained yourself a lifetime ban for contributing to Julius.
