### ISSUE TITLE
Breaking the limits of buildings, walkers and point-to-point routes

### ISSUE THREAD

**Issue by 411752230** [bvschaik/julius#390]
How about an option about this? 

There is a c3 breaker like this.
[c3_limits_alpha2.zip](https://github.com/bvschaik/julius/files/4371276/c3_limits_alpha2.zip)

**Comment by Legionary2** [comment]
Augustus is working on this

**Comment by crudelios** [comment]
Yes, that's a feature for Augustus, not Julius :)

**Comment by Legionary2** [comment]
> How about an option about this?
> 
> There is a c3 breaker like this.
> [c3_limits_alpha2.zip](https://github.com/bvschaik/julius/files/4371276/c3_limits_alpha2.zip)

you can check out the discords to see developments for Augustus as well as Julius through gamerzachs discord

**Comment by 411752230** [comment]
@crudelios @Legionary2 Thanks. I will check it later.

**Comment by bvschaik** [comment]
Increasing building/walker/route limits will cause Julius savegames to crash in Caesar 3, so that is why it won't be implemented in Julius.

Duplicate of #369.
