### ISSUE TITLE
Display workers needed in fountains and missions

### ISSUE THREAD

**Issue by LePatator** [bvschaik/julius#392]
The fountains and the missions consume workers but it is not displayed in their description panel.

I fixed it, now the workers counter is displayed like in the other buildings.
![workers](https://user-images.githubusercontent.com/62617403/77463886-9e205680-6e06-11ea-8f30-8157b7c3ed9e.png)

My fix is on a local branch. If you want i can give it to you, but for now i can't push it to make a pull request (err 403).

**Comment by crudelios** [comment]
I like this, but since fountains and mission posts don't need to spawn citizens, could you get rid of the message "poor access to workers"?

**Comment by LePatator** [comment]
Ok, i removed this messages. I left the one displayed when there is nobody in the city because it still makes sense.
![workers](https://user-images.githubusercontent.com/62617403/77472488-4a1c6e80-6e14-11ea-9935-4d725142d49c.png)

**Comment by crudelios** [comment]
I think you can keep the "too few people alocated by the labor advisor", as it also makes sense to keep :+1:

**Comment by LePatator** [comment]
Ok I did it
![Sans titre](https://user-images.githubusercontent.com/62617403/77532223-b8087a80-6e94-11ea-9bc4-fe9122bfc17d.png)

**Comment by bvschaik** [comment]
Fixed by #396
