### ISSUE TITLE
Message 'city need workers' when building a fort

### ISSUE THREAD

**Issue by LePatator** [bvschaik/julius#393]
As we discussed on discord, i fixed on a local branch this very little bug : 
If you build a fort when your city need workers, a message is displayed saying 'city need workers' which doesn't make sense since a fort doesn't consume workers.

![message](https://user-images.githubusercontent.com/62617403/77535261-9f9b5e80-6e9a-11ea-9b18-77657c8f4d23.png)

So the fix is only to not display this message in this particular case.

![noMessage](https://user-images.githubusercontent.com/62617403/77535336-bd68c380-6e9a-11ea-92eb-f005c03cf3bb.png)

**Comment by bvschaik** [comment]
Hi @LePatator, nice going! To contribute your code, do the following:

1. **Fork** this project to your own Github account
2. Clone the fork to your local computer
3. Apply the code changes and push them to your Github
4. Create a **pull request**

**Comment by LePatator** [comment]
I have a question : the 2 fix i just proposed with the 2 issues i opened could be added in Augustus as well. Is there an automatic process for this ? Or should do the same (fork, branch, pull request) with Augustus code ?

**Comment by bvschaik** [comment]
Keriew normally pulls all Julius changes into Augustus before he creates a release, so nothing needs to be done for that :)
