### ISSUE TITLE
Production facilities don't get source materials

### ISSUE THREAD

**Issue by atolstoy** [bvschaik/julius#4]
I've been playing Caesar III with Julius lately, and first of all I'd like to say big THANK YOU for making it possible to run my favourite game natively on Linux!
However, in a big city I noticed some strange behaviour, which I suspect may be a bug in ther game's mechanics. Here is an example.
I import clay and produce pottery locally. I have one warehouse and several pottery workshops in different part of my city. BUT, cartmen seem to deliver clay only to workshops that are close to warehouse. It leads to a situation when there is enough clay in the warehouse, some workshops also have clay and work fine, but more distant workshops stay useless because they never get clay.
I remember that the original Caesar III didn't have such issue.

It would be great if you fix it!

**Comment by bvschaik** [comment]
Could you attach a saved game so I can take a look?

**Comment by atolstoy** [comment]
After another few hours of playing, I'm not quite sure that the issue is present, because previously I didn't have enough staff at my warehouse - that's why they couldn't deliver clay. I must be sorry ))
Anyway, find my city here:
https://www.dropbox.com/s/hs0hyi1i6p5uw3r/examplecity.sav?dl=0

**Comment by bvschaik** [comment]
No problem, this got me thinking about setting up some automated tests to check saved games against the original game, to ensure the behaviour is the same :)
Nice city you have there. Though I do see some corruption on the empty land on the plateau, something I will have to look into. Do you happen to know when the rocks there were turned into empty land you can't build on?

**Comment by bvschaik** [comment]
Elevation issue on map rotation has been fixed.
I've been running some tests against the original and cannot find any difference in the raw material distribution, so I'm closing this.
