### ISSUE TITLE
Warehousemen not visible in Food Stocks overlay

### ISSUE THREAD

**Issue by Rijk** [bvschaik/julius#413]
Not sure if this is the same in the original game. But it's kind of weird when you see all the cart pushers and market ladies, but not the warehousemen (you just suddenly see food disappearing and reappearing in another granary). Would be nice if there were visible on the overlay as well.

**Comment by bvschaik** [comment]
Caesar 3 also does not show them.
I tried adding support but it's quite tricky to determine when food enters the food supply chain and its corresponding cartpusher should be shown on the overlay: a warehouseman transporting food between warehouses should not show up, for example.

**Comment by bvschaik** [comment]
Since C3 also has this behaviour, I'm closing this issue.
