### ISSUE TITLE
Modularizing extra_info panel to make future additions easier

### ISSUE THREAD

**Issue by bbright024** [bvschaik/julius#423]
Hey all,

First time contributing here, long-time C3 player.  

I'd like to add some extra info to the extra_info sidebar - e.g. salary, tax, maybe throw festival

In order to do that, I think it would help out to standardize some of the y values in`draw_extra_info_panel()` - see https://github.com/bvschaik/julius/pull/422

The more info on the sidebar, the tougher it is to scale with the current design.  Ideally I'd like to add some stuff in the options to let the user control what's shown in the sidebar, but that's further down the line.

Again, first time contributor here; my style's always been to make lots of small changes rather than a single large change, let me know if that's cool.

**Comment by bvschaik** [comment]
First of all, thanks for taking the time to contribute!

> Again, first time contributor here; my style's always been to make lots of small changes rather than a single large change, let me know if that's cool.

I certainly prefer multiple smaller PR's over one very large one, so that's cool.

I was thinking: perhaps we should move the sidebar info code to a separate file? `sidebar.c` is getting quite large already.

**Comment by bbright024** [comment]
>First of all, thanks for taking the time to contribute!

You're welcome!  Thanks for setting all this up; C3 is my favorite game of all-time, so it's an absolute treat to be able to modify it a bit and keep my programming skills sharp while I look for a new paying gig (coronavirus related job loss).

>I was thinking: perhaps we should move the sidebar info code to a separate file? sidebar.c is getting quite large already.

@bvschaik yeah, I was getting that feeling too when I started adding more `#define` values.  I'll make an attempt at splitting it up, been a while since I've worked in C.

**Comment by bbright024** [comment]
Heh, well, I broke out extra_info from sidebar.c in this commit - 

https://github.com/bvschaik/julius/pull/422/commits/45c87fdc71fe04c2df456f80c4affb123acde776

bigger PR than I'd like, but it works and is mainly just renaming variables/structs/whatnot.
i had to introduce a few more globals because of the entanglement between sidebar.c and extra_info.c, but itll be easy to clean them up by adding struct pointers as args to the functions.

let me know how you'd like me to proceed :-)

**Comment by bvschaik** [comment]
> i had to introduce a few more globals because of the entanglement between sidebar.c and extra_info.c

No globals please... Check the PR for my suggestion for reducing the tangle.

**Comment by bbright024** [comment]
awesome, big thank-you for those comments @bvschaik 

on the globals - totally agree; only used them temporarily because i wanted to get confirmation that you're fine with how i was proceeding before committing the time to modifying the function parameters.  

btw, saw on a different issue's comment that you guys have a discord channel, would I be able to get an invite to that 🙂

**Comment by crudelios** [comment]
We have a gitter channel as well which is more developer-focused.

For discord, search on google for "GamerZakh discord" and you'll get there :wink:

**Comment by bvschaik** [comment]
Discord: https://discordapp.com/invite/GamerZakh
I'll add it to the readme later.
