### ISSUE TITLE
once sidebar_filler is complete in issue #423, complete simplification of functions

### ISSUE THREAD

**Issue by bbright024** [bvschaik/julius#425]
request from [bvschaik in this pr](https://github.com/bvschaik/julius/pull/422#discussion_r413654123):

> I'd rather call this sidebar_filler, and use it for drawing both the extra info and the relief images below it.
> The interface can then become much simpler:
> 
>     one function for drawing the collapsed filler, arguments: x, y, width, height
>     one function for drawing the expanded filler, arguments: x, y, width, height
>     one function for handling mouse (the button clicks), arguments: mouse, x, y, width, height
> 

https://github.com/bvschaik/julius/pull/422#discussion_r413654123

**Comment by bvschaik** [comment]
Like I mentioned in a comment, don't create "technical" issues for code improvements, just open a PR so there's only 1 discussion to keep track of. Therefore I'm closing this.
