### ISSUE TITLE
All animations stop while you move the map

### ISSUE THREAD

**Issue by jonathanmcnamee** [bvschaik/julius#426]
As per title. Just checked original c3 and animations continue while panning map

**Comment by crudelios** [comment]
Please be more descriptive of your bug.

Caesar 3 also stops movement while scrolling, and Julius keeps that.

In Julius, if smooth scrolling is active, the animations don't stop on the latest revisions of Julius. Which version of Julius did you use? 1.3.1 had this problem but it has been fixed meanwhile. Try using the latest version.

Also, I'm assuming you have enabled smooth scrolling.

**Comment by jonathanmcnamee** [comment]
Hi José,

Was using v1.3.1 official, animation stopped for about a second after you
moved even with smooth animation on.

I've switched to latest nightly build and this is now fixed.

Really appreciate the work you and others have done on this :)

Thanks

J

**Comment by bvschaik** [comment]
Thanks for checking, glad it was already solved.
