### ISSUE TITLE
Use system libpng if available

### ISSUE THREAD

**Issue by jetomit** [bvschaik/julius#432]
Hi,

I have a [small patch](https://github.com/jetomit/julius/commit/2d7785f9cccb0455cc1267f8ecdd4490b0b0c9c5) to use the system libpng where available. This is mainly to make it easier to package julius for distros. The Switch and Vita platforms apparently also provide libpng.

I successfully built the modified version for Linux, Switch and Vita, and tested on Linux. If it’s OK, I’d like to submit a PR, otherwise please let me know if there’s anything I could improve.

Thanks!

**Comment by crudelios** [comment]
Hummm. I'm undecided about this. While this will reduce build times for Linux/Switch/Vita, this also adds an extra outside dependency which we are trying to avoid.

**Comment by jetomit** [comment]
It’s optional – if libpng is not found on the system, it will use the bundled copy.

**Comment by crudelios** [comment]
During compilation, yes. The problem is if Julius is compiled expecting a library then run on a system without it.

This may very well happen as we deploy a Linux binary using bintray.

**Comment by jetomit** [comment]
I see. What about adding a cmake option to compile with system png (or, more generally, system libs where they are found)? Otherwise I’ll just unbundle it in the package script.

In any case, thanks for the feedback!

**Comment by crudelios** [comment]
That's certainly possible, but I'm curious, why do you want to do that?

I know that it's generally preferred to use system libraries as they can be updated and reused, but we have trimmed our own implementation of libpng to be as less intrusive as possible.

**Comment by jetomit** [comment]
> I know that it's generally preferred to use system libraries as they can be updated and reused

Pretty much this. I want to update the [package for Guix](http://guix.gnu.org/packages/julius-1.3.0/), where system libraries are preferred. Many other distros have a similar policy, including [Debian](https://www.debian.org/doc/debian-policy/ch-source.html#s-embeddedfiles) and [Fedora](https://fedoraproject.org/wiki/Bundled_Libraries?rd=Packaging:Bundled_Libraries).

I know that bundling dependencies makes it much easier to distribute the game outside distro channels, especially since Julius supports many different platforms. It's not a critical package, and potential security issues are very limited even if a vulnerability is found in libpng in the future, so it’s really more of a policy issue.

I think that adding a cmake option is a good compromise, but it does introduce some complexity to the build process. Since there might be additional dependencies in the future, I’d go with a single option such as `USE_SYSTEM_LIBS`. If that is OK with you, I can try putting together a new patch. Otherwise I’ll just replace the bundled libs in the package script.

**Comment by crudelios** [comment]
I think adding an option to cmake is a good compromise. However, wait for @bvschaik's opinion before you delve into it!

**Comment by bvschaik** [comment]
An option for cmake would be nice: I understand the need to use system libs where possible for Linux distros, but we want to make sure never to use system libraries for Mac and Windows.
Perhaps make it use the system libs by default (if available), and pass a `static-libs` option to force the internal libraries?

**Comment by jetomit** [comment]
I agree with making this the default, though I’d rather name the option `SYSTEM_LIBS` to prevent confusion with static linking. I’ll submit a PR and we can discuss further specifics there. Thank you both!

**Comment by bvschaik** [comment]
Thank you! PR has been merged so I'm closing the issue.
