### ISSUE TITLE
Few text overlaps with the French language pack

### ISSUE THREAD

**Issue by constant-current** [bvschaik/julius#437]
Here are few graphical bugs I've found. I'm not sure if they were into the original game as the exe was deleted years ago since it was locked to run only on some Packard Bell prebuild.
Some may be compromises with other languages, I don't know. Tested with yesterday's build and the stable 1.3.1 one.

![julius-glitch-difficulty](https://user-images.githubusercontent.com/64451925/81037669-e0c45c80-8ea3-11ea-85ab-21a20e525eee.jpg) 
Difficulty settings menu

![julius-glitch-mercury](https://user-images.githubusercontent.com/64451925/81037773-2c770600-8ea4-11ea-924e-adbf12231dc7.jpg) 
Right click on Mercury temple

![julius-glitch-granary](https://user-images.githubusercontent.com/64451925/81037814-4dd7f200-8ea4-11ea-9d5e-d424e72adb66.jpg)
Setting "get the food" and emptying a granary

![julius-glitch-legionformation](https://user-images.githubusercontent.com/64451925/81037825-5c260e00-8ea4-11ea-99d4-5febebb03e14.jpg)
setting the first or second troop formation

![julius-glitch-warehouse](https://user-images.githubusercontent.com/64451925/81037832-60522b80-8ea4-11ea-9b47-151821865c7e.jpg)
Right click on a warehouse

![julius-glitch-warehouse-special](https://user-images.githubusercontent.com/64451925/81037839-647e4900-8ea4-11ea-842f-5a7deb77f988.jpg)
warehouse special order "get the goods"

![julius-glitch-marketdeliverykid](https://user-images.githubusercontent.com/64451925/81037862-73fd9200-8ea4-11ea-8b3e-4f68420a307b.jpg)
Right click on an angry market delivery kid

![julius-glitch-carrier](https://user-images.githubusercontent.com/64451925/81037870-7a8c0980-8ea4-11ea-8a6c-eeb314d7e9e1.jpg)
Right click on a carrier when gods are furious

![julius-glitch-worldmap](https://user-images.githubusercontent.com/64451925/81037944-b8892d80-8ea4-11ea-8b8b-3b64499d6ebb.jpg)
The new boat/wagon icon overlaps with the opening trade text in the world map

![julius-glitch-missionvictory](https://user-images.githubusercontent.com/64451925/81037947-bcb54b00-8ea4-11ea-9482-67ccb4d6adee.jpg)
Any victory screen in the campaign

![julius-glitch-festivalpopup](https://user-images.githubusercontent.com/64451925/81037961-c9d23a00-8ea4-11ea-9e11-96aa3382b57c.jpg)
Most event popups when the name is unchanged to "new governor".

![julius-glitch-commerce](https://user-images.githubusercontent.com/64451925/81037995-dfdffa80-8ea4-11ea-98c4-01b4e2f726b9.jpg)
In the Commerce advisor screen, export amounts are overlapping the text

![julius-glitch-festival-advisor](https://user-images.githubusercontent.com/64451925/81038011-ea01f900-8ea4-11ea-9e5a-77f514d4eee2.jpg)
several months after the last festival, also cells are a bit crowded up here.

![julius-glitch-hygiene-advisor](https://user-images.githubusercontent.com/64451925/81038015-ee2e1680-8ea4-11ea-953f-abf4184b3b55.jpg)
when the population coverage of some sanitary building is not available

![julius-glitch-cityadvisor](https://user-images.githubusercontent.com/64451925/81038023-f5552480-8ea4-11ea-92f2-55c2a7aafb08.jpg)
some texts in the city advisor, it also occurs on hygiene line but it's a bit less than this food one.

**Comment by crudelios** [comment]
Thanks for the report.

I hereby crown the french language as the new champion of verbosity! :trophy:

**Comment by bvschaik** [comment]
Thanks for the detailed report. I'll have a look, but keep in mind that we have 11 languages to support, and the game should run with a resolution of 640x480 so not everywhere boxes can be increased in size. In some cases it will not be possible to fix it.

**Comment by constant-current** [comment]
>  In some cases it will not be possible to fix it.

Of course I fully expect unfixables due to concessions, especially with columns.
Also I strongly suspect that at least the "get the food" or the city advisor lines were already overlapping in the original game.

**Comment by constant-current** [comment]
I checked the changes, that looks great!
I've also discovered new bugs or new occurrences:

![julius-glitch-carrier2](https://user-images.githubusercontent.com/64451925/81261897-308a5b80-903d-11ea-88a4-9cdc01dbcc8d.jpg)
a very happy carrier or docker.

![julius-glitch-engineer](https://user-images.githubusercontent.com/64451925/81262163-95de4c80-903d-11ea-9645-096d24a1e087.jpg)
a very bored engineer.

![julius-glitch-emperor-gift](https://user-images.githubusercontent.com/64451925/81262756-b5c24000-903e-11ea-8caa-70da62ebe1b1.jpg)
when wanting to give the best gift to the emperor

![julius-glitch-city-gift](https://user-images.githubusercontent.com/64451925/81262866-e6a27500-903e-11ea-99c7-86f8906f9e7e.jpg)
when donating money to the city. The text before the arrows is partially hidden.

**Comment by bvschaik** [comment]
Talking citizens: it's not possible to do much there. I've given the text a little more space in the next commit, so more will fit on one line, but other than that there's no solution. The bottom "empty" bit has text when you right-click on something other than road, and those texts can also be pretty long.

I'll have a look at the other texts.

**Comment by constant-current** [comment]
> I've given the text a little more space in the next commit, so more will fit on one line, but other than that there's no solution.

This solves the angry kid and the bored engineer lines. Thanks, that's already good :)

For the happy cartpusher, it's quite close. 
![julius-glitch-cartpusher](https://user-images.githubusercontent.com/64451925/81283552-20827400-905d-11ea-997a-eaf0ea23fcd6.jpg)
but this text is desperately too long, the best-looking I was able to make with Gimp is this:
![julius-glitch-cartpusher2](https://user-images.githubusercontent.com/64451925/81291303-d2c03880-9069-11ea-9f22-67e94d625648.jpg)
Even with such a crude cheat to shoehorn the word "de " on the second line and to allow the third line to overlap on the right, the ending question mark (it's a typo, it should be an exclamation point) and the final quote mark don't properly fit.

**Comment by bvschaik** [comment]
I compared the text to the English one: the French text is about twice as long... no wonder it doesn't fit. I can't do anything without making it look bad in other languages.
```
Pushing carts all day long is hardly fun, but living here makes it worthwhile.
Pousser des charrettes à longueur de journée n'est pas vraiment passionnant, mais le fait de vivre dans une si belle cité compense largement !
```
More fixes for the other places are incoming.

**Comment by crudelios** [comment]
> I compared the text to the English one: the French text is about twice as long... no wonder it doesn't fit.

It's not just french that is more verbose, the translator decided to go to China and back to say more or less the same thing.

**Comment by bvschaik** [comment]
> Maybe you can reduce the actual text in your translated files while keeping the meaning? Granted it wouldn't match the dialogue, but then again there already are some discrepancies.

I'd rather not: derivative works and copyright etc. Plus I'm not going to make such a call for a language I don't know well enough.

I just pushed the last of the changes.

**Comment by constant-current** [comment]
> I can't do anything without making it look bad in other languages.

That's what I thought, technical limitations and concessions. Thanks for the try at least.

> I'd rather not: derivative works and copyright etc.

That's the main reason why I didn't propose any correction or rewording work.

> It's not just french that is more verbose, the translator decided to go to China and back to say more or less the same thing.

Exactly. It's the so-called "adaptation". They obviously didn't respect the space constraint.
I guess voice actors also rephrased the translation. It's common in the European French/Belgian dubbing scene to not respect the original material, to the point where sometimes it leads to improvisations that completely reverse the meaning (without being a censorship or a parody). The teenage me quickly realized that French subtitles were often more accurate.

All in all, most is already fixed, it even might be cleaner than the original game I vaguely recall so that's more than I expected.

**Comment by bvschaik** [comment]
:+1: Thanks for checking.

Since most of the issues have been fixed, and the remaining ones cannot be fixed, I'm closing the issue. If you find any more problems, just open a new one 😃
