### ISSUE TITLE
broken export amount arrows

### ISSUE THREAD

**Issue by constant-current** [bvschaik/julius#440]
In the trade advisor screen, when clicking on a good to change the amount of the kept quantity before exporting surplus, the value change correctly but it also set the good to no export as if the arrows and the underneath button are on the same detection layer.

This is a regression which apparently started with the 1.3.1-20200504-9cca52f build. It's not on 1.3.1-20200504-a0d6cc2 and the previous 20200430 builds.
Tested on Debian Buster with Appimage builds.

**Comment by bvschaik** [comment]
Nice one. Thanks for checking where this was introduced!
