### ISSUE TITLE
Where is the .exe?

### ISSUE THREAD

**Issue by Renovatio211** [bvschaik/julius#441]
I can't find any .exe in my extracted files.

**Comment by bvschaik** [comment]
What did you download? Assuming you use Windows, the correct file to use is "julius-1.3.1-windows.zip" on the [releases page](https://github.com/bvschaik/julius/releases/tag/v1.3.1)

**Comment by Renovatio211** [comment]
Ah i downloaded the master assuming it was just the "best" version..

**Comment by bvschaik** [comment]
Ah, then you downloaded the source of the game, not the .exe.
The link I gave is the latest stable release, if you'd like to try the latest and greatest, you can try the "Latest build (may be unstable)" download option from the [homepage](https://github.com/bvschaik/julius#julius-).
