### ISSUE TITLE
CD request while loading game

### ISSUE THREAD

**Issue by giggietto** [bvschaik/julius#442]
Hi, 
I have caesar 3 with its CD ROM installed on my desktop.  If I want to play I need to insert CD.  With Julius release I can fix this problem? How? 
Thanks!!

**Comment by crudelios** [comment]
If you copy all the files (`julius.exe`, `SDL.dll`, `SDL_mixer.dll` and `libmpg123.dll`) to the same folder of the Caesar 3 installation, you can then run `julius.exe` without the CD. Give it a try :wink:

**Comment by giggietto** [comment]
Thanks,  Julius contain also the famous patch 1.0.1 changes?  Thanks

**Comment by bvschaik** [comment]
Yes, it does. If Julius complains that the patch is not installed, follow the instructions [here](https://github.com/bvschaik/julius/wiki/Patches) to install it.

**Comment by giggietto** [comment]
I have installed the English patch for 64 bit and manually replaced the files to get the Italian language.  I have also the Italian version without patch and with 32 bit crack, that work standalone in my external HDD ....

**Comment by giggietto** [comment]
And after Julius if I want using Augustus what procedure should I follow..  Thanks so much!!

**Comment by crudelios** [comment]
You don't need any crack to run Julius or Augustus, and you don't need to add Julius to play Augustus. You just get Augustus instead of Julius and run it.

**Comment by giggietto** [comment]
> If you copy all the files (`julius.exe`, `SDL.dll`, `SDL_mixer.dll` and `libmpg123.dll`) to the same folder of the Caesar 3 installation, you can then run `julius.exe` without the CD. Give it a try 😉

Work!! Thanks

**Comment by bvschaik** [comment]
Good to hear, enjoy!
