### ISSUE TITLE
Psvita : unrecoverable game freeze when using the ps button (or the sleep button)

### ISSUE THREAD

**Issue by Samsoulee** [bvschaik/julius#443]
Hi, I'm having a problem on psvita each time I play the game :
The game works fine but everytime I push the ps button (the one that brings you to the psvita home screen) and then come back to the game (even instantly) the game sound shuts down and the game freezes up, and I have to close it.
It does the same with the power ( = sleep) button .
Any idea why ? 
For info, I use an SD2VITA with no issue whatsoever.

**Comment by crudelios** [comment]
This is likely an issue with SDL and not something we can fix ourselves, but I don't know nearly enough about PSVita to be sure.

Anyway, @devnoname120 may have a better idea.

**Comment by Samsoulee** [comment]
Did I post this issue in the wrong place ? (sorry i'm old)

**Comment by crudelios** [comment]
> Did I post this issue in the wrong place ?

You didn't. This may very well be an issue with Julius, it needs investigating and I don't know enough about Vita to confirm my suspicions about SDL being the culprit.

**Comment by devnoname120** [comment]
@Samsoulee which plugin do you use for SD2Vita? I suggest using https://github.com/xyzz/gamecard-microsd/releases/latest

**Comment by Samsoulee** [comment]
Hello, I Updated the plugin to that 1.6 version and still the same problem
... *sad face*
(^__^)


Manu.


Le mar. 12 mai 2020 à 23:28, devnoname120 <notifications@github.com> a
écrit :

**Comment by Samsoulee** [comment]
Do you think this could be related to henkaku enso ? or the sd2vita card itself ? 
i'm surprise to be the only one to have this probelm ...

**Comment by theradeonxt** [comment]
I have no experiece for Ps Vita, but does the same sleep scenario cause problems for Windows or Linux?
I assume it's a SDL + platform combination which makes this happen,

**Comment by bvschaik** [comment]
> does the same sleep scenario cause problems for Windows or Linux?

No, it doesn't because window handling is totally different on those platforms. I also suspect something with the way Vita handles things.

Unfortunately both crudelios and myself are not familiar with the Vita at all, and do not have access to a physical Vita to test things, so it's impossible to debug from our end. Vita support was built by @devnoname120, maybe he can suggest something?

**Comment by crudelios** [comment]
> Unfortunately both crudelios and myself are not familiar with the Vita at all, and do not have access to a physical Vita to test things

I'm getting a Vita to test this (they're cheap enough nowadays), so maybe I'll have an answer next week.

**Comment by Samsoulee** [comment]
Wow, thanks man, that's dedication ! and welcom to the psvita family :)
Plenty of good games here 👍

**Comment by crudelios** [comment]
@Samsoulee: 

> Wow, thanks man, that's dedication ! and welcom to the psvita family :)

Thanks, looking forward to playing Persona 4 Golden 😃 

Anyway, so I got the Vita (1000) and installed Julius.

Regarding your issue, I found that in my case, when I click on the PS button or the power button, the game does not crash but the music does indeed stop and not resume unless I go to the sound settings and manually restart it.

I'm not using an SD2Vita (yet), but I'm also running Henkaku Enso on 3.60 firmware. Also I'm not using reF00D, but 0syscall6.

**Comment by Samsoulee** [comment]
Tested without ref00d, same problem : When i press the psbutton (or sleep button) the ingame sound stops, then a little while after that, the game freezes. It doesn't make my console crash but the game is totally frozen. 
Ps : the sd2vita is mandatory for every psvita owner believe me ;-) (especially if you want to travel with your 50 psvita games + your 50 psp games )

**Comment by crudelios** [comment]
I've ordered an sd2vita to see if that may be the cause.

Honestly while I can probably make the game restart the music if it stop, there's not much more I can do.

By the way, which version of Julius are you running? It should appear on the lower left corner of the main menu.

**Comment by Samsoulee** [comment]
the last one : 1.4
The weird thing is that no other App or game has this problem.


Le ven. 29 mai 2020 à 13:00, José Cadete <notifications@github.com> a
écrit :

**Comment by crudelios** [comment]
Please do an experiment: turn all the audio off in the sound settings (open a city and then on the top menu go to Options -> Sound Settings, set everything to Off (not 0% volume, actually off), click OK, then see if the problem persists.

**Comment by crudelios** [comment]
I finally managed to reproduce the bug. Turns out the game only freezes if you have the wav music files playing, but not the mp3 (which stop the music but the game keeps going).

So, for now there are two workarounds:

1. Use the mp3 files for the music instead ofbthe wavs. Check [MP3-Support](https://github.com/bvschaik/julius/wiki/MP3-Support) for instructions. The mp3 files are of much better quality anyway, so this is definitely recommended. The music will still stop when you resume the game, but at least it won't freeze and the rest of the audio will keep working; or
2. Before going to sleep or to the home screen, disable all the audio as I mentioned in the above post. I tested that and it works just fine.

**Comment by Samsoulee** [comment]
Ho yes ! It works fine without the music, I'm going to test with mp3s asap !
Nice !!

I finally managed to reproduce the bug. Turns out the game only freezes if
> you have the wav music files playing, but not the mp3 (which stop the music
> but the game keeps going).
>

**Comment by bvschaik** [comment]
@Samsoulee Could you try [this version](https://bintray.com/bvschaik/julius-branches/vita/pause-music-when-window-hidden-1.4.0.26-e6a02ca#files) and see if it improves things? I've made a change that pauses the music when the window is hidden, and resumes it when it's shown again. I hope that also covers the case with sleeping/going to home on Vita.

**Comment by Samsoulee** [comment]
Hi, this version doesn't solve the problem with the wav version. - same problem.
With The mp3 files installed, the music cuts, but I can restart the music afterward + no freezes. 


> 
> @Samsoulee Could you try [this version](https://bintray.com/bvschaik/julius-branches/vita/pause-music-when-window-hidden-1.4.0.27-03a42ea#files) and see if it improves things? I've made a change that pauses the music when the window is hidden, and resumes it when it's shown again. I hope that also covers the case with sleeping/going to home on Vita.
> If it doesn't fix the music automatically restarting, could you post the `julius-log.txt` file that is written to the C3 directory?

**Comment by bvschaik** [comment]
Could you post julius-log.txt? I have added extra logging there.

**Comment by Samsoulee** [comment]
[julius-log.txt](https://github.com/bvschaik/julius/files/4706260/julius-log.txt)

**Comment by crudelios** [comment]
@Samsoulee:

Can you please try [this version](https://drive.google.com/file/d/1nt6BJMyPmx52zBIyMl7mDq3WkVZD_oVG/view?usp=sharing)?

It should stop the crashes.

However, since it loads the entire music into memory, it should be really slow when opening a music. At least it is, when using an official PSVita memory card. I haven't yet got my sd2vita to test.

Can you test the speed loading the music using the sd2vita?

**Comment by Samsoulee** [comment]
> 
> 
> @Samsoulee:
> 
> Can you please try [this version](https://drive.google.com/file/d/1nt6BJMyPmx52zBIyMl7mDq3WkVZD_oVG/view?usp=sharing)?
> 
> It should stop the crashes.
> 
> However, since it loads the entire music into memory, it should be really slow when opening a music. At least it is, when using an official PSVita memory card. I haven't yet got my sd2vita to test.
> 
> Can you test the speed loading the music using the sd2vita?

It says access denied for this google drive ....

**Comment by crudelios** [comment]
@Samsoulee:

[Try this one](http://public.josecadete.net/julius.vpk), then. This is an updated build that should be much faster loading the music, especially if it's an mp3.

It's working fine for me now, so hopefully it will work well for you too.

**Comment by Samsoulee** [comment]
yes, it seems to be working fine 👍👍
nice work !
