### ISSUE TITLE
"Mute music" button in main menu?

### ISSUE THREAD

**Issue by ArtySh0ck** [bvschaik/julius#447]
I LOVE Caesar's III in-game soundtracks and play with listening to them, BUT... sometimes i need to run C3 to check something in main menu, and often im listening my youtube playlists, and... you know how it works when to songs playing in one moment, and i cant mute c3 music while main menu, i need to load some map, go to options and mute it there, or i need to pause my playlist... horrible things )

Maybe some "Mute music" button in Main Menu please? THANKS!

**Comment by crudelios** [comment]
How about a `--no-audio` command line instead?

**Comment by ArtySh0ck** [comment]
this way almost the same as load map and turn music off, cause, sometimes we need to add this command line to shortcut or run command, and sometimes we need to erase this command line. too hardly to switch. i thought it is maybe as one little button in some corner of main menu.

**Comment by crudelios** [comment]
I honestly don't think we should be crowding the main menu with all these buttons, big or small.

What I think that could be done is to integrate the in-game options menu with the Julius configuration options. That way the audio options would be accessible from the main menu.

**Comment by bvschaik** [comment]
I agree with crudelios: the main menu is crowded already, compared to Caesar 3, so we won't be adding any more buttons. Besides, we only add functionality that will benefit a large percentage of users, and I don't think this is one that many people will use.
