### ISSUE TITLE
How about to clone Language Option from Settings to Main Menu?

### ISSUE THREAD

**Issue by ArtySh0ck** [bvschaik/julius#448]
How do you thing, would it be efficient if Main Menu have a same option of Change Language as Settings Menu has? By my opinion it would be cool, cause some of my people are too bad in English (even worse than me, can u imagine? xD ) and when they install Julius 1.4.0 with russian language pack im afraid they will have some problems to switch language of game... cause its too difficult to click Settings button, u know... i do not justify them, but maybe it make sense...

**Comment by crudelios** [comment]
I can undrrstand that, but the truth is the main menu is becoming overcrowded with buttons already!

Also, since they need to follow instructions to add the language pack, it's just a matter of telling users where to go to change the language.

**Comment by ArtySh0ck** [comment]
as an option, maybe this setting in main menu can be located in some corner... or this idea is really bad

**Comment by bvschaik** [comment]
Like I mentioned in your other issue: the main menu is too full of buttons so we won't be adding more. Also, detecting languages is a pretty time-consuming operation, something I don't want to do on the main menu.
