### ISSUE TITLE
Autosave filename in the used language

### ISSUE THREAD

**Issue by TheRealAyCe** [bvschaik/julius#450]
I would expect the autosaves "Architect", "Citizen", etc. to be named "Architekt", "Bürger", etc. in the german version. I just checked, and c3.exe saves them with the german names, Julius always uses english. Is this intended or just an oversight?

**Comment by bvschaik** [comment]
Hmm, interesting. The file names used for the autosaves are hardcoded into the executable, also for the original Caesar 3 versions. Apparently the German version also changed those names; I never knew that those were translated as well.

Theoretically we could use the player's rank and add `.sav`, but we have a problem with the different encodings we need to support: for Traditional Chinese we need a mapping from in-game character to UTF-8. Once that has been added, we can localize the autosave names.

**Comment by constant-current** [comment]
> I just checked, and c3.exe saves them with the german names

Same with French but I didn't mind to report because I don't like this naming scheme at the first place as it's not intuitive so I systematically rename my manual saves. But I see the annoyance if you autosave.

@bvschaik  Can the saving names be more intuitive (something like 03-Engineer-Capua-auto-0001.sav) or is it too problematic for retro-compatibility? Sorry if this was already asked before.

**Comment by TheRealAyCe** [comment]
I agree with @constant-current, I never liked that naming schema too. The proposed one is great imo. :D I also like the idea of having certain non-vanilla fixes/improvements switchable in the options, so maybe the savegame naming schema could be toggled between "legacy" (as it is now, maybe including the translation fix) and "structured" (the save name tells you the mission number and city name - maybe even use this as the default name (0001, 0002,...) for manual saves too?).

**Comment by constant-current** [comment]
> The proposed one is great imo. :D

It's just a crude example. Also this might be more suited to Augustus, that's why it's a question rather than a suggestion. ;-)

**Comment by crudelios** [comment]
Autosaves can definitely be improved, our original problem was that the game didn't support displaying more than 200 files, but now that's been fixed.

The only problem now is file clutter if there are too many autosaves...

**Comment by TheRealAyCe** [comment]
> 
> 
> > The proposed one is great imo. :D
> 
> It's just a crude example. Also this might be more suited to Augustus, that's why it's a question rather than a suggestion. ;-)

Well, I'd like it even more if the game groups savefiles by their "origin", either flat or in a tree. That way you always know which savegame is the most recent for mission X, while still allowing you to start playing another mission. But that might be too complex for too little gain.

Where can I get Augustus?

**Comment by crudelios** [comment]
@TheRealAyCe 

> Where can I get Augustus?

[Here](https://github.com/Keriew/julius) :wink:
