### ISSUE TITLE
Original, but, remastered Main Menu? (for future...)

### ISSUE THREAD

**Issue by ArtySh0ck** [bvschaik/julius#451]
![image](https://user-images.githubusercontent.com/46932541/81943694-5ea30900-9604-11ea-8640-86f98ddde2d1.png)

Do you like it? That black "padding" around menu is so sexy when you play it 1920x1080 for example...

Why cant we resize (with quality ofcrs) that background image and do it autoresizable in depending of user's screen resolution? and then, we can do these button, or, larger (if we need), or re-arrange their position... for example. And number of Julius version can be resized for more but its still too invisible (who needs can see it, but NOW its too small i think...).
With new MENU, i believe, we can do a Caesar 3 even MORE affable to, even, NOVICES of a game, and for every player. Just imagine! All these buttons are there, but, in some another place maybe imaged shortcuts with, i dont now, LAST PLAYED MAP? or clickable button to "Go to Julius devs site", what if someone wanna update his Julius but he dont know about github? with link it will be easier. AND SO! There can be a field with a "Name of Emperor (player)", to change it if player needs, or just to see his name and proud of it. You must accept, all of us we love C3's menu (nostalgia), but today its too OLD and very inefficient. But, to save nostalgia factor, we dont need to make a new menu, we just can do a REMASTER of current main menu. I guarantee, when (if) works on that will be started you'll get a TONS of ideas to do it better, nicer and more "today".

And, if u found this interesting one, it can be done in last of all, its not so critical, but its too worthy to be. Thanks!

**Comment by crudelios** [comment]
This is better suited for Augustus, not Julius. In fact, given enough time (think years) and developer dedication, Augustus' user interface may get a revamp.

From a technical standpoint, it's not so easy to implement those ideas. Julius does not have any sort of image scaling, and loading custom images is not supported (it's planned for Augustus though). Allowing images to scale would require a big rewrite of all the drawing code, which is a big undertake to say the least.

**Comment by NeoXaero** [comment]
I've been trying to make Keriew do a new main menu revamp, and he doesn't seem to have that on his plans right now, i've even volunteered to design the new UI, and i got a big NO, so yeah.

We'll have to wait.

**Comment by bvschaik** [comment]
> Why cant we resize (with quality ofcrs) that background image and do it autoresizable in depending of user's screen resolution?

We have to work with the images and texts we have available. Resizing the background can be done but will become pixelated, I don't think this is what we want:

![main_menu_scaled](https://user-images.githubusercontent.com/104874/82138673-8a9bd580-9822-11ea-8934-6a99e801e4f3.png)

> and then, we can do these button, or, larger (if we need), or re-arrange their position... for example. And number of Julius version can be resized for more but its still too invisible (who needs can see it, but NOW its too small i think...).

All the letters are images: we can't do bigger letters, or bigger buttons for that matter.

> All these buttons are there, but, in some another place maybe imaged shortcuts with, i dont now, LAST PLAYED MAP? or clickable button to "Go to Julius devs site"

We have to work with the texts that are provided by C3. I made an exception for the configuration menu since that's in a whole extra screen, but I'm not going to mix original C3 texts with Julius texts in one menu.

> You must accept, all of us we love C3's menu (nostalgia), but today its too OLD and very inefficient. But, to save nostalgia factor, we dont need to make a new menu, we just can do a REMASTER of current main menu. I guarantee, when (if) works on that will be started you'll get a TONS of ideas to do it better, nicer and more "today".

What Julius attempts to do is recreate Caesar 3, including its nostalgia, even though it's old. A remastered main menu belongs in forks like Augustus, not in Julius.
