### ISSUE TITLE
Strange bug with Reservoir

### ISSUE THREAD

**Issue by ArtySh0ck** [bvschaik/julius#452]
It's second mission.

![image](https://user-images.githubusercontent.com/46932541/81954876-11c62f00-9612-11ea-94ae-018ddedb076e.png)

1. Take a look to these TWO fountains. Now i will try to build reservoir using Julius Water Highlight.

![image](https://user-images.githubusercontent.com/46932541/81955044-4a660880-9612-11ea-8a1e-b25841936724.png)

2. You can see those two fountains covered by this blue area. (and take attention to several empty (not blue) inside blue area, near to new reservoir). Now we built it.

![image](https://user-images.githubusercontent.com/46932541/81955296-93b65800-9612-11ea-9ad0-ba1c1f5c46b6.png)
![image](https://user-images.githubusercontent.com/46932541/81955357-a6309180-9612-11ea-9e66-9066cc386d58.png)

3. As you can see one of those fountains get water, another one didnt. And when we enable water-layer we can see pumps of that reservoir cant be so far to second fountain.

**Comment by ArtySh0ck** [comment]
BUT i try it in another map, and there its good!

![image](https://user-images.githubusercontent.com/46932541/81955786-3373e600-9613-11ea-9b24-b568681ae801.png)
![image](https://user-images.githubusercontent.com/46932541/81955918-5c947680-9613-11ea-8eca-9ddcda1f9bee.png)

**Comment by ArtySh0ck** [comment]
NEW thing. These "empty highlight holes" depends on how we rotate map in 2nd mission

![image](https://user-images.githubusercontent.com/46932541/81956504-0ecc3e00-9614-11ea-9f23-08bed62b9cf0.png)

**Comment by crudelios** [comment]
Confirmed. Must have something to do with the map size. Thanks for the report!

**Comment by ArtySh0ck** [comment]
you have so low resolution, u play with tablet?

**Comment by crudelios** [comment]
No, I reduce the resolution to take the screenshot :wink:
