### ISSUE TITLE
Cursor disappearing when clicking with the right mouse button

### ISSUE THREAD

**Issue by MegaVat30** [bvschaik/julius#455]
As the title says. Sometimes wean I click with the right mouse button on any building or on anything in general, the cursor is disappearing.

The cursor can appear back if I pres 'shift+tab' to bring the Steam overlay, but this works not every time.

Clear Steam install
Windows 10
1.4.0 stable ver.

**Comment by crudelios** [comment]
Hi, thanks for the report?

Are you moving the cursor when you click it? You can right-click drag to move the map and when in that mode the cursor disappears, but it should reappear when you stop.

**Comment by MegaVat30** [comment]
Hi! Thanks for the suggestion.

I maybe indeed move my mouse **very slightly** when I click the button. But the cursor is not appearing back after this.
The only solution is Alt+F4.

**Comment by crudelios** [comment]
Just for testing, can you try [this version](https://ci.appveyor.com/project/bvschaik/julius/builds/32721310/job/aqs9f7mk7j8mc8ps/artifacts) please?

It's an older build before some changes I made (for reference: it's right before the merge of #434).

**Comment by MegaVat30** [comment]
Both versions have the same problem.

I noticed that the first time click and drag the camera with the right button it's working normally. But on the second click, my mouse cursor is disappearing. During that the game running normally and it responses on keyboard inputs.

Maybe it has to do something with the 4K resolution? However, I'm experiencing the same problem in window mode.

**Comment by crudelios** [comment]
Thanks for the report.

When the mouse cursor disappears, does the game open a window (like the building/terrain properties window) or does it stay in the normal city view?

**Comment by MegaVat30** [comment]
It stays in a normal view.
But if I go to Steam overlay and return back with the cursor repairing, there will be an open window of the building information on witch I clicked before.

**Comment by crudelios** [comment]
I cannot reproduce the bug. It may be an incompatibility with the steam overlay.

Try opening Julius outside of Steam to see if it happens.

**Comment by MegaVat30** [comment]
Ok, the bug was caused by renaming julius.exe to c3.exe in order to lunch the game from the Steam library. WIthout renaming the exe file the game works as intended.

In order to lunch game from the Steam library open SierraLauncher.ini and replace 'Game1Exe=c3.exe' with the 'Game1Exe=julius.exe'

Thanks for the help!

**Comment by crudelios** [comment]
Strange... But you can manually add julius.exe to the steam library and it will also work, that's what I did :+1:

**Comment by bvschaik** [comment]
Right-click to drag the map can now be disabled in the options.
