### ISSUE TITLE
Grand Insulae 4x4 Display Issue

### ISSUE THREAD

**Issue by jdmillard** [bvschaik/julius#47]
Fresh clone, compile with mingw (64 bit). Run game using path to game files (GOG install). Some Grand Insulae 2x2 houses have a bug where a graphic for a MEDIUM Insulae (1x1 size) is displayed in one corner while the other 3 squares are bugged out and seem to "remember" what was displayed in that square last iteration. An easy way to demonstrate this is by hitting "D" for engineer view, then switching back. The old engineering view graphic is remembered. Also, as walkers' images overlay part of the square, their silhouettes are captured in the square even after they're gone. Scrolling has the similar effect.

See screenshot attached. It has blue circles showing 2 Grand Insulaes with the bug and 1 without the bug. See the zipped .sav that *should* reproduce the issue just by loading it.

I suspect the reason for only some of the houses having the bug has to do with the case when a 1x1 house upgrades such that is expands into a 2x2. I could be wrong. Also, once it continues upgrading past Grand Insulae onto the Patrician housing, the issue seems to be gone (so far as I can tell).

I'm using Windows 10
MingGW-w64 (latest release)
SDL2 (2.0.9)
SDL2_mixer(2.0.4)
HEAD of master branch as of 1/24/2019

![grand_insulae](https://user-images.githubusercontent.com/11249742/51655610-651ef480-1f6b-11e9-9e4d-6a532b005474.png)

[display_issue.sav.zip](https://github.com/bvschaik/julius/files/2790266/display_issue.sav.zip)

I'll gladly try to help with this, but you might need to point me in the right direction since you are more familiar with the codebase. I'm impressed with your work. I'm fairly familiar with CMake and cross-platform C/C++ development.

**Comment by crudelios** [comment]
Already fixed, check pull request #44.

I have placed  a bunch of pull requests that might fix some issues you may have, please check them.

**Comment by Hirosimych** [comment]
Same issue, but I have no idea how to apply this fix. I use julius-windows-1.0.0. Maybe you will update the exe file, please?

**Comment by jdmillard** [comment]
It's mostly straight forward if you already have a compiler set up and have a bit of git experience.

Waiting for a new release exe will depend on how quickly the devs decide to move with it.

**Comment by AzureDragon-1** [comment]
Hey.Can anyone tell me exactly how to make changes to my directory respective file so that I also can resolve this problem. Where to download the fixed file from ? Where to put the downloaded file ?

**Comment by bvschaik** [comment]
If you're using Windows, you can download the current build from [AppVeyor](https://ci.appveyor.com/project/bvschaik/julius/build/job/kldvc4efa8phsrl3/artifacts). Download the julius.zip and follow the regular [installation instructions](blob/master/RUNNING.md).
