### ISSUE TITLE
Wrong popup message on building offroad houses

### ISSUE THREAD

**Issue by agruzdev** [bvschaik/julius#471]
When building houses too far away from a road, I get a weird popup message with text "before a.d." (Actually I see it in russian "до н.э.") 
I checked an original Russian version, there is no message at all

**Comment by bvschaik** [comment]
Please make sure you have the (unofficial) [Russian patch](https://bintray.com/bvschaik/caesar3-patches/russian/1.0.1.0) files installed: some texts were added in the patch, which the Russian game version never received. This "Some plots are too far from a road" message is one of them.

**Comment by agruzdev** [comment]
Yes, it fixes this problem.
Thank you
