### ISSUE TITLE
Cliffs drawn improperly with improved visual feedback.

### ISSUE THREAD

**Issue by Keriew** [bvschaik/julius#472]
Julius 1.4.1 on Windows.

With "improve visual feedback when clearing land" selected, selecting the clear tool will cause the top parts of the cliffs to be drawn with some graphical glitches. This is particularly visible on the northern province maps, but other climates also show artifacts. Unselecting the tool redraws them properly. With the option turned off, the problem doesn't appear.

It appears that the function `city_without_overlay_draw` is drawing cliffs in the wrong order.

**Comment by crudelios** [comment]
I've known about this for a while, but unfortunately this is not fixable. I had to change the way cliffs were drawn when using the visual feedback, and this was the best compromise I could manage.
