### ISSUE TITLE
I lose my cursor if I right click and Drag

### ISSUE THREAD

**Issue by DantoeJoe** [bvschaik/julius#476]
Hello,

With the Julius mod, if I right click on the map the first time after I load it, I can drag the map.
After that, if I right click and drag again, my cursor just disappear (the game not freeze, and the keyboard works). I just have to ALT+F4 to unlock.

Any solution for that ?

Thanks.

**Comment by crudelios** [comment]
What version of Julius are you running? Also, what OS?

As a workaround, pressing `Esc` to bring up the `Exit game` popup window should bring the cursor back.

**Comment by DantoeJoe** [comment]
I'm using the latest version of Julius (1.4.1) with the steam version of the game.
`Esc` bring back my cursor.


The link you post (#455) is exactly my problem, and I solve it with what he explains:
`the bug was caused by renaming julius.exe to c3.exe in order to lunch the game from the Steam library. WIthout renaming the exe file the game works as intended.`

`In order to lunch game from the Steam library open SierraLauncher.ini and replace 'Game1Exe=c3.exe' with the 'Game1Exe=julius.exe'`
