### ISSUE TITLE
Text overlay

### ISSUE THREAD

**Issue by MarkusCicero** [bvschaik/julius#478]
Hello!
In the Russian version of the game there are problems with the display of text:
1) Text overlay in speech of some citizens. As an example, a cart pusher:
![01](https://user-images.githubusercontent.com/60564622/83949293-22527980-a84d-11ea-918a-59906fdf2bbe.jpg)
-the orange rectangle is his speech
-the red rectangle is its action

2) Report of a decline in the mood of citizens:
![02](https://user-images.githubusercontent.com/60564622/83950175-d9052880-a852-11ea-81d1-bbfe4f4e2a1f.jpg)
-text in a green rectangle that describes the event does not fit in the window

Maybe there is an opportunity to make the window auto-fit to text lines for these cases?

**Comment by bvschaik** [comment]
Thanks for reporting, both issues should be fixed now.
