### ISSUE TITLE
Two health entries in Chief advisor

### ISSUE THREAD

**Issue by abdelrahmantoptal** [bvschaik/julius#479]
![image](https://user-images.githubusercontent.com/20311318/83955001-97727e80-a84e-11ea-9367-25008591bad1.png)
In the Chief advisor view the Health entry appears twice.

**Comment by abdelrahmantoptal** [comment]
I think the second one should be Religioin

**Comment by bvschaik** [comment]
Good find! The second one should indeed be Religion.
