### ISSUE TITLE
Storages getting linked

### ISSUE THREAD

**Issue by Keriew** [bvschaik/julius#481]
When a granary or warehouse is destroyed and afterwards the destruction is undone with the use of an undo button, the storage is still marked as unused. This causes the next build warehouse/granary to use that same storage, causing them to become linked, making their special orders the same and having changes to one cause changes to the other.

This behaviour matches the behaviour of original Caesar 3.

While replicating each Caesar 3 behaviour is one of the goals of the project, I think that the fact it's clearly a bug, as indicated by Caesar 3 patch notes, and one that can cause serious gameplay disruption would make this a good candidate for an optional gameplay fix.

**Comment by crudelios** [comment]
I agree this should be fixed, and I think we shouldn't have a config for this. Granted the gameplay will change slightly, but this is a very random and annoying bug, and the savegames wouldn't be incompatible. 
Loading a C3 city with linked storages in Julius will keep the link, loading a Julius city in C3 without linked storages will keep them unlinked (unless the user does the undo thing in C3 to link them).

**Comment by Keriew** [comment]
Loading a city with linked warehouses/granaries already unlinks them both in Julius and (patched) C3. The problem is only with formation of new links.

**Comment by crudelios** [comment]
Oh ok, I didn't know about that. That's yet another reason to fix it then.

You've added a fix to Augustus, right?

**Comment by bvschaik** [comment]
Thanks for finding and fixing it! I knew there were still cases of storages getting linked but couldn't find out how.

I cherry-picked [your commit](https://github.com/Keriew/augustus/commit/92f56ec6a28970cd8b2043c42f34cd7bbe25cb49) as 5ea301e.
