### ISSUE TITLE
SDL2 Renderer

### ISSUE THREAD

**Issue by BeWorld2018** [bvschaik/julius#484]
Hello

Little bug.

First test SDL_CreateRenderer() (screen.c) SDL_RENDERER_PRESENTVSYNC use (ACCELERATED MODE), but second test use : SDL_RENDERER_PRESENTVSYNC | SDL_RENDERER_SOFTWARE. and not working.

SDL_RENDERER_SOFTWARE can't working with SDL_RENDERER_PRESENTVSYNC (doesnt support this flag)

I could test it because MorphOS SDL2 version dont have yet SDL_RENDERER_ACCELERATED (working only in SOFTWARE mode)
You can find Fork here : https://github.com/BeWorld2018/julius
It's same for Augustus repository.

If you want put this new plateform (MORPHOS) in master, you can, tell me.
Thanks
BeWorld

**Comment by bvschaik** [comment]
According to the [documentation](https://wiki.libsdl.org/SDL_CreateRenderer#flags) the flags can be mixed without restrictions. If a software renderer supports vsync, we prefer that, but I think that means we need a third option that requests a renderer without any flags if the other two options fail.

Regarding MorphOS: does the game work properly on big endian devices? Especially loading/saving games.

**Comment by crudelios** [comment]
If vsync fails, it will still create a renderer without vsync.

**Comment by BeWorld2018** [comment]
Ok, it's not a big problem :-)

Yes Julius and Augustus work perfectly !!! i play a few hours on it

**Comment by crudelios** [comment]
Glad you like it and it works fine!

I'm closing this since there really isn't anything we can do to improve things.
