### ISSUE TITLE
Open source code Julius/Augustus

### ISSUE THREAD

**Issue by sTorrro** [bvschaik/julius#485]
HI, is this a complete copy with extra features, only using the 3D/2D assets from the original game, or does it run ontop of the original encrypted exe only adding extra features? Im asking because I want to study the code and learn to make similar simulation/strategy game. What scripting language is used, would I have to learn, to study this code?

**Comment by crudelios** [comment]
Hi, this is original, open-source code, written in C.

It does not require the original exe in order to run, only the data files such as images, text and the like.
