### ISSUE TITLE
issue with win 10

### ISSUE THREAD

**Issue by robfairchild** [bvschaik/julius#489]
Hi

Is there any issues running this on win 10?
I have bought the game from steam and I placed the files in the save directory but when I run the game nothing happens, If I try to launch either julius or augustus win 10 blocks me from running it

**Comment by bvschaik** [comment]
There should be no issues. If Windows blocks the executable, right-click julius.exe, go to properties and click "unblock".

**Comment by robfairchild** [comment]
Hi Bianca


Thanks for the reply. I think I got it working now. Looks like my Av was
blocking it
