### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by ksv1986voss** [bvschaik/julius#491]
Hi Everyone, i tried as mentionned to put on a SD card the installed game and Julius.nro, but i cannot see it in the nintendo switch, am i missing something ? i tried a few times but no success. 
Can you help me please ? Thanks

**Comment by ksv1986voss** [comment]
Ah really ? That’s a shame a toujours it would be easier than that, because the author never mentionned a hacked switch 
Do you have any complet tutorials ? 

Envoyé de mon iPhone

**Comment by crudelios** [comment]
We do mention a jailbroken (which means hacked) Switch is needed.

Per [our instructions](https://github.com/bvschaik/julius/blob/master/doc/RUNNING.md#switch), check [Nintendo Homebrew's Guide](https://nh-server.github.io/switch-guide/) for instructions on how to hack it.

Beware though: Switches bought after July 2018 are highly unlikely to be unhackable. Also, even if it is hackable, by hacking the Switch you risk getting banned from Nintendo Switch Online. So proceed with caution.
