### ISSUE TITLE
Deleting save files with special characters

### ISSUE THREAD

**Issue by SzKrisz22** [bvschaik/julius#493]
I can't delete save files which contain a special letter (á, é, ű etc.)
It's not important (Can be deleted manually), but it's a bug.
It's probably present in the original game too, but I think it's an UI improvement, not a gameplay changer.

**Comment by crudelios** [comment]
Bug confirmed on Windows. Definitely needs fixing.

**Comment by bvschaik** [comment]
Yup, it was a Windows-only bug that's now fixed :)
