### ISSUE TITLE
Reservoir Overlay incorrect on rotated map (corrected for v1.4.0)

### ISSUE THREAD

**Issue by ralphcook** [bvschaik/julius#504]
This is in Valentia, though I've seen something similar elsewhere and just didn't follow it up, 

When the user has selected a Reservoir building and is dragging it across the map (and if the option is selected), a light blue overlay shows the extent of the pipes that result from placing the reservoir at any given point on the map (at least those where it can be placed).

When I have the Map rotated clockwise 90 degrees, the "pipes" overlay is offset from where it's supposed to be. The following is a portion of Tingis, oriented with North at the top, and a reservoir about to be placed in the middle of a 9x9 block (I would never put it there, but it's a convenient way to show 4-way dimensions):

![image](https://user-images.githubusercontent.com/5413117/87083145-21b95400-c1fa-11ea-8182-69c54ddfba1e.png)

Here is the same map, rotated 90 degrees so East is at the top, with the reservoir placed at the same location:

![image](https://user-images.githubusercontent.com/5413117/87083277-575e3d00-c1fa-11ea-80dc-b15f7be0d2ac.png)

As (I hope) you can see, the pipes overlay on the east-is-top version extends a couple of extra tiles beyond the road compared to the  north-is-top version. In addition, there seems to be a 'hole' in the bluish overlay color of 2x3 tiles on the side where the 'extra' pipes are drawn -- as if a miscalculation of the starting point of the pipes might be to blame.

The same things happen for west- and south-is-top.

Here's the game file:

[Valentia 02 a02 a04 werehouses.zip](https://github.com/bvschaik/julius/files/4899169/Valentia.02.a02.a04.werehouses.zip)

**Comment by crudelios** [comment]
What version of Julius are you using? This was a known issue and was supposed to be fixed.

**Comment by ralphcook** [comment]
I'm sorry, my mistake -- evidently this was corrrect for version 1.4.0, which I did not know had been released.

**Comment by crudelios** [comment]
No problem. There are also many new features. Have fun!
