### ISSUE TITLE
Graphics corruption when Undo-ing cleared housing

### ISSUE THREAD

**Issue by attrition** [bvschaik/julius#505]
When clicking UNDO after deleting a housing block, the houses re-appear but begin devolving. Some of these houses appear to stop drawing until they reach their original housing evolution.

Seen in Julius 1.4.1, present in unstable.

**Comment by bvschaik** [comment]
This also happens in Caesar 3: when you delete houses, all occupants are kicked out, so if you hit undo it's basically a vacant lot with graphics corruption that stays there until new people move in, at which point it starts evolving rapidly.
Undo is unreliable.

**Comment by attrition** [comment]
Addendum to my initial post. The graphics corruption appears when the house is re-occupied, as it remains the original house graphic until that time

**Comment by crudelios** [comment]
I'm not sure about compatibility with savegames, but if the bug is only visual maybe we can/should fix it.

**Comment by crudelios** [comment]
Just a heads up: the visual issue has been fixed, the devolution will be fixed in Augustus (it is a gameplay change for C3 so it will be kept in Julius)
