### ISSUE TITLE
Numerical overflow when sending too strong a relief force

### ISSUE THREAD

**Issue by siddharthprabhu** [bvschaik/julius#511]
As described [here](http://web.archive.org/web/20060712222055/http://caesaralan.co.uk/strategy/battles.html), it is possible to fail a distant battle relief mission by sending an extremely powerful relief force. I'm guessing this is because the strength is represented with a single byte and thus overflows for values greater than 255.

Is this something that can be fixed in Julius without breaking savegame compatibility with C3?

**Comment by bvschaik** [comment]
You're right, the strength is stored in an unsigned byte, which has range 0-255.

Unfortunately this cannot be fixed without breaking savegame compatibility: the army's strength is calculated when you send the relief force, and then stored in a 1-byte field in the savegame. Fixing it would require expanding the field.

**Comment by crudelios** [comment]
This is a good fix for Augustus though.
