### ISSUE TITLE
Cart from 'getting' granary sometimes gets no load

### ISSUE THREAD

**Issue by ralphcook** [bvschaik/julius#512]
I've rotated the given Londinium map. There are two granaries visible, both set to getting wheat; the cart from the more Northern granary is just returning. Wait a short time, and carts from both granaries set out.

While the first cart is crossing the bridge to the Southern island, a message from Ceres appears, followed by one from Mars (we're actually having a short battle at the moment). Also, the three farms on the island send loaded carts to the granary; the granary fills up with the first two, and the third continues on to one of the getting granaries, passing the two granary carts going the other way.

The first 'getting' cart picks up a load from the granary and heads back; the second cart arrives at the granary and heads back but has no wheat on it.

If you continue to watch (on, say, 200%), the next two pairs of round trips made by the 'getting' carts proceed normally, both getting loads, but on the third pair of round trips, the 2nd cart again fails to get a load. You can see that it goes all the way back to its granary and nothing is delivered.

The Caesar III game doesn't do this -- both carts get wheat.

I don't know if it's significant, but the times the bug shows up, it seems the two carts arrive at the farms' granary closer together than they do the other times.

[Londinium 02 i 5405 getting wheat bug.zip](https://github.com/bvschaik/julius/files/5130851/Londinium.02.i.5405.getting.wheat.bug.zip)

**Comment by bvschaik** [comment]
Hi Ralph, thanks for the detailed report.

I loaded the saved game in Julius: your granary on the farmland has had a blessing of Mercury, so it contains 600 fruit, 600 vegetables and 600 meat. There's only room for 600 more wheat. Getting cartpushers can take up to 800 wheat at the time.

What happens in the 4 trips I watched:

1. granary contains 600 wheat, getting cart 1 loads up all 600, getting cart 2 finds a granary without wheat and returns empty
2. two cartpushers set out again, cart 1 arrives at the granary, takes all 400 wheat. Meanwhile, one farm cart drops 100 at the granary, and cart 2 can return with 100 wheat
3. two cartpushers set out again, cart 1 takes 300 wheat, two farm carts drop wheat, and cart 2 takes 200 wheat
4. they set out again, this time closer together indeed, so cart 1 takes 400, no farm carts drop food between the two carts, and cart 2 again finds a granary without wheat so it returns empty

When loading the saved game in Caesar 3, I saw exactly the same thing happening. This works as expected, so I'm closing this bug.

**Comment by ralphcook** [comment]
My apologies - at least it was easy (for you) to find out what was 
happening. I must have mistaken which trip to the farmland granary was 
being executed when I got to the lower-resolution Caesar III game I tried.

And, of course, there's no way for granaries to be set to get fruit in 
Londinium. But that's the way Caesar III works, also...

rc
