### ISSUE TITLE
Documentation on file formats

### ISSUE THREAD

**Issue by Banderi** [bvschaik/julius#513]
Hello there!

I'm amazed by the amount of work poured into this project, so I was trying to go through the code a bit and poke my head at other games like Pharaoh, and got stumped on the internals of the graphics system. I was wondering if there was any notes or documentation or explanation for how they are handled by Julius and how the file formats work.

So far what I was able to piece together, very very slowly:

- .555 files store the actual image (BMP) data
- .sgx files store indexing and metadata linking to .555 files
	- the header is always 20680 long?
		- first 80 bytes are some overhead ints that are skipped over
		- a sequence of uint16s with each being the index of the image in the
		  global pool/array, arranged in order of the "group ids" that are used
		  internally (300~ in C3.sg2). not sure if this sequence is the global
		  list of images ordered the same way they appear in SGReader or if
		  some other order.
		- a sequence of strings each 200 char. long corresponding to the
		  "filename" of the stored image data - all in .BMP - and also the name
		  of the external .555 file if it's not stored in the initial .555 of
		  the same name as the .sgx file (97 in C3.sg2, 18 in Pharaoh's file)
	- the rest of the .sgx file?
- the `image`s are structs of metadata/headers stored in a global pool (e.g.
  "main") in the engine
	- they contain data about sprite size, frames, animation speed, etc. as
	  well as a secondary struct containing data like the index of the string
	  corresponding to "filename.BMP", the compression, the "external" flag and
	  the offset of the image data in the corresponding global BMP data pool
- the "data" (`color_t` array) is the global pool of BMP data that is accessed
  via the offset
- fonts glyph data is accessed via getting the offset in the global BMP data
  pool from the image (or image from an external file for other locales),
  additionally offset by the requested letter and a base offset (201 for
  Cyrillic locale, 0 otherwise?) e.g.:
```
			if external file:
				image = font[base_offset + letter_index]
				data = font_data[data offset from the image struct]
			else:
				image = main[index from group "GROUP_FONT"]
				data = main_data[data offset from the image struct]
```
- the "Empire" data is stored in a separate pool, although I can't see at first
  glance the reason for that

I'm trying to understand the indexing better and how it's decided so as to figure out what would be the best way to deal with Pharaoh's files, which are split into multiple ones (merge them up internally, if necessary?) including the enemies.

Thanks again for the amazing work so far!

**Comment by bvschaik** [comment]
Hi! Nice to hear you're interested in the graphics file formats.
I've also written a utility to read the images in the graphics files for all Impressions citybuilder games called SGReader ([Github repo](https://github.com/bvschaik/citybuilding-tools)). I've written [documentation](https://github.com/bvschaik/citybuilding-tools/wiki/SG-file-format) for the file format on the wiki of that project.
I hope that gets you started, let me know if you miss anything so I can edit that page.

**Comment by Banderi** [comment]
Ooh, that is immensely helpful! Thanks so much for the swift response!

For the moment the only curiosity I had is if there's any particular reason the "Empire" map data is stored separately? I assume just for performance since the only part that's used is the bitmap?

I'll post here any other question if I get stuck again and/or progress on my endeavor if that's alright.

**Comment by bvschaik** [comment]
My guess is performance and disk space.

Every time you switch to a savegame with another climate (northern, central, desert), the game switches to a different graphics set: C3_North.sg2, C3.sg2, C3_South.sg2 respectively, including corresponding .555 file. Since the empire is the same in all climates, it doesn't make sense to duplicate 4MB of data three times in the .555 files. You see the same with the mission intro/win graphics which are stored in the SG2 folder: they are what I call "external" images. Furthermore, the empire map is treated specially in Julius/C3: it's loaded once when starting the game and kept in memory, even when switching climates.

I'll keep this issue open for more questions.

**Comment by Banderi** [comment]
I'm looking through the .sg3 at the moment, and I guess it's worth sharing here, the header size (normally set to 20000 or 20608 for buffer padding after the group index) has 20,000 additional bytes for Pharaoh files making the header 40608 when using the same parsing in the code.

I assume it's actually known info since the SGreader tools can open them just fine, but couldn't find this mentioned in the docs or anywhere else!

**Comment by Banderi** [comment]
Is there any documentation/info on how the .sav and mission1.pak files are loaded, by any chance?

**Comment by bvschaik** [comment]
The header is actually only 80 bytes long, plus 300 index entries. The rest of what you consider the header are bitmap records, and the number of those depend on the value in the header at position 20 (see the link I posted earlier). For C3's SG2 files, that's 100, for SG3 files it's set to 200.

There's no documentation for the .sav/.pak/.map files since nobody has asked for it yet. `mission1.pak` is just a collection of `.sav` files with a header detailing at which position which savegame starts.
For savegame format, you might want to check [src/game/file_io.c](https://github.com/bvschaik/julius/blob/master/src/game/file_io.c).

**Comment by Banderi** [comment]
> The header is actually only 80 bytes long, plus 300 index entries. The rest of what you consider the header are bitmap records, and the number of those depend on the value in the header at position 20 (see the link I posted earlier). For C3's SG2 files, that's 100, for SG3 files it's set to 200.

Ahh, that makes sense. I said header because the code calls it `HEADER_SIZE` and sets a fixed value that isn't immediately explained in the doc.

> There's no documentation for the .sav/.pak/.map files since nobody has asked for it yet. `mission1.pak` is just a collection of `.sav` files with a header detailing at which position which savegame starts.
> For savegame format, you might want to check [src/game/file_io.c](https://github.com/bvschaik/julius/blob/master/src/game/file_io.c).

I'm going through it right now! I'm trying to load Pharaoh's `mission1.pak` but it's crashing on the decompression of the third "file piece", maybe some offset issue. Any info at all, even if it's a small summary of the loadup process, would be immensely helpful!

**Comment by bvschaik** [comment]
> I said header because the code calls it `HEADER_SIZE` and sets a fixed value that isn't immediately explained in the doc.

The Julius code is tailored to what the Caesar 3 files contain, so I hardcoded it to avoid unnecessary complexity in the code.

> I'm trying to load Pharaoh's `mission1.pak` but it's crashing on the decompression of the third "file piece", maybe some offset issue. Any info at all, even if it's a small summary of the loadup process, would be immensely helpful!

Note that every game (and later even every game version) has a different format for storing data in the saved games.  You cannot take the code for Caesar 3 and expect the same fields to be present in Pharaoh saved games. For one, the map grids have a different size, plus there's the monuments that need to be stored somewhere in Pharaoh.

**Comment by Banderi** [comment]
Phew! I've put together a doc with all the info I could gather up together so far!
https://github.com/Banderi/Ozymandias/blob/master/doc/wiki/SAV-file-format.md
I left in most of the chunks that at first glance appeared to remain aligned/unchanged from Caesar 3 with the same descriptions, but I'm sure most of them will need to be tweaked or repurposed (like the "aqueduct" data chunk or, as you mention, the grid size)

Do you reckon is there anything in there that I missed at first glance or some data that is already known?

**Comment by bvschaik** [comment]
To be honest I don't know as much about the Pharaoh savegame format, so I can't really comment on it.

**Comment by bvschaik** [comment]
Since there have been no more questions, I'm closing this issue :)
