### ISSUE TITLE
There's no julius.exe, shame on you

### ISSUE THREAD

**Issue by Pyronia** [bvschaik/julius#519]
The issue is so obvious there is no need to describe it. Wish you lovely stay in Hell.

**Comment by Pyronia** [comment]
The issue is so obvious there is no need to describe it. Wish you lovely stay in Hell.

**Comment by bvschaik** [comment]
I've actually been in [Hell](https://www.google.com/maps/place/7517+Hell,+Norway/@63.4444475,10.8872628,15z/data=!3m1!4b1!4m5!3m4!1s0x466d16fb3ae6fd6d:0x1596b57897c52a6b!8m2!3d63.4451715!4d10.9052167) and it looked like a nice town, albeit a bit too close to the airport.

Maybe you need to [follow the instructions](https://github.com/bvschaik/julius/blob/master/doc/RUNNING.md#windows)?
