### ISSUE TITLE
Error - Wrong folder selected

### ISSUE THREAD

**Issue by ade-x1** [bvschaik/julius#523]
Hello team,

I am trying to use Julius on Catalina for the first time but when I try to select the folder containing my copy of the game containing the installer it says that the selected folder doesn't contain the game.

Can this be due to the fact that the game is the very first version? I took a copy of the files from my old original CD

Many thanks!

**Comment by crudelios** [comment]
Hi, well maybe we explained ourselves wrong.

You do need to install the game from the CD, then point Julius to the installed C3 folder.

Also, if you install C3 on Program Files, you may need to run Julius as administrator for the saves to work (you will be able to load but nothing will save due to lack of pernissions). Ideally you should install C3 somewhere else, like on C:\Games\C3.

**Comment by bvschaik** [comment]
You indeed need to find a way to install the game on your Mac. If you have access to a Windows machine, you can install there and move the files to your Mac. Alternatively, you can use the command-line tool `unshield` (can be installed through homebrew) to extract the contents of your CD installation.

I have a tool in the planning to automate this, but I haven't started work on it yet.

**Comment by ade-x1** [comment]
Thank you for your reply!
As I don’t have a Windows machine and I am using Catalina, I’ll try via command line. 

Many thanks!

**Comment by bvschaik** [comment]
Step-by-step instructions using `unshield`:

1. Get `unshield`, you can install it through Homebrew: `brew install unshield`
1. Open a Terminal in the directory where you want the Caesar 3 files
1. Execute the following command to extract the installer (replace `{CD}` with the name of your C3 cd-rom):
    ```
    unshield x /Volumes/{CD}/data1.cab
    ```
1. Remove all directories except the one named `Exe` (in my case I could remove OLEAUT, SIGS, Sierra_System_Files, wininit)
1. Copy sound and video files over to the Exe directory:
   ```
   cp -r /Volumes/{CD}/555 Exe
   cp -r /Volumes/{CD}/SMK Exe
   cp -r /Volumes/{CD}/wavs Exe
   cp -r /Volumes/{CD}/soundfx/* Exe/wavs
   ```
1. Rename `Exe` to something more logical
1. Start Julius, point it to that directory and you should be ready to play
