### ISSUE TITLE
Building's Shotcuts Overriding Restrictions

### ISSUE THREAD

**Issue by nathanbsouza** [bvschaik/julius#526]
Just reporting: I found a bug/glitch that overrides some event-related restrictions on building edification. I was playing the first mission of the campaign and the prefecture and engineering's post were supposed to be disabled until a fire or building collapse took place. It turns out that if you have the shortcuts binded for those buildings, you can override this event-related restriction and build them anyway (screenshot). I wonder if it also happens in missions where the edification is definitely disabled.

![city 2020-11-04 17 44 40](https://user-images.githubusercontent.com/73966482/98166778-ba20c600-1ec6-11eb-8782-8a804093d247.png)

**Comment by crudelios** [comment]
Nice catch!

**Comment by bvschaik** [comment]
Nice find indeed! I checked: if the scenario doesn't allow structures, it will not be possible to build them using the hotkeys. Since prefect and engineer's post will be enabled later in the tutorial mission, it's possible to build them. I'll have a look.

**Comment by bvschaik** [comment]
Should be fixed in the latest version, thanks!

**Comment by nathanbsouza** [comment]
Thank you too! I more than glad to help.
