### ISSUE TITLE
Game goes black when I go to task manager

### ISSUE THREAD

**Issue by FOSSHipster** [bvschaik/julius#528]
When I hit ctrl alt delete on Windows 10 while playing Julius, then try going back into the game, the game display goes completely black. I can still hear audio, but I cannot see what is happening in-game. Any recommendations?

**Comment by crudelios** [comment]
I can confirm this problem. As a workaround, press `F6` twice to go to windowed mode and fullscreen again and the display should reappear.

Strangely enough, this only happens when pressing `CTRL`+ `ALT` + `DEL`, but not when using `ALT`+ `TAB` or the `Windows` key.

**Comment by m-mohr** [comment]
Could you just twice do the F6 thing programatically when you detect Windows and a CTRL + ALT + DEL somehow? @crudelios

**Comment by bvschaik** [comment]
The problem will be detecting coming back from the lock screen. Since SDL itself doesn't appear to have support for it, I doubt we can fix this. I'll have a quick look on a VM though to see what we can do.

**Comment by bvschaik** [comment]
This should now be fixed.
@FOSSHipster could you give the [latest development build](https://bintray.com/bvschaik/julius-dev/windows/_latestVersion#files) a try and see if it is indeed fixed for you?
