### ISSUE TITLE
All the original MP3 files

### ISSUE THREAD

**Issue by gergelypap** [bvschaik/julius#532]
I think I found an original Sierra file dump, which contains all the MP3 soundtracks: http://sierrachest.com/gfx/games/Caesar3/music/

Even an additional one, called `WinAssignment.mp3`, which the wiki does not list.

My suggestions:
- Upload the remaining mp3 files to the mirror link in the wiki.
- Update the wiki page accordingly.

Fun fact: the server seems to be containing lots of original box art, PDF manuals, splash screens and even demos to many Sierra games.

**Comment by bvschaik** [comment]
Those are not the original high-quality MP3 files, they appear to be the .WAV files converted to .MP3 (and .OGG), which still remain low-quality despite being .mp3.

Only the Rome1-5 files were ever released in high quality.
