### ISSUE TITLE
Saving a screenshot crashes the game on big endian systems

### ISSUE THREAD

**Issue by crudelios** [bvschaik/julius#533]
_Originally posted by @BeWorld2018 in https://github.com/Keriew/augustus/issues/150#issuecomment-728712448:_

> Ok :-) Julius same crash

On big endian systems (MorphOS in the user's case), pressing `F12` to save a screenshot crashes the game.

Definitely not a nice feature to have!

**Comment by crudelios** [comment]
@BeWorld2018, @bvschaik just tested saving a screenshot on her PPC virtual machine and it worked, colors and all.

Are you using our internal png library or the system's own png libraries?

**Comment by BeWorld2018** [comment]
I am using my own system png, but i can try internal png to test

**Comment by BeWorld2018** [comment]
so i try to compile with png internal... now F12 working but i have a message "Mods folder can't be found", /mods directory... 
I use zlib system... i will test with your internal zlib

Logs (extrait)

INFO: Model loaded
INFO: Loading mod file  mods/aesthetics.xml
ERROR: Unable to create a png struct
INFO: Unable to load image  Ornamental_Tree_01_Top_Layer
INFO: Invalid layer for image  ornamental pine
ERROR: Unable to create a png struct
INFO: Unable to load image  Ornamental_Tree_06_Top_Layer
INFO: Invalid layer for image  ornamental fir

**Comment by crudelios** [comment]
There may be a problem with he external libs. Run cmake with `-DSYSTEM_LIBS=OFF` to force the use of the internal libpng/zlib (and expat in the case of Augustus).

**Comment by BeWorld2018** [comment]
Ok.... after some research, all is OK with internal libs (Zlib/Expat/Png), no more errors.
Next release for MorphOS will have internal libs.

**Comment by crudelios** [comment]
All right, since this seems to be some sort of library incompatibility I'll be closing this then. Thanks for your feedback!
