### ISSUE TITLE
File menu appears in the citizen thumbnail

### ISSUE THREAD

**Issue by gergelypap** [bvschaik/julius#535]
When clicking a citizen, who is walking on a bridge (either Low or Ship), the focus thumbnail in the dialog shows the File menu, instead of the citizen. Bug is also present in the original Caesar III.

![image](https://user-images.githubusercontent.com/5883922/99385154-d95d2180-28d0-11eb-8243-7eebf5b95293.png)

![image](https://user-images.githubusercontent.com/5883922/99385590-7a4bdc80-28d1-11eb-85b6-63ac268998eb.png)

Reproduction:

1. Build a Low Bridge or Ship Bridge above water and connect to citizens.
2. Wait for citizens to cross the bridge.
3. Right-click on them while they are on the bridge.

I could not reproduce this with any other citizen, who is _not_ on a bridge. Maybe it has something to do with their elevation, as opposed to ground level, I don't know.

**Comment by crudelios** [comment]
This is an old one. When I have the time I can have a look at this to see if it's easily fixable.
