### ISSUE TITLE
Road texture with stairs

### ISSUE THREAD

**Issue by gergelypap** [bvschaik/julius#536]
Similarly to roads leading into Granaries, roads leading to stairs should have the correct texture.

![image](https://user-images.githubusercontent.com/5883922/99391504-8ee0a280-28da-11eb-8200-0ee1a1968d8b.png)

**Comment by crudelios** [comment]
I know this one was fixed in Augustus, so it can easily be fixed in Julius. The only thing I have against it is that if you have two roads paralell to the stairs, you'll get a bunch of intersections and it'll look weird.

**Comment by bvschaik** [comment]
It may look weird with parallel roads but It does make the user aware that the access ramp is one big 2x2 road tile, so I think this would be nice to have.
