### ISSUE TITLE
Stop playing city and speech sounds when the game is paused

### ISSUE THREAD

**Issue by gergelypap** [bvschaik/julius#537]
When the game is paused, time basically stops, and it makes no sense that the city still produces sounds and citizens still speak when clicked. Only the sound effects and the music should be playing in pause state.

(It would be even better to stop their sprite animations, but that's another issue.)

**Comment by crudelios** [comment]
Why shouldn't citizens speak when clicked? It's an information menu, independent of the game's actual speed.

**Comment by gergelypap** [comment]
@crudelios  To me, pause means time and the city stops, people don't move and don't do anything. So why play city sounds? And if we are not playing city sounds, why play speeches?

Anyway, this is more like an realism improvement for me. They still have their phrases in the dialog window, and they can speak if after an unpause.

**Comment by bvschaik** [comment]
I agree with Crudelios: why block the sounds? I like to pause often to consider what to do next and to check my citizens before they run away from my mouse cursor. If there were no speech or other city sounds I would think the game was broken.

**Comment by gergelypap** [comment]
@bvschaik Fine, you convinced me not to disable speeches. However, hearing city sounds when paused indicate me that the city is running and people are doing stuff.

**Comment by crudelios** [comment]
This is a very minor thing, but I actually don't disagree on disabling city sounds (and animations for that matter, but that's a whole different can of worms). Most other games (Cities Skylines comes to mind) also disable city sounds to further reinforce the idea of time being paused.

Either way, in the end of things I feel indifferent to this change.

**Comment by gergelypap** [comment]
> This is a very minor thing

These very minor things makes this project awesome to me :)

**Comment by bvschaik** [comment]
I still think we should not change this, for these reasons:
- All games in the series behave like this
- The project goals of Julius state we want the same look and feel of the original. Removing sounds from the paused game is a deterioration of the feel of the game
- Animations are still playing on pause, if I see a theater working, I expect theater sounds every once in a while

So while I appreciate the suggestion, I will close this issue (and related PR).
