### ISSUE TITLE
People are visible behind large buildings if they walk on a bridge

### ISSUE THREAD

**Issue by gergelypap** [bvschaik/julius#544]
Put any large building in a way that it hides parts of a bridge. People are visible through if they are walking on the bridge:

![image](https://user-images.githubusercontent.com/5883922/99805139-58a25d80-2b3c-11eb-9d14-4411e35a818d.png)

**Comment by crudelios** [comment]
I had a look at this.

Due to the way the drawing code works, it's not possible for us to fix it without causing other graphical artifacts.

Therefore I'm closing this.
