### ISSUE TITLE
Allow mp3 support for every wav files

### ISSUE THREAD

**Issue by Irv1n3** [bvschaik/julius#550]
Hi!

I was cleaning the wav music files to suppress the more noise possible and came to the idea of cleaning also voices files.
I don't think it would have a major impact with the music in the game but you can still hear the difference outside.
A sample here: https://youtu.be/bwASYOY1X80

I was wondering since you support mp3 files to replace some of the original wav if you can enhance this support to cover the dialogues too.
It's not a big deal, but if it's simply enough to implement I would be pretty curious to see if there's indeed a notable impact for the player.

Thanks!

**Comment by crudelios** [comment]
Hey, what are you using to clean the audio? I tried it myself but didn't get far.

I think we can add support for this. It shouldn't be hard to implement.

**Comment by Irv1n3** [comment]
I only used Audacity and the Noise reduction feature, the most difficult part was to find a good isolated part with only noise, I've tried various files but finally stick with the French version of pupils_needjob1. 
Then I used the settings noise reduction 48dB, sensibility 3 and frequency smoothing 1 and batch all wav French and English wav.

I can send you my result but I don't think I can post it in public since it's copyright & all I guess

**Comment by crudelios** [comment]
No unfortunately you can't. I tried using the denoise filter for the intro music, but the end result was far from perfect. I'm waiting for an AI for that.

**Comment by Irv1n3** [comment]
Drop me an email to my github username followed by @hotmail.fr
I'm pretty satisfied with what I got for the main menu music, even if it's not as clear as the official mp3 (even with a bitrate of only 128kbps)

**Comment by crudelios** [comment]
I just had a look at our code, the voices files cannot be open as mp3, only the musics can. You can save the improved voice files as wav and backup the old wav files, however I doubt the new voice wavs will open correctly on the original C3.

**Comment by Irv1n3** [comment]
Actually I had tested previously to replace directly the wav but it didn't work, but I've tried again with another encoding and it works!
And it works even without Julius with the original C3 😃

**Comment by crudelios** [comment]
That's great! Does audacity support bash scripting via shell? With that and the noise sample you used, we could at least provide the tools for users to improve their files.

**Comment by Irv1n3** [comment]
I don't think so, but I can write a small tutorial:

1. Install Audacity and download this archive
2. Go to %AppData%/Roaming/Audacity/Macros
3. Copy Remove noise Caesar 3.txt
4. Open Audacity
5. Open sample.wav
6. Ctrl+A to select the whole sample
7. Effect -> Noise Reduction -> Get Noise Profile (the window closes itself)
8. Close the sample track and open a testing track, for example SETUP.wav which has a lot of noise
8. Effect -> Noise Reduction -> Set the Step 2, Noise reduction 48, Sensitivity 3, Frequency smoothing 1, Noise: Reduce and click OK.
9. File -> Export -> Export as WAV -> Choose the Encoding Signed 16-bit PCM and save.
10. Put the file in your wavs folder and launch the game to test if it works correctly
11. Then close the Setup track
12. Tools -> Apply Macro -> Palette -> Remove noise Caesar 3 -> Files -> Go to your Caesar 3 wavs folder and ctrl+a to select all the tracks (don't select Setup.wav if you have already cleaned it) -> Open
13. It takes a while, sometimes Audacity isn't even responsive, just give it a few minutes.
14. Once done, you can find a folder macro-output in your wavs folder, just copy to replace the tracks directly in the wavs folder

It's not a simple click but it's pretty straightforward, tell me if you manage to get the same result as me.
Note that maybe it's possible to get an even better result by tweaking a bit the settings or find a better noise sample, but it's a good first step in my opinion.

[Caesar 3 clean wavs.zip](https://github.com/bvschaik/julius/files/5583565/Caesar.3.clean.wavs.zip)

**Comment by crudelios** [comment]
Thanks for the instructions. I actually had a look and I think it's possible to create a command-line script using sox instead of audacity.

**Comment by crudelios** [comment]
I had a look at your settings and for the music they have the same problem I found before when trying to denoise. If you listen to setup.wav with your settings and noise filter, the music becomes much duller. The drums and trombone lack the original "oomph" (you can "feel" it from the first seconds of playback).

**Comment by Irv1n3** [comment]
Yep, I'll try to improve a bit the result, at least for voices it's enough because it's much less complex than musics.
You can already get a more clearer sound by lowering the Sensitivity but at the cost of still hearing the noise.
I'll let you know if I found something better!

**Comment by crudelios** [comment]
I'm still waiting for an AI that would do this for us. Unfortunately audio does not get nearly as much attention as images!
