### ISSUE TITLE
Default C3 arrow-cursor by win98 - is a most beautiful thing! (no)

### ISSUE THREAD

**Issue by ArtySh0ck** [bvschaik/julius#554]
Hello my favorite JULIUS! It's been so long, but i think a have an idea!

For this, probably, we need services of some designer (maybe not), but it worth...

NEW INTERACTIVE CURSORS for JULIUS! Let it be kind a "Romal" for standart use, it could be still an arrow, but remastered for C3 atmosphere. But it could have a several forms, for example, if we touch npc (market lady, medic, actor, etc..) it could appear as arrow with "talking head" near to arrow, to user to know if right now he clicks right-button he summon "dialogue" window to this npc. Or if touching houses, it could appear as arrow with house near to it or something like... 

For first its more aestetic, it will help bring c3 a little "today" of playing. For second, its necessary when it runs in 1920x1080 and more, cause its too hard to see what exactly arrow touching right now (i have a couple times when miss-click cause hard too see).

For people who loves standart cursor and sword it may be off or on in config menu.

Thanks! Nice too see all of you, i really miss =)

**Comment by crudelios** [comment]
Hey @ArtySh0ck, long time no see! As Julius wants to keep faithful to the original C3, I think the new cursor types are a better change for Augustus.

Regarding the game being "hard to see", there is now a `Display scale` and a `Cursor scale` option in the main menu options, which make the screen or the cursor larger. Check it out, it might fix your problem!
