### ISSUE TITLE
Overlay View and Farms

### ISSUE THREAD

**Issue by jdmillard** [bvschaik/julius#56]
Overlay views (Damage, Fire,  take your pick etc) don't render farms properly. It seems to work fine when facing North and South.

When facing West, the area where the farm is, "captures" whatever was last shown in that location (which you can mouse-over to exaggerate the effect):
![image](https://user-images.githubusercontent.com/11249742/51949972-c37d2480-23fc-11e9-9e83-cf93709fc1fb.png)

When facing East, it seems to just mangle the appearance:
![image](https://user-images.githubusercontent.com/11249742/51950009-e3ace380-23fc-11e9-8868-23c97b087f03.png)

**Comment by bvschaik** [comment]
Good catch!
