### ISSUE TITLE
Translation request: "Display scale" and "Cursor scale"

### ISSUE THREAD

**Issue by bvschaik** [bvschaik/julius#562]
For the next release, we have two additional settings in the configuration screen, the sliders for "Display scale" and "Cursor scale":

![Scale options](https://user-images.githubusercontent.com/6518876/98830686-9b747f00-2432-11eb-97ba-9b192edfe4bf.png)

A description of the options is [here](https://github.com/bvschaik/julius/wiki/Configuration#display-options).

We need translations for "Display scale:" and "Cursor scale:" in the following languages:

- [x] French
- [x] German
- [x] Italian
- [x] Korean

@m-mohr, @constant-current, @basilero, @fetchinist - you have contributed translations before, could you perhaps provide them?

**Comment by m-mohr** [comment]
Sure, I've aligned them with Windows terminology:

Display Scale: 
> Skalierung der Anzeige:

Cursor Scale:
> Skalierung des Mauszeigers:

**Comment by catch220** [comment]
Russian translation, if needed:
"Display scale:"  "Масштабирование изображения в окне"
"Cursor scale:" "Масштабирование курсора"

**Comment by constant-current** [comment]
I have also aligned with Win10 options and it seems to be quite similar on different Linux desktop environments.
 Display scale "Mise à l'échelle de l'affichage"
 Cursor scale "Taille du curseur de souris"

**Comment by fetchinist** [comment]
in korean:
Display scale - 화면 배율
Cursor scale - 커서 배율

**Comment by crudelios** [comment]
@tafazzi maybe you could help with the italian translation, please?

**Comment by tafazzi** [comment]
> @tafazzi maybe you could help with the italian translation, please?

Sure! Here are the two options in Italian:

Display Scale:
`Ridimensionamento display`

Cursor Scale:
`Ridimensionamento cursore`

**Comment by bvschaik** [comment]
Thanks all!
