### ISSUE TITLE
I have the original PT-BR 1.1 Patch Setup if it's useful

### ISSUE THREAD

**Issue by felipecrs** [bvschaik/julius#566]
[C3_PATCH.zip](https://github.com/bvschaik/julius/files/5770384/C3_PATCH.zip)

It has the `Setup.exe`.

**Comment by bvschaik** [comment]
Thanks, I didn't even know there was a 1.1 patch for PT-BR, the version I had was 1.0 unpatched. I've updated the [patch file](https://github.com/bvschaik/julius/wiki/Patches).

**Comment by felipecrs** [comment]
So what was the version that was in there before? I mean here: https://github.com/bvschaik/julius/wiki/Patches

**Comment by bvschaik** [comment]
The two language files in which the new strings for 1.1 were fan-translated, see #217

**Comment by felipecrs** [comment]
Wow. Thanks.

**Comment by felipecrs** [comment]
I applied the patch in my 1.0 version as well and compared the binaries with yours, they match (just a confirmation). :-)
