### ISSUE TITLE
1st impressions / A few suggestions (quality-of-life improvements)

### ISSUE THREAD

**Issue by DwarfFighterCleric** [bvschaik/julius#567]
edit: this is on Windows EXE version...
("UI improvement"? Is it the right section for stuff like this? Anyway...)  
I just played Julius for the 1st time and a few things came to my attention right away that got in the way of playing the game, in order of priority:  
1) When using keyboard to scroll map, scrolling is not immediate (there's a delay between the time you hold the key and the time it actually starts to scroll)  
2) Please add option to disable mouse (edge) map-scrolling entirely, but important: leave keyboard scrolling on. (for windowed play, switching between windows constantly, etc)  
3) Option "Scrolling speed" affects keyboard scrolling too (WASD controls)  
3b) Possible fix for this one: differentiate between "Edge" scrolling and "Keys" scrolling (not a single function for both)  
..  
For code reference, these changes already exist in another open-source project called OpenXcom, if you need help seeing how they made it over there.
It's mentioned that "for technical reasons, when playing the game in a window mouse edge scrolling will only work when the mouse is close to the screen edges". I was able to play the original game EXE using DxWnd which addresses this issue and allow me to have Edge scrolling when the mouse is anywhere on the screen, not only near the edges. The only reason I don't continue using DxWnd for the game is lack of WASD controls which help tremendously.

**Comment by bvschaik** [comment]
Thanks for the suggestions.

1. This should only happen when smooth scrolling is disabled, did you try with and without it? I think you did because point 3 only happens when using smooth scrolling: with it off the keyboard scroll speed does not depend on scroll speed
2. That might actually be useful, especially for windowed mode.

**Comment by DwarfFighterCleric** [comment]
Yes, smooth scrolling gets rid of the keyboard input delay. But it feels weird, it's like the framerate to the scrolling is too high and it makes me feel dizzy. Also, it seems to cause a lot of eye strain after a while, I can feel the physical strain on my eyes after a while. That is also the reason why I personally limit most of my games to 30 FPS, otherwise they make me dizzy.  
Is there some kind of framerate limit to the scrolling? Or is it unlimited frames?  
If there was some kind of built-in framerate limiter in the game it would be cool.  
When I played this using DxWnd, I limited the game to 20 FPS, that allowed the perfect amount of scrolling speed and minimal eye strain for prolonged sessions. (I think anyone that play these types of games will play them for prolonged sessions anyway)  
If I was on Windows, I would use some external framerate limiter like DxTory, but I'm on Linux, not many options. This game doesn't load with DxWnd (can't be hooked)  
Still not a permanent solution to avoid fixing the original keyboard delay.  
..  
Another potential quality-of-life enchancement that I noticed while playing:  
4) Include a "mouselook" key binding. Pressing that key would make the mouse scroll the map by itself (not mouse button, just the mouse cursor itself, while that key is pressed) That would be a pretty neat feature. Using WASD controls, I could bind that key to Tab for example, and have the mouse scrolling the map. Much better.

**Comment by crudelios** [comment]
The key lag you're mentioning is actually implemented on purpose. You'll notice when you press the key, it scrolls one tile, stops half a second and then resumes scrolling. It's how the original game behaved and it's helpful when you want to scroll tile by tile.

The game is limited to your monitor's refresh rate, which usually is 60fps. I think the best solution for you would be to cap the refresh rate of your whole system to 30fps, that would also reduce the fps of your distro's GUI special effects.

Regarding using the mouse cursor to scroll: you can already do that if you click and hold the right mouse button, but I guess we could make it configurable.

**Comment by devnoname120** [comment]
Adding to the discussion, I think that for 2) it should be disabled by default on the Vita. With mouse emulation, it's pretty annoying when the virtual mouse accidentally touches the border, and it's highly impractical to use the virtual mouse to scroll using the borders.

**Comment by DwarfFighterCleric** [comment]
I think we can agree then that ability to disable mouse-scroll should be a priority, but while keep keyboard scrolling active. These have to be separate, not one tied to the other.  
Regarding the "keyboard input delay", that could be a valid argument, but then how come smooth scrolling doesn't have delay? Which proves that it can be done. Should be fairly simple to do and would enhance the overall experience.  
Thank god there's already an option to disable "hold X mouse button to scroll the map" entirely. On laptop touchpads that feature was causing havoc. For laptop touchpads, the less you rely on mouse button presses or drags, the better.

**Comment by devnoname120** [comment]
@DwarfFighterCleric Feel free to do a pull request. I've done lots of pull requests on julius but right now I'm incredibly busy and I can't work on it.

**Comment by DwarfFighterCleric** [comment]
Oh really, they do this for free? OMG I would never guess it

**Comment by bvschaik** [comment]
> Oh really, they do this for free? OMG I would never guess it

Yes. We do this for free. In our spare time. For fun. With comments like yours it's no longer fun, please show a little more respect for what we do.

Mouse scrolling can now be disabled in the options, so I'm closing this.
