### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [bvschaik/julius#58]
Would you like to add more error handling for return values from functions like the following?
- [fopen](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fopen.html "Open a stream.") ⇒ [graphics_save_screenshot](https://github.com/bvschaik/julius/blob/d8e7b3302e542d7787a2ac447f4664239ced2824/src/graphics/screenshot.c#L52)
- [fseek](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fseek.html "Reposition a file-position indicator.") ⇒ [io_read_file_into_buffer](https://github.com/bvschaik/julius/blob/159a5084a4a5e899d87c9ce89b7d330ae2141dc9/src/core/io.c#L7)
- [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [clear_dir_listing](https://github.com/bvschaik/julius/blob/4ccbf4ef472b43eedbb2b4c6fd8f36eab4e45f2d/src/core/dir.c#L14)

**Comment by bvschaik** [comment]
I suggest ignorance of Elfring a bit more.
