### ISSUE TITLE
Language pack download link & updated manual

### ISSUE THREAD

**Issue by sickchicken** [bvschaik/julius#589]
"You can download the patch files for your language here."
I think crudelios added this link for Augustus, but it's not in Julius mod github main page just yet.

And I made little installation guide for Korean players in language pack readme, but it's still not in there. Would you please double-check it for me?

[patch_readme_KR.txt](https://github.com/bvschaik/julius/files/6060988/patch_readme_KR.txt)

**Comment by bvschaik** [comment]
I updated the `patch_readme.txt` in the download with the addition of your Korean texts a few weeks ago.

I'll update the readme shortly.
