### ISSUE TITLE
Avoid potential for memory leaks

### ISSUE THREAD

**Issue by elfring** [bvschaik/julius#59]
[The implementation of the function “image_init”](https://github.com/bvschaik/julius/blob/d8e7b3302e542d7787a2ac447f4664239ced2824/src/core/image.c#L98 "Update candidate") tries to allocate memory for four data structures together.
It returns immediately if a function call failed. But this memory is not released if one of these allocations succeeded already.
How would you like to [fix such questionable software](https://en.wikipedia.org/wiki/Memory_leak#Programming_issues "Description for memory leaks")?

-----

Will an immediate program exit be achieved also after a partial memory allocation failure (instead of additional resource releases before)?

**Comment by bvschaik** [comment]
It's not a memory leak per se since the program exits when image_init returns zero. But you're right that there's room for improvement.
