### ISSUE TITLE
Julius thinks he owns my mouse cursor via my gamepad!

### ISSUE THREAD

**Issue by ArtySh0ck** [bvschaik/julius#591]
It's not a bug, im sure, but Julius needs a setting option for gamepad on\off

Problem:

Have a laptop with connected monitor and gamepad too for my wife to play her crazy gta-v. While its playing - screen of laptop is free to work, like right now ) but when i start julius (or augustus) and when left stick of gamepad (x360 controller) is using - a mouse cursor do movings! cant play. when i play some other game, Sacred for example - it's ok... gamepad does control game for connected monitor, and my mouse is free for using, no problems.

Thanks!

**Comment by crudelios** [comment]
Hi, this should be fixed now, but please test to make sure.

**Comment by ArtySh0ck** [comment]
Allright now, thanks!
