### ISSUE TITLE
Damascus start date

### ISSUE THREAD

**Issue by Riww** [bvschaik/julius#592]
Campaign Damascus shall start January 10 BC, as is implied from the mission selection screen. However, it actually starts 50 AD.
It is original game bug, which shall be fixed. Me thinks this can be done without changing the original files, just do
IF (city name=Damascus)   (or  campaign is level 9 military) 
THEN all date display -60 years.
I know this would be kind of "hack" still it improves player's experience and is worth the effort. Mission selection says 10 BC, then suddenly the date is 50 AD?!

**Comment by crudelios** [comment]
Frankly, I feel adding hacks for such a small oversight (and more broadly: adding specific hacks to fix anything at all) is not only ugly code-wise, but goes beyond the scope of Julius.

**Comment by bvschaik** [comment]
I agree with @crudelios: adding this "hack" would introduce a dependency between the code displaying dates and the city name/campaign id. Not only is that not a good idea from a clean code perspective, it might introduce unforeseen bugs in other parts of Julius. Not to mention that detecting "are we campaign mission Damascus?" is hard to do in the first place.

So therefore I'm closing this as won't fix.
