### ISSUE TITLE
I will miss the days when there were a lot of problems and ideas here

### ISSUE THREAD

**Issue by ArtySh0ck** [bvschaik/julius#595]
Thank you.

**Comment by crudelios** [comment]
No, thank **you** for the kind words!

Julius development is more or less done and new features are being added to Augustus, so there's more activity over there.

With that said, there are some things still being added to Julius. At the very least, I've been porting it to whatever I can remember 😉

**Comment by ArtySh0ck** [comment]
I want to say honest words of thanks for people who made and help to make Julius.
All of you - bring child memories, bring hours of pleasure
All of you - are not about money, are not about popularity, not about glory
All of you - are about sense of life. Just think, we born and die, but in the middle of this section you waste your time for those who, i believe, will try Julius after many years! It means, some of your time has been paid for another human.
And now i think, i love YOU even much more than i love Julius...

:cupid::cupid::cupid:

**Comment by CommonLoon102** [comment]
The label should be `wontfix` instead of `bug`.

**Comment by bvschaik** [comment]
Thanks all. Yes, this is a `wontfix` 😉 

Thanks for the loving words. It's been a rollercoaster ride from time to time, but to see people playing and enjoying your creation is very rewarding. Thanks for playing!
