### ISSUE TITLE
Starting screen and Advisor screens scaling up? (zoom, font size)

### ISSUE THREAD

**Issue by DwarfFighterCleric** [bvschaik/julius#598]
Hey, I know this is "done for free by volunteer labor", as it was made clear in that post HeHe  
But could we have some Scaling Up/Zoom feature for the starting screen and for the advisor screens?  
The text is so tiny when playing with game scale 70%.  
I don't think any game should cause me to risk start wearing glasses and have eye strain headaches?  
I feel like that would be easy to solve?  
And I'm not even playing this in 1080p like I had seen people playing out there, that must be insane.  
  
Real-time scaling/zooming inside the city screen itself would be nice too, but let's not aim too big for now.  
Remember, this is "done for free".  
  
Real-time window size adjusting is really nice too, that's a great feature.

**Comment by bvschaik** [comment]
You can adjust display scale in the options. If you have it set to 70%, no wonder that you can't read anything... Why set it so small if you can't read it? The default is 100%.

**Comment by DwarfFighterCleric** [comment]
Display scale can only be accessed at the start of the game, it's not an option you can change on the fly back and forth.  
What I'm talking about is to make advisor screens and the starting screen independent of Display Scale.  
Eventually, scale in-game UI too, but not essential for right now.  
  
I know it's a "free thing made by volunteers", but don't you think your product would have a better presentation if the starting screen of the game wasn't a tiny window surrounded by black borders? :P LOL  
This is how the game looks at 80%  
https://i.imgur.com/PYx1EJn.jpg

**Comment by crudelios** [comment]
It seems to me that what you really want is city zoom: The entire UI stays at the scale you want and you can view more or less of the city on command.

We actively decided not to implement city zoom in Julius. Augustus, however,  has built in city zoom as well as background image scaling on the menus (no black borders), but the buttons are still small.

Augustus however implements some big gameplay changes that may not entirely suit your taste. It's a trade-off you'll have to make.

**Comment by DwarfFighterCleric** [comment]
No. Not city zoom.
Advisor Screens (the screens that have text) and the starting screen

**Comment by crudelios** [comment]
> Do you even know this app?

I should since I'm one of the main developers.

Honestly I don't like your attitude. You claim to respect the fact that Julius is a "free thing made by volunteers" but then you mock when said volunteers take their time to help you.

I already said there's no way to fix this, so I'm closing the issue.
