### ISSUE TITLE
No options in main menu on Windows

### ISSUE THREAD

**Issue by IwoHerka** [bvschaik/julius#599]
Hi, the bug is really simple - the "Options" menu doesn't show up for me.
I'm on version 1.6.0, Windows 10 (Version 10.0.18363) and Caesar 3 version 1.1 from GOG.

**Comment by IwoHerka** [comment]
I checked that on version 1.5.1 the options work correctly.

**Comment by bvschaik** [comment]
Very weird, we didn't change anything about that in 1.6.0. Are you sure you are running julius.exe and not c3.exe? Could you attach a screenshot of the main menu?

**Comment by IwoHerka** [comment]
> Are you sure you are running julius.exe and not c3.exe?

I'm positive, I'm launching it exactly as the 1.5.1 version. Here is the screenshot:


![Capture](https://user-images.githubusercontent.com/9204550/116044318-0f1ce800-a671-11eb-99f4-410ece97f6ac.PNG)

**Comment by bvschaik** [comment]
The main menu from 1.6.0 should look like this (note the version number in the bottom left corner):
![city 2021-04-26 09 30 02](https://user-images.githubusercontent.com/104874/116045901-cf570000-a672-11eb-9f11-08ec4944c833.png)

The screenshot you posted looks like it's from 1.2.0: that has the editor but not the options, nor the version number on the screen. If you right-click the .exe, go to properties and then the tab "Details", what version does it list there? Also, in which folder do you have C3 installed?

Just to be sure: could you download [version 1.6.0](https://github.com/bvschaik/julius/wiki/Julius-release) again to make sure you have the correct version?

**Comment by IwoHerka** [comment]
@bvschaik I'm a dummy. No idea how, but somehow I've downloaded the 1.2.0. I've checked the links in the releases tab and they all point to the right version so probably I used some external link from reddit or something - no idea. Anyway, thank you for the quick response and sorry for taking your time!

**Comment by bvschaik** [comment]
No problem, enjoy the game!
