### ISSUE TITLE
Game is broken upon saving

### ISSUE THREAD

**Issue by atolstoy** [bvschaik/julius#6]
Hello again!
Last time I found a false issue, but now it's something different. I started building a city and proceeded to a quite sizeable settlement with three legions, pottery, oil and furniture industries, but I didn't save my game from the started. Finally I decided to save it and immediately the map got corrupted - most of objects were gone, but not all, oddly. I also got a population of 0. Please see the screenshots and have a look at the saved game as well.

https://yadi.sk/i/21kT2vWR3QPCw9
https://yadi.sk/i/nb5O8bv_3QPCxw
https://yadi.sk/d/dXkMbCcU3QPCyy

P.S. I was using the latest Julius code from your Master branch.

**Comment by bvschaik** [comment]
Hi again!

Yes, this is indeed a real bug: I forgot to save the grid with building IDs. I already fixed it in commit bcf1584eecc3778dfde7e73b62633d11342ad38e but I hadn't pushed that one yet.

I tried to fix your saved game but couldn't. You'll have to rebuild, sorry :(
