### ISSUE TITLE
Entire block of housing evolves immediately after placing Amphitheater

### ISSUE THREAD

**Issue by DwarfFighterCleric** [bvschaik/julius#600]
Not sure if this happened in the original game too? But marking as a bug anyway.  
  
IMAGE  
https://i.imgur.com/GjkYzul.png  
  
As soon as I placed the Amphitheater in a block, all the houses evolved immediately (instead of evolving only after a walker passed in front of it)
But what was really strange is that the house that is shown in the picture in the top right, near the industry, immediately evolved from a Large Shack (that was complaining about desirability) into a Small Casa.

**Comment by bvschaik** [comment]
This is expected behaviour: each venue type gives up to 5 extra "entertainment points" depending on city-wide coverage. For the nitty-gritty details, check [this thread](https://caesar3.heavengames.com/cgi-bin/caeforumscgi/display.cgi?action=ct&f=2,6325,,all).
