### ISSUE TITLE
Black Screen on launch

### ISSUE THREAD

**Issue by evillurker** [bvschaik/julius#601]
Vita FW: 3.60
When launching, I get a black screen, game won't launch
Used the GOG copy and put it on ux0:/data/julius as described
patched to the latest update

**Comment by crudelios** [comment]
Do you have a `julius-log.txt` on `ux0:/data/julius`?

Also, what's the Julius version you're trying to launch?

Also note that the game can take more than 10 seconds to load.

**Comment by evillurker** [comment]
No i dont have that file
I waited nearly 5 minutes and gave up on the loading
The version is the one that shows up on Gog.com - Caesar 3
C3.ENG is present as well

**Comment by crudelios** [comment]
I don't mean the Caesar 3 version but the actual Julius version which you downloaded.

The most recent is v1.6.0 and it should work (it works on my Vita).

**Comment by evillurker** [comment]
1.6.0 the latest vpk
:/
So sad, it's actually one of my favorites
I tested it on 2 of my vitas and none work sadly

**Comment by crudelios** [comment]
I'll have a look.

In the mean time, please try the unstable build.

**Comment by evillurker** [comment]
Which unstable build?
If you can contact me on discord it might be faster to communicate EvilLurker#3059
Thank you for your help

**Comment by crudelios** [comment]
This version:

https://julius.biancavanschaik.nl/download/julius-1.6.0.60-66d7540f-vita.vpk

There have been quite some changes to our Vita version since v1.6.0 so the latest development version may work fine for you.

Let me know if it works. If it doesn't, I'll chat you on discord for more info.

**Comment by evillurker** [comment]
Yep that dev release works for me
Thank you :)

**Comment by crudelios** [comment]
You're welcome!

As a bonus the unstable version is actually more stable and has better gamepad integration and overall performance than 1.6.0 anyway. So it's a win-win 😉
