### ISSUE TITLE
Russian translation: one string is missed

### ISSUE THREAD

**Issue by catch220** [bvschaik/julius#602]
Please add Russian translation for string in "Settings": "Disable map scrolling on window edge" = "Откл. перемещение по карте при движении за край дисплея".

**Comment by crudelios** [comment]
Thanks, this was actually an oversight as we already had the translation but never added it!

**Comment by bvschaik** [comment]
I've added the string.

Could you perhaps also translate these two? They're used when you try to configure a hotkey that is already in use:

- Hotkey already used
- This key combination is already assigned to the following action:

**Comment by crudelios** [comment]
@MSTVD provided the following translations:

```
{TR_HOTKEY_DUPLICATE_TITLE, "Горячая клавиша уже назначена"},
{TR_HOTKEY_DUPLICATE_MESSAGE, "Эта комбинация клавиш уже назначена на следующее действие:"},
```
