### ISSUE TITLE
Polish language isn't available in patches for Julius project

### ISSUE THREAD

**Issue by Valdesam** [bvschaik/julius#604]
Please add the polish language that will be realy awesome.

**Comment by crudelios** [comment]
Hi, 

I don't think there's an official Polish translation. 

If we are wrong and there is one, please let us know, especially if you have access to it.

Thank you!

**Comment by crudelios** [comment]
Hi, 

Yes it is, look here:

https://github.com/bvschaik/julius/wiki/Patches
