### ISSUE TITLE
Sprite bug with new Augustus feature

### ISSUE THREAD

**Issue by Kallydrael** [bvschaik/julius#607]
I dont know what happened. when i try to build any new building (roadblock, temple, guild or whatever) it doesnt have any sprite, and when the temple is complete it just goes dark and i cant interact with it, even delete is impossible. Here's a picture
![image](https://user-images.githubusercontent.com/84463125/118840497-d651e680-b89d-11eb-8f55-322a736a1603.png)

**Comment by gusowski1** [comment]
Probally you should report it to https://github.com/Keriew/augustus as this is the issue tracker for julius
