### ISSUE TITLE
Linguaggio

### ISSUE THREAD

**Issue by gianlore** [bvschaik/julius#611]
Il mio Caesar 3 italiano, diventa inglese ci ci metto sopra Julius?

**Comment by crudelios** [comment]
No, Julius resta Italiano.

**Comment by gianlore** [comment]
Perfetto, in tal caso lo scaricherò quanto prima e cercherò di installarlo sul mio sistema.
Grazie per la pronta risposta.
--
Inviato da Libero Mail per Android sabato, 05 giugno 2021, 07:39PM +02:00 da José Cadete  ***@***.*** :
