### ISSUE TITLE
Poor Sound Quality using Augustus 3.0.1 on Win 7x64

### ISSUE THREAD

**Issue by Enrada** [bvschaik/julius#612]
Hello all,

I have start using Augustus 3.0.1 around a week before.
In general, it works very fine and fulfills very most of my needs and desires on gameplay side.
Concerning the sound, 
it shows poor quality (at least on my system) as all audio files (music, speech, effects) are played slower than the original speed (around 90% I guess). 
I do not know if the lowered tempo is a random issue or maybe a "feature" which is intended from your side 
(from my side, I would prefer to have the original tempo instead of lower tempo)
... However, the audio timestretching algorithm shows a very, very poor quality and means a considerable detraction of pleasure on gameplay.
I would be very pleased if you could find a way to improve or remove this bad-working timestretching effect (or to make the usage selectable for user) for one of the next releases?
Many thanks in advance and both thumps up for this fulminant mod!

**Comment by gianlore** [comment]
when you copied the contents of the Augustus 3.01 zip file to the Caesar 3 directory, there was no "assets" directory? and the game started without asking for anything ?? there is an "assets?" directory in your system.

**Comment by Enrada** [comment]
I have extracted the zip file and have copied all the subfolders and files straight into the main game folder 
(the base game installation I have is provided by Steam), 
my Caesar 3 installation folder including the Augustus v3 content is this:

![Caesar 3 directory level 1](https://user-images.githubusercontent.com/85795573/121788471-cb088700-cbcd-11eb-8089-383f0d21425c.PNG)

**Comment by Enrada** [comment]
This picture shows the content I have added to the base installation (except subfolder "maps", but I guess this will not make a difference regarding the issue).

![Augustus content](https://user-images.githubusercontent.com/85795573/121788655-343cca00-cbcf-11eb-94ae-02b2880ab62b.PNG)

**Comment by crudelios** [comment]
This isn't a Julius issue, but Augustus.

Anyway,  try following the steps from here:

https://github.com/Keriew/augustus/issues/194

**Comment by Enrada** [comment]
Ah okay, 
sorry for confusion, 
I have followed the path starting from dispository with Augustus 3 files and thought to be on the correct place to report this.
Many thanks.

**Comment by gianlore** [comment]
Thank you for your answers, but I am extarendo the content of the file augustus3.01. zip I can't find the "assets" folder or manual, but I find this:
![image](https://user-images.githubusercontent.com/72648521/121788920-c80f9580-cbd1-11eb-9b56-09e022014c85.png)


To tell the truth, not even in the root directory of the Caesar 3 installation can I find an "Assets" directory
I do not think I will come to the end!

**Comment by gianlore** [comment]
x crudelios
ok, I'm confused !!!

**Comment by Enrada** [comment]
Okay, 
as the topic concerned to Augustus 3 is not correctly placed here, 
I will close this issue thread and open another one in the correct location right now. 
Many thanks!
