### ISSUE TITLE
Pause in Android version

### ISSUE THREAD

**Issue by catch220** [bvschaik/julius#613]
Hi all!
Playing on android tablet, I've bumped into a moment when I've badly need to pause the game to give the orders. I'm guessing that it's hard to add any onscreen "pause button", but is it viable to allow game speed 0 with "pause" function?

**Comment by crudelios** [comment]
Hey,

This is a good idea. I'd like to add a pause button, but I'm not really sure where to add it though.

**Comment by catch220** [comment]
In one hand, there are successful experiments with placing legion panel, so the pause button can be placed under legion panel. But in other hand, pause as a zero speed in properties tab is sufficient

**Comment by crudelios** [comment]
I could add a pause button that would appear on the top left corner only when touch is used (much like the X button when placing buildings). What do you think?

**Comment by bvschaik** [comment]
> I could add a pause button that would appear on the top left corner only when touch is used (much like the X button when placing buildings). What do you think?

Sounds good to me!

**Comment by crudelios** [comment]
Tentative implementation:

Game paused:
![city 2021-09-29 17 45 42](https://user-images.githubusercontent.com/6518876/135313097-c2ce1306-dd03-4475-a0e0-16381aec324f.png)

Game not paused:
![city 2021-09-29 17 45 49](https://user-images.githubusercontent.com/6518876/135313098-2e4dc207-8bf3-4400-93a6-1d137a34eacf.png)

I think this could be improved, suggestions are accepted.
