### ISSUE TITLE
Russian Language missed after update to 1.0.1.0

### ISSUE THREAD

**Issue by ARGAMX** [bvschaik/julius#614]
Hello.

I download Julius and Augustus for my Caesar III. My Caesar III is Russian version.
I have run Julius and Augustus but got message about patch 1.0.1.0 needed.
I have downloaded Russian patch, extracted and overwrite to game folder.
This didn't change anything - got the same error about patch 1.0.1.0 needed.

Ok. 
I have downloaded English patch, extracted and overwrite to game folder.
After that 1.0.1.0 error are gone.
But game now in English.

I have extracted Russian patch and overwrite to game folder again.
Game still in English.

In game settings there is no option to select language.
https://i.postimg.cc/0PY3sB5y/Screenshot-2021-07-05-at-21-04-54.png 

Looks like a bug.
Thanks!

**Comment by MSTVD** [comment]
У вас локализация от 1С или другая?

**Comment by ArtySh0ck** [comment]
Смотри, ты не можешь выбрать другой язык игры в настройках потому что его нет как опционального. 

У меня вот так:

![image](https://user-images.githubusercontent.com/46932541/124685535-1dda1380-deda-11eb-9fdc-f3d3558ca1d5.png)

Видишь папка "rus" ? Там лежат файлы необходимые для всех элементов игры где есть языковая переменная, будто то видео, звук, текст...

Я собирал себе сборку так : устанавливал версию от GOG (она английская), добавлял папку "rus" с переводом от 1С и патчил его. Ну и всё. Работает второй год, хотя обновляю "ночными" билдами.

Если хочешь могу скинуть тебе ссылку на такую сборку.

**Comment by ARGAMX** [comment]
> У вас локализация от 1С или другая?

Фиг его знает, русская версия, в которую я играл все детство под виндой.
А как это определить?
Видимо, это какая-то пиратка. Но она была русской изначально.

**Comment by ARGAMX** [comment]
> Смотри, ты не можешь выбрать другой язык игры в настройках потому что его нет как опционального.
> 
> У меня вот так:
> 
> ![image](https://user-images.githubusercontent.com/46932541/124686709-3f3bff00-dedc-11eb-9939-0c1dd03a3f1d.png)
> 
> Видишь папка "rus" ? Там лежат файлы необходимые для всех элементов игры где есть языковая переменная, будь то видео, звук, текст...
> 
> Я собирал себе сборку так : устанавливал версию от GOG (она английская), добавлял папку "rus" с переводом от 1С и патчил его. Ну и всё. Работает второй год, хотя обновляю "ночными" билдами.
> На самом деле проблем быть не должно, возможно что-то не так делаешь, хз.
> 
> Если хочешь могу скинуть тебе ссылку на такую сборку. Включает и eng и рус версию, с возможностью переключения между ними, всё пропатчено.

Спасибо больше, рабочий подход!
Все получилось!

Изначально я качал патчи и кидал их в корень, так как не было сказано иное.
Тем более английский патч таким образом накатился и работал исправно.
Возможно, наверно, в русском патче нужно хранить файлы по пути './rus' ?
Тогда бы они легли куда надо.

Мне кажется, если немного поправить архивы или экран закачки патчей, то этот момент был бы более прозрачным.

Спасибо!

**Comment by ArtySh0ck** [comment]
Пожалуйста, обращайтесь =)

ps: на счет фиксированного названия каталога как 'rus' есть сомнения, так как название этой папке я дал чисто спонтанно и назвал rus, игра видимо по содержимому определяет что это языковой пакет. Я думаю, можно называть как угодно, но только латиницей.

**Comment by ArtySh0ck** [comment]
Topic could be closed.

**Comment by MSTVD** [comment]
> > У вас локализация от 1С или другая?
> 
> Фиг его знает, русская версия, в которую я играл все детство под виндой.
> А как это определить?
> Видимо, это какая-то пиратка. Но она была русской изначально.

Можете пожалуйста прислать мне файлы вашей версии? Мне интересно узнать если это Фаргус

yburmin@gmail.com

**Comment by ARGAMX** [comment]
> Можете пожалуйста прислать мне файлы вашей версии? Мне интересно узнать если это Фаргус

https://disk.yandex.ru/d/p6L4VQw2hlLG7Q
