### ISSUE TITLE
Xbox port?

### ISSUE THREAD

**Issue by Xbox-Series-X-User** [bvschaik/julius#615]
Hello wonderful dev. Thanks to you I've been able to enjoy my favorite classic city builder game on many of the platforms I own. I can play caeser III with windows 98 on dosbox but it's extremely inconvenient. Now to the question at hand. Would it be possible to port to UWP for xbox series consoles? I have tried to on my own but I can't get passed the signing process it is beyond me. Adding to that even if I were to get it signed I had issues with the cmake finding the sdl2 libraries for some reason. Either way I hope you see this and know how much your work is appreciated.

**Comment by crudelios** [comment]
Hi,  thanks for your suggestion but right now this is not possible for two reasons:

1. We don't own a xbox to test and are totally unaware of the state of emulation/tools needed to do it. 
2. Julius requires `SDL_mixer`, which doesn't seem to be supported yet. While we could probably compile it ourselves, we'd also need to compile its dependencies, which again is to difficult considering we have zero experience with xbox development.

Obviously if anyone with better knowledge about xbox development came along, adapting Julius for a new platform is relatively trivial nowadays, so we're always open to that!

**Comment by Xbox-Series-X-User** [comment]
well the xbox isn't hacked or anything just has a developer mode which can run UWP's basically zip files with an exe in it, dependencies, cert, and appxmanifest.xml. Thanks for your reply I will continue to try and figure things out on my side until then I still use this amazing open-source engine on what is available. Best wishes

**Comment by crudelios** [comment]
Ah, well as I mentioned we have zero knowledge about xbox. It you do figure things out, please share!

**Comment by Xbox-Series-X-User** [comment]
will do
