### ISSUE TITLE
Earthquakes hitting warehouses can cause corruption.

### ISSUE THREAD

**Issue by Keriew** [bvschaik/julius#616]
Multiple part buildings hit by earthquakes can cause some tiles to become corrupted, making building grid link to wrong buildings and cause eternal fires. Link to a save which displays this behaviour: [earthquake bug.zip](https://github.com/bvschaik/julius/files/6947460/earthquake.bug.zip) While this matches the behaviour from Caesar 3, most of the other earthquake/corruption bugs have been fixed, so I thought it'd be a good idea to fix this one too.

Mechanism of the bug happening:

Earthquake tries to expand. Game calls ```advance_earthquake_to_tile``` from ```scenario/earthquake.c```, causing a warehouse to turn into the rubble. That tile then becomes an earthquake tile and the warehouse/storage bay that existed before has its image removed and its state is changed to ```BUILDING_STATE_DELETED_BY_GAME```. Before ```building_update_state``` is called (which would remove all the data of that warehouse/storage bay), ```advance_earthquake_to_tile``` is called again, advancing on a different rubble tile of that same warehouse. The rubble tile is destroyed via ```building_destroy_by_fire```, which calls ```destroy_linked_parts```. This causes all the tiles of the former warehouse to be destroyed again, included the one marked as ```BUILDING_STATE_DELETED_BY_GAME```, which adds it back to the building grid as the burning ruin. The building is later deleted by the game, which causes the next built building to share its id, linking rubble with that building.

**Comment by crudelios** [comment]
Really nice catch!

**Comment by Keriew** [comment]
Further problem, related to earthquakes:

Advancing earthquake calls ```building_destroy_by_fire``` which calls ```building_clear_related_data```. For warehouses/granaries, it marks their storage as inactive. If it touches the northernmost warehouse building tile, it'll also mark it as ```BUILDING_STATE_DELETED_BY_GAME```, which will eventually also call ```building_clear_related_data``` again. If a warehouse or granary is built between ```building_clear_related_data``` calls, the second call can mark its storage as unused, causing linking of storages.

If a granary or warehouse is set on fire (either earthquake or Mercury's curse), it will also call ```building_clear_related_data``` twice - once when originally set on fire, and second time, when the fire goes out and the building is converted to rubble. This can also cause linking of storages.

**Comment by bvschaik** [comment]
The solution for the linking of storages appears to be simple: set the building's `storage_id` to 0 in `building_clear_related_data()`.

I'll have to think about the corrupting tiles.
What exactly was the problem with the PR you opened?

**Comment by Keriew** [comment]
It prevents formation of the corrupted tiles on the earthquake lines, but doesn't prevent advancing earthquakes from destroying burning ruins and calling `destroy_linked_parts`  on an already destroyed buildings, so buildings built during expansion may get destroyed/corrupted if they match `prev/next_part_building_id`. I fixed it in Augustus by having earthquake not destroy burning ruins again (c2faa5d), but that makes numerous changes to the game state so writing an exception to tests was challenging.

![earthquake bug](https://user-images.githubusercontent.com/59965174/132041700-d0e5a423-eca9-4d2a-bfd5-c306aa7ea8f7.gif) Gif demonstrating the effect.

**Comment by bvschaik** [comment]
I tried the suggestion by @crudelios in the PR: unlinking the building parts when the warehouse first gets destroyed. This works perfectly, and perhaps most importantly: it doesn't cause any differences in the tests. Apparently we don't have a test where an earthquake destroys a warehouse, because that _will_ now result in differences.
