### ISSUE TITLE
Clearing the road to Rome sometimes fails to remove wall/aqueduct

### ISSUE THREAD

**Issue by Keriew** [bvschaik/julius#618]
Save attached: [aquebug.zip](https://github.com/bvschaik/julius/files/6951700/aquebug.zip)

Upon loading, the game tries to clear the road to Rome, because of the blocking aqueduct (same behaviour with wall in that place). However, it fails to do so, and destroys all the buildings, native huts included, both in the latest stable and unstable Julius releases.

In Caesar 3, the aqueduct is removed on the first attempt without destroying any of the buildings.

**Comment by crudelios** [comment]
You're on fire lately! Good catch.

**Comment by bvschaik** [comment]
Interesting one! Walls/aqueducts were never removed due to a mixed-up return value for the routing function.
