### ISSUE TITLE
android port speed of game not adjustable

### ISSUE THREAD

**Issue by Poligraf** [bvschaik/julius#619]
I am running an unofficial lineage OS  android 11 on a samaung galaxy tab A 2016.
I do not own other android devices to verity issue on other  devices.

Game speed is always set to max and reducing game speed does not appear to do anything.

No such issues on the linux port.

Running julius 1.6.0 and patch 1.0.1.0 applied.

Issue occurs both on apk from github and google play store

**Comment by bvschaik** [comment]
That's really weird. On my Android phone both the Options -> Speed settings panel and the sidebar work for setting the game speed. What speed does it say it's running at? Even though it's a relatively old tablet, you should definitely notice a huge difference between 10% and 500%.

Do note that the speed settings may not be saved when you close the game by switching to another app without going to File -> Exit game.

**Comment by Poligraf** [comment]
Ok, so I have downgraded from lineage 18 to the last official standard android 8.1.0 

On 8.1.0 no issue on controlling speed of game, everything works fine as expected.

Reinstalled unofficial lineageOS 18 (android 11) from https://forum.xda-developers.com/t/lineageos-18-1-for-sm-t580-gtaxlwifi.4274293/  and speed is not controllable. Game music and videos run fine.

**Comment by Poligraf** [comment]
logcat
[logcat.txt](https://github.com/bvschaik/julius/files/7021091/logcat.txt)

**Comment by Poligraf** [comment]
Borrowed another android device. One PLus One 2. Flashed lineage OS 18. Installed game. Issue does not occur. Problem seems to be specific to ROM above

**Comment by crudelios** [comment]
This is very strange. Out of curiosity, besides the speed issue, did videos work at all on that rom version M

**Comment by Poligraf** [comment]
That is why I logged the bug, thinking that it was a testing issue and not a rom issue.

The video of caesar getting angry and other in game videos seem to run fine. Its only speed that is uncontrollable.
