### ISSUE TITLE
Incorrect images in sidepanel when selecting "Clear Land" and "Build Roads" tools

### ISSUE THREAD

**Issue by Ouaz** [bvschaik/julius#620]
Hi,

Currently, both in Julius and Augustus, the image displayed for _Clear Land_ and _Build Roads_ tools are the one for _Build Housing_ tool:

![sidepanel_housing_tool](https://user-images.githubusercontent.com/11946570/132069578-f16c81ed-8575-4ec8-af76-0d35d563dc3a.png)

When selecting _Clear Land_ tool in the sidepanel, this image should be displayed:

![sidepanel_clearland_imagel](https://user-images.githubusercontent.com/11946570/132069385-167cffcf-f74e-444e-9084-8c8471c6ecc4.png)

When selecting _Build Roads_ tool in the sidepanel, this image should be displayed:

![sidepanel_roads_imagel](https://user-images.githubusercontent.com/11946570/132069477-f9ce20fe-e969-448f-87d0-939710e85886.png)

These two images are in `c3.sg2`, in `panelwindows.bmp`.

Note: I tested in C3 vanilla, and the correct images are displayed.

(bug report fetched from[ Joey Maximus on Caesar III Heaven forums](https://caesar3.heavengames.com/cgi-bin/caeforumscgi/display.cgi?action=st&fn=2&tn=7838&st=47#post48), thanks to him)

**Comment by bvschaik** [comment]
Thanks for reporting!

It was working in 1.5.0, it looks like the functionality fell over when we refactored the building menus. Also for the other buildings it wasn't working properly. I've restored the old behaviour, and also made the images change when you select a building for construction using a hotkey.

**Comment by Ouaz** [comment]
Thank you!

And nice work for the additional enhancements!
