### ISSUE TITLE
Oops, crashed with signal 11 :( when building senate 

### ISSUE THREAD

**Issue by JamesBolivar** [bvschaik/julius#622]
Greetings
Crash (msg from log in title) happens immidiately, everytime, with julius 1.6 aswell as with julius 1.5, CD version of C3 with update to 1.1 on freshly installed W10 - first level, first try, not much done before trying to build the senate.

Thx in advance

**Comment by crudelios** [comment]
I can't reproduce this on android but I'll try on windows.

Either way, you can have a corrupted C3 file somewhere. Could even be due to the CD, because it's old. Can you try reinstalling, please?

**Comment by JamesBolivar** [comment]
Building the Senate works when done from C3.
Reinstalling the game  from CD solved the problem.
I guess my installation was somehow corrupted.

Thanks for your support.
