### ISSUE TITLE
Minor fixes requested for french translation

### ISSUE THREAD

**Issue by Ouaz** [bvschaik/julius#625]
Hi,

Two french strings need a little fix in Julius:

![build_clone_option_french](https://user-images.githubusercontent.com/11946570/135674184-621664df-181e-436b-82d6-7b371ef9acd8.png)

**Fix ->** `TR_HOTKEY_BUILD_CLONE` Cloner l'objet sous le curseur

![build_all_temples_french](https://user-images.githubusercontent.com/11946570/135674161-e16b0596-d8d0-4983-add8-067b8443ff4d.png)

**Fix ->** `TR_BUILD_ALL_TEMPLES` Tous

"All" is translated "Tous" in this case, because it means "Tous les temples" (All the temples)

These translation fixes have already been committed to Augustus.

I could have fork the repo and open a PR, but I'm currently sat on the Senate steps, like a lazy unemployed fella. :yum:

**Comment by bvschaik** [comment]
Updated them, thanks!
