### ISSUE TITLE
Translation request: Korean

### ISSUE THREAD

**Issue by bvschaik** [bvschaik/julius#627]
We're nearing release 1.7, and we're missing translations of three strings into Korean:

- "Disable map scrolling on window edge"
- "Hotkey already used"
- "This key combination is already assigned to the following action:"

Could someone translate these into Korean and post them here?
@fetchinist / @sickchicken: you've contributed before, could you perhaps help?

**Comment by fetchinist** [comment]
"Disable map scrolling on window edge"
"창 가장자리 스크롤 끄기"

"Hotkey already used"
"단축키가 이미 사용 중"

"This key combination is already assigned to the following action:"
"해당 키 조합은 이미 다음의 행동에 할당되어 있습니다:"
