### ISSUE TITLE
Building while paused

### ISSUE THREAD

**Issue by crudelios** [bvschaik/julius#63]
**Describe the bug**
Julius allows building while paused.

**To Reproduce**
1. Pause the game.
2. Make sure you don't owe Caesar more than 5000 dn otherwise you won't observe the bug :P
3. Build something.

**Expected behavior**
Nothing should be built.

**Actual behavior**
A shiny new building appears.

**Additional context**
Line 133 of `city.c` has the following code:
`if (tile->grid_offset /*&& !game_state_is_paused()*/) { // TODO FIXME`

I uncommented the code and observed no odd behavior. Why is this commented, did I miss something or is it just for debugging purposes?

**Comment by crudelios** [comment]
Oh ok, I thought there might be a bug I didn't know about... I have to say it's very useful to be able to build while paused, as it allows for better city planning without feeling any pressure. It's just a shame any building you demolish doesn't disappear while the game is paused.

**Comment by jdmillard** [comment]
It is a nice convenience, but if the priority is mirroring the original, then this should be removed. I personally don't feel strongly either way.

**Comment by Hirosimych** [comment]
That's a great feature, actually. Please, make it optional.

**Comment by XJDHDR** [comment]
I would say the ideal behaviour is that default should be mirror the original behaviour but add an option to enable placing buildings while paused.

**Comment by devnoname120** [comment]
Considering that the game's speed can already be changed to be very slow in the original game, imho it makes sense to enable building while paused without an option.

**Comment by crudelios** [comment]
Since building while pausing was intended, I'm closing the issue. Feel free to reopen it if you want.

**Comment by ralphcook** [comment]
Why do you think this was intended? Perhaps you meant that bvschaik intended it for convenience, as opposed to being intended in the original game? 

I have a small desire that it be put back to the original behavior, but it's not a big deal -- greatly slowing the game is similar, as already pointed out.

**Comment by crudelios** [comment]
This was intended for the original game, as programmers had to explicitly add a function to check if the game was paused.

Bvschaik changed it for convenience.

**Comment by ralphcook** [comment]
I don't agree that we can tell it was "intended for the original game"; I think it unlikely that we can discern "original" intent much from code. I'd still be in favor of putting it back the way it was, but, as I said before, it isn't a big deal.
