### ISSUE TITLE
Android: resolution scale and virtual keyboard

### ISSUE THREAD

**Issue by Ouaz** [bvschaik/julius#631]
Hi,

I installed Julius on Android to see how it runs. And this is impressive, it works perfectly. Playing Caesar III on the go is really a nice experience.

But I have two questions:

1) Why is it impossible to set a display scale custom value? I saw on the log that the resolution is auto-set at launch (1440x900 downscaled to 1261 x 803), but everything is still too tiny for my big fingers. I tried to force a custom value in `julius.ini` but it does nothing.
There's still some place in the UI to make things bigger, especially in portrait mode, which simply looks like the goo' old Caesar III in 4:3 format. And also in landscape mode, where there's some space on the side panel bottom (the population stat could be cut, as it is also displayed in the upper menu bar).
For my part, I don't mind the blurry graphics on a handheld device, I just want things to be bigger. :smile: 

2) Could it be possible to add a virtual keyboard to Julius, like in ScummVM Android ?
It's a semi-transparent keyboard, toggled by a button on the upper right corner of the screen:

![scummvm-android_virtual_keyboard](https://user-images.githubusercontent.com/11946570/138507729-651fb04b-e6f3-48a6-bc70-71ff29c91bb0.jpg)

The game is still playable on the background, with the virtual keyboard used for shortcuts, and it can be hidden quickly simply by pressing the dedicated button.

It would work well in Julius, especially on portrait mode, allowing to use the usual shorcuts (Fire, Damage, Advisors, etc), while still being able to drag the map.

Thanks in advance for the answer.

**Comment by catch220** [comment]
Hello!

I'm frequently playing Julius on a business trip on 6 inch phone. So it will be a great deal for me, if there will be option to downscale resolution. No matter if it will be blurry graphics or big pixels... 

Main device to play is a 8 inch tablet, and somehow there are no problems to touch precisely, especially with that new "Pause" button (many thanks for that).

**Comment by Ouaz** [comment]
I post this here, maybe some people could be interested (if it is not allowed, please, feel free to delete this post).

I installed a virtual keyboard app that allows to use a keyboard inside Julius and Augustus, and all hotkeys function properly (except arrow keys, but it is useless anyway).

Despite its name, **Hacker's Keyboard** is 100% safe and is actually a free open-source project on Github: https://github.com/klausw/hackerskeyboard (can be also download via the Google Store). No collected data, no dubious permissions (in fact, it's safer than any OEM built-in keyboard, or GBoard)

On left Julius, on right Augustus (with Fn key enabled)

![Julius_keyboard](https://user-images.githubusercontent.com/11946570/156442469-443739cd-7cb8-46dd-bae8-7f7a938c1a7e.png) ![augustus_keyboard](https://user-images.githubusercontent.com/11946570/156442744-1385f74b-b7ee-4185-979b-6791d8d613df.png)

These screenshots have been taken with Hacker's Keyboard default settings, but it's possible to modify the keyboard height (both in portrait and landscape mode, separatly), key size, color theme, etc. Language is automatically detected through the system language (here's AZERTY aka french keyboard)

It perfectly works on Android 8.1, but I can't assure it will work flawlessy starting from Android 10, as the support has been discontinued. It is very light on RAM (2 MB consumption, up to 10).

Installation is pretty simple: download and launch the app, then follow the instructions displayed on the main page to activate the keyboard (don't be afraid by the warning message when activating it, it's a default message when any third-party keyboard is installed on an Android device).

**The important thing to check is the "Permanent notification" setting:**

![perm_notif](https://user-images.githubusercontent.com/11946570/156443694-880b6d10-63a4-473a-b462-6d25cad54f53.png)

which allows to call the keyboard in Julius/Augustus, by clicking its icon in the Notification bar. Julius and Augustus are still playable even when the keyboard is active. To close the keyboard, just swipe down it with a gesture or click on the "Back" button of your device. To open it again, just click the notification bar again.

All hotkeys are working fine.
To clone a building, just drag the building (do not click on it) a bit to put focus on it, then press the hotkey.
To display a relative overlay (Augustus), do the same thing.

Feel free to ask any question here (if allowed), if you have trouble to install it or use it.

**Comment by catch220** [comment]
Hello! 
Are there any chances to make things larger to play with 6 inch? Here is the log with resolution changing, and the last resolution mentioned is 2160 x 1080. Can I force 960 x 480 resolution with ini file or other option?


INFO: Creating screen 1080 x 2160, fullscreen, driver: Android
INFO: pixel format wanted SDL_PIXELFORMAT_RGBX8888 (2), got SDL_PIXELFORMAT_RGBX8888 (2)
INFO: Creating renderer
INFO: Maximum scale of 168 applied
INFO: Auto-setting scale to 168
INFO: Texture created: 642 x 1242
INFO: Model loaded
INFO: Loading audio files
INFO: Window resized to 1080 x 2160
INFO: Maximum scale of 168 applied
INFO: Auto-setting scale to 168
INFO: Texture created: 642 x 1285
INFO: System resize to 1080 x 2160
INFO: Window resized to 2160 x 1080
INFO: Maximum scale of 225 applied
INFO: Auto-setting scale to 225
INFO: Texture created: 960 x 480
INFO: System resize to 2160 x 1080
INFO: Loading saved game  Quaestor cont3.sav

**Comment by crudelios** [comment]
In landscape mode the game is already running at 960x480 (and it's running at 642x1285 in portrait mode).

A height of 480 is the minimum the game accepts. Likewise, the minimum width is 640.

Your game is already scaling to the minimum width and height, so it can't scale any more.

Truth be told, the game runs well on tablets but not so much on phones.

**Comment by bvschaik** [comment]
You can now scale the display on Android tablets, so I'm closing this issue.

**Comment by Ouaz** [comment]
> You can now scale the display on Android tablets, so I'm closing this issue.

Thank you very much!

I'll test it tonight, once I get hands on the tablet. Such a good news! :+1:
