### ISSUE TITLE
Auto-select legions when cycling through and not close military sidebar after issuing an order

### ISSUE THREAD

**Issue by Ouaz** [bvschaik/julius#633]
Moving several legions in a row from point A to point B is still a bit cumbersome, requiring too much mouse clicks, even if the military sidebar is quite a godsend.

Current behavior to move 6 legions to the same destination point using the military sidebar requires a minimum of 17 clicks (without misclicks on this damned legion flags), because after issuing an order, the cursor loses focus on legions and the military sidebar closes each time (requiring to click again on a legion flag, to gain focus again on legions and re-open the military sidebar)

Requests:

1) Auto-select the legion when using the military sidebar arrows or the "L" keyboard shortcut.
2) After an order has been issued, the military sidebar stays opened, so it's possible to click directly on its arrows, to gain focus on the next legion and select it automatically, then set the destination point (and this, without moving the map!).
3) If the player changes his mind and wants to stop moving legions, ESC (or right-clicking anywhere on the map) closes the military sidebar (current behavior anyway)

Clicks reduced to 6-11 depending the used process (without any risk of misclicks ^^).

Thanks for reading (I hope I explained well...)

**Comment by crudelios** [comment]
Hi,

> Auto-select the legion when using the military sidebar arrows or the "L" keyboard shortcut.

This is the current behaviour. If you cycle through legions you can immediately control them

> After an order has been issued, the military sidebar stays opened, so it's possible to click directly on its arrows, to gain focus on the next legion and select it automatically, then set the destination point (and this, without moving the map!).

This one is harder as there's not a consensus on whether we should exit military mode when clicking a legion (current behaviour) or keep the military unit selected.

The way the military sidebar works, it requires having one legion selected, so there's also no easy way to deselect a legion (when moving it) and keeping the military sidebar active.

Anyway, this can be up for review. Attached @bvschaik 

> If the player changes his mind and wants to stop moving legions, ESC (or right-clicking anywhere on the map) closes the military sidebar (current behavior anyway)

Yeah, this is the current behaviour and it should be kept 👍

**Comment by Ouaz** [comment]
Hello!

> > Auto-select the legion when using the military sidebar arrows or the "L" keyboard shortcut.
> This is the current behaviour. If you cycle through legions you can immediately control them

Did I miss something? When using the "L" shortcut, it only centers the screen on a legion. I still have to click on the legion to take control of it.
But after clicking a legion, then using the "L" shorcut, it keeps focus on cycled through legions (until an order is issued).

So the request was when using the "L" shorcut, the screen is centered on a legion, but it also selects the legion automatically (for each legion in the cycle). Along with setting a bookmark to the destination point, it would be the fastest way to move 6 legions in row: L , F1, click, L, F1, click, and so on.

> This one is harder as there's not a consensus on whether we should exit military mode when clicking a legion (current behaviour) or keep the military unit selected.
> The way the military sidebar works, it requires having one legion selected, so there's also no easy way to deselect a legion (when moving it) and keeping the military sidebar active.

Deselecting the legion after issuing an order makes more sense... but it has to close the military sidebar at the same time. Yep, it seems it would require too much work to change that.

**Comment by bvschaik** [comment]
It's been a while, but:

> In a few words, "L" key = center + click on a legion. Is this possible?

Yes, I just implemented it.

**Comment by Ouaz** [comment]
Haha, this was... unexpected.^^

I tested and it works perfectly. Much more "fluid" to control several legions now.

Thank you!
