### ISSUE TITLE
Not working on Windows 11

### ISSUE THREAD

**Issue by amengaji** [bvschaik/julius#634]
Caesar 3 or Julius.exe is not opening in Windows 11. 
Have a steam version installed. Installed the Julius Release 1.7.0 and tried. Nothing happens. No window opens.

**Comment by crudelios** [comment]
This is strange, I have windows 11 and have no such issue.

Can you post `julius-log.txt`, please? It's on the same directory of `julius.exe`.

**Comment by amengaji** [comment]
Found the issue. c3_model.txt was giving error. Re-installed and now it's working fine.
