### ISSUE TITLE
Wrong image length?

### ISSUE THREAD

**Issue by crudelios** [bvschaik/julius#637]
https://github.com/bvschaik/julius/blob/14ccc48a48331bcc2461463d825b50648e572b02/src/core/image.c#L381

Shouldn't this be `char_size * (char_size + letter_spacing)`?

**Comment by bvschaik** [comment]
It should indeed, or even better: `img->width * img->height`.
Technically these fields aren't used for non-isometric internal images, so in this case it doesn't lead to problems if it's wrong.
