### ISSUE TITLE
Traditional chinese: v2 fonts don't seem to load properly

### ISSUE THREAD

**Issue by crudelios** [bvschaik/julius#638]
It seems something is wrong either with the font parser or with the `rome2.555` of the Traditional Chinese fonts.

The displayed characters are entirely different depending on the version, and in the some cases the characters don't seem to fit in the font size (they become truncated).

Here's some comparison images:

![config_trad_chinese_v1_v2](https://user-images.githubusercontent.com/6518876/150784894-5972d80f-7e38-439b-851e-d56117d941d8.png)

Config window

![main_menu_trad_chinese_v1_v2](https://user-images.githubusercontent.com/6518876/150784925-4aaf495d-c2e7-4970-842f-ce2065403125.png)

Main menu

**Comment by bvschaik** [comment]
I'm surprised no one complained about this before... I accidentally uploaded the Simplified Chinese font file as the Traditional Chinese one. Since the number of characters in those two font files are different, that makes it look like gibberish. I've uploaded the correct one to the Patches wiki page.

**Comment by ltaskpt** [comment]
The simplified file 'rome-v2.555' seems wrong. 
![image](https://github.com/bvschaik/julius/assets/12380166/97b5a479-9f3d-4617-9729-025db119ab54)

**Comment by bvschaik** [comment]
@ltaskpt That's what it looks like when you use the .555 font file for Simplified Chinese but the .eng files from Traditional Chinese. Please use the right combination. The correct combinations can be downloaded from the [patches page](https://github.com/bvschaik/julius/wiki/Patches).
