### ISSUE TITLE
Support for the Japanese release?

### ISSUE THREAD

**Issue by IcySon55** [bvschaik/julius#639]
I just got my hands on the Japanese release of Caesar 3 and tried it out with Julius.

It of course doesn't work all that well. The text is stored in Shift-JIS most likely and what we get on the screen is, gibberish.

I can provide files as needed to get this version supported. Also of note, this version never received patch v1.0.1.0.
I can also help translate any new lines that the game doesn't include, for things like v1.0.1.0 features and Julius features.

It's been a long hunt for this version. It's surreal to witness...

![DSC_0210](https://user-images.githubusercontent.com/4888934/150826029-4e6b2282-81cd-4713-89db-730e07ad51de.JPG)

**Comment by bvschaik** [comment]
Great! We knew the version existed but without someone to help with translations and testing it's very hard to implement support. I briefly looked into Shift-JIS and it'll be tough to support that encoding...

For starters, could you send me the C3.eng and C3_mm.eng files so I can have a closer look? Either by email (bvschaik AT gmail DOT com) or upload here.

**Comment by IcySon55** [comment]
The project has been taken on!
