### ISSUE TITLE
Simplified and Traditional Chinese patch files are missing c3_mm.eng

### ISSUE THREAD

**Issue by crudelios** [bvschaik/julius#644]
Because those files are missing, they won't appear as available languages on the config window.

If you somehow lost the files, here they are:

[c3_mm.zip](https://github.com/bvschaik/julius/files/8169097/c3_mm.zip)

**Comment by bvschaik** [comment]
They weren't in the patches because those files are unchanged from the originals. But anyway, added 'em just to be sure.

**Comment by crudelios** [comment]
Ah, makes sense. Then an alternative fix is not to check for those files as a requirement for the directory to appear as an available language.

**Comment by bvschaik** [comment]
I think you're mixing things up: the patches are for people who already have that language but are missing the changes made from 1.0 to 1.1. You're after adding an alternative language to another language-version of Julius.
