### ISSUE TITLE
Pharaoh port?

### ISSUE THREAD

**Issue by Crescendo-BLYAT** [bvschaik/julius#646]
Could you please also port this for Pharaoh?
Is it doable or not?

Thanks a lot.

**Comment by crudelios** [comment]
1. It took 10 years to develop this open-source alternative, so you have your answer there.
2. However, there was a guy that was adapting Augustus code to Pharaoh, and he made some progress. The code is on github on a fork of either Julius or Augustus, but I don't remember which one.

Anyway, best to wait for Pharaoh: ANE, which will have improved graphics anyway!

**Comment by bvschaik** [comment]
The Pharaoh fork is [this one](https://github.com/Banderi/Ozymandias).

**Comment by Crescendo-BLYAT** [comment]
Thanks a lot for your hardwork & yeah I get the idea but thanks also to you that laid the groundwork for this to be possible....
