### ISSUE TITLE
Can't compile on Mac OS 10.4

### ISSUE THREAD

**Issue by lubert** [bvschaik/julius#650]
I'm trying to compile Julius on a Powerbook G4 TI 1.0ghz with Mac OS 10.4.

What I ran:
```
cmake .
make
```
Error I received:
```
/bin/sh: line 1: iconutil: command not found
```

I haven't found anything definitive, but I think `iconutil` was introduced in a later version of Mac OS X. Not sure if you have any ideas @evanmiller, was trying to compile after I saw your patch got merged in. Appreciate any leads!

**Comment by evanmiller** [comment]
@lubert You are asking the right questions I see!

I suggest taking a look at the patches in MacPorts:

https://github.com/macports/macports-ports/tree/master/games/julius-caesar-3/files

The second patch doesn't quite work on 10.4 because Tiger can't read PNG files in ICNS files, but you can just rip out that `makeicns` line. If there's interest I might modify that patch to produce an icon that will work on Tiger.

In general, I'm a big fan of MacPorts for installing software on Tiger. It takes a little bit of work to set up properly but it opens up a world of patched open-source software.

**Comment by lubert** [comment]
Ah, thanks for the lead!

I've made some progress, patching the CMakeLists.txt with the macports changes works, though I also needed to install a more recent version of gcc to get past some of the compiler flag errors.

The build finished, though exited immediately with an SDL error. Seems like the version of SDL that I have locally doesn't support joysticks, which Julius looks for. I'm actually trying out TigerPorts from your fork, and attempting to see I can build SDL2 on Tiger with joystick support.

**Comment by evanmiller** [comment]
You have made it deep into the rabbit hole! The TigerPorts SDL2 that you discovered was going to be my next suggestion, and includes some joystick patches which you probably saw. 

MacPorts includes a GCC7 that works pretty well on Tiger. There are a couple of run-time oddities with C++ projects, but overall it's a reliable and modern-ish compiler.

To get Julius running on a G3 iMac, I had to remove the Caesar 3 video files. The A/V support should be a bit better on a G4, so I'll be curious as to whether the in-game videos work on your system.

The final bit of work I did related to this all-important Julius on Tiger endeavor was to patch `unshield` to work properly on PowerPC. There's a [good-enough](https://github.com/macports/macports-ports/pull/14364) fix included in MacPorts, and a [better one](https://github.com/twogood/unshield/pull/143) upstream.

**Comment by lubert** [comment]
@crudelios I've lost the console output, but the SDL error was something like `Could not initialize SDL: joystick support missing`, which appears to be logged by https://github.com/bvschaik/julius/blob/0c260f8bf30d44637038861f76b2dfc48ebe334a/src/platform/julius.c#L395-L398

Anyways last night, I installed gcc7, libsdl2, and libsdl2_mixer from TigerPorts, and with the patches linked to skip icon generation and remove the `CMAKE_OSX_DEPLOYMENT_TARGET`. The build succeeds and doesn't crash on load, and I've managed to get a little farther to the data folder chooser, but it crashes after loading with:

```
Exception:  EXC_BAD_ACCESS (0x0001)
Codes:      KERN_INVALID_ADDRESS (0x0001) at 0x301760a0

Thread 0 Crashed:
0   com.github.bvschaik.julius 	0x00087b58 difficulty_starting_favor + 56
1   com.github.bvschaik.julius 	0x000bbc1c scenario_settings_init + 80
2   com.github.bvschaik.julius 	0x0008ab78 game_pre_init + 44
3   com.github.bvschaik.julius 	0x00007dac pre_init + 412
4   com.github.bvschaik.julius 	0x00007e80 setup + 128
5   com.github.bvschaik.julius 	0x0000807c main + 68
6   com.github.bvschaik.julius 	0x00005a64 _start + 760
7   com.github.bvschaik.julius 	0x00005768 start + 48
```
@evanmiller I didn't see your comment regarding unshield, might try that later today

**Comment by lubert** [comment]
Update, turns out it was the data files, doesn't work with the original mac data files, but worked after I used the GOG files. Thanks for the help everyone!
