### ISSUE TITLE
Docks/wharves/shipyards corruption after catching fire

### ISSUE THREAD

**Issue by crudelios** [bvschaik/julius#651]
This bug has been plaguing Augustus for a while but it turns out to be an original bug! @Keriew discovered the cause.

If a waterside building catches fire and you immediately rotate the map, the building that caught fire becomes corrupted. It no longer appears to be on fire but it can't be selected or deleted anymore. If you wait for a few ticks before rotating the map, the bug won't happen.

This has been fixed on b92ddf4e73b04bb1e81b1ea76efe490ef9d1d43b in Augustus and I think it should be fixed here too, as it doesn't change the gameplay.

**Comment by bvschaik** [comment]
Nice find!

Agreed, I cherry-picked the change.
