### ISSUE TITLE
Caesar's Legions calculation wrong?

### ISSUE THREAD

**Issue by TheRealAyCe** [bvschaik/julius#655]
https://github.com/bvschaik/julius/blob/805b3333f66f6b8bc13431f4ce3bda71dbd86f84/src/city/emperor.c#L135-L144

A legion is 4x4 men, correct?

I think in the original game Caesar sent 2 legions at first, and then 1 more each time until max 6, if I'm not mistaken. This seems like 2,4,6,9, which sounds excessive.

Hmm, after checking it with the original game I may have been mistaken. Can someone else please weigh in?

**Comment by bvschaik** [comment]
I checked against the original and the numbers are correct. Be aware that the numbers you see here are further modified based on difficulty level. The numbers here are for "hard" difficulty; for "normal" difficulty it's 80%, for example.
