### ISSUE TITLE
Replace tinyfiledialogs

### ISSUE THREAD

**Issue by crudelios** [bvschaik/julius#664]
The external lib tinyfiledialogs is bloated and has some safety issues.

Maybe we should replace it with [`noc_file_dialog.h`](https://github.com/guillaumechereau/noc/blob/master/noc_file_dialog.h) ?

**Comment by bvschaik** [comment]
The disadvantage for Linux is that we then need to link to libgtk, while there's no good reason to want that. Maybe roll our own/strip tinyfiledialogs?

**Comment by crudelios** [comment]
We could do that as well. I'm not sure how tinyfiledialogs is doing it for linux without linking to anything actually.

**Comment by crudelios** [comment]
I just had a slightly better look at tinyfiledialogs. Turns out the code problems and bloat are what allow it to not rely on anything.

We can remove some things like the color picker but the code will always be kinda large.
