### ISSUE TITLE
“This building needs road access” when building anything near a highway

### ISSUE THREAD

**Issue by Miha-x64** [bvschaik/julius#668]
Highway is a sort of road, isn't it?

Discovered in `augustus-3.2.0.222-6c272b3d-linux` but I guess the issue actually comes from Julius.

![image](https://user-images.githubusercontent.com/14016119/210556398-705b9553-11de-4633-959c-3b8b9306bae5.png)

P. S. Thanks for your work, this is fantastic!

**Comment by crudelios** [comment]
This is intended.

Highway doesn't count as a road for building access or for roaming walkers.

They are only intended to be used as travelling paths for destination walkers.

When v4.0.0 is released sometime this century, there'll be a manual that will properly explain the highway mechanics!

**Comment by bvschaik** [comment]
And highways are Augustus-only.

**Comment by crudelios** [comment]
Oh I didn't even notice this was on Julius.

**Comment by Miha-x64** [comment]
Thanks @bvschaik, my bad.
