### ISSUE TITLE
RPI 4, RetroPie, Will Not Launch 

### ISSUE THREAD

**Issue by JSchul72** [bvschaik/julius#671]
Attempting to run Julius/Augustus on a Pi 4 with RetroPie and I think Raspbian Buster v10?

Unfortunately I am not savvy enough to be able to take a screenshot or otherwise save or be able to move text directly from the log via the terminal to the body of this post, but the error I get when attempting to launch Julius from RetroPie is:

/opt/RetroPie/roms/ports/julius/julius

/home/pi/RetroPie/roms/ports/Caesar3

ERROR: 'c3.eng' or 'c3_mm.eng' files not found or too large

I'm using the version of C3 purchased and downloaded from gog.com. I checked the folders referenced and both files are present.

As a guess, maybe the application is expecting the files to be in a specific location and not finding them? I have the Android version of this application and it works great on my phone :) I understand there have been some issues with the app running on the Pi 4 and am prepared for the answer if that's why I can't get it to run. Any help appreciated/more details on my system or the error available upon request, thank you.

**Comment by JSchul72** [comment]
Hello---

It appears I misspoke :/

The referenced files are in the directory
home/pi/RetroPie/roms/ports/caesar3/app

subfolder.

As an experiment I tried copying the 2 files the app was looking for into
the /caesar3 file. Still doesn't work but now there is new log stuff:


Detected Language: English
Detected Encoding: 1252
Creating Screen 1360 x 768, Fullscreen, driver: KMSDRM
Creating renderer
Texture created: 1360 x 768
ERROR: unable to load main graphics

So this could maybe mean moving more files from the sub to the parent
folder?

Thank you for your help :)

**Comment by bvschaik** [comment]
Either move all of the files in `app` to the main folder, or just use `/home/pi/RetroPie/roms/ports/caesar3/app` as directory for Julius. The game initially checks for the presence of the two .eng files to verify a Caesar 3 installation, but it needs most of the other files as well to run.

**Comment by JSchul72** [comment]
As you were sending the previous message to me, I decided to try for myself
to copy the files (the idea being if the app needed files from the /app sub
they would still be there)---got the game to successfully load!

Thank you very much!

**Comment by bvschaik** [comment]
Glad you got it working, enjoy!
