### ISSUE TITLE
Show water range when building a blocked reservoir

### ISSUE THREAD

**Issue by feiyunw** [bvschaik/julius#680]
When building a reservoir but blocked, the game should still show the water range for convenience.
It will look like:
![city 2023-03-20 08 36 20](https://user-images.githubusercontent.com/10295404/226222506-cb931e92-11c8-45d6-80f8-b05945251461.png)
Current implementation does not show the water range (masked blue).

**Comment by bvschaik** [comment]
Back when the range was implemented, it was a conscious decision on my part to not show the range when you can't build a reservoir. I see Augustus does show it, and we already do the same for fountains in Julius, so I see no problem in also showing the reservoir range in Julius.
