### ISSUE TITLE
Is it possible to display the vavle of desirability of each tile on Desirability layout?

### ISSUE THREAD

**Issue by stucowade** [bvschaik/julius#686]
Describe your improvement here.
Keep in mind that UI improvements which require new texts will most likely be declined because we can only work with the original text files. Also, large UI changes will not be accepted.

I have been wondering if it is possible to display that. As the game goes on, I want to control the house to or (not to) evolve to the next level with desirability, however it's a headache to remember and calculate the values again and again.
Thank you

**Comment by bvschaik** [comment]
Possible: yes, but useful for the majority of players: no. For controlling house evolution, it's better to use access to goods and services than desirability.

**Comment by stucowade** [comment]
> 

Thank you! I really want to build some cities where citizens are free to get access to all goods and services and control their houses' evolution. To me, that's how a wonderful world should be.
Can you advise how I can do this feature myself if it's not on your agenda? Really like it and need it.
Thank you again,

**Comment by bvschaik** [comment]
You can do this easily by editing function [draw_top_desirability](https://github.com/bvschaik/julius/blob/b5fa1b59bb8ddfc9d5eee96ea2125454d4a42331/src/widget/city_overlay_other.c#L440C1-L460C2).

Apply this patch for a rudimentary implementation:
```patch
diff --git a/src/widget/city_overlay_other.c b/src/widget/city_overlay_other.c
index 0178be94..6cd9f236 100644
--- a/src/widget/city_overlay_other.c
+++ b/src/widget/city_overlay_other.c
@@ -15,6 +15,9 @@
 #include "map/random.h"
 #include "map/terrain.h"
 
+#include "core/string.h"
+#include "graphics/text.h"
+
 static int show_building_religion(const building *b)
 {
     return
@@ -454,6 +457,9 @@ static void draw_top_desirability(int x, int y, int grid_offset)
         }
         int offset = get_desirability_image_offset(map_desirability_get(grid_offset));
         image_draw_isometric_top_from_draw_tile(image_group(GROUP_TERRAIN_DESIRABILITY) + offset, x, y, co
lor_mask);
+        uint8_t number_string[10];
+        string_from_int(number_string, map_desirability_get(grid_offset), 0);
+        text_draw_centered(number_string, x, y, 58, FONT_NORMAL_PLAIN, COLOR_BLACK);
     } else {
         image_draw_isometric_top_from_draw_tile(map_image_at(grid_offset), x, y, color_mask);
     }
```

**Comment by stucowade** [comment]
> You can do this easily by editing function [draw_top_desirability](https://github.com/bvschaik/julius/blob/b5fa1b59bb8ddfc9d5eee96ea2125454d4a42331/src/widget/city_overlay_other.c#L440C1-L460C2).
> 
> Apply this patch for a rudimentary implementation:
> 
> ```diff
> diff --git a/src/widget/city_overlay_other.c b/src/widget/city_overlay_other.c
> index 0178be94..6cd9f236 100644
> --- a/src/widget/city_overlay_other.c
> +++ b/src/widget/city_overlay_other.c
> @@ -15,6 +15,9 @@
>  #include "map/random.h"
>  #include "map/terrain.h"
>  
> +#include "core/string.h"
> +#include "graphics/text.h"
> +
>  static int show_building_religion(const building *b)
>  {
>      return
> @@ -454,6 +457,9 @@ static void draw_top_desirability(int x, int y, int grid_offset)
>          }
>          int offset = get_desirability_image_offset(map_desirability_get(grid_offset));
>          image_draw_isometric_top_from_draw_tile(image_group(GROUP_TERRAIN_DESIRABILITY) + offset, x, y, co
> lor_mask);
> +        uint8_t number_string[10];
> +        string_from_int(number_string, map_desirability_get(grid_offset), 0);
> +        text_draw_centered(number_string, x, y, 58, FONT_NORMAL_PLAIN, COLOR_BLACK);
>      } else {
>          image_draw_isometric_top_from_draw_tile(map_image_at(grid_offset), x, y, color_mask);
>      }
> ```

Thank you, bro. I must confess it's much more complicated than I expected.
But I do want to get a version to have this feature.
If you are willing to help with this, please email your quotation to stucowade@qq.com,  and let's discuss it.
I'd like to pay for it at a reasonable rate.
I am looking forward to hearing from you,
Yours faithfully,

**Comment by crudelios** [comment]
> Thank you, bro. I must confess it's much more complicated than I expected. But I do want to get a version to have this feature. If you are willing to help with this, please email your quotation to [stucowade@qq.com](mailto:stucowade@qq.com), and let's discuss it. I'd like to pay for it at a reasonable rate. I am looking forward to hearing from you, Yours faithfully,

No need for quotations, here's a build that implements the above code.

To see the values, just go to the "desirability" overlay.

[julius-custom-desirability-values-overlay.zip](https://github.com/bvschaik/julius/files/12315023/julius-custom-desirability-values-overlay.zip)

**Comment by stucowade** [comment]
> 

Thank you SOOOOOO much for your help and kindness!!!
Gonna read the codes and try to learn.
I like coding, just start to learn Python and made some small projects for my daily work.
C is really hard and deep for me....(I believe, hard and deep for most people)

**Comment by crudelios** [comment]
Not to sound like bragging, but even though julius is a big project, it's also one of the clearest codebases around, so it should be relatively straightforward to follow.

The game begins execution on function `main` in the file `src/platform/julius.c` of you're interested.

**Comment by stucowade** [comment]
> The game begins execution on function `main` in the file `src/platform/julius.c` if you're interested.

YES, I AM INTERESTED!!! REALLY APPRECIATE YOUR INSTRUCTION!!
 I found myself enjoying coding and seeing it produce whatever I want---It's always a great pleasure to see my codes work well and produce what I need!!
The only problem is that I am too old to learn it thoroughly--40 yrs old already...
So only been enjoying some basic pleasure brought by some basic codings : )
Thank you again, bro, Sooo kind of you!!!

**Comment by crudelios** [comment]
Nice comment @ralphcook!

Well, I was purposefully vague on the "relatively straightforward" adjective. As you mentioned, it straightforward compared to some projects of the same dimension, but it's not easy. As an entire game, the Julius codebase branches off in many different directions.

However, I do mantain that starting at the `main` function, it's not really too hard to understand the broad workings of the game. You have the game loop, the input events, the simulation processing and frame drawing. With a reasonable IDE, you can follow or skip some of these parts of the game and learn as you go around.

I also believe that I would have delved in many other projects if only I figured out where their entry point was and understood from "top to bottom" how things worked and were related to each other.

Also, @bvschaik already knows this, but I can't overemphasise how much I learned from this project in terms of general code structure and design principles. I'm not as mentally organised myself, but I have really started using some principles found on this codebase elsewhere.
