### ISSUE TITLE
Minor typo in wiki page

### ISSUE THREAD

**Issue by lpea** [bvschaik/julius#687]
Hello! Thanks for this great project, I'd like to point out a small typo in the Configuration page of the wiki, in the "[Fix immigration bug on very hard](https://github.com/bvschaik/julius/wiki/Configuration#fix-immigration-bug-on-very-hard)" section:

> However, any conditions in your city that might improve their happiness, such as **no employment**, high wages, etc,

Shouldn't it read 

> However, any conditions in your city that might improve their happiness, such as **no unemployment**, high wages, etc,

instead?

The fix is also available here for cherry-pick: https://github.com/lpea/julius-wiki/commit/470fc8e571e3a110fba6b065f62eb2bdee03d0bb

Cheers,

**Comment by bvschaik** [comment]
Thanks! I have cherry-picked your fix.
