### ISSUE TITLE
bookmark after rotation

### ISSUE THREAD

**Issue by feiyunw** [bvschaik/julius#688]
Steps to produce the bug:
- when playing a scenario, move to a map corner (using arrow keys)
- set a bookmark using hotkey Ctrl+F1
- use hotkey Home or End to rotate the map
- press hotkey F1
It does not go back to the bookmarked point in the global map.
It saves and restores the camera position (like in the mini-map), without handling the map orientation.

**Comment by bvschaik** [comment]
Interesting one. I'm guessing the original C3 also has the same issue. The bookmark stored the view coordinates without taking orientation into account.
