### ISSUE TITLE
corrupted Traditional Chinese font

### ISSUE THREAD

**Issue by feiyunw** [bvschaik/julius#691]
In the [Patches](https://github.com/bvschaik/julius/wiki/Patches) webpage, the font file in "[Traditional Chinese](https://github.com/bvschaik/julius-support/releases/download/patches/caesar3_update_traditional_chinese.zip)" is identical to the one in [Simplified Chinese](https://github.com/bvschaik/julius-support/releases/download/patches/caesar3_update_simplified_chinese.zip).
It does not work with the master branch for Traditional Chinese.

**Comment by bvschaik** [comment]
Oops, my bad. I just uploaded an updated patch for Traditional Chinese that includes the correct font file.
