### ISSUE TITLE
Misaligned button texts (building menu, overlay list, and main menu)

### ISSUE THREAD

**Issue by Ouaz** [bvschaik/julius#692]
Texts are 1 pixel too high on buttons. Happens on Vanilla too.

1) In the building menu, for building names:

<details><summary>screenshot</summary><img src="https://github.com/bvschaik/julius/assets/11946570/1b619258-d12f-4318-88a2-5da33fff7a20">
</details>

Comparison of 1px lowered text for building names (made on Augustus, but it's similar on Julius)

<details><summary>comparison</summary><img src="https://github.com/bvschaik/julius/assets/11946570/065cd670-5f35-4545-995f-ae26ab569ca7">
</details>

2) In the main menu:

<details><summary>screenshot</summary><img src="https://github.com/bvschaik/julius/assets/11946570/e5fde930-cebf-46ef-8415-32f365fcb317">
</details>

It has been fixed on Augustus ( https://github.com/Keriew/augustus/commit/27e080eb651fb01efae518a0ca2532ca11044e03 and https://github.com/Keriew/augustus/commit/947768cbd20a769b285b3bd89ee29b65b7155284 )

---EDIT---

3) I forgot the Overlay buttons (texts are 1 pixel too high there too)

<details><summary>screenshot</summary><img src="https://github.com/bvschaik/julius/assets/11946570/ffdcc9be-f135-41ed-b7fc-4c61bfa7990b">
</details>

**Comment by bvschaik** [comment]
Thanks. I fixed all of them, and also improved the alignment of the "Overlays" button.
