### ISSUE TITLE
[BUG] Warehouse being cleared

### ISSUE THREAD

**Issue by leobastiani** [bvschaik/julius#699]
Seems to be a bug that my Warehouse start to be emptied just after configuring Granaries
 
https://github.com/bvschaik/julius/assets/8663061/28aa23a6-1d53-4aa0-bb2d-90a5e695224a

[autosave.zip](https://github.com/bvschaik/julius/files/12256059/autosave.zip)

Some details about my Caesar 3 assets file
I have the .iso from the original game in Portuguese Brazil, so I'm not using Steam either GOG version
Another strange piece of information about my folder's game, I'm use git with [nodemon](https://www.npmjs.com/package/nodemon) to watch for changes on autosave.sav and keep a history of autosave, Sometimes, months in game passes too quick and I already saw an autosave corrupted, I'm not sure if it's related to the fact I'm using git

**Comment by crudelios** [comment]
So from what I understand, if you set a warehouse to "empty" and then no granaries accept that resource, the granary will fully empty by itself without delivering the resource anywhere, is that right?

Regarding your corrupted autosave, it's very possible the game is saving over while also you're syncing the file. That would certainly result in corruption. There's really no way around that.

**Comment by leobastiani** [comment]
> So from what I understand, if you set a warehouse to "empty" and then no granaries accept that resource, the granary will fully empty by itself without delivering the resource anywhere, is that right?

The warehouse is not set to `empty warehouse`
You can see someone stealing my wheat haha, and flashing between seconds 31 and 35 on the video
![warehouse-flashing-bug](https://github.com/bvschaik/julius/assets/8663061/b6cc6890-e8ed-4e24-b198-4439093949d6)

**Comment by bvschaik** [comment]
As discussed on Discord after investigation by @crudelios: the wheat warehouse is trying to deliver to a warehouse that has two road connections. Since the road access tile of the target warehouse is unreachable, the deliveryman is lost, taking the wheat with him. This works the same in Caesar 3. Since fixing this requires reworking the pathing algorithm, breaking compatibility with C3 along the way, we won't fix this.

**Comment by crudelios** [comment]
Also, this issue is somewhat fixed in Augustus as the cartpusher will in certain cases go offroad, allowing access to the main warehouse tile.
