### ISSUE TITLE
I am getting a garden+cart pusher glitch in which they get stuck on gardens sometimes.

### ISSUE THREAD

**Issue by Zeg4** [bvschaik/julius#702]
I often get a glitch in which my cart pushers try to cut across gardens with their goods, but get stuck on them. When right-clicking them, they just say there is no space anywhere in the city, but it is clearly not true, and they stay like that forever or until I delete the building they came from (deleting the pusher and the goods on the cart in the process).

This does NOT happen on the original unmodded game, meaning that the glitch is on Augustus' side, the mod I am playing with. Is this a known glitch? It happens often for me, almost unavoidable unless I plan my building layout around the bug, which is annoying and often results in money loss. I suspect that it may have something to do with road layouts - the pushers stop in a separate road not connected to the destination. I believe that this may have something to do with the way cart pushers were adjusted to detect city space on Augustus, where they check that at all times instead of only when going out or arriving at their destination like they do in the unmodded game. Since they check for that all the time on Augustus, they do that on smaller roads too, resulting in the glitch that seems to be partially connected with the known garden glitch and making cart pushers unable to detect anything not connected to roads not directly connected to a valid destination while crossing a road after a garden shortcut was taken. Indeed, the cart pushers can be unstuck if the road they get stuck on is connected to the road they are supposed to head towards with an actual road instead of a garden.

Oh, and I also get a similar glitch with market ladies trying to cut across gardens to buy something with the same trigger conditions and then they either disappear there or return to their market before buying any goods, then repeat that action infinitely, effectively bricking that market until something is changed, be the market, destination or the road connection as described above.

[This Dropbox link](https://www.dropbox.com/scl/fi/x929ahwb9dugmlp0f2ya3/bug-report.svx?rlkey=9n22wi4l2mbtoa5ml9ls3gjr4&dl=0) contains a save file that I have prepared with the glitch ready to happen shortly after on the position the camera is on, with vegetable farm cart pushers. They would normally use the granary on the left, but I blocked vegetable trade on that granary to force them to use the granary on the right, which will make them cut across the gardens there, making the bug happen. The market on that neighborhood will also recreate the bug once the market lady tries to buy from the granary on the right (she will return to the market before getting to the granary). Connecting the middle road with the outer road does "fix" the bug as well.

Perhaps the weirdest part of this glitch is that it does not ALWAYS happen for all garden path cuts. They sometimes cut across them just fine and I cannot quite tell what the trigger difference is. The rest of my city on this save file does contain some cart pushers and market ladies that do exactly this, if that helps.

That is all for now. The glitch can happen with just about any cart pusher and market lady regardless of good type and destination building (granary, warehouse, workshop, even barracks), from what I can tell.

**Comment by crudelios** [comment]
This is an augustus bug, please post it there.

Link to post the issue: https://github.com/Keriew/augustus/issues/new?assignees=&labels=bug&projects=&template=bug_report.md

Also, please tell which version you are running. Stable v3.2.0 is known for that, but it should be fixed on the latest unstable.
