### ISSUE TITLE
How can I edit .555, .eng and .emp files for localization?

### ISSUE THREAD

**Issue by stucowade** [bvschaik/julius#705]
Ask your question here.
Hi there,
I found the language patch for my language (Simplified Chinese) is not complete-- some parts are missing and just left blank in the "knowledge base" --- the wordings appear after clicking on the question mark in some panels in the game.
It doesn't affect the gameplay but I'd like to make it complete, however have no idea which software I should use to edit these localization files.
Tried to Google it, FileViewPro is recommended but I can not install it (said my Internet failed). 
My OP is Win 11.
Please help.
Thank you,

**Comment by crudelios** [comment]
Hi,

You can use the engconverter to convert the files to and from xml.

Here's the link: https://github.com/bvschaik/citybuilding-tools/releases/tag/engconverter-v0.5

**Comment by bvschaik** [comment]
In addition, the .eng file is the only one that contains text; the .emp (empire map data) and .555 (graphics data) do not contain any localizable text.

When editing the xml file created by engconverter, be aware that not every Chinese character is supported in the game.

**Comment by stucowade** [comment]
Thank you! @crudelios @bvschaik 
It seems you guy have developped everything for making C3 better and better, which is too good to be true!!!

**Comment by stucowade** [comment]
Hey guys, @bvschaik @crudelios 
I started to work on the localization today but unfortunately, I got garbled texts after converting the .eng file to an XML file regardless of the encoding I selected.
Any advice?
Thanks,

**Comment by bvschaik** [comment]
That's weird. Selecting Simplified Chinese should work for you.

Could you share the .eng file here so I can have a look?

**Comment by stucowade** [comment]
> That's weird. Selecting Simplified Chinese should work for you.
> 
> Could you share the .eng file here so I can have a look?

I downloaded it from your WIKI, 
I tried to convert c3.eng and c3_mm.eng, nono work properly.
Here it is:
https://github.com/bvschaik/julius-support/releases/download/patches/caesar3_update_simplified_chinese.zip

Thank you for your help.

**Comment by bvschaik** [comment]
I just tried again and the XML file looks OK to me, using "Simplified Chinese (C3)" (c3.eng):

```
<?xml version="1.0" encoding="UTF-8"?>
<strings name="C3 textfile." indexWithCounts="false">
    <group id="1">
        <string id="0">档  案</string>
        <string id="1">新 游 戏</string>
        <string id="2">重玩地图</string>
        <string id="3">载入游戏</string>
        <string id="4">储存游戏</string>
        <string id="5">离开游戏</string>
        <string id="6">删除游戏</string>
...
```

Note that the resulting XML file is in UTF-8 encoding, make sure the editor you use also supports that.

**Comment by stucowade** [comment]
> I just tried again and the XML file looks OK to me, using "Simplified Chinese (C3)" (c3.eng):
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <strings name="C3 textfile." indexWithCounts="false">
>     <group id="1">
>         <string id="0">档  案</string>
>         <string id="1">新 游 戏</string>
>         <string id="2">重玩地图</string>
>         <string id="3">载入游戏</string>
>         <string id="4">储存游戏</string>
>         <string id="5">离开游戏</string>
>         <string id="6">删除游戏</string>
> ...
> ```
> 
> Note that the resulting XML file is in UTF-8 encoding, make sure the editor you use also supports that.

Hmmm, it turns out it's my editor's problem, I tried with another one now it's OK. Thanks, bro.

**Comment by bvschaik** [comment]
Unfortunately you can't :(
The Chinese "font" is a set of 6000 images: 2000 characters in three sizes. The only thing that might help is changing the display scale in the Julius settings to make everything a little bigger.

**Comment by stucowade** [comment]
> Unfortunately you can't :( The Chinese "font" is a set of 6000 images: 2000 characters in three sizes. The only thing that might help is changing the display scale in the Julius settings to make everything a little bigger.

Life becomes harder after hearing this.... 
Anyway, I will keep going with that. 
Could you do me a favor to upload it when it's finished?
Thanks,

**Comment by bvschaik** [comment]
> Could you do me a favor to upload it when it's finished?

You mean to the patches section? Yes, of course.

**Comment by stucowade** [comment]
Hi bvschaik,
Attached you will find the patch for Simplified Chinese completed (not sure if totally completed though).
I am sure it's not a a perfect one due to my knowledge level.
And, it could be better if the editor supports more Chinese characters : )
Stucowade




发件人:                                                                                                                        "bvschaik/julius"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月15日(星期五) 凌晨2:21
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [bvschaik/julius] How can I edit .555, .eng and .emp files for localization? (Issue #705)





  
Could you do me a favor to upload it when it's finished?
  
You mean to the patches section? Yes, of course.

**Comment by crudelios** [comment]
@stucowade I don't think email attachments will show up here, you need to add the attachment directy on github page.

**Comment by stucowade** [comment]
> @stucowade I don't think email attachments will show up here, you need to add the attachment directy on github page.

I will be pleased to do that but have no idea how : )....
Is it possible you download it from your email, and upload it here in Github? 
Many thanks,

**Comment by bvschaik** [comment]
@stucowade Could you mail them directly to bvschaik@gmail.com?
