### ISSUE TITLE
After moving the game files to a new PC with another harddrive letter, it crashes.

### ISSUE THREAD

**Issue by Febbe** [bvschaik/julius#706]
Describe the bug, the steps to reproduce, and if possible attach a saved game that show the wrong behavior.

Caesaria logfile created: 14:29:24
[INFO]Setting workdir to E:/SteamLibrary/steamapps/common/CaesarIA
[INFO]Loading game settings
[INFO]SaveAdapter: try load model from E:/SteamLibrary/steamapps/common/CaesarIA/resources/settings.model
[INFO]SaveAdapter: try load model from E:/SteamLibrary/steamapps/common/CaesarIA/resources/settings.model
[WARN]FileNative: Can't open file G:/Steam/steamapps/common/CaesarIA/resources/locale/caesar.en
[WARN]Can't find file G:/Steam/steamapps/common/CaesarIA/resources/locale/caesar.en
[WARN]FileNative: Can't open file G:/Steam/steamapps/common/CaesarIA/resources/locale/caesar.de
[WARN]Can't find file G:/Steam/steamapps/common/CaesarIA/resources/locale/caesar.de
[WARN]SDLGraficEngine: init successfull
[WARN]Game: load fonts

**Comment by dalerank** [comment]
It strange that u attach log from another game here ;)

**Comment by Febbe** [comment]
> It strange that u attach log from another game here ;)

Isn't this the official fork of your original remake?

**Comment by dalerank** [comment]
Nope, that game from @bvschaik
