### ISSUE TITLE
CLI option to choose which monitor to display on

### ISSUE THREAD

**Issue by dotnetCarpenter** [bvschaik/julius#717]
Having multiple monitors, it would be nice to have a CLI option to choose which monitor to display the game on.

I imagine something like:

```
./julius --monitor 2
```
_Where the number after `--monitor`, is the OS monitor identity number._

PS. The identity number could also be zero-based as it seems to currently be:
> INFO: User to windowed 1024 x 768 on display 0
> INFO: User to fullscreen 1920 x 1200 on display 1

**Comment by dotnetCarpenter** [comment]
After experiencing #716 I feel this option would go well, hand in hand with a `--fullscreen` option.
Instead of starting a game to set the full screen mode on the correct monitor. I could simply do `./julius --monitor 2 --fullscreen` when I have connected my secondary monitor.

**Comment by bvschaik** [comment]
Has been fixed by PR #722.
