### ISSUE TITLE
Map Limits and Graphics Artifacts

### ISSUE THREAD

**Issue by jdmillard** [bvschaik/julius#72]
In C3, when scrolling to the extremes of the map, you see a standard 1-tile gap of black like this:
![image](https://user-images.githubusercontent.com/11249742/52096586-62d51f80-2595-11e9-8297-123724ca3734.png)

In Julius, we see this in the south corner:
![image](https://user-images.githubusercontent.com/11249742/52096649-987a0880-2595-11e9-9d3e-4cb33939a1eb.png)

As you rotate around, the exact corner that this happens in changes, but I haven't figured out the relationship.

This causes rendering artifacts. Scroll to one of the problematic corners, then go to the empire/trade map. Then go back. You can see this:

![image](https://user-images.githubusercontent.com/11249742/52096747-fb6b9f80-2595-11e9-949f-b090bf45d9fa.png)

Other things can cause these render artifacts as well, but that was the easiest way to show it.

**Comment by crudelios** [comment]
You're right that Julius shows one extra row of black tiles, however I'm not able to reproduce the render artifactseither in windowed or in fullscreen mode.

What I did: with map orientation set to north, went to the souternmost edge of the map until scrolling stopped, went to the empire map, went back to city. Borders remained black.

**Comment by jdmillard** [comment]
Oh that's interesting. Can you try on an enormous map? (I didn't expect that to matter, but that's what I was on)

**Comment by crudelios** [comment]
You're right. It happens on enormous maps.

**Comment by jdmillard** [comment]
I think limiting that extra line will solve this (and match original game). But I agree that this does need investigation because I saw some strange stuff when rotating the map at the East extreme. But I didn't notice a specific pattern and I don't know if it's only on enormous maps.

**Comment by crudelios** [comment]
The strange stuff seems to be caused by the window not redrawing those particular pixels, hence whatever was drawn there will stay there.

**Comment by jdmillard** [comment]
Hmm, this does not happen on my version.

**Comment by crudelios** [comment]
Upon further testing, I found that in C3, it only happens on the 1024x768 resolution, but not on 640x480, 800x600 or 1600x900.

In julius, it happens on every resolution.

It's definitely a difference, albeit one that seems easy to fix. I'll do it later today if no one beats me to it.
