### ISSUE TITLE
OH MY GOD THANK YOU!

### ISSUE THREAD

**Issue by arthurwolf** [bvschaik/julius#721]
I started coding this twice. I emailed people trying to get the source released. I was obsessed with having an open version of c3, but gave up a few years back.
I jumped in my seat when I saw this at random in a github search.
Thank you SO much for doing this.

**Comment by bvschaik** [comment]
You're welcome, enjoy!

**Comment by crudelios** [comment]
Haha this was more or less my reaction when I found out about Julius 5 years ago!
