### ISSUE TITLE
Building Julius locally - works but executable doesn't show change

### ISSUE THREAD

**Issue by adysuciu** [bvschaik/julius#723]
Hi,
First of all:
Congrats for the work to replicate C3 - one of my favorite games!
I wanted to play on my MacOS10.12 and built it from source successfully.

Now I want to play with the source code and see changes in the game.
Cmake works and builds julius.app correctly, still I can see no change in the game.

Made a local branch and committed the change locally.
Commit # 1cabf8
[adibranch 1cacbf8] want to check game
Image attached.
<img width="1075" alt="Screen Shot 2024-02-04 at 21 07 06" src="https://github.com/bvschaik/julius/assets/2750249/49b182c8-4582-4b0d-95b8-865bcaa5788c">

I do not have too much experience with cmake, maybe I am missing some steps to propagate the source change.

Thanks in advance!

**Comment by crudelios** [comment]
I'm not sure what change you made, but for the app to update you don't need to commit but rather to use the `make` command again.

**Comment by adysuciu** [comment]
I have updated   city/data.c and changed values for 
    city_data.labor.wages_rome = 50;
    city_data.labor.wages = 50;
    city_data.finance.tax_percentage = 10;

After building I am expecting to see the new values in the Advisor Labor screen.

**Comment by crudelios** [comment]
Ah, I see the issue.

Those variables are updated every time the simulation runs and also during game load, so likely they are getting overwritten.

**Comment by bvschaik** [comment]
The variables you change indeed get overwritten on save load. You will see the changes only when you start a new game through the City Construction Kit.

Considering that the main menu shows the new commit hash in the version string in the bottom left corner, the source changes have been compiled: I'm closing this as fixed.
