### ISSUE TITLE
Texture filter when rising display scale above 100%

### ISSUE THREAD

**Issue by lordrius** [bvschaik/julius#727]
Hi!

I was testing Julius and it's wonderful, thanks! I have a question, when rising the display scale above 100% I have the feeling that it applies some kind of texture filtering such us bilinear or bicubic, can it be? I attach a couple of screenshots...

**Original c3.exe at 1024x768**
![original 1024x768](https://github.com/bvschaik/julius/assets/483570/f442a09b-3228-4367-9d0b-3733bf43de93)

Julius 150% display scale
![julius scaled 150%](https://github.com/bvschaik/julius/assets/483570/cb51fe97-8774-4198-a8de-26a8c6f89c4e)

Thank you :)

**Comment by bvschaik** [comment]
You're right, linear scaling is applied on anything other than multiples of 100: [source](https://github.com/bvschaik/julius/blob/ef1547d8a1e532fc8e4595541051e38f2ef90092/src/platform/screen.c#L89).

**Comment by bvschaik** [comment]
You can already override it by setting the [SDL_HINT_RENDER_SCALE_QUALITY](https://wiki.libsdl.org/SDL2/SDL_HINT_RENDER_SCALE_QUALITY) environment variable.

We will not make it an option since the nearest neighbour setting simply does not look good.

**Comment by lordrius** [comment]
All right, thank you very much!
