### ISSUE TITLE
Possible error in trunk (c87d131)

### ISSUE THREAD

**Issue by dotnetCarpenter** [bvschaik/julius#730]
I've just build c87d131 and am seeing the following error a few times:

```
[src/libmpg123/id3.c:process_comment():587] error: No comment text / valid description?
```

I'm not sure, but it might happen when a small video clip is displayed. E.i. when having a festival or hitting a population milestone.

Let me know if I should make a debug build with a backtrace or similar if needed - and please add some instruction on how to do so ;)
Unfortunately, I'm not a C programmer.

<details><summary>Last game console output</summary>
<pre>
INFO: Julius version 1.7.0-20240530-c87d131
INFO: Initializing SDL
INFO: SDL initialized
INFO: Loading game from working directory
INFO: Config key  gameplay_fix_immigration
INFO: Config key  gameplay_fix_100y_ghosts  1
INFO: Config key  screen_display_scale  130
INFO: Config key  screen_cursor_scale  100
INFO: Config key  ui_sidebar_info  1
INFO: Config key  ui_show_intro_video
INFO: Config key  ui_smooth_scrolling
INFO: Config key  ui_disable_mouse_edge_scrolling
INFO: Config key  ui_disable_map_drag
INFO: Config key  ui_visual_feedback_on_delete  1
INFO: Config key  ui_allow_cycling_temples  1
INFO: Config key  ui_show_water_structure_range  1
INFO: Config key  ui_show_construction_size  1
INFO: Config key  ui_highlight_legions
INFO: Config key  ui_show_military_sidebar
INFO: Config key  ui_show_speedrun_info
INFO: Config key  ui_language_dir
INFO: Config value  
INFO: No key found on layout for  [
INFO: No key found on layout for  ]
INFO: No key found on layout for  =
INFO: Detected language:  English
INFO: Detected encoding:  1252
INFO: Creating screen 1920 x 1080 on display 0, fullscreen, driver: x11
INFO: Creating renderer
INFO: Texture created: 1476 x 830
INFO: Model loaded
INFO: Loading audio files
INFO: Window 1 shown
INFO: Window 1 hidden
INFO: Window 1 shown
INFO: Window move to coordinates x: 0 y: 0
INFO: System resize to 1920 x 1080
INFO: Window resized to 1920 x 1080
INFO: System resize to 1920 x 1080
INFO: Loading saved game  Quaestor.sav
[src/libmpg123/id3.c:process_comment():587] error: No comment text / valid description?
INFO: Loading saved game  Quaestor Final Battle.sav
INFO: Loading saved game  Procurator.sav
[src/libmpg123/id3.c:process_comment():587] error: No comment text / valid description?
INFO: Loading saved game  Procurator Fred II.sav
[src/libmpg123/id3.c:process_comment():587] error: No comment text / valid description?
[src/libmpg123/id3.c:process_comment():587] error: No comment text / valid description?
[src/libmpg123/id3.c:process_comment():587] error: No comment text / valid description?
INFO: Saving game  Procurator Fred II.sav
[src/libmpg123/id3.c:process_comment():587] error: No comment text / valid description?
INFO: Saving game  Procurator Fred II.sav
[src/libmpg123/id3.c:process_comment():587] error: No comment text / valid description?
[src/libmpg123/id3.c:process_comment():587] error: No comment text / valid description?
INFO: Saving game  Procurator Fred III.sav
[src/libmpg123/id3.c:process_comment():587] error: No comment text / valid description?
[src/libmpg123/id3.c:process_comment():587] error: No comment text / valid description?
INFO: Saving game  Procurator Fred III.sav
INFO: Exiting game
</pre>
</details>

**Comment by dotnetCarpenter** [comment]
:thinking: it's not related to video playback. I've tried only using the map editor and got the same error message again.

**Comment by crudelios** [comment]
Hi!

This isn't really an error, the issue is that the mp3 files we've provided don't have any metadata and the player warns about that.

It's harmless 🙂

**Comment by dotnetCarpenter** [comment]
@crudelios thanks for the info :yellow_heart:
