### ISSUE TITLE
Ubuntu 23.10 requires libflac8 manual install

### ISSUE THREAD

**Issue by d-damien** [bvschaik/julius#734]
I have no expertise with that but your Appimage script uses `ldconfig -p` which lists libflac8, whereas more recent Ubuntu 23.10 only has libflac12. See https://packages.ubuntu.com/jammy-updates/libflac8. I had to manually download and install the libflac8 deb to make it work.

Thanks for your work.

**Comment by bvschaik** [comment]
Are you trying to run the AppImage or creating one yourself? For running you should not need any libraries. For creating one: we purposely build the AppImage on an older version of Ubuntu so it runs on as many operating versions as possible.

**Comment by Incognito-1** [comment]
download and and install the package manually : https://www.ubuntuupdates.org/package/core/jammy/main/security/libflac8
