### ISSUE TITLE
[Bug] A double free bug in /src/core/smacker.c

### ISSUE THREAD

**Issue by shiyujunz** [bvschaik/julius#737]
I have found a potential double free bug in the julius project and would like to report it to the maintainers. This vulnerability has the potential to cause unexpected application behavior, crashes. Can you please help me check it? Thank you for your effort and patience!
Below is the execution sequence of the program that may produce  double free bug .
First, in the file /src/core/smacker.c, in the function **smacker_open**, line 524 first calls the function **read_frame_info**, which will free s->frame_types at line 459, and second, the function **smacker_open** calls the function **smacker_close**  at line 525, which will free s-> frame_types for a second time, which leads to a double free vulnerability.
![double free](https://github.com/user-attachments/assets/fd23acbe-5829-4636-b682-d8f1c3585d53)

**Comment by crudelios** [comment]
Good catch!

We likely never caught it because I don't think I ever saw an smk file failing to load.
