### ISSUE TITLE
No directory selection dialog on first launch

### ISSUE THREAD

**Issue by vv221** [bvschaik/julius#741]
On a fresh profile, where ~/.local/share/bvschaik/julius/data_dir.txt is not set yet, I can run julius for the first time in two distinct ways:
- By running the `julius` command in a terminal;
- By clicking on the "Julius" entry in my applications menu.

The first one, running from a terminal, spawns a prompt (not a GUI one, one rendered directly in the terminal) asking me where it can find the game data. This is the kind of behaviour I expected, so all good on this front.

But the second one, running from the applications menu, does not spawn any kind of prompt. It does not seem that any kind of process is lingering either, it seems to simply fail to run.

Once the path in ~/.local/share/bvschaik/julius/data_dir.txt is set (either manually or by running `julius` from a terminal) this is no longer a problem, the menu entry then works nicely and starts the game as it should.

**Comment by vv221** [comment]
Maybe an useful detail: I am not using a full blown desktop environment like Gnome or KDE, but something quite minimal based on sway. So maybe julius assumes some things to always be present, that would be missing on my setup.

**Comment by crudelios** [comment]
> Maybe an useful detail: I am not using a full blown desktop environment like Gnome or KDE, but something quite minimal based on sway. So maybe julius assumes some things to always be present, that would be missing on my setup.

Ahhh, so that's the issue. The file picker looks for many dialog alternatives to show a window and if it can't find one it resorts to the console prompt, so this is intended behaviour.

**Comment by crudelios** [comment]
Ah

> @crudelios, could you give me the list of the supported dialog alternatives?

Ah, I'm not sure about all supported alternatives. I know there are some. 

Internally we use [Tinyfiledialogs](https://sourceforge.net/projects/tinyfiledialogs/) to manage that, and that's the lib that checks for an available file dialog.

We've also trimmed the list quite a bit to save space, but that was so long ago I don't even remember what support we left.

**Comment by bvschaik** [comment]
> We've also trimmed the list quite a bit to save space, but that was so long ago I don't even remember what support we left.

For Linux I don't think we did. For Windows we stripped quite a bit, and we removed everything apart from the directory picker and an alert dialog.

Anyway, these are currently tried in order:

- kdialog
- zenity
- matedialog
- qarma
- Xdialog
- tkinter via Python 2
- tkinter via Python 3
- terminal input

Maybe I should have a look at the latest tinyfd to see if they added support for new file pickers.

**Comment by vv221** [comment]
Thanks, I’m going to add an extra dependency to ensure at least one of the GUI dialog interfaces is available for Debian users who did not tweak their package manager settings.

**Comment by bvschaik** [comment]
I had a quick look at tinyfd: they added shellementary and yad. Never heard of either so I have no clue how common those two are.

**Comment by vv221** [comment]
For the Debian package, I’m making the Python tkinter the default (from a package dependencies perspective, I am not tweaking your code setting the priority order) as it is the one coming with less environment-specific dependencies (you would not want kdialog in a GTK environment or zenity in a Qt environment). This Python package is only installed if the user does not already have zenity or kdialog installed.

I could not find the other three GUI supported in the Debian repositories: matedialog, qarma and Xdialog. But maybe my way of looking for them was incorrect: I searched for packages with similar names, and for packages providing a command with that exact name.

**Comment by bvschaik** [comment]
Apparently:
- qarma is a one man's qt port of zenity
- matedialog sounds like it's part of the MATE desktop environment
- Xdialog is another one man's project with the last release in 2006...

**Comment by vv221** [comment]
I guess qarma and Xdialog are simply not packaged for Debian yet.

For matedialog it is a bit more surprising. I’m going to look a bit further, maybe it is hiding under another name (MATE is provided by Debian).
