### ISSUE TITLE
Create a Gitter room for julius

### ISSUE THREAD

**Issue by devnoname120** [bvschaik/julius#76]
It would be great to create a Gitter room to improve collaboration.

You can do this in a few clicks by clicking [here](https://gitter.im/#createcommunity), then on "do you want to start a community for one of your github projects?".

**Comment by crudelios** [comment]
I agree that having a place to discuss the code besides opening issues on Github would be a good idea!

**Comment by jdmillard** [comment]
This would be nice. I have a pet peeve about creating new accounts for every little thing, but I suppose there's no getting around that.

At least with Gitter you can log in with github (that will still create an underlying account automatically, but whatever). I'm just picky lol.

**Comment by bvschaik** [comment]
Not a clue how this works, but there ya go: https://gitter.im/julius-game/community
