### ISSUE TITLE
Crash on clicking "visit yoyr advisors".

### ISSUE THREAD

**Issue by crudelios** [bvschaik/julius#77]
Every now and then clicking the "advisors" button (the one at the sidebar, not the menu) causes the game to immediately crash. The game will keep crashing every time I click the button until I select a specific advisor from the menu, then the button starts working again.

I haven't had the time to study the code and my main PC fried today so I'm limited in resources, but I suspect that some "advisor id" is being set a bogus value that is out of bounds, and that value is saved to c3.inf. This may in no small part be due to the fact that my c3.inf is load and shared between different builds and operating systems.

Still, I believe sanity checking the id of the last visitor advisor to only accept valid values could prevent these crashes.

**Comment by crudelios** [comment]
Case in note: I will eventually fix this.

**Comment by crudelios** [comment]
My pattern was to constantly rebuild Julius in multiple platforms, and still it only happened twice in the course of two months.

So it's fairly rare...

**Comment by bvschaik** [comment]
I have managed to reproduce this: remove `c3.inf`, start the game, click the button. Voila. Fix incoming in a couple of minutes 😉

**Comment by jdmillard** [comment]
Oh nice!
