### ISSUE TITLE
Towers don't fire

### ISSUE THREAD

**Issue by atolstoy** [bvschaik/julius#8]
Hello!
Looks like there is another issue, this time with defense towers. I can't figure out why they are not acting as expected. Please have a look:
https://yadi.sk/d/rUD1XSY33QSYey
I deliberately made the emperor angry and he sent his legion to arrest me. As you can see, towers in my game don't produce any ballista fire and stay useless, even though they have enough workers. I'm pretty sure there was ballista fire in the original Caesar 3 game.
Cheers!

**Comment by bvschaik** [comment]
For how long did you let the invasion continue? Towers have a range of 12 tiles. Caesar's troops muster farther away from the towers. Once they attack, the ballistae work properly and send the invaders packing.
I have compared the saved game with the original game, no difference. I'm going to add your .sav to my automatic tests, if you don't mind.

By the way, thanks for being an alpha tester, this is highly useful :+1:

**Comment by atolstoy** [comment]
Hi.
Just tried the kknight.sav with the latest Julius code, and towers worked just fine. You can close this issue now.
