### ISSUE TITLE
Full load of the first processor core

### ISSUE THREAD

**Issue by m1rcl** [bvschaik/julius#88]
Thank you for your amazing work. On my laptop running Julius fully loads CPU0 (25%) of my 4-core processor AMD A8-7410 Windows 7 64-bit. I checked both the release version and the Appveyor build. Please tell me how to fix it

**Comment by crudelios** [comment]
There is no way to fix it as it is not a bug, julius only uses one core by design.

**Comment by m1rcl** [comment]
thanks for explaining
