### ISSUE TITLE
Avoiding usage of magic numbers via/with enums/consts?

### ISSUE THREAD

**Issue by ShFil119** [bvschaik/julius#90]
There are many in code connected with UI. I think this makes code hard to read and maintain. 

(This issue is just suggestion. :) )

**Comment by crudelios** [comment]
I agree! But it's a huge undertaking to fix....

**Comment by bvschaik** [comment]
For the UI, I've given up on extracting the integers to constants, there are way too many and effort required vs benefit gained is low. Ideally for the UI, the layout of the buttons/text/etc should be in some external file like the layout files on Android, but that would again be a major effort. It will help with porting the game to for example Android devices with smaller screens than 640x480 though...

For any other code, any magic numbers should indeed be a constant/enum. I think I got most of them now, but if you come across magic numbers, please let me know.
