### ISSUE TITLE
Micro stuttering issues

### ISSUE THREAD

**Issue by adrian5683** [bvschaik/julius#92]
I'm experience stuttering every 2 seconds or so, this does not happen or the vanilla or HD modded .exe. Let me know what system info to provide, if any.

**Comment by crudelios** [comment]
It might be a bug regarding SDL and the use of USB devices.

Please download the following SDL version:

http://libsdl.org/release/SDL2-2.0.8-win32-x86.zip

Replace SDL2.dll with the one from that download and see if the pro bnlem persists, please.

For reference: https://stackoverflow.com/questions/53644628/sdl-pollevent-stuttering-while-idle

**Comment by adrian5683** [comment]
Problem solved, thank you.
