### ISSUE TITLE
Taking a screenshot results in corrupt file

### ISSUE THREAD

**Issue by bvschaik** [bvschaik/julius#95]
Screenshots saved with a resolution with a width not divisible by 4 result in corrupt files.

**To Reproduce**
1. Resize the screen to a width not divisible by 4
2. Take a screenshot by pressing F12
3. Try to open the resulting bmp file in an image viewer

**Comment by crudelios** [comment]
This happens on my end as well.

**Comment by bvschaik** [comment]
For BMP, one row of pixels is supposed to be a multiple of 4. With 24-bit bitmaps that's only the case when width of the image is a multiple of 4... Fix incoming in a couple of minutes.

**Comment by crudelios** [comment]
Yeah I seem to remember BMPs needing some sort of padding... But last time I created BMP files was many many years ago so I may be "hallucinating".
