### ISSUE TITLE
Raspberry pi: sound of .smk videos is mangled

### ISSUE THREAD

**Issue by bvschaik** [bvschaik/julius#96]
When playing on Raspberry PI, the sound from the videos sounds like static.

**Expected behavior**
Sound is crisp and clear.

**Additional context**
Tested on Raspberry PI 3B with TV. Other sounds are OK.

**Comment by crudelios** [comment]
I guess the rest of the sounds work ok, right? Off the top of my head, it might be a problem with SDL_mixer and not with libsmacker...

**Comment by bvschaik** [comment]
Yeah, rest of the sounds are OK. I'll try to debug this with a mini-app having just the libsmacker library + SDL.

**Comment by crudelios** [comment]
You can also use the convert to AVI demo program that comes with libsmacker to easily see if the problem is in libsmacker's decoding algorithm.
