### ISSUE TITLE
In-game options to resize screen place window in top-left corner

### ISSUE THREAD

**Issue by bvschaik** [bvschaik/julius#97]
When using F7/F8/F9, or the Options -> Display menu to resize the window in windowed mode, the window jumps to the top-left corner of the screen.

**To Reproduce**
1. Start the game in windowed mode, with the window not in the top-left corner of the screen
2. Resize using F7/F8/F9, or using Options -> Display
3. Note that the window jumps to (0,0)

**Expected behavior**
Window stays at the position it's currently at.

Seen on macOS and Raspberry Pi.

**Comment by crudelios** [comment]
See #57 for a fix.

**Comment by crudelios** [comment]
While #57 awaits merge, I can create a separate PR to fix this bug if you're interested.

Another thing that #57 does is set the minimum window size to 640x480, as that's the minimum size supported by C3. I can also implement that in a new PR.

**Comment by bvschaik** [comment]
That would be nice, yes.

Minimum size: I couldn't get that to work consistently and decided to let the user be in control there. I fixed some crashes related to too small windows, so I don't see any harm in allowing windows smaller than 640x480.

**Comment by crudelios** [comment]
Really? In my tests it seems to work well in Windows, Linux and Mac.

Also, `graphics_save_to_buffer` and `graphics_load_from_buffer` may crash the game on low enough resolutions, due to the minimap cache.

**Comment by bvschaik** [comment]
My memory is a little hazy. It might have been with SDL 1.2...

**Comment by bvschaik** [comment]
> Really? In my tests it seems to work well in Windows, Linux and Mac.

I've looked into this: when I was playing around with minimum window size, I was still using SDL1.2, which did not have any means to set the minimum size: you had to force-reset the window to 640x480 when your window got resized to something lower, which caused too much trouble.
