### ISSUE TITLE
[macOS] Menu-bar buttons cannot be clicked in windowed mode

### ISSUE THREAD

**Issue by shirakaba** [bvschaik/julius#99]
I entered windowed mode by pressing F7, as described in #97.

<img width="216" alt="image" src="https://user-images.githubusercontent.com/14055146/52747016-bfdfc500-2fda-11e9-810b-01be5d1f2f27.png">

If you click them, they don't highlight and don't contain any children. If they don't do anything, they shouldn't really be visible, in my mind.

Giving functionality to these may have some overlap with the macOS app bundling effort..?

**Comment by bvschaik** [comment]
Hmm, on my mac (High Sierra) they do work. But indeed, I think it's related to not having an app bundle.

**Comment by shirakaba** [comment]
Conclusion: it's a fault of macOS Mojave's interaction with older (certainly at least up to 2.0.3) versions of SDL, as it doesn't manifest on High Sierra with the same version of SDL.

Upgrading to SDL v2.0.9 fixes it!

No need to update any of the other SDL-related frameworks.
